/*********************************************************************************
 * FileName:    AlgoMinAngle.c
 * Description: Auto-generated by test/s06_export_min_angle_packed32.m
 *              32-bit packed minimum-angle white-ratio lookup module.
 *
 * Strategy:
 *   For target A and white point W, search LUT points B with Delta uv < 0.010000.
 *   Select B whose angle between AW and BW is minimal, then use B's ratio.
 *   Override macro: ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 (default 10u).
 *
 * Packed LUT:
 *   bit[ 0: 9] = U,      10 bit, u' * 1000
 *   bit[10:19] = V,      10 bit, v' * 1000
 *   bit[20:31] = ratio,  12 bit, whiteRatio * 4095
 **********************************************************************************/

#include "AlgoMinAngle.h"

#define ALGO_MIN_ANGLE_LUT_COUNT            (990u)

#define ALGO_MIN_ANGLE_U_MASK               (0x000003FFu)
#define ALGO_MIN_ANGLE_V_MASK               (0x000FFC00u)
#define ALGO_MIN_ANGLE_RATIO_MASK           (0xFFF00000u)

#define ALGO_MIN_ANGLE_V_SHIFT              (10u)
#define ALGO_MIN_ANGLE_RATIO_SHIFT          (20u)

#define ALGO_MIN_ANGLE_RATIO12_MAX          (4095u)
#define ALGO_MIN_ANGLE_RATIO_Q10000_MAX     (10000u)
#define ALGO_MIN_ANGLE_DISTANCE_MAX         (0xFFFFFFFFu)
#ifndef ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000
#define ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 (10u)
#endif
#define ALGO_MIN_ANGLE_DELTA_UV_LIMIT2      ((uint32_t)(ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 * ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000))

#define ALGO_MIN_ANGLE_PACK(U_, V_, RATIO12_) \
    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_MIN_ANGLE_RATIO_SHIFT) | \
     (((uint32_t)(V_)       & 0x3FFu) << ALGO_MIN_ANGLE_V_SHIFT) | \
     (((uint32_t)(U_)       & 0x3FFu)))

static const uint32_t g_algoMinAnglePackedLut[ALGO_MIN_ANGLE_LUT_COUNT] =
{
    ALGO_MIN_ANGLE_PACK( 201u,   84u,    0u),  /* idx=  0, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 197u,   95u,    0u),  /* idx=  1, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 194u,  107u,    0u),  /* idx=  2, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 190u,  118u,    0u),  /* idx=  3, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 186u,  129u,    0u),  /* idx=  4, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 183u,  140u,    0u),  /* idx=  5, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 179u,  152u,    0u),  /* idx=  6, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 176u,  163u,    0u),  /* idx=  7, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 172u,  174u,    0u),  /* idx=  8, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 169u,  185u,    0u),  /* idx=  9, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 165u,  196u,    0u),  /* idx= 10, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 162u,  208u,    0u),  /* idx= 11, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 158u,  219u,    0u),  /* idx= 12, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 155u,  230u,    0u),  /* idx= 13, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 151u,  241u,    0u),  /* idx= 14, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 148u,  253u,    0u),  /* idx= 15, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 144u,  264u,    0u),  /* idx= 16, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 141u,  275u,    0u),  /* idx= 17, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 137u,  286u,    0u),  /* idx= 18, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 133u,  298u,    0u),  /* idx= 19, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 130u,  309u,    0u),  /* idx= 20, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 126u,  320u,    0u),  /* idx= 21, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 123u,  331u,    0u),  /* idx= 22, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 119u,  343u,    0u),  /* idx= 23, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 116u,  354u,    0u),  /* idx= 24, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 112u,  365u,    0u),  /* idx= 25, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 109u,  376u,    0u),  /* idx= 26, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 105u,  388u,    0u),  /* idx= 27, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 102u,  399u,    0u),  /* idx= 28, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK(  98u,  410u,    0u),  /* idx= 29, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  95u,  421u,    0u),  /* idx= 30, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  91u,  433u,    0u),  /* idx= 31, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  88u,  444u,    0u),  /* idx= 32, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  84u,  455u,    0u),  /* idx= 33, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  80u,  466u,    0u),  /* idx= 34, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK(  77u,  478u,    0u),  /* idx= 35, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  73u,  489u,    0u),  /* idx= 36, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  70u,  500u,    0u),  /* idx= 37, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK(  66u,  511u,    0u),  /* idx= 38, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  63u,  523u,    0u),  /* idx= 39, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  59u,  534u,    0u),  /* idx= 40, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK(  56u,  545u,    0u),  /* idx= 41, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  52u,  556u,    0u),  /* idx= 42, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK(  49u,  568u,    0u),  /* idx= 43, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 209u,   94u,    0u),  /* idx= 44, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 205u,  105u,    0u),  /* idx= 45, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 202u,  117u,    0u),  /* idx= 46, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 198u,  128u,    0u),  /* idx= 47, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 194u,  139u,    0u),  /* idx= 48, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 191u,  150u,    0u),  /* idx= 49, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 187u,  162u,    0u),  /* idx= 50, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 184u,  173u,    0u),  /* idx= 51, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 180u,  184u,    0u),  /* idx= 52, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 177u,  195u,    0u),  /* idx= 53, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 173u,  207u,    0u),  /* idx= 54, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 170u,  218u,    0u),  /* idx= 55, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 166u,  229u,    0u),  /* idx= 56, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 163u,  240u,    0u),  /* idx= 57, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 159u,  252u,    0u),  /* idx= 58, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 156u,  263u,    0u),  /* idx= 59, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 152u,  274u,    0u),  /* idx= 60, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 149u,  285u,    0u),  /* idx= 61, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 145u,  297u,    0u),  /* idx= 62, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 141u,  308u,    0u),  /* idx= 63, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 138u,  319u,    0u),  /* idx= 64, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 134u,  330u,    0u),  /* idx= 65, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 131u,  342u,    0u),  /* idx= 66, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 127u,  353u,    0u),  /* idx= 67, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 124u,  364u,    0u),  /* idx= 68, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 120u,  375u,    0u),  /* idx= 69, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 117u,  387u,    0u),  /* idx= 70, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 113u,  398u,    0u),  /* idx= 71, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 110u,  409u,    0u),  /* idx= 72, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 106u,  420u,    0u),  /* idx= 73, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 103u,  432u,    0u),  /* idx= 74, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  99u,  443u,    0u),  /* idx= 75, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  96u,  454u,    0u),  /* idx= 76, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  92u,  465u,    0u),  /* idx= 77, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  89u,  477u,    0u),  /* idx= 78, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  85u,  488u,    0u),  /* idx= 79, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  81u,  499u,    0u),  /* idx= 80, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  78u,  510u,    0u),  /* idx= 81, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  74u,  522u,    0u),  /* idx= 82, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  71u,  533u,    0u),  /* idx= 83, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  67u,  544u,    0u),  /* idx= 84, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  64u,  555u,    0u),  /* idx= 85, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  60u,  567u,    0u),  /* idx= 86, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 217u,  104u,    0u),  /* idx= 87, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 213u,  115u,  446u),  /* idx= 88, ratio=0.108936 */
    ALGO_MIN_ANGLE_PACK( 210u,  127u,  252u),  /* idx= 89, ratio=0.061492 */
    ALGO_MIN_ANGLE_PACK( 206u,  138u,   95u),  /* idx= 90, ratio=0.023078 */
    ALGO_MIN_ANGLE_PACK( 203u,  149u,    0u),  /* idx= 91, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 199u,  160u,    0u),  /* idx= 92, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 195u,  172u,    0u),  /* idx= 93, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 192u,  183u,    0u),  /* idx= 94, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 188u,  194u,    0u),  /* idx= 95, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 185u,  205u,    0u),  /* idx= 96, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 181u,  217u,    0u),  /* idx= 97, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 178u,  228u,    0u),  /* idx= 98, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 174u,  239u,    0u),  /* idx= 99, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 171u,  250u,    0u),  /* idx=100, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 167u,  262u,    0u),  /* idx=101, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 164u,  273u,    0u),  /* idx=102, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 160u,  284u,    0u),  /* idx=103, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 157u,  295u,    0u),  /* idx=104, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 153u,  307u,    0u),  /* idx=105, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 150u,  318u,    0u),  /* idx=106, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 146u,  329u,    0u),  /* idx=107, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 142u,  340u,    0u),  /* idx=108, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 139u,  352u,    0u),  /* idx=109, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 135u,  363u,    0u),  /* idx=110, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 132u,  374u,    0u),  /* idx=111, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 128u,  385u,    0u),  /* idx=112, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 125u,  397u,    0u),  /* idx=113, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 121u,  408u,    0u),  /* idx=114, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 118u,  419u,    0u),  /* idx=115, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 114u,  430u,    0u),  /* idx=116, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 111u,  442u,    0u),  /* idx=117, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 107u,  453u,    0u),  /* idx=118, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 104u,  464u,    0u),  /* idx=119, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 100u,  475u,    0u),  /* idx=120, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  97u,  487u,    0u),  /* idx=121, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  93u,  498u,    0u),  /* idx=122, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  89u,  509u,    0u),  /* idx=123, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  86u,  520u,    0u),  /* idx=124, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  82u,  532u,    0u),  /* idx=125, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  79u,  543u,    0u),  /* idx=126, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  75u,  554u,    0u),  /* idx=127, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  72u,  565u,    0u),  /* idx=128, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 225u,  114u,    0u),  /* idx=129, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 221u,  126u,  628u),  /* idx=130, ratio=0.153315 */
    ALGO_MIN_ANGLE_PACK( 218u,  137u, 1152u),  /* idx=131, ratio=0.281410 */
    ALGO_MIN_ANGLE_PACK( 214u,  148u, 1504u),  /* idx=132, ratio=0.367235 */
    ALGO_MIN_ANGLE_PACK( 211u,  159u, 1355u),  /* idx=133, ratio=0.330996 */
    ALGO_MIN_ANGLE_PACK( 207u,  171u, 1229u),  /* idx=134, ratio=0.300018 */
    ALGO_MIN_ANGLE_PACK( 203u,  182u, 1117u),  /* idx=135, ratio=0.272701 */
    ALGO_MIN_ANGLE_PACK( 200u,  193u, 1008u),  /* idx=136, ratio=0.246150 */
    ALGO_MIN_ANGLE_PACK( 196u,  204u,  904u),  /* idx=137, ratio=0.220845 */
    ALGO_MIN_ANGLE_PACK( 193u,  216u,  801u),  /* idx=138, ratio=0.195640 */
    ALGO_MIN_ANGLE_PACK( 189u,  227u,  700u),  /* idx=139, ratio=0.171044 */
    ALGO_MIN_ANGLE_PACK( 186u,  238u,  609u),  /* idx=140, ratio=0.148621 */
    ALGO_MIN_ANGLE_PACK( 182u,  249u,  524u),  /* idx=141, ratio=0.128063 */
    ALGO_MIN_ANGLE_PACK( 179u,  261u,  453u),  /* idx=142, ratio=0.110715 */
    ALGO_MIN_ANGLE_PACK( 175u,  272u,  392u),  /* idx=143, ratio=0.095698 */
    ALGO_MIN_ANGLE_PACK( 172u,  283u,  345u),  /* idx=144, ratio=0.084258 */
    ALGO_MIN_ANGLE_PACK( 168u,  294u,  309u),  /* idx=145, ratio=0.075556 */
    ALGO_MIN_ANGLE_PACK( 165u,  306u,  282u),  /* idx=146, ratio=0.068861 */
    ALGO_MIN_ANGLE_PACK( 161u,  317u,  264u),  /* idx=147, ratio=0.064442 */
    ALGO_MIN_ANGLE_PACK( 158u,  328u,  252u),  /* idx=148, ratio=0.061651 */
    ALGO_MIN_ANGLE_PACK( 154u,  339u,  249u),  /* idx=149, ratio=0.060777 */
    ALGO_MIN_ANGLE_PACK( 150u,  351u,  251u),  /* idx=150, ratio=0.061237 */
    ALGO_MIN_ANGLE_PACK( 147u,  362u,  254u),  /* idx=151, ratio=0.062107 */
    ALGO_MIN_ANGLE_PACK( 143u,  373u,  235u),  /* idx=152, ratio=0.057445 */
    ALGO_MIN_ANGLE_PACK( 140u,  384u,  216u),  /* idx=153, ratio=0.052649 */
    ALGO_MIN_ANGLE_PACK( 136u,  395u,  205u),  /* idx=154, ratio=0.050001 */
    ALGO_MIN_ANGLE_PACK( 133u,  407u,  196u),  /* idx=155, ratio=0.047878 */
    ALGO_MIN_ANGLE_PACK( 129u,  418u,  185u),  /* idx=156, ratio=0.045152 */
    ALGO_MIN_ANGLE_PACK( 126u,  429u,  173u),  /* idx=157, ratio=0.042209 */
    ALGO_MIN_ANGLE_PACK( 122u,  440u,  145u),  /* idx=158, ratio=0.035486 */
    ALGO_MIN_ANGLE_PACK( 119u,  452u,   56u),  /* idx=159, ratio=0.013763 */
    ALGO_MIN_ANGLE_PACK( 115u,  463u,    0u),  /* idx=160, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 112u,  474u,    0u),  /* idx=161, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 108u,  485u,    0u),  /* idx=162, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 105u,  497u,    0u),  /* idx=163, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 101u,  508u,    0u),  /* idx=164, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  98u,  519u,    0u),  /* idx=165, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  94u,  530u,    0u),  /* idx=166, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  90u,  542u,    0u),  /* idx=167, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  87u,  553u,    0u),  /* idx=168, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  83u,  564u,    0u),  /* idx=169, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 233u,  124u,    0u),  /* idx=170, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 229u,  136u,  581u),  /* idx=171, ratio=0.141909 */
    ALGO_MIN_ANGLE_PACK( 226u,  147u, 1073u),  /* idx=172, ratio=0.262078 */
    ALGO_MIN_ANGLE_PACK( 222u,  158u, 1495u),  /* idx=173, ratio=0.365149 */
    ALGO_MIN_ANGLE_PACK( 219u,  169u, 1861u),  /* idx=174, ratio=0.454527 */
    ALGO_MIN_ANGLE_PACK( 215u,  181u, 2182u),  /* idx=175, ratio=0.532772 */
    ALGO_MIN_ANGLE_PACK( 212u,  192u, 2258u),  /* idx=176, ratio=0.551467 */
    ALGO_MIN_ANGLE_PACK( 208u,  203u, 2124u),  /* idx=177, ratio=0.518640 */
    ALGO_MIN_ANGLE_PACK( 204u,  214u, 2005u),  /* idx=178, ratio=0.489529 */
    ALGO_MIN_ANGLE_PACK( 201u,  226u, 1895u),  /* idx=179, ratio=0.462784 */
    ALGO_MIN_ANGLE_PACK( 197u,  237u, 1792u),  /* idx=180, ratio=0.437634 */
    ALGO_MIN_ANGLE_PACK( 194u,  248u, 1691u),  /* idx=181, ratio=0.412860 */
    ALGO_MIN_ANGLE_PACK( 190u,  259u, 1588u),  /* idx=182, ratio=0.387776 */
    ALGO_MIN_ANGLE_PACK( 187u,  271u, 1486u),  /* idx=183, ratio=0.362990 */
    ALGO_MIN_ANGLE_PACK( 183u,  282u, 1388u),  /* idx=184, ratio=0.339014 */
    ALGO_MIN_ANGLE_PACK( 180u,  293u, 1298u),  /* idx=185, ratio=0.316856 */
    ALGO_MIN_ANGLE_PACK( 176u,  304u, 1218u),  /* idx=186, ratio=0.297409 */
    ALGO_MIN_ANGLE_PACK( 173u,  316u, 1150u),  /* idx=187, ratio=0.280939 */
    ALGO_MIN_ANGLE_PACK( 169u,  327u, 1094u),  /* idx=188, ratio=0.267169 */
    ALGO_MIN_ANGLE_PACK( 166u,  338u, 1050u),  /* idx=189, ratio=0.256359 */
    ALGO_MIN_ANGLE_PACK( 162u,  349u, 1015u),  /* idx=190, ratio=0.247759 */
    ALGO_MIN_ANGLE_PACK( 159u,  361u,  990u),  /* idx=191, ratio=0.241646 */
    ALGO_MIN_ANGLE_PACK( 155u,  372u,  972u),  /* idx=192, ratio=0.237342 */
    ALGO_MIN_ANGLE_PACK( 151u,  383u,  930u),  /* idx=193, ratio=0.227186 */
    ALGO_MIN_ANGLE_PACK( 148u,  394u,  902u),  /* idx=194, ratio=0.220268 */
    ALGO_MIN_ANGLE_PACK( 144u,  406u,  879u),  /* idx=195, ratio=0.214667 */
    ALGO_MIN_ANGLE_PACK( 141u,  417u,  854u),  /* idx=196, ratio=0.208653 */
    ALGO_MIN_ANGLE_PACK( 137u,  428u,  825u),  /* idx=197, ratio=0.201463 */
    ALGO_MIN_ANGLE_PACK( 134u,  439u,  749u),  /* idx=198, ratio=0.182802 */
    ALGO_MIN_ANGLE_PACK( 130u,  451u,  643u),  /* idx=199, ratio=0.156920 */
    ALGO_MIN_ANGLE_PACK( 127u,  462u,  539u),  /* idx=200, ratio=0.131564 */
    ALGO_MIN_ANGLE_PACK( 123u,  473u,  440u),  /* idx=201, ratio=0.107377 */
    ALGO_MIN_ANGLE_PACK( 120u,  484u,  345u),  /* idx=202, ratio=0.084188 */
    ALGO_MIN_ANGLE_PACK( 116u,  496u,  247u),  /* idx=203, ratio=0.060350 */
    ALGO_MIN_ANGLE_PACK( 113u,  507u,  147u),  /* idx=204, ratio=0.035890 */
    ALGO_MIN_ANGLE_PACK( 109u,  518u,   37u),  /* idx=205, ratio=0.009113 */
    ALGO_MIN_ANGLE_PACK( 106u,  529u,    0u),  /* idx=206, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 102u,  541u,    0u),  /* idx=207, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  98u,  552u,    0u),  /* idx=208, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK(  95u,  563u,    0u),  /* idx=209, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 241u,  134u,    0u),  /* idx=210, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 237u,  146u,  541u),  /* idx=211, ratio=0.132082 */
    ALGO_MIN_ANGLE_PACK( 234u,  157u, 1004u),  /* idx=212, ratio=0.245231 */
    ALGO_MIN_ANGLE_PACK( 230u,  168u, 1406u),  /* idx=213, ratio=0.343246 */
    ALGO_MIN_ANGLE_PACK( 227u,  179u, 1757u),  /* idx=214, ratio=0.428973 */
    ALGO_MIN_ANGLE_PACK( 223u,  191u, 2066u),  /* idx=215, ratio=0.504585 */
    ALGO_MIN_ANGLE_PACK( 220u,  202u, 2341u),  /* idx=216, ratio=0.571775 */
    ALGO_MIN_ANGLE_PACK( 216u,  213u, 2588u),  /* idx=217, ratio=0.631874 */
    ALGO_MIN_ANGLE_PACK( 212u,  224u, 2809u),  /* idx=218, ratio=0.685949 */
    ALGO_MIN_ANGLE_PACK( 209u,  236u, 2823u),  /* idx=219, ratio=0.689393 */
    ALGO_MIN_ANGLE_PACK( 205u,  247u, 2694u),  /* idx=220, ratio=0.657844 */
    ALGO_MIN_ANGLE_PACK( 202u,  258u, 2581u),  /* idx=221, ratio=0.630195 */
    ALGO_MIN_ANGLE_PACK( 198u,  269u, 2475u),  /* idx=222, ratio=0.604316 */
    ALGO_MIN_ANGLE_PACK( 195u,  281u, 2375u),  /* idx=223, ratio=0.579936 */
    ALGO_MIN_ANGLE_PACK( 191u,  292u, 2278u),  /* idx=224, ratio=0.556283 */
    ALGO_MIN_ANGLE_PACK( 188u,  303u, 2181u),  /* idx=225, ratio=0.532706 */
    ALGO_MIN_ANGLE_PACK( 184u,  314u, 2078u),  /* idx=226, ratio=0.507512 */
    ALGO_MIN_ANGLE_PACK( 181u,  326u, 1980u),  /* idx=227, ratio=0.483595 */
    ALGO_MIN_ANGLE_PACK( 177u,  337u, 1889u),  /* idx=228, ratio=0.461362 */
    ALGO_MIN_ANGLE_PACK( 174u,  348u, 1809u),  /* idx=229, ratio=0.441693 */
    ALGO_MIN_ANGLE_PACK( 170u,  359u, 1744u),  /* idx=230, ratio=0.425868 */
    ALGO_MIN_ANGLE_PACK( 167u,  371u, 1691u),  /* idx=231, ratio=0.413058 */
    ALGO_MIN_ANGLE_PACK( 163u,  382u, 1650u),  /* idx=232, ratio=0.402983 */
    ALGO_MIN_ANGLE_PACK( 159u,  393u, 1595u),  /* idx=233, ratio=0.389542 */
    ALGO_MIN_ANGLE_PACK( 156u,  404u, 1563u),  /* idx=234, ratio=0.381795 */
    ALGO_MIN_ANGLE_PACK( 152u,  416u, 1518u),  /* idx=235, ratio=0.370801 */
    ALGO_MIN_ANGLE_PACK( 149u,  427u, 1470u),  /* idx=236, ratio=0.358928 */
    ALGO_MIN_ANGLE_PACK( 145u,  438u, 1346u),  /* idx=237, ratio=0.328709 */
    ALGO_MIN_ANGLE_PACK( 142u,  449u, 1222u),  /* idx=238, ratio=0.298441 */
    ALGO_MIN_ANGLE_PACK( 138u,  461u, 1104u),  /* idx=239, ratio=0.269582 */
    ALGO_MIN_ANGLE_PACK( 135u,  472u,  989u),  /* idx=240, ratio=0.241490 */
    ALGO_MIN_ANGLE_PACK( 131u,  483u,  876u),  /* idx=241, ratio=0.213910 */
    ALGO_MIN_ANGLE_PACK( 128u,  494u,  766u),  /* idx=242, ratio=0.187037 */
    ALGO_MIN_ANGLE_PACK( 124u,  506u,  651u),  /* idx=243, ratio=0.158926 */
    ALGO_MIN_ANGLE_PACK( 121u,  517u,  527u),  /* idx=244, ratio=0.128736 */
    ALGO_MIN_ANGLE_PACK( 117u,  528u,  392u),  /* idx=245, ratio=0.095795 */
    ALGO_MIN_ANGLE_PACK( 114u,  539u,  253u),  /* idx=246, ratio=0.061835 */
    ALGO_MIN_ANGLE_PACK( 110u,  551u,  128u),  /* idx=247, ratio=0.031330 */
    ALGO_MIN_ANGLE_PACK( 106u,  562u,    0u),  /* idx=248, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 249u,  145u,    0u),  /* idx=249, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 245u,  156u,  506u),  /* idx=250, ratio=0.123528 */
    ALGO_MIN_ANGLE_PACK( 242u,  167u,  944u),  /* idx=251, ratio=0.230419 */
    ALGO_MIN_ANGLE_PACK( 238u,  178u, 1326u),  /* idx=252, ratio=0.323822 */
    ALGO_MIN_ANGLE_PACK( 235u,  190u, 1663u),  /* idx=253, ratio=0.406138 */
    ALGO_MIN_ANGLE_PACK( 231u,  201u, 1962u),  /* idx=254, ratio=0.479231 */
    ALGO_MIN_ANGLE_PACK( 228u,  212u, 2230u),  /* idx=255, ratio=0.544568 */
    ALGO_MIN_ANGLE_PACK( 224u,  223u, 2471u),  /* idx=256, ratio=0.603322 */
    ALGO_MIN_ANGLE_PACK( 221u,  235u, 2688u),  /* idx=257, ratio=0.656440 */
    ALGO_MIN_ANGLE_PACK( 217u,  246u, 2886u),  /* idx=258, ratio=0.704696 */
    ALGO_MIN_ANGLE_PACK( 213u,  257u, 3066u),  /* idx=259, ratio=0.748728 */
    ALGO_MIN_ANGLE_PACK( 210u,  268u, 3231u),  /* idx=260, ratio=0.789068 */
    ALGO_MIN_ANGLE_PACK( 206u,  280u, 3234u),  /* idx=261, ratio=0.789727 */
    ALGO_MIN_ANGLE_PACK( 203u,  291u, 3114u),  /* idx=262, ratio=0.760438 */
    ALGO_MIN_ANGLE_PACK( 199u,  302u, 3004u),  /* idx=263, ratio=0.733619 */
    ALGO_MIN_ANGLE_PACK( 196u,  313u, 2903u),  /* idx=264, ratio=0.708942 */
    ALGO_MIN_ANGLE_PACK( 192u,  325u, 2814u),  /* idx=265, ratio=0.687137 */
    ALGO_MIN_ANGLE_PACK( 189u,  336u, 2728u),  /* idx=266, ratio=0.666278 */
    ALGO_MIN_ANGLE_PACK( 185u,  347u, 2638u),  /* idx=267, ratio=0.644257 */
    ALGO_MIN_ANGLE_PACK( 182u,  358u, 2536u),  /* idx=268, ratio=0.619297 */
    ALGO_MIN_ANGLE_PACK( 178u,  370u, 2439u),  /* idx=269, ratio=0.595549 */
    ALGO_MIN_ANGLE_PACK( 175u,  381u, 2357u),  /* idx=270, ratio=0.575691 */
    ALGO_MIN_ANGLE_PACK( 171u,  392u, 2289u),  /* idx=271, ratio=0.558912 */
    ALGO_MIN_ANGLE_PACK( 168u,  403u, 2231u),  /* idx=272, ratio=0.544906 */
    ALGO_MIN_ANGLE_PACK( 164u,  415u, 2168u),  /* idx=273, ratio=0.529350 */
    ALGO_MIN_ANGLE_PACK( 160u,  426u, 2070u),  /* idx=274, ratio=0.505388 */
    ALGO_MIN_ANGLE_PACK( 157u,  437u, 1932u),  /* idx=275, ratio=0.471770 */
    ALGO_MIN_ANGLE_PACK( 153u,  448u, 1795u),  /* idx=276, ratio=0.438233 */
    ALGO_MIN_ANGLE_PACK( 150u,  460u, 1660u),  /* idx=277, ratio=0.405323 */
    ALGO_MIN_ANGLE_PACK( 146u,  471u, 1528u),  /* idx=278, ratio=0.373194 */
    ALGO_MIN_ANGLE_PACK( 143u,  482u, 1401u),  /* idx=279, ratio=0.342019 */
    ALGO_MIN_ANGLE_PACK( 139u,  493u, 1276u),  /* idx=280, ratio=0.311509 */
    ALGO_MIN_ANGLE_PACK( 136u,  505u, 1147u),  /* idx=281, ratio=0.280191 */
    ALGO_MIN_ANGLE_PACK( 132u,  516u, 1010u),  /* idx=282, ratio=0.246565 */
    ALGO_MIN_ANGLE_PACK( 129u,  527u,  863u),  /* idx=283, ratio=0.210649 */
    ALGO_MIN_ANGLE_PACK( 125u,  538u,  714u),  /* idx=284, ratio=0.174361 */
    ALGO_MIN_ANGLE_PACK( 122u,  550u,  555u),  /* idx=285, ratio=0.135553 */
    ALGO_MIN_ANGLE_PACK( 118u,  561u,    0u),  /* idx=286, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 257u,  155u,    0u),  /* idx=287, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 253u,  166u,  475u),  /* idx=288, ratio=0.116015 */
    ALGO_MIN_ANGLE_PACK( 250u,  177u,  890u),  /* idx=289, ratio=0.217295 */
    ALGO_MIN_ANGLE_PACK( 246u,  188u, 1255u),  /* idx=290, ratio=0.306479 */
    ALGO_MIN_ANGLE_PACK( 243u,  200u, 1579u),  /* idx=291, ratio=0.385612 */
    ALGO_MIN_ANGLE_PACK( 239u,  211u, 1869u),  /* idx=292, ratio=0.456303 */
    ALGO_MIN_ANGLE_PACK( 236u,  222u, 2129u),  /* idx=293, ratio=0.519834 */
    ALGO_MIN_ANGLE_PACK( 232u,  233u, 2364u),  /* idx=294, ratio=0.577240 */
    ALGO_MIN_ANGLE_PACK( 229u,  245u, 2577u),  /* idx=295, ratio=0.629366 */
    ALGO_MIN_ANGLE_PACK( 225u,  256u, 2772u),  /* idx=296, ratio=0.676910 */
    ALGO_MIN_ANGLE_PACK( 221u,  267u, 2950u),  /* idx=297, ratio=0.720449 */
    ALGO_MIN_ANGLE_PACK( 218u,  278u, 3114u),  /* idx=298, ratio=0.760469 */
    ALGO_MIN_ANGLE_PACK( 214u,  290u, 3265u),  /* idx=299, ratio=0.797381 */
    ALGO_MIN_ANGLE_PACK( 211u,  301u, 3405u),  /* idx=300, ratio=0.831532 */
    ALGO_MIN_ANGLE_PACK( 207u,  312u, 3535u),  /* idx=301, ratio=0.863222 */
    ALGO_MIN_ANGLE_PACK( 204u,  323u, 3543u),  /* idx=302, ratio=0.865323 */
    ALGO_MIN_ANGLE_PACK( 200u,  335u, 3431u),  /* idx=303, ratio=0.837826 */
    ALGO_MIN_ANGLE_PACK( 197u,  346u, 3326u),  /* idx=304, ratio=0.812278 */
    ALGO_MIN_ANGLE_PACK( 193u,  357u, 3230u),  /* idx=305, ratio=0.788816 */
    ALGO_MIN_ANGLE_PACK( 190u,  368u, 3144u),  /* idx=306, ratio=0.767669 */
    ALGO_MIN_ANGLE_PACK( 186u,  380u, 3060u),  /* idx=307, ratio=0.747274 */
    ALGO_MIN_ANGLE_PACK( 183u,  391u, 2975u),  /* idx=308, ratio=0.726386 */
    ALGO_MIN_ANGLE_PACK( 179u,  402u, 2881u),  /* idx=309, ratio=0.703631 */
    ALGO_MIN_ANGLE_PACK( 176u,  413u, 2791u),  /* idx=310, ratio=0.681572 */
    ALGO_MIN_ANGLE_PACK( 172u,  425u, 2655u),  /* idx=311, ratio=0.648408 */
    ALGO_MIN_ANGLE_PACK( 168u,  436u, 2502u),  /* idx=312, ratio=0.611058 */
    ALGO_MIN_ANGLE_PACK( 165u,  447u, 2351u),  /* idx=313, ratio=0.574052 */
    ALGO_MIN_ANGLE_PACK( 161u,  458u, 2203u),  /* idx=314, ratio=0.537886 */
    ALGO_MIN_ANGLE_PACK( 158u,  470u, 2057u),  /* idx=315, ratio=0.502281 */
    ALGO_MIN_ANGLE_PACK( 154u,  481u, 1915u),  /* idx=316, ratio=0.467746 */
    ALGO_MIN_ANGLE_PACK( 151u,  492u, 1775u),  /* idx=317, ratio=0.433501 */
    ALGO_MIN_ANGLE_PACK( 147u,  503u, 1634u),  /* idx=318, ratio=0.398978 */
    ALGO_MIN_ANGLE_PACK( 144u,  515u, 1483u),  /* idx=319, ratio=0.362043 */
    ALGO_MIN_ANGLE_PACK( 140u,  526u, 1326u),  /* idx=320, ratio=0.323706 */
    ALGO_MIN_ANGLE_PACK( 137u,  537u, 1136u),  /* idx=321, ratio=0.277369 */
    ALGO_MIN_ANGLE_PACK( 133u,  548u,  556u),  /* idx=322, ratio=0.135839 */
    ALGO_MIN_ANGLE_PACK( 130u,  560u,    0u),  /* idx=323, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 265u,  165u,    0u),  /* idx=324, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 261u,  176u,  448u),  /* idx=325, ratio=0.109364 */
    ALGO_MIN_ANGLE_PACK( 258u,  187u,  842u),  /* idx=326, ratio=0.205585 */
    ALGO_MIN_ANGLE_PACK( 254u,  198u, 1191u),  /* idx=327, ratio=0.290899 */
    ALGO_MIN_ANGLE_PACK( 251u,  210u, 1503u),  /* idx=328, ratio=0.367061 */
    ALGO_MIN_ANGLE_PACK( 247u,  221u, 1783u),  /* idx=329, ratio=0.435468 */
    ALGO_MIN_ANGLE_PACK( 244u,  232u, 2036u),  /* idx=330, ratio=0.497248 */
    ALGO_MIN_ANGLE_PACK( 240u,  243u, 2266u),  /* idx=331, ratio=0.553319 */
    ALGO_MIN_ANGLE_PACK( 237u,  255u, 2475u),  /* idx=332, ratio=0.604437 */
    ALGO_MIN_ANGLE_PACK( 233u,  266u, 2667u),  /* idx=333, ratio=0.651232 */
    ALGO_MIN_ANGLE_PACK( 229u,  277u, 2843u),  /* idx=334, ratio=0.694228 */
    ALGO_MIN_ANGLE_PACK( 226u,  288u, 3005u),  /* idx=335, ratio=0.733871 */
    ALGO_MIN_ANGLE_PACK( 222u,  300u, 3155u),  /* idx=336, ratio=0.770538 */
    ALGO_MIN_ANGLE_PACK( 219u,  311u, 3295u),  /* idx=337, ratio=0.804553 */
    ALGO_MIN_ANGLE_PACK( 215u,  322u, 3424u),  /* idx=338, ratio=0.836192 */
    ALGO_MIN_ANGLE_PACK( 212u,  333u, 3545u),  /* idx=339, ratio=0.865697 */
    ALGO_MIN_ANGLE_PACK( 208u,  345u, 3658u),  /* idx=340, ratio=0.893276 */
    ALGO_MIN_ANGLE_PACK( 205u,  356u, 3764u),  /* idx=341, ratio=0.919112 */
    ALGO_MIN_ANGLE_PACK( 201u,  367u, 3734u),  /* idx=342, ratio=0.911846 */
    ALGO_MIN_ANGLE_PACK( 198u,  378u, 3623u),  /* idx=343, ratio=0.884742 */
    ALGO_MIN_ANGLE_PACK( 194u,  390u, 3518u),  /* idx=344, ratio=0.859204 */
    ALGO_MIN_ANGLE_PACK( 191u,  401u, 3420u),  /* idx=345, ratio=0.835098 */
    ALGO_MIN_ANGLE_PACK( 187u,  412u, 3326u),  /* idx=346, ratio=0.812308 */
    ALGO_MIN_ANGLE_PACK( 184u,  423u, 3238u),  /* idx=347, ratio=0.790729 */
    ALGO_MIN_ANGLE_PACK( 180u,  435u, 3046u),  /* idx=348, ratio=0.743807 */
    ALGO_MIN_ANGLE_PACK( 177u,  446u, 2887u),  /* idx=349, ratio=0.704966 */
    ALGO_MIN_ANGLE_PACK( 173u,  457u, 2725u),  /* idx=350, ratio=0.665432 */
    ALGO_MIN_ANGLE_PACK( 169u,  468u, 2567u),  /* idx=351, ratio=0.626902 */
    ALGO_MIN_ANGLE_PACK( 166u,  480u, 2412u),  /* idx=352, ratio=0.589083 */
    ALGO_MIN_ANGLE_PACK( 162u,  491u, 2260u),  /* idx=353, ratio=0.551971 */
    ALGO_MIN_ANGLE_PACK( 159u,  502u, 2105u),  /* idx=354, ratio=0.514072 */
    ALGO_MIN_ANGLE_PACK( 155u,  513u, 1943u),  /* idx=355, ratio=0.474492 */
    ALGO_MIN_ANGLE_PACK( 152u,  525u, 1744u),  /* idx=356, ratio=0.425893 */
    ALGO_MIN_ANGLE_PACK( 148u,  536u, 1138u),  /* idx=357, ratio=0.277969 */
    ALGO_MIN_ANGLE_PACK( 145u,  547u,  557u),  /* idx=358, ratio=0.136127 */
    ALGO_MIN_ANGLE_PACK( 141u,  558u,    0u),  /* idx=359, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 273u,  175u,    0u),  /* idx=360, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 269u,  186u,  424u),  /* idx=361, ratio=0.103433 */
    ALGO_MIN_ANGLE_PACK( 266u,  197u,  799u),  /* idx=362, ratio=0.195073 */
    ALGO_MIN_ANGLE_PACK( 262u,  209u, 1134u),  /* idx=363, ratio=0.276827 */
    ALGO_MIN_ANGLE_PACK( 259u,  220u, 1434u),  /* idx=364, ratio=0.350213 */
    ALGO_MIN_ANGLE_PACK( 255u,  231u, 1705u),  /* idx=365, ratio=0.416453 */
    ALGO_MIN_ANGLE_PACK( 252u,  242u, 1951u),  /* idx=366, ratio=0.476543 */
    ALGO_MIN_ANGLE_PACK( 248u,  254u, 2176u),  /* idx=367, ratio=0.531302 */
    ALGO_MIN_ANGLE_PACK( 245u,  265u, 2381u),  /* idx=368, ratio=0.581408 */
    ALGO_MIN_ANGLE_PACK( 241u,  276u, 2569u),  /* idx=369, ratio=0.627430 */
    ALGO_MIN_ANGLE_PACK( 238u,  287u, 2743u),  /* idx=370, ratio=0.669849 */
    ALGO_MIN_ANGLE_PACK( 234u,  299u, 2904u),  /* idx=371, ratio=0.709071 */
    ALGO_MIN_ANGLE_PACK( 230u,  310u, 3053u),  /* idx=372, ratio=0.745444 */
    ALGO_MIN_ANGLE_PACK( 227u,  321u, 3191u),  /* idx=373, ratio=0.779269 */
    ALGO_MIN_ANGLE_PACK( 223u,  332u, 3320u),  /* idx=374, ratio=0.810804 */
    ALGO_MIN_ANGLE_PACK( 220u,  344u, 3441u),  /* idx=375, ratio=0.840273 */
    ALGO_MIN_ANGLE_PACK( 216u,  355u, 3554u),  /* idx=376, ratio=0.867874 */
    ALGO_MIN_ANGLE_PACK( 213u,  366u, 3660u),  /* idx=377, ratio=0.893778 */
    ALGO_MIN_ANGLE_PACK( 209u,  377u, 3760u),  /* idx=378, ratio=0.918138 */
    ALGO_MIN_ANGLE_PACK( 206u,  389u, 3854u),  /* idx=379, ratio=0.941087 */
    ALGO_MIN_ANGLE_PACK( 202u,  400u, 3858u),  /* idx=380, ratio=0.942211 */
    ALGO_MIN_ANGLE_PACK( 199u,  411u, 3753u),  /* idx=381, ratio=0.916425 */
    ALGO_MIN_ANGLE_PACK( 195u,  422u, 3653u),  /* idx=382, ratio=0.892013 */
    ALGO_MIN_ANGLE_PACK( 192u,  434u, 3558u),  /* idx=383, ratio=0.868868 */
    ALGO_MIN_ANGLE_PACK( 188u,  445u, 3407u),  /* idx=384, ratio=0.831935 */
    ALGO_MIN_ANGLE_PACK( 185u,  456u, 3217u),  /* idx=385, ratio=0.785555 */
    ALGO_MIN_ANGLE_PACK( 181u,  467u, 3050u),  /* idx=386, ratio=0.744930 */
    ALGO_MIN_ANGLE_PACK( 177u,  479u, 2885u),  /* idx=387, ratio=0.704493 */
    ALGO_MIN_ANGLE_PACK( 174u,  490u, 2722u),  /* idx=388, ratio=0.664763 */
    ALGO_MIN_ANGLE_PACK( 170u,  501u, 2557u),  /* idx=389, ratio=0.624498 */
    ALGO_MIN_ANGLE_PACK( 167u,  512u, 2382u),  /* idx=390, ratio=0.581612 */
    ALGO_MIN_ANGLE_PACK( 163u,  524u, 1748u),  /* idx=391, ratio=0.426837 */
    ALGO_MIN_ANGLE_PACK( 160u,  535u, 1141u),  /* idx=392, ratio=0.278572 */
    ALGO_MIN_ANGLE_PACK( 156u,  546u,  559u),  /* idx=393, ratio=0.136417 */
    ALGO_MIN_ANGLE_PACK( 153u,  557u,    0u),  /* idx=394, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 281u,  185u,    0u),  /* idx=395, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 277u,  196u,  402u),  /* idx=396, ratio=0.098113 */
    ALGO_MIN_ANGLE_PACK( 274u,  207u,  760u),  /* idx=397, ratio=0.185583 */
    ALGO_MIN_ANGLE_PACK( 270u,  219u, 1081u),  /* idx=398, ratio=0.264053 */
    ALGO_MIN_ANGLE_PACK( 267u,  230u, 1371u),  /* idx=399, ratio=0.334843 */
    ALGO_MIN_ANGLE_PACK( 263u,  241u, 1634u),  /* idx=400, ratio=0.399029 */
    ALGO_MIN_ANGLE_PACK( 260u,  252u, 1873u),  /* idx=401, ratio=0.457494 */
    ALGO_MIN_ANGLE_PACK( 256u,  264u, 2092u),  /* idx=402, ratio=0.510970 */
    ALGO_MIN_ANGLE_PACK( 253u,  275u, 2293u),  /* idx=403, ratio=0.560069 */
    ALGO_MIN_ANGLE_PACK( 249u,  286u, 2479u),  /* idx=404, ratio=0.605307 */
    ALGO_MIN_ANGLE_PACK( 246u,  297u, 2650u),  /* idx=405, ratio=0.647123 */
    ALGO_MIN_ANGLE_PACK( 242u,  309u, 2809u),  /* idx=406, ratio=0.685892 */
    ALGO_MIN_ANGLE_PACK( 238u,  320u, 2956u),  /* idx=407, ratio=0.721933 */
    ALGO_MIN_ANGLE_PACK( 235u,  331u, 3094u),  /* idx=408, ratio=0.755526 */
    ALGO_MIN_ANGLE_PACK( 231u,  342u, 3222u),  /* idx=409, ratio=0.786911 */
    ALGO_MIN_ANGLE_PACK( 228u,  354u, 3343u),  /* idx=410, ratio=0.816300 */
    ALGO_MIN_ANGLE_PACK( 224u,  365u, 3456u),  /* idx=411, ratio=0.843877 */
    ALGO_MIN_ANGLE_PACK( 221u,  376u, 3562u),  /* idx=412, ratio=0.869804 */
    ALGO_MIN_ANGLE_PACK( 217u,  387u, 3662u),  /* idx=413, ratio=0.894225 */
    ALGO_MIN_ANGLE_PACK( 214u,  399u, 3756u),  /* idx=414, ratio=0.917269 */
    ALGO_MIN_ANGLE_PACK( 210u,  410u, 3845u),  /* idx=415, ratio=0.939047 */
    ALGO_MIN_ANGLE_PACK( 207u,  421u, 3930u),  /* idx=416, ratio=0.959662 */
    ALGO_MIN_ANGLE_PACK( 203u,  432u, 3964u),  /* idx=417, ratio=0.967999 */
    ALGO_MIN_ANGLE_PACK( 200u,  444u, 3863u),  /* idx=418, ratio=0.943454 */
    ALGO_MIN_ANGLE_PACK( 196u,  455u, 3709u),  /* idx=419, ratio=0.905825 */
    ALGO_MIN_ANGLE_PACK( 193u,  466u, 3489u),  /* idx=420, ratio=0.852120 */
    ALGO_MIN_ANGLE_PACK( 189u,  477u, 3323u),  /* idx=421, ratio=0.811414 */
    ALGO_MIN_ANGLE_PACK( 186u,  489u, 3153u),  /* idx=422, ratio=0.770007 */
    ALGO_MIN_ANGLE_PACK( 182u,  500u, 2982u),  /* idx=423, ratio=0.728227 */
    ALGO_MIN_ANGLE_PACK( 178u,  511u, 2387u),  /* idx=424, ratio=0.582932 */
    ALGO_MIN_ANGLE_PACK( 175u,  522u, 1752u),  /* idx=425, ratio=0.427784 */
    ALGO_MIN_ANGLE_PACK( 171u,  534u, 1143u),  /* idx=426, ratio=0.279177 */
    ALGO_MIN_ANGLE_PACK( 168u,  545u,  560u),  /* idx=427, ratio=0.136707 */
    ALGO_MIN_ANGLE_PACK( 164u,  556u,    0u),  /* idx=428, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 289u,  195u,    0u),  /* idx=429, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 285u,  206u,  382u),  /* idx=430, ratio=0.093313 */
    ALGO_MIN_ANGLE_PACK( 282u,  217u,  725u),  /* idx=431, ratio=0.176974 */
    ALGO_MIN_ANGLE_PACK( 278u,  229u, 1034u),  /* idx=432, ratio=0.252406 */
    ALGO_MIN_ANGLE_PACK( 275u,  240u, 1314u),  /* idx=433, ratio=0.320766 */
    ALGO_MIN_ANGLE_PACK( 271u,  251u, 1568u),  /* idx=434, ratio=0.383005 */
    ALGO_MIN_ANGLE_PACK( 268u,  262u, 1801u),  /* idx=435, ratio=0.439909 */
    ALGO_MIN_ANGLE_PACK( 264u,  274u, 2015u),  /* idx=436, ratio=0.492136 */
    ALGO_MIN_ANGLE_PACK( 261u,  285u, 2212u),  /* idx=437, ratio=0.540241 */
    ALGO_MIN_ANGLE_PACK( 257u,  296u, 2394u),  /* idx=438, ratio=0.584691 */
    ALGO_MIN_ANGLE_PACK( 254u,  307u, 2563u),  /* idx=439, ratio=0.625890 */
    ALGO_MIN_ANGLE_PACK( 250u,  319u, 2720u),  /* idx=440, ratio=0.664180 */
    ALGO_MIN_ANGLE_PACK( 247u,  330u, 2866u),  /* idx=441, ratio=0.699860 */
    ALGO_MIN_ANGLE_PACK( 243u,  341u, 3002u),  /* idx=442, ratio=0.733187 */
    ALGO_MIN_ANGLE_PACK( 239u,  352u, 3130u),  /* idx=443, ratio=0.764387 */
    ALGO_MIN_ANGLE_PACK( 236u,  364u, 3250u),  /* idx=444, ratio=0.793657 */
    ALGO_MIN_ANGLE_PACK( 232u,  375u, 3363u),  /* idx=445, ratio=0.821171 */
    ALGO_MIN_ANGLE_PACK( 229u,  386u, 3469u),  /* idx=446, ratio=0.847082 */
    ALGO_MIN_ANGLE_PACK( 225u,  397u, 3569u),  /* idx=447, ratio=0.871527 */
    ALGO_MIN_ANGLE_PACK( 222u,  409u, 3663u),  /* idx=448, ratio=0.894626 */
    ALGO_MIN_ANGLE_PACK( 218u,  420u, 3753u),  /* idx=449, ratio=0.916488 */
    ALGO_MIN_ANGLE_PACK( 215u,  431u, 3838u),  /* idx=450, ratio=0.937209 */
    ALGO_MIN_ANGLE_PACK( 211u,  442u, 3918u),  /* idx=451, ratio=0.956876 */
    ALGO_MIN_ANGLE_PACK( 208u,  454u, 3995u),  /* idx=452, ratio=0.975568 */
    ALGO_MIN_ANGLE_PACK( 204u,  465u, 3928u),  /* idx=453, ratio=0.959211 */
    ALGO_MIN_ANGLE_PACK( 201u,  476u, 3706u),  /* idx=454, ratio=0.905118 */
    ALGO_MIN_ANGLE_PACK( 197u,  487u, 3540u),  /* idx=455, ratio=0.864429 */
    ALGO_MIN_ANGLE_PACK( 194u,  499u, 3058u),  /* idx=456, ratio=0.746795 */
    ALGO_MIN_ANGLE_PACK( 190u,  510u, 2393u),  /* idx=457, ratio=0.584258 */
    ALGO_MIN_ANGLE_PACK( 186u,  521u, 1756u),  /* idx=458, ratio=0.428736 */
    ALGO_MIN_ANGLE_PACK( 183u,  532u, 1146u),  /* idx=459, ratio=0.279786 */
    ALGO_MIN_ANGLE_PACK( 179u,  544u,  561u),  /* idx=460, ratio=0.136998 */
    ALGO_MIN_ANGLE_PACK( 176u,  555u,    0u),  /* idx=461, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 297u,  205u,    0u),  /* idx=462, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 293u,  216u,  364u),  /* idx=463, ratio=0.088961 */
    ALGO_MIN_ANGLE_PACK( 290u,  228u,  693u),  /* idx=464, ratio=0.169128 */
    ALGO_MIN_ANGLE_PACK( 286u,  239u,  990u),  /* idx=465, ratio=0.241743 */
    ALGO_MIN_ANGLE_PACK( 283u,  250u, 1261u),  /* idx=466, ratio=0.307825 */
    ALGO_MIN_ANGLE_PACK( 279u,  261u, 1508u),  /* idx=467, ratio=0.368218 */
    ALGO_MIN_ANGLE_PACK( 276u,  273u, 1735u),  /* idx=468, ratio=0.423626 */
    ALGO_MIN_ANGLE_PACK( 272u,  284u, 1944u),  /* idx=469, ratio=0.474642 */
    ALGO_MIN_ANGLE_PACK( 269u,  295u, 2137u),  /* idx=470, ratio=0.521768 */
    ALGO_MIN_ANGLE_PACK( 265u,  306u, 2315u),  /* idx=471, ratio=0.565433 */
    ALGO_MIN_ANGLE_PACK( 262u,  318u, 2482u),  /* idx=472, ratio=0.606005 */
    ALGO_MIN_ANGLE_PACK( 258u,  329u, 2636u),  /* idx=473, ratio=0.643801 */
    ALGO_MIN_ANGLE_PACK( 255u,  340u, 2781u),  /* idx=474, ratio=0.679096 */
    ALGO_MIN_ANGLE_PACK( 251u,  351u, 2916u),  /* idx=475, ratio=0.712131 */
    ALGO_MIN_ANGLE_PACK( 247u,  363u, 3043u),  /* idx=476, ratio=0.743116 */
    ALGO_MIN_ANGLE_PACK( 244u,  374u, 3162u),  /* idx=477, ratio=0.772236 */
    ALGO_MIN_ANGLE_PACK( 240u,  385u, 3275u),  /* idx=478, ratio=0.799655 */
    ALGO_MIN_ANGLE_PACK( 237u,  396u, 3380u),  /* idx=479, ratio=0.825517 */
    ALGO_MIN_ANGLE_PACK( 233u,  408u, 3481u),  /* idx=480, ratio=0.849952 */
    ALGO_MIN_ANGLE_PACK( 230u,  419u, 3575u),  /* idx=481, ratio=0.873074 */
    ALGO_MIN_ANGLE_PACK( 226u,  430u, 3665u),  /* idx=482, ratio=0.894987 */
    ALGO_MIN_ANGLE_PACK( 223u,  441u, 3750u),  /* idx=483, ratio=0.915782 */
    ALGO_MIN_ANGLE_PACK( 219u,  453u, 3831u),  /* idx=484, ratio=0.935544 */
    ALGO_MIN_ANGLE_PACK( 216u,  464u, 3908u),  /* idx=485, ratio=0.954347 */
    ALGO_MIN_ANGLE_PACK( 212u,  475u, 3981u),  /* idx=486, ratio=0.972259 */
    ALGO_MIN_ANGLE_PACK( 209u,  486u, 3763u),  /* idx=487, ratio=0.919021 */
    ALGO_MIN_ANGLE_PACK( 205u,  498u, 3065u),  /* idx=488, ratio=0.748536 */
    ALGO_MIN_ANGLE_PACK( 202u,  509u, 2398u),  /* idx=489, ratio=0.585589 */
    ALGO_MIN_ANGLE_PACK( 198u,  520u, 1760u),  /* idx=490, ratio=0.429692 */
    ALGO_MIN_ANGLE_PACK( 194u,  531u, 1148u),  /* idx=491, ratio=0.280396 */
    ALGO_MIN_ANGLE_PACK( 191u,  543u,  562u),  /* idx=492, ratio=0.137291 */
    ALGO_MIN_ANGLE_PACK( 187u,  554u,    0u),  /* idx=493, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 305u,  215u,    0u),  /* idx=494, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 301u,  226u,  348u),  /* idx=495, ratio=0.084997 */
    ALGO_MIN_ANGLE_PACK( 298u,  238u,  663u),  /* idx=496, ratio=0.161948 */
    ALGO_MIN_ANGLE_PACK( 294u,  249u,  950u),  /* idx=497, ratio=0.231944 */
    ALGO_MIN_ANGLE_PACK( 291u,  260u, 1212u),  /* idx=498, ratio=0.295887 */
    ALGO_MIN_ANGLE_PACK( 287u,  271u, 1452u),  /* idx=499, ratio=0.354530 */
    ALGO_MIN_ANGLE_PACK( 284u,  283u, 1673u),  /* idx=500, ratio=0.408505 */
    ALGO_MIN_ANGLE_PACK( 280u,  294u, 1877u),  /* idx=501, ratio=0.458349 */
    ALGO_MIN_ANGLE_PACK( 277u,  305u, 2066u),  /* idx=502, ratio=0.504518 */
    ALGO_MIN_ANGLE_PACK( 273u,  316u, 2242u),  /* idx=503, ratio=0.547404 */
    ALGO_MIN_ANGLE_PACK( 270u,  328u, 2405u),  /* idx=504, ratio=0.587345 */
    ALGO_MIN_ANGLE_PACK( 266u,  339u, 2558u),  /* idx=505, ratio=0.624635 */
    ALGO_MIN_ANGLE_PACK( 263u,  350u, 2701u),  /* idx=506, ratio=0.659529 */
    ALGO_MIN_ANGLE_PACK( 259u,  361u, 2835u),  /* idx=507, ratio=0.692251 */
    ALGO_MIN_ANGLE_PACK( 256u,  373u, 2961u),  /* idx=508, ratio=0.722997 */
    ALGO_MIN_ANGLE_PACK( 252u,  384u, 3079u),  /* idx=509, ratio=0.751941 */
    ALGO_MIN_ANGLE_PACK( 248u,  395u, 3191u),  /* idx=510, ratio=0.779238 */
    ALGO_MIN_ANGLE_PACK( 245u,  406u, 3297u),  /* idx=511, ratio=0.805023 */
    ALGO_MIN_ANGLE_PACK( 241u,  418u, 3396u),  /* idx=512, ratio=0.829420 */
    ALGO_MIN_ANGLE_PACK( 238u,  429u, 3491u),  /* idx=513, ratio=0.852536 */
    ALGO_MIN_ANGLE_PACK( 234u,  440u, 3581u),  /* idx=514, ratio=0.874471 */
    ALGO_MIN_ANGLE_PACK( 231u,  451u, 3666u),  /* idx=515, ratio=0.895313 */
    ALGO_MIN_ANGLE_PACK( 227u,  463u, 3748u),  /* idx=516, ratio=0.915142 */
    ALGO_MIN_ANGLE_PACK( 224u,  474u, 3825u),  /* idx=517, ratio=0.934029 */
    ALGO_MIN_ANGLE_PACK( 220u,  485u, 3772u),  /* idx=518, ratio=0.921218 */
    ALGO_MIN_ANGLE_PACK( 217u,  496u, 3072u),  /* idx=519, ratio=0.750285 */
    ALGO_MIN_ANGLE_PACK( 213u,  508u, 2403u),  /* idx=520, ratio=0.586927 */
    ALGO_MIN_ANGLE_PACK( 210u,  519u, 1764u),  /* idx=521, ratio=0.430653 */
    ALGO_MIN_ANGLE_PACK( 206u,  530u, 1151u),  /* idx=522, ratio=0.281010 */
    ALGO_MIN_ANGLE_PACK( 203u,  541u,  563u),  /* idx=523, ratio=0.137585 */
    ALGO_MIN_ANGLE_PACK( 199u,  553u,    0u),  /* idx=524, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 313u,  225u,    0u),  /* idx=525, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 309u,  237u,  333u),  /* idx=526, ratio=0.081371 */
    ALGO_MIN_ANGLE_PACK( 306u,  248u,  636u),  /* idx=527, ratio=0.155353 */
    ALGO_MIN_ANGLE_PACK( 302u,  259u,  913u),  /* idx=528, ratio=0.222909 */
    ALGO_MIN_ANGLE_PACK( 299u,  270u, 1166u),  /* idx=529, ratio=0.284841 */
    ALGO_MIN_ANGLE_PACK( 295u,  281u, 1400u),  /* idx=530, ratio=0.341824 */
    ALGO_MIN_ANGLE_PACK( 292u,  293u, 1615u),  /* idx=531, ratio=0.394427 */
    ALGO_MIN_ANGLE_PACK( 288u,  304u, 1815u),  /* idx=532, ratio=0.443137 */
    ALGO_MIN_ANGLE_PACK( 285u,  315u, 2000u),  /* idx=533, ratio=0.488371 */
    ALGO_MIN_ANGLE_PACK( 281u,  326u, 2172u),  /* idx=534, ratio=0.530488 */
    ALGO_MIN_ANGLE_PACK( 278u,  338u, 2333u),  /* idx=535, ratio=0.569800 */
    ALGO_MIN_ANGLE_PACK( 274u,  349u, 2484u),  /* idx=536, ratio=0.606577 */
    ALGO_MIN_ANGLE_PACK( 271u,  360u, 2625u),  /* idx=537, ratio=0.641058 */
    ALGO_MIN_ANGLE_PACK( 267u,  371u, 2758u),  /* idx=538, ratio=0.673450 */
    ALGO_MIN_ANGLE_PACK( 264u,  383u, 2883u),  /* idx=539, ratio=0.703938 */
    ALGO_MIN_ANGLE_PACK( 260u,  394u, 3000u),  /* idx=540, ratio=0.732686 */
    ALGO_MIN_ANGLE_PACK( 256u,  405u, 3112u),  /* idx=541, ratio=0.759837 */
    ALGO_MIN_ANGLE_PACK( 253u,  416u, 3217u),  /* idx=542, ratio=0.785522 */
    ALGO_MIN_ANGLE_PACK( 249u,  428u, 3316u),  /* idx=543, ratio=0.809856 */
    ALGO_MIN_ANGLE_PACK( 246u,  439u, 3411u),  /* idx=544, ratio=0.832943 */
    ALGO_MIN_ANGLE_PACK( 242u,  450u, 3501u),  /* idx=545, ratio=0.854876 */
    ALGO_MIN_ANGLE_PACK( 239u,  461u, 3586u),  /* idx=546, ratio=0.875739 */
    ALGO_MIN_ANGLE_PACK( 235u,  473u, 3668u),  /* idx=547, ratio=0.895610 */
    ALGO_MIN_ANGLE_PACK( 232u,  484u, 3745u),  /* idx=548, ratio=0.914558 */
    ALGO_MIN_ANGLE_PACK( 228u,  495u, 3080u),  /* idx=549, ratio=0.752042 */
    ALGO_MIN_ANGLE_PACK( 225u,  506u, 2409u),  /* idx=550, ratio=0.588271 */
    ALGO_MIN_ANGLE_PACK( 221u,  518u, 1767u),  /* idx=551, ratio=0.431617 */
    ALGO_MIN_ANGLE_PACK( 218u,  529u, 1153u),  /* idx=552, ratio=0.281626 */
    ALGO_MIN_ANGLE_PACK( 214u,  540u,  565u),  /* idx=553, ratio=0.137881 */
    ALGO_MIN_ANGLE_PACK( 211u,  551u,    0u),  /* idx=554, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 321u,  235u,    0u),  /* idx=555, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 317u,  247u,  320u),  /* idx=556, ratio=0.078042 */
    ALGO_MIN_ANGLE_PACK( 314u,  258u,  611u),  /* idx=557, ratio=0.149275 */
    ALGO_MIN_ANGLE_PACK( 310u,  269u,  879u),  /* idx=558, ratio=0.214552 */
    ALGO_MIN_ANGLE_PACK( 307u,  280u, 1124u),  /* idx=559, ratio=0.274590 */
    ALGO_MIN_ANGLE_PACK( 303u,  292u, 1351u),  /* idx=560, ratio=0.329996 */
    ALGO_MIN_ANGLE_PACK( 300u,  303u, 1561u),  /* idx=561, ratio=0.381286 */
    ALGO_MIN_ANGLE_PACK( 296u,  314u, 1756u),  /* idx=562, ratio=0.428903 */
    ALGO_MIN_ANGLE_PACK( 293u,  325u, 1938u),  /* idx=563, ratio=0.473226 */
    ALGO_MIN_ANGLE_PACK( 289u,  337u, 2107u),  /* idx=564, ratio=0.514587 */
    ALGO_MIN_ANGLE_PACK( 286u,  348u, 2266u),  /* idx=565, ratio=0.553272 */
    ALGO_MIN_ANGLE_PACK( 282u,  359u, 2414u),  /* idx=566, ratio=0.589534 */
    ALGO_MIN_ANGLE_PACK( 279u,  370u, 2554u),  /* idx=567, ratio=0.623593 */
    ALGO_MIN_ANGLE_PACK( 275u,  382u, 2685u),  /* idx=568, ratio=0.655644 */
    ALGO_MIN_ANGLE_PACK( 272u,  393u, 2809u),  /* idx=569, ratio=0.685859 */
    ALGO_MIN_ANGLE_PACK( 268u,  404u, 2925u),  /* idx=570, ratio=0.714392 */
    ALGO_MIN_ANGLE_PACK( 265u,  415u, 3036u),  /* idx=571, ratio=0.741379 */
    ALGO_MIN_ANGLE_PACK( 261u,  427u, 3141u),  /* idx=572, ratio=0.766943 */
    ALGO_MIN_ANGLE_PACK( 257u,  438u, 3240u),  /* idx=573, ratio=0.791194 */
    ALGO_MIN_ANGLE_PACK( 254u,  449u, 3334u),  /* idx=574, ratio=0.814229 */
    ALGO_MIN_ANGLE_PACK( 250u,  460u, 3424u),  /* idx=575, ratio=0.836139 */
    ALGO_MIN_ANGLE_PACK( 247u,  472u, 3509u),  /* idx=576, ratio=0.857003 */
    ALGO_MIN_ANGLE_PACK( 243u,  483u, 3591u),  /* idx=577, ratio=0.876895 */
    ALGO_MIN_ANGLE_PACK( 240u,  494u, 3087u),  /* idx=578, ratio=0.753807 */
    ALGO_MIN_ANGLE_PACK( 236u,  505u, 2414u),  /* idx=579, ratio=0.589621 */
    ALGO_MIN_ANGLE_PACK( 233u,  517u, 1771u),  /* idx=580, ratio=0.432586 */
    ALGO_MIN_ANGLE_PACK( 229u,  528u, 1156u),  /* idx=581, ratio=0.282245 */
    ALGO_MIN_ANGLE_PACK( 226u,  539u,  566u),  /* idx=582, ratio=0.138177 */
    ALGO_MIN_ANGLE_PACK( 222u,  550u,    0u),  /* idx=583, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 329u,  245u,    0u),  /* idx=584, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 326u,  257u,  307u),  /* idx=585, ratio=0.074975 */
    ALGO_MIN_ANGLE_PACK( 322u,  268u,  588u),  /* idx=586, ratio=0.143654 */
    ALGO_MIN_ANGLE_PACK( 318u,  279u,  847u),  /* idx=587, ratio=0.206798 */
    ALGO_MIN_ANGLE_PACK( 315u,  290u, 1085u),  /* idx=588, ratio=0.265051 */
    ALGO_MIN_ANGLE_PACK( 311u,  302u, 1306u),  /* idx=589, ratio=0.318960 */
    ALGO_MIN_ANGLE_PACK( 308u,  313u, 1511u),  /* idx=590, ratio=0.368993 */
    ALGO_MIN_ANGLE_PACK( 304u,  324u, 1702u),  /* idx=591, ratio=0.415554 */
    ALGO_MIN_ANGLE_PACK( 301u,  335u, 1880u),  /* idx=592, ratio=0.458992 */
    ALGO_MIN_ANGLE_PACK( 297u,  347u, 2046u),  /* idx=593, ratio=0.499611 */
    ALGO_MIN_ANGLE_PACK( 294u,  358u, 2202u),  /* idx=594, ratio=0.537677 */
    ALGO_MIN_ANGLE_PACK( 290u,  369u, 2348u),  /* idx=595, ratio=0.573423 */
    ALGO_MIN_ANGLE_PACK( 287u,  380u, 2486u),  /* idx=596, ratio=0.607055 */
    ALGO_MIN_ANGLE_PACK( 283u,  392u, 2616u),  /* idx=597, ratio=0.638755 */
    ALGO_MIN_ANGLE_PACK( 280u,  403u, 2738u),  /* idx=598, ratio=0.668685 */
    ALGO_MIN_ANGLE_PACK( 276u,  414u, 2854u),  /* idx=599, ratio=0.696989 */
    ALGO_MIN_ANGLE_PACK( 273u,  425u, 2964u),  /* idx=600, ratio=0.723797 */
    ALGO_MIN_ANGLE_PACK( 269u,  437u, 3068u),  /* idx=601, ratio=0.749223 */
    ALGO_MIN_ANGLE_PACK( 265u,  448u, 3167u),  /* idx=602, ratio=0.773372 */
    ALGO_MIN_ANGLE_PACK( 262u,  459u, 3261u),  /* idx=603, ratio=0.796338 */
    ALGO_MIN_ANGLE_PACK( 258u,  470u, 3351u),  /* idx=604, ratio=0.818206 */
    ALGO_MIN_ANGLE_PACK( 255u,  482u, 3436u),  /* idx=605, ratio=0.839052 */
    ALGO_MIN_ANGLE_PACK( 251u,  493u, 3094u),  /* idx=606, ratio=0.755581 */
    ALGO_MIN_ANGLE_PACK( 248u,  504u, 2420u),  /* idx=607, ratio=0.590978 */
    ALGO_MIN_ANGLE_PACK( 244u,  515u, 1775u),  /* idx=608, ratio=0.433560 */
    ALGO_MIN_ANGLE_PACK( 241u,  527u, 1158u),  /* idx=609, ratio=0.282866 */
    ALGO_MIN_ANGLE_PACK( 237u,  538u,  567u),  /* idx=610, ratio=0.138475 */
    ALGO_MIN_ANGLE_PACK( 234u,  549u,    0u),  /* idx=611, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 337u,  256u,    0u),  /* idx=612, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 334u,  267u,  295u),  /* idx=613, ratio=0.072139 */
    ALGO_MIN_ANGLE_PACK( 330u,  278u,  567u),  /* idx=614, ratio=0.138440 */
    ALGO_MIN_ANGLE_PACK( 326u,  289u,  817u),  /* idx=615, ratio=0.199585 */
    ALGO_MIN_ANGLE_PACK( 323u,  301u, 1049u),  /* idx=616, ratio=0.256153 */
    ALGO_MIN_ANGLE_PACK( 319u,  312u, 1264u),  /* idx=617, ratio=0.308638 */
    ALGO_MIN_ANGLE_PACK( 316u,  323u, 1464u),  /* idx=618, ratio=0.357468 */
    ALGO_MIN_ANGLE_PACK( 312u,  334u, 1650u),  /* idx=619, ratio=0.403011 */
    ALGO_MIN_ANGLE_PACK( 309u,  346u, 1825u),  /* idx=620, ratio=0.445589 */
    ALGO_MIN_ANGLE_PACK( 305u,  357u, 1988u),  /* idx=621, ratio=0.485482 */
    ALGO_MIN_ANGLE_PACK( 302u,  368u, 2141u),  /* idx=622, ratio=0.522936 */
    ALGO_MIN_ANGLE_PACK( 298u,  379u, 2286u),  /* idx=623, ratio=0.558168 */
    ALGO_MIN_ANGLE_PACK( 295u,  391u, 2422u),  /* idx=624, ratio=0.591371 */
    ALGO_MIN_ANGLE_PACK( 291u,  402u, 2550u),  /* idx=625, ratio=0.622714 */
    ALGO_MIN_ANGLE_PACK( 288u,  413u, 2671u),  /* idx=626, ratio=0.652350 */
    ALGO_MIN_ANGLE_PACK( 284u,  424u, 2786u),  /* idx=627, ratio=0.680414 */
    ALGO_MIN_ANGLE_PACK( 281u,  436u, 2895u),  /* idx=628, ratio=0.707029 */
    ALGO_MIN_ANGLE_PACK( 277u,  447u, 2999u),  /* idx=629, ratio=0.732303 */
    ALGO_MIN_ANGLE_PACK( 274u,  458u, 3097u),  /* idx=630, ratio=0.756336 */
    ALGO_MIN_ANGLE_PACK( 270u,  469u, 3191u),  /* idx=631, ratio=0.779217 */
    ALGO_MIN_ANGLE_PACK( 266u,  480u, 3280u),  /* idx=632, ratio=0.801026 */
    ALGO_MIN_ANGLE_PACK( 263u,  492u, 3101u),  /* idx=633, ratio=0.757363 */
    ALGO_MIN_ANGLE_PACK( 259u,  503u, 2426u),  /* idx=634, ratio=0.592340 */
    ALGO_MIN_ANGLE_PACK( 256u,  514u, 1779u),  /* idx=635, ratio=0.434537 */
    ALGO_MIN_ANGLE_PACK( 252u,  525u, 1161u),  /* idx=636, ratio=0.283490 */
    ALGO_MIN_ANGLE_PACK( 249u,  537u,  568u),  /* idx=637, ratio=0.138775 */
    ALGO_MIN_ANGLE_PACK( 245u,  548u,    0u),  /* idx=638, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 345u,  266u,    0u),  /* idx=639, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 342u,  277u,  285u),  /* idx=640, ratio=0.069510 */
    ALGO_MIN_ANGLE_PACK( 338u,  288u,  547u),  /* idx=641, ratio=0.133593 */
    ALGO_MIN_ANGLE_PACK( 335u,  299u,  790u),  /* idx=642, ratio=0.192859 */
    ALGO_MIN_ANGLE_PACK( 331u,  311u, 1015u),  /* idx=643, ratio=0.247832 */
    ALGO_MIN_ANGLE_PACK( 327u,  322u, 1224u),  /* idx=644, ratio=0.298963 */
    ALGO_MIN_ANGLE_PACK( 324u,  333u, 1419u),  /* idx=645, ratio=0.346641 */
    ALGO_MIN_ANGLE_PACK( 320u,  344u, 1602u),  /* idx=646, ratio=0.391204 */
    ALGO_MIN_ANGLE_PACK( 317u,  356u, 1773u),  /* idx=647, ratio=0.432947 */
    ALGO_MIN_ANGLE_PACK( 313u,  367u, 1933u),  /* idx=648, ratio=0.472130 */
    ALGO_MIN_ANGLE_PACK( 310u,  378u, 2084u),  /* idx=649, ratio=0.508982 */
    ALGO_MIN_ANGLE_PACK( 306u,  389u, 2226u),  /* idx=650, ratio=0.543705 */
    ALGO_MIN_ANGLE_PACK( 303u,  401u, 2361u),  /* idx=651, ratio=0.576477 */
    ALGO_MIN_ANGLE_PACK( 299u,  412u, 2488u),  /* idx=652, ratio=0.607459 */
    ALGO_MIN_ANGLE_PACK( 296u,  423u, 2608u),  /* idx=653, ratio=0.636794 */
    ALGO_MIN_ANGLE_PACK( 292u,  434u, 2722u),  /* idx=654, ratio=0.664609 */
    ALGO_MIN_ANGLE_PACK( 289u,  446u, 2830u),  /* idx=655, ratio=0.691020 */
    ALGO_MIN_ANGLE_PACK( 285u,  457u, 2933u),  /* idx=656, ratio=0.716131 */
    ALGO_MIN_ANGLE_PACK( 282u,  468u, 3030u),  /* idx=657, ratio=0.740034 */
    ALGO_MIN_ANGLE_PACK( 278u,  479u, 3124u),  /* idx=658, ratio=0.762816 */
    ALGO_MIN_ANGLE_PACK( 274u,  491u, 3109u),  /* idx=659, ratio=0.759153 */
    ALGO_MIN_ANGLE_PACK( 271u,  502u, 2431u),  /* idx=660, ratio=0.593709 */
    ALGO_MIN_ANGLE_PACK( 267u,  513u, 1783u),  /* idx=661, ratio=0.435520 */
    ALGO_MIN_ANGLE_PACK( 264u,  524u, 1163u),  /* idx=662, ratio=0.284117 */
    ALGO_MIN_ANGLE_PACK( 260u,  536u,  570u),  /* idx=663, ratio=0.139075 */
    ALGO_MIN_ANGLE_PACK( 257u,  547u,    0u),  /* idx=664, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 353u,  276u,    0u),  /* idx=665, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 350u,  287u,  275u),  /* idx=666, ratio=0.067066 */
    ALGO_MIN_ANGLE_PACK( 346u,  298u,  529u),  /* idx=667, ratio=0.129073 */
    ALGO_MIN_ANGLE_PACK( 343u,  309u,  764u),  /* idx=668, ratio=0.186571 */
    ALGO_MIN_ANGLE_PACK( 339u,  321u,  983u),  /* idx=669, ratio=0.240036 */
    ALGO_MIN_ANGLE_PACK( 335u,  332u, 1187u),  /* idx=670, ratio=0.289877 */
    ALGO_MIN_ANGLE_PACK( 332u,  343u, 1378u),  /* idx=671, ratio=0.336451 */
    ALGO_MIN_ANGLE_PACK( 328u,  354u, 1556u),  /* idx=672, ratio=0.380068 */
    ALGO_MIN_ANGLE_PACK( 325u,  366u, 1724u),  /* idx=673, ratio=0.421002 */
    ALGO_MIN_ANGLE_PACK( 321u,  377u, 1882u),  /* idx=674, ratio=0.459493 */
    ALGO_MIN_ANGLE_PACK( 318u,  388u, 2030u),  /* idx=675, ratio=0.495754 */
    ALGO_MIN_ANGLE_PACK( 314u,  399u, 2170u),  /* idx=676, ratio=0.529972 */
    ALGO_MIN_ANGLE_PACK( 311u,  411u, 2303u),  /* idx=677, ratio=0.562315 */
    ALGO_MIN_ANGLE_PACK( 307u,  422u, 2428u),  /* idx=678, ratio=0.592934 */
    ALGO_MIN_ANGLE_PACK( 304u,  433u, 2547u),  /* idx=679, ratio=0.621963 */
    ALGO_MIN_ANGLE_PACK( 300u,  444u, 2660u),  /* idx=680, ratio=0.649522 */
    ALGO_MIN_ANGLE_PACK( 297u,  456u, 2767u),  /* idx=681, ratio=0.675721 */
    ALGO_MIN_ANGLE_PACK( 293u,  467u, 2869u),  /* idx=682, ratio=0.700657 */
    ALGO_MIN_ANGLE_PACK( 290u,  478u, 2967u),  /* idx=683, ratio=0.724420 */
    ALGO_MIN_ANGLE_PACK( 286u,  489u, 3059u),  /* idx=684, ratio=0.747091 */
    ALGO_MIN_ANGLE_PACK( 282u,  501u, 2437u),  /* idx=685, ratio=0.595084 */
    ALGO_MIN_ANGLE_PACK( 279u,  512u, 1787u),  /* idx=686, ratio=0.436506 */
    ALGO_MIN_ANGLE_PACK( 275u,  523u, 1166u),  /* idx=687, ratio=0.284747 */
    ALGO_MIN_ANGLE_PACK( 272u,  534u,  571u),  /* idx=688, ratio=0.139377 */
    ALGO_MIN_ANGLE_PACK( 268u,  546u,    0u),  /* idx=689, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 361u,  286u,    0u),  /* idx=690, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 358u,  297u,  265u),  /* idx=691, ratio=0.064788 */
    ALGO_MIN_ANGLE_PACK( 354u,  308u,  511u),  /* idx=692, ratio=0.124849 */
    ALGO_MIN_ANGLE_PACK( 351u,  320u,  740u),  /* idx=693, ratio=0.180680 */
    ALGO_MIN_ANGLE_PACK( 347u,  331u,  953u),  /* idx=694, ratio=0.232714 */
    ALGO_MIN_ANGLE_PACK( 344u,  342u, 1152u),  /* idx=695, ratio=0.281326 */
    ALGO_MIN_ANGLE_PACK( 340u,  353u, 1338u),  /* idx=696, ratio=0.326842 */
    ALGO_MIN_ANGLE_PACK( 336u,  365u, 1513u),  /* idx=697, ratio=0.369549 */
    ALGO_MIN_ANGLE_PACK( 333u,  376u, 1678u),  /* idx=698, ratio=0.409699 */
    ALGO_MIN_ANGLE_PACK( 329u,  387u, 1833u),  /* idx=699, ratio=0.447515 */
    ALGO_MIN_ANGLE_PACK( 326u,  398u, 1979u),  /* idx=700, ratio=0.483195 */
    ALGO_MIN_ANGLE_PACK( 322u,  410u, 2117u),  /* idx=701, ratio=0.516915 */
    ALGO_MIN_ANGLE_PACK( 319u,  421u, 2247u),  /* idx=702, ratio=0.548832 */
    ALGO_MIN_ANGLE_PACK( 315u,  432u, 2371u),  /* idx=703, ratio=0.579087 */
    ALGO_MIN_ANGLE_PACK( 312u,  443u, 2489u),  /* idx=704, ratio=0.607807 */
    ALGO_MIN_ANGLE_PACK( 308u,  455u, 2601u),  /* idx=705, ratio=0.635105 */
    ALGO_MIN_ANGLE_PACK( 305u,  466u, 2707u),  /* idx=706, ratio=0.661084 */
    ALGO_MIN_ANGLE_PACK( 301u,  477u, 2809u),  /* idx=707, ratio=0.685838 */
    ALGO_MIN_ANGLE_PACK( 298u,  488u, 2905u),  /* idx=708, ratio=0.709451 */
    ALGO_MIN_ANGLE_PACK( 294u,  500u, 2443u),  /* idx=709, ratio=0.596466 */
    ALGO_MIN_ANGLE_PACK( 291u,  511u, 1792u),  /* idx=710, ratio=0.437497 */
    ALGO_MIN_ANGLE_PACK( 287u,  522u, 1169u),  /* idx=711, ratio=0.285380 */
    ALGO_MIN_ANGLE_PACK( 283u,  533u,  572u),  /* idx=712, ratio=0.139680 */
    ALGO_MIN_ANGLE_PACK( 280u,  545u,    0u),  /* idx=713, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 369u,  296u,    0u),  /* idx=714, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 366u,  307u,  257u),  /* idx=715, ratio=0.062660 */
    ALGO_MIN_ANGLE_PACK( 362u,  318u,  495u),  /* idx=716, ratio=0.120892 */
    ALGO_MIN_ANGLE_PACK( 359u,  330u,  717u),  /* idx=717, ratio=0.175150 */
    ALGO_MIN_ANGLE_PACK( 355u,  341u,  925u),  /* idx=718, ratio=0.225827 */
    ALGO_MIN_ANGLE_PACK( 352u,  352u, 1119u),  /* idx=719, ratio=0.273266 */
    ALGO_MIN_ANGLE_PACK( 348u,  363u, 1301u),  /* idx=720, ratio=0.317767 */
    ALGO_MIN_ANGLE_PACK( 344u,  375u, 1473u),  /* idx=721, ratio=0.359597 */
    ALGO_MIN_ANGLE_PACK( 341u,  386u, 1634u),  /* idx=722, ratio=0.398987 */
    ALGO_MIN_ANGLE_PACK( 337u,  397u, 1786u),  /* idx=723, ratio=0.436146 */
    ALGO_MIN_ANGLE_PACK( 334u,  408u, 1930u),  /* idx=724, ratio=0.471258 */
    ALGO_MIN_ANGLE_PACK( 330u,  420u, 2066u),  /* idx=725, ratio=0.504487 */
    ALGO_MIN_ANGLE_PACK( 327u,  431u, 2195u),  /* idx=726, ratio=0.535981 */
    ALGO_MIN_ANGLE_PACK( 323u,  442u, 2317u),  /* idx=727, ratio=0.565872 */
    ALGO_MIN_ANGLE_PACK( 320u,  453u, 2434u),  /* idx=728, ratio=0.594281 */
    ALGO_MIN_ANGLE_PACK( 316u,  465u, 2544u),  /* idx=729, ratio=0.621313 */
    ALGO_MIN_ANGLE_PACK( 313u,  476u, 2650u),  /* idx=730, ratio=0.647068 */
    ALGO_MIN_ANGLE_PACK( 309u,  487u, 2750u),  /* idx=731, ratio=0.671633 */
    ALGO_MIN_ANGLE_PACK( 306u,  498u, 2448u),  /* idx=732, ratio=0.597854 */
    ALGO_MIN_ANGLE_PACK( 302u,  510u, 1796u),  /* idx=733, ratio=0.438493 */
    ALGO_MIN_ANGLE_PACK( 299u,  521u, 1171u),  /* idx=734, ratio=0.286015 */
    ALGO_MIN_ANGLE_PACK( 295u,  532u,  573u),  /* idx=735, ratio=0.139984 */
    ALGO_MIN_ANGLE_PACK( 291u,  543u,    0u),  /* idx=736, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 377u,  306u,    0u),  /* idx=737, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 374u,  317u,  248u),  /* idx=738, ratio=0.060667 */
    ALGO_MIN_ANGLE_PACK( 370u,  328u,  480u),  /* idx=739, ratio=0.117179 */
    ALGO_MIN_ANGLE_PACK( 367u,  340u,  696u),  /* idx=740, ratio=0.169948 */
    ALGO_MIN_ANGLE_PACK( 363u,  351u,  898u),  /* idx=741, ratio=0.219335 */
    ALGO_MIN_ANGLE_PACK( 360u,  362u, 1088u),  /* idx=742, ratio=0.265654 */
    ALGO_MIN_ANGLE_PACK( 356u,  373u, 1266u),  /* idx=743, ratio=0.309183 */
    ALGO_MIN_ANGLE_PACK( 353u,  385u, 1434u),  /* idx=744, ratio=0.350166 */
    ALGO_MIN_ANGLE_PACK( 349u,  396u, 1592u),  /* idx=745, ratio=0.388821 */
    ALGO_MIN_ANGLE_PACK( 345u,  407u, 1742u),  /* idx=746, ratio=0.425340 */
    ALGO_MIN_ANGLE_PACK( 342u,  418u, 1883u),  /* idx=747, ratio=0.459895 */
    ALGO_MIN_ANGLE_PACK( 338u,  430u, 2017u),  /* idx=748, ratio=0.492642 */
    ALGO_MIN_ANGLE_PACK( 335u,  441u, 2145u),  /* idx=749, ratio=0.523718 */
    ALGO_MIN_ANGLE_PACK( 331u,  452u, 2266u),  /* idx=750, ratio=0.553247 */
    ALGO_MIN_ANGLE_PACK( 328u,  463u, 2381u),  /* idx=751, ratio=0.581343 */
    ALGO_MIN_ANGLE_PACK( 324u,  475u, 2490u),  /* idx=752, ratio=0.608108 */
    ALGO_MIN_ANGLE_PACK( 321u,  486u, 2595u),  /* idx=753, ratio=0.633634 */
    ALGO_MIN_ANGLE_PACK( 317u,  497u, 2454u),  /* idx=754, ratio=0.599249 */
    ALGO_MIN_ANGLE_PACK( 314u,  508u, 1800u),  /* idx=755, ratio=0.439493 */
    ALGO_MIN_ANGLE_PACK( 310u,  520u, 1174u),  /* idx=756, ratio=0.286654 */
    ALGO_MIN_ANGLE_PACK( 307u,  531u,  574u),  /* idx=757, ratio=0.140290 */
    ALGO_MIN_ANGLE_PACK( 303u,  542u,    0u),  /* idx=758, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 385u,  316u,    0u),  /* idx=759, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 382u,  327u,  241u),  /* idx=760, ratio=0.058797 */
    ALGO_MIN_ANGLE_PACK( 378u,  339u,  466u),  /* idx=761, ratio=0.113687 */
    ALGO_MIN_ANGLE_PACK( 375u,  350u,  676u),  /* idx=762, ratio=0.165046 */
    ALGO_MIN_ANGLE_PACK( 371u,  361u,  873u),  /* idx=763, ratio=0.213206 */
    ALGO_MIN_ANGLE_PACK( 368u,  372u, 1058u),  /* idx=764, ratio=0.258455 */
    ALGO_MIN_ANGLE_PACK( 364u,  384u, 1233u),  /* idx=765, ratio=0.301050 */
    ALGO_MIN_ANGLE_PACK( 361u,  395u, 1397u),  /* idx=766, ratio=0.341218 */
    ALGO_MIN_ANGLE_PACK( 357u,  406u, 1553u),  /* idx=767, ratio=0.379160 */
    ALGO_MIN_ANGLE_PACK( 353u,  417u, 1700u),  /* idx=768, ratio=0.415056 */
    ALGO_MIN_ANGLE_PACK( 350u,  429u, 1839u),  /* idx=769, ratio=0.449068 */
    ALGO_MIN_ANGLE_PACK( 346u,  440u, 1971u),  /* idx=770, ratio=0.481340 */
    ALGO_MIN_ANGLE_PACK( 343u,  451u, 2097u),  /* idx=771, ratio=0.512003 */
    ALGO_MIN_ANGLE_PACK( 339u,  462u, 2216u),  /* idx=772, ratio=0.541173 */
    ALGO_MIN_ANGLE_PACK( 336u,  474u, 2330u),  /* idx=773, ratio=0.568958 */
    ALGO_MIN_ANGLE_PACK( 332u,  485u, 2438u),  /* idx=774, ratio=0.595453 */
    ALGO_MIN_ANGLE_PACK( 329u,  496u, 2460u),  /* idx=775, ratio=0.600650 */
    ALGO_MIN_ANGLE_PACK( 325u,  507u, 1804u),  /* idx=776, ratio=0.440498 */
    ALGO_MIN_ANGLE_PACK( 322u,  519u, 1176u),  /* idx=777, ratio=0.287295 */
    ALGO_MIN_ANGLE_PACK( 318u,  530u,  576u),  /* idx=778, ratio=0.140597 */
    ALGO_MIN_ANGLE_PACK( 315u,  541u,    0u),  /* idx=779, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 393u,  326u,    0u),  /* idx=780, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 390u,  337u,  234u),  /* idx=781, ratio=0.057039 */
    ALGO_MIN_ANGLE_PACK( 386u,  349u,  452u),  /* idx=782, ratio=0.110397 */
    ALGO_MIN_ANGLE_PACK( 383u,  360u,  657u),  /* idx=783, ratio=0.160420 */
    ALGO_MIN_ANGLE_PACK( 379u,  371u,  849u),  /* idx=784, ratio=0.207410 */
    ALGO_MIN_ANGLE_PACK( 376u,  382u, 1030u),  /* idx=785, ratio=0.251636 */
    ALGO_MIN_ANGLE_PACK( 372u,  394u, 1201u),  /* idx=786, ratio=0.293334 */
    ALGO_MIN_ANGLE_PACK( 369u,  405u, 1362u),  /* idx=787, ratio=0.332715 */
    ALGO_MIN_ANGLE_PACK( 365u,  416u, 1515u),  /* idx=788, ratio=0.369967 */
    ALGO_MIN_ANGLE_PACK( 362u,  427u, 1660u),  /* idx=789, ratio=0.405258 */
    ALGO_MIN_ANGLE_PACK( 358u,  439u, 1797u),  /* idx=790, ratio=0.438739 */
    ALGO_MIN_ANGLE_PACK( 354u,  450u, 1927u),  /* idx=791, ratio=0.470546 */
    ALGO_MIN_ANGLE_PACK( 351u,  461u, 2051u),  /* idx=792, ratio=0.500801 */
    ALGO_MIN_ANGLE_PACK( 347u,  472u, 2169u),  /* idx=793, ratio=0.529615 */
    ALGO_MIN_ANGLE_PACK( 344u,  484u, 2281u),  /* idx=794, ratio=0.557088 */
    ALGO_MIN_ANGLE_PACK( 340u,  495u, 2389u),  /* idx=795, ratio=0.583313 */
    ALGO_MIN_ANGLE_PACK( 337u,  506u, 1808u),  /* idx=796, ratio=0.441507 */
    ALGO_MIN_ANGLE_PACK( 333u,  517u, 1179u),  /* idx=797, ratio=0.287939 */
    ALGO_MIN_ANGLE_PACK( 330u,  529u,  577u),  /* idx=798, ratio=0.140906 */
    ALGO_MIN_ANGLE_PACK( 326u,  540u,    0u),  /* idx=799, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 401u,  336u,    0u),  /* idx=800, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 398u,  347u,  227u),  /* idx=801, ratio=0.055383 */
    ALGO_MIN_ANGLE_PACK( 394u,  359u,  439u),  /* idx=802, ratio=0.107292 */
    ALGO_MIN_ANGLE_PACK( 391u,  370u,  639u),  /* idx=803, ratio=0.156045 */
    ALGO_MIN_ANGLE_PACK( 387u,  381u,  827u),  /* idx=804, ratio=0.201921 */
    ALGO_MIN_ANGLE_PACK( 384u,  392u, 1004u),  /* idx=805, ratio=0.245167 */
    ALGO_MIN_ANGLE_PACK( 380u,  404u, 1171u),  /* idx=806, ratio=0.286003 */
    ALGO_MIN_ANGLE_PACK( 377u,  415u, 1329u),  /* idx=807, ratio=0.324626 */
    ALGO_MIN_ANGLE_PACK( 373u,  426u, 1479u),  /* idx=808, ratio=0.361210 */
    ALGO_MIN_ANGLE_PACK( 370u,  437u, 1621u),  /* idx=809, ratio=0.395912 */
    ALGO_MIN_ANGLE_PACK( 366u,  449u, 1756u),  /* idx=810, ratio=0.428875 */
    ALGO_MIN_ANGLE_PACK( 362u,  460u, 1885u),  /* idx=811, ratio=0.460225 */
    ALGO_MIN_ANGLE_PACK( 359u,  471u, 2007u),  /* idx=812, ratio=0.490078 */
    ALGO_MIN_ANGLE_PACK( 355u,  482u, 2123u),  /* idx=813, ratio=0.518540 */
    ALGO_MIN_ANGLE_PACK( 352u,  494u, 2235u),  /* idx=814, ratio=0.545704 */
    ALGO_MIN_ANGLE_PACK( 348u,  505u, 1812u),  /* idx=815, ratio=0.442521 */
    ALGO_MIN_ANGLE_PACK( 345u,  516u, 1182u),  /* idx=816, ratio=0.288586 */
    ALGO_MIN_ANGLE_PACK( 341u,  527u,  578u),  /* idx=817, ratio=0.141216 */
    ALGO_MIN_ANGLE_PACK( 338u,  539u,    0u),  /* idx=818, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 409u,  346u,    0u),  /* idx=819, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 406u,  358u,  220u),  /* idx=820, ratio=0.053820 */
    ALGO_MIN_ANGLE_PACK( 402u,  369u,  427u),  /* idx=821, ratio=0.104357 */
    ALGO_MIN_ANGLE_PACK( 399u,  380u,  622u),  /* idx=822, ratio=0.151903 */
    ALGO_MIN_ANGLE_PACK( 395u,  391u,  806u),  /* idx=823, ratio=0.196715 */
    ALGO_MIN_ANGLE_PACK( 392u,  403u,  979u),  /* idx=824, ratio=0.239023 */
    ALGO_MIN_ANGLE_PACK( 388u,  414u, 1143u),  /* idx=825, ratio=0.279031 */
    ALGO_MIN_ANGLE_PACK( 385u,  425u, 1298u),  /* idx=826, ratio=0.316921 */
    ALGO_MIN_ANGLE_PACK( 381u,  436u, 1445u),  /* idx=827, ratio=0.352857 */
    ALGO_MIN_ANGLE_PACK( 378u,  448u, 1585u),  /* idx=828, ratio=0.386987 */
    ALGO_MIN_ANGLE_PACK( 374u,  459u, 1718u),  /* idx=829, ratio=0.419444 */
    ALGO_MIN_ANGLE_PACK( 370u,  470u, 1844u),  /* idx=830, ratio=0.450347 */
    ALGO_MIN_ANGLE_PACK( 367u,  481u, 1965u),  /* idx=831, ratio=0.479805 */
    ALGO_MIN_ANGLE_PACK( 363u,  493u, 2080u),  /* idx=832, ratio=0.507919 */
    ALGO_MIN_ANGLE_PACK( 360u,  504u, 1816u),  /* idx=833, ratio=0.443540 */
    ALGO_MIN_ANGLE_PACK( 356u,  515u, 1184u),  /* idx=834, ratio=0.289235 */
    ALGO_MIN_ANGLE_PACK( 353u,  526u,  580u),  /* idx=835, ratio=0.141527 */
    ALGO_MIN_ANGLE_PACK( 349u,  538u,    0u),  /* idx=836, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 417u,  356u,    0u),  /* idx=837, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 414u,  368u,  214u),  /* idx=838, ratio=0.052343 */
    ALGO_MIN_ANGLE_PACK( 410u,  379u,  416u),  /* idx=839, ratio=0.101579 */
    ALGO_MIN_ANGLE_PACK( 407u,  390u,  606u),  /* idx=840, ratio=0.147975 */
    ALGO_MIN_ANGLE_PACK( 403u,  401u,  785u),  /* idx=841, ratio=0.191771 */
    ALGO_MIN_ANGLE_PACK( 400u,  413u,  955u),  /* idx=842, ratio=0.233179 */
    ALGO_MIN_ANGLE_PACK( 396u,  424u, 1115u),  /* idx=843, ratio=0.272390 */
    ALGO_MIN_ANGLE_PACK( 393u,  435u, 1268u),  /* idx=844, ratio=0.309573 */
    ALGO_MIN_ANGLE_PACK( 389u,  446u, 1412u),  /* idx=845, ratio=0.344882 */
    ALGO_MIN_ANGLE_PACK( 386u,  458u, 1550u),  /* idx=846, ratio=0.378456 */
    ALGO_MIN_ANGLE_PACK( 382u,  469u, 1681u),  /* idx=847, ratio=0.410419 */
    ALGO_MIN_ANGLE_PACK( 379u,  480u, 1805u),  /* idx=848, ratio=0.440884 */
    ALGO_MIN_ANGLE_PACK( 375u,  491u, 1924u),  /* idx=849, ratio=0.469954 */
    ALGO_MIN_ANGLE_PACK( 371u,  503u, 1820u),  /* idx=850, ratio=0.444563 */
    ALGO_MIN_ANGLE_PACK( 368u,  514u, 1187u),  /* idx=851, ratio=0.289888 */
    ALGO_MIN_ANGLE_PACK( 364u,  525u,  581u),  /* idx=852, ratio=0.141839 */
    ALGO_MIN_ANGLE_PACK( 361u,  536u,    0u),  /* idx=853, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 425u,  367u,    0u),  /* idx=854, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 422u,  378u,  209u),  /* idx=855, ratio=0.050945 */
    ALGO_MIN_ANGLE_PACK( 418u,  389u,  405u),  /* idx=856, ratio=0.098944 */
    ALGO_MIN_ANGLE_PACK( 415u,  400u,  591u),  /* idx=857, ratio=0.144245 */
    ALGO_MIN_ANGLE_PACK( 411u,  411u,  766u),  /* idx=858, ratio=0.187069 */
    ALGO_MIN_ANGLE_PACK( 408u,  423u,  932u),  /* idx=859, ratio=0.227614 */
    ALGO_MIN_ANGLE_PACK( 404u,  434u, 1090u),  /* idx=860, ratio=0.266057 */
    ALGO_MIN_ANGLE_PACK( 401u,  445u, 1239u),  /* idx=861, ratio=0.302558 */
    ALGO_MIN_ANGLE_PACK( 397u,  456u, 1381u),  /* idx=862, ratio=0.337260 */
    ALGO_MIN_ANGLE_PACK( 394u,  468u, 1516u),  /* idx=863, ratio=0.370293 */
    ALGO_MIN_ANGLE_PACK( 390u,  479u, 1645u),  /* idx=864, ratio=0.401774 */
    ALGO_MIN_ANGLE_PACK( 387u,  490u, 1768u),  /* idx=865, ratio=0.431811 */
    ALGO_MIN_ANGLE_PACK( 383u,  501u, 1825u),  /* idx=866, ratio=0.445591 */
    ALGO_MIN_ANGLE_PACK( 379u,  513u, 1190u),  /* idx=867, ratio=0.290544 */
    ALGO_MIN_ANGLE_PACK( 376u,  524u,  582u),  /* idx=868, ratio=0.142153 */
    ALGO_MIN_ANGLE_PACK( 372u,  535u,    0u),  /* idx=869, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 433u,  377u,    0u),  /* idx=870, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 430u,  388u,  203u),  /* idx=871, ratio=0.049620 */
    ALGO_MIN_ANGLE_PACK( 426u,  399u,  395u),  /* idx=872, ratio=0.096443 */
    ALGO_MIN_ANGLE_PACK( 423u,  410u,  576u),  /* idx=873, ratio=0.140698 */
    ALGO_MIN_ANGLE_PACK( 419u,  422u,  748u),  /* idx=874, ratio=0.182592 */
    ALGO_MIN_ANGLE_PACK( 416u,  433u,  910u),  /* idx=875, ratio=0.222308 */
    ALGO_MIN_ANGLE_PACK( 412u,  444u, 1065u),  /* idx=876, ratio=0.260013 */
    ALGO_MIN_ANGLE_PACK( 409u,  455u, 1212u),  /* idx=877, ratio=0.295854 */
    ALGO_MIN_ANGLE_PACK( 405u,  467u, 1351u),  /* idx=878, ratio=0.329967 */
    ALGO_MIN_ANGLE_PACK( 402u,  478u, 1484u),  /* idx=879, ratio=0.362474 */
    ALGO_MIN_ANGLE_PACK( 398u,  489u, 1611u),  /* idx=880, ratio=0.393486 */
    ALGO_MIN_ANGLE_PACK( 395u,  500u, 1733u),  /* idx=881, ratio=0.423103 */
    ALGO_MIN_ANGLE_PACK( 391u,  512u, 1192u),  /* idx=882, ratio=0.291202 */
    ALGO_MIN_ANGLE_PACK( 388u,  523u,  583u),  /* idx=883, ratio=0.142469 */
    ALGO_MIN_ANGLE_PACK( 384u,  534u,    0u),  /* idx=884, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 441u,  387u,    0u),  /* idx=885, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 438u,  398u,  198u),  /* idx=886, ratio=0.048362 */
    ALGO_MIN_ANGLE_PACK( 434u,  409u,  385u),  /* idx=887, ratio=0.094065 */
    ALGO_MIN_ANGLE_PACK( 431u,  420u,  562u),  /* idx=888, ratio=0.137322 */
    ALGO_MIN_ANGLE_PACK( 427u,  432u,  730u),  /* idx=889, ratio=0.178325 */
    ALGO_MIN_ANGLE_PACK( 424u,  443u,  890u),  /* idx=890, ratio=0.217245 */
    ALGO_MIN_ANGLE_PACK( 420u,  454u, 1041u),  /* idx=891, ratio=0.254237 */
    ALGO_MIN_ANGLE_PACK( 417u,  465u, 1185u),  /* idx=892, ratio=0.289441 */
    ALGO_MIN_ANGLE_PACK( 413u,  477u, 1323u),  /* idx=893, ratio=0.322983 */
    ALGO_MIN_ANGLE_PACK( 410u,  488u, 1454u),  /* idx=894, ratio=0.354979 */
    ALGO_MIN_ANGLE_PACK( 406u,  499u, 1579u),  /* idx=895, ratio=0.385533 */
    ALGO_MIN_ANGLE_PACK( 403u,  510u, 1195u),  /* idx=896, ratio=0.291864 */
    ALGO_MIN_ANGLE_PACK( 399u,  522u,  585u),  /* idx=897, ratio=0.142785 */
    ALGO_MIN_ANGLE_PACK( 396u,  533u,    0u),  /* idx=898, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 450u,  397u,    0u),  /* idx=899, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 446u,  408u,  193u),  /* idx=900, ratio=0.047166 */
    ALGO_MIN_ANGLE_PACK( 442u,  419u,  376u),  /* idx=901, ratio=0.091801 */
    ALGO_MIN_ANGLE_PACK( 439u,  431u,  549u),  /* idx=902, ratio=0.134104 */
    ALGO_MIN_ANGLE_PACK( 435u,  442u,  714u),  /* idx=903, ratio=0.174252 */
    ALGO_MIN_ANGLE_PACK( 432u,  453u,  870u),  /* idx=904, ratio=0.212406 */
    ALGO_MIN_ANGLE_PACK( 428u,  464u, 1018u),  /* idx=905, ratio=0.248712 */
    ALGO_MIN_ANGLE_PACK( 425u,  476u, 1160u),  /* idx=906, ratio=0.283300 */
    ALGO_MIN_ANGLE_PACK( 421u,  487u, 1295u),  /* idx=907, ratio=0.316289 */
    ALGO_MIN_ANGLE_PACK( 418u,  498u, 1424u),  /* idx=908, ratio=0.347788 */
    ALGO_MIN_ANGLE_PACK( 414u,  509u, 1198u),  /* idx=909, ratio=0.292529 */
    ALGO_MIN_ANGLE_PACK( 411u,  521u,  586u),  /* idx=910, ratio=0.143103 */
    ALGO_MIN_ANGLE_PACK( 407u,  532u,    0u),  /* idx=911, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 458u,  407u,    0u),  /* idx=912, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 454u,  418u,  188u),  /* idx=913, ratio=0.046028 */
    ALGO_MIN_ANGLE_PACK( 450u,  429u,  367u),  /* idx=914, ratio=0.089644 */
    ALGO_MIN_ANGLE_PACK( 447u,  441u,  537u),  /* idx=915, ratio=0.131033 */
    ALGO_MIN_ANGLE_PACK( 443u,  452u,  698u),  /* idx=916, ratio=0.170361 */
    ALGO_MIN_ANGLE_PACK( 440u,  463u,  851u),  /* idx=917, ratio=0.207779 */
    ALGO_MIN_ANGLE_PACK( 436u,  474u,  997u),  /* idx=918, ratio=0.243422 */
    ALGO_MIN_ANGLE_PACK( 433u,  486u, 1136u),  /* idx=919, ratio=0.277414 */
    ALGO_MIN_ANGLE_PACK( 429u,  497u, 1269u),  /* idx=920, ratio=0.309866 */
    ALGO_MIN_ANGLE_PACK( 426u,  508u, 1201u),  /* idx=921, ratio=0.293196 */
    ALGO_MIN_ANGLE_PACK( 422u,  519u,  587u),  /* idx=922, ratio=0.143423 */
    ALGO_MIN_ANGLE_PACK( 419u,  531u,    0u),  /* idx=923, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 466u,  417u,    0u),  /* idx=924, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 462u,  428u,  184u),  /* idx=925, ratio=0.044943 */
    ALGO_MIN_ANGLE_PACK( 458u,  439u,  359u),  /* idx=926, ratio=0.087586 */
    ALGO_MIN_ANGLE_PACK( 455u,  451u,  525u),  /* idx=927, ratio=0.128100 */
    ALGO_MIN_ANGLE_PACK( 451u,  462u,  682u),  /* idx=928, ratio=0.166640 */
    ALGO_MIN_ANGLE_PACK( 448u,  473u,  833u),  /* idx=929, ratio=0.203349 */
    ALGO_MIN_ANGLE_PACK( 444u,  484u,  976u),  /* idx=930, ratio=0.238352 */
    ALGO_MIN_ANGLE_PACK( 441u,  496u, 1113u),  /* idx=931, ratio=0.271767 */
    ALGO_MIN_ANGLE_PACK( 437u,  507u, 1203u),  /* idx=932, ratio=0.293867 */
    ALGO_MIN_ANGLE_PACK( 434u,  518u,  589u),  /* idx=933, ratio=0.143744 */
    ALGO_MIN_ANGLE_PACK( 430u,  529u,    0u),  /* idx=934, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 474u,  427u,    0u),  /* idx=935, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 470u,  438u,  180u),  /* idx=936, ratio=0.043909 */
    ALGO_MIN_ANGLE_PACK( 467u,  450u,  351u),  /* idx=937, ratio=0.085620 */
    ALGO_MIN_ANGLE_PACK( 463u,  461u,  513u),  /* idx=938, ratio=0.125295 */
    ALGO_MIN_ANGLE_PACK( 459u,  472u,  668u),  /* idx=939, ratio=0.163079 */
    ALGO_MIN_ANGLE_PACK( 456u,  483u,  815u),  /* idx=940, ratio=0.199104 */
    ALGO_MIN_ANGLE_PACK( 452u,  495u,  956u),  /* idx=941, ratio=0.233490 */
    ALGO_MIN_ANGLE_PACK( 449u,  506u, 1091u),  /* idx=942, ratio=0.266346 */
    ALGO_MIN_ANGLE_PACK( 445u,  517u,  590u),  /* idx=943, ratio=0.144066 */
    ALGO_MIN_ANGLE_PACK( 442u,  528u,    0u),  /* idx=944, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 482u,  437u,    0u),  /* idx=945, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 478u,  448u,  176u),  /* idx=946, ratio=0.042921 */
    ALGO_MIN_ANGLE_PACK( 475u,  460u,  343u),  /* idx=947, ratio=0.083741 */
    ALGO_MIN_ANGLE_PACK( 471u,  471u,  502u),  /* idx=948, ratio=0.122610 */
    ALGO_MIN_ANGLE_PACK( 467u,  482u,  654u),  /* idx=949, ratio=0.159666 */
    ALGO_MIN_ANGLE_PACK( 464u,  493u,  799u),  /* idx=950, ratio=0.195032 */
    ALGO_MIN_ANGLE_PACK( 460u,  505u,  937u),  /* idx=951, ratio=0.228821 */
    ALGO_MIN_ANGLE_PACK( 457u,  516u,  591u),  /* idx=952, ratio=0.144390 */
    ALGO_MIN_ANGLE_PACK( 453u,  527u,    0u),  /* idx=953, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 490u,  447u,    0u),  /* idx=954, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 486u,  458u,  172u),  /* idx=955, ratio=0.041976 */
    ALGO_MIN_ANGLE_PACK( 483u,  470u,  336u),  /* idx=956, ratio=0.081942 */
    ALGO_MIN_ANGLE_PACK( 479u,  481u,  492u),  /* idx=957, ratio=0.120038 */
    ALGO_MIN_ANGLE_PACK( 476u,  492u,  640u),  /* idx=958, ratio=0.156393 */
    ALGO_MIN_ANGLE_PACK( 472u,  503u,  783u),  /* idx=959, ratio=0.191124 */
    ALGO_MIN_ANGLE_PACK( 468u,  515u,  593u),  /* idx=960, ratio=0.144716 */
    ALGO_MIN_ANGLE_PACK( 465u,  526u,    0u),  /* idx=961, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 498u,  457u,    0u),  /* idx=962, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 494u,  469u,  168u),  /* idx=963, ratio=0.041072 */
    ALGO_MIN_ANGLE_PACK( 491u,  480u,  328u),  /* idx=964, ratio=0.080219 */
    ALGO_MIN_ANGLE_PACK( 487u,  491u,  481u),  /* idx=965, ratio=0.117572 */
    ALGO_MIN_ANGLE_PACK( 484u,  502u,  628u),  /* idx=966, ratio=0.153252 */
    ALGO_MIN_ANGLE_PACK( 480u,  514u,  594u),  /* idx=967, ratio=0.145042 */
    ALGO_MIN_ANGLE_PACK( 476u,  525u,    0u),  /* idx=968, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 506u,  467u,    0u),  /* idx=969, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 502u,  479u,  121u),  /* idx=970, ratio=0.029591 */
    ALGO_MIN_ANGLE_PACK( 499u,  490u,  322u),  /* idx=971, ratio=0.078567 */
    ALGO_MIN_ANGLE_PACK( 495u,  501u,  472u),  /* idx=972, ratio=0.115205 */
    ALGO_MIN_ANGLE_PACK( 492u,  512u,  595u),  /* idx=973, ratio=0.145371 */
    ALGO_MIN_ANGLE_PACK( 488u,  524u,    0u),  /* idx=974, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 514u,  477u,    0u),  /* idx=975, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 510u,  489u,    0u),  /* idx=976, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 507u,  500u,  315u),  /* idx=977, ratio=0.076981 */
    ALGO_MIN_ANGLE_PACK( 503u,  511u,  462u),  /* idx=978, ratio=0.112931 */
    ALGO_MIN_ANGLE_PACK( 500u,  522u,    0u),  /* idx=979, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 522u,  488u,    0u),  /* idx=980, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 518u,  499u,    0u),  /* idx=981, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 515u,  510u,  233u),  /* idx=982, ratio=0.056926 */
    ALGO_MIN_ANGLE_PACK( 511u,  521u,    0u),  /* idx=983, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 530u,  498u,    0u),  /* idx=984, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 526u,  509u,    0u),  /* idx=985, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 523u,  520u,    0u),  /* idx=986, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 538u,  508u,    0u),  /* idx=987, ratio=0.000000 */
    ALGO_MIN_ANGLE_PACK( 534u,  519u,    0u),  /* idx=988, ratio=-0.000000 */
    ALGO_MIN_ANGLE_PACK( 546u,  518u,    0u),  /* idx=989, ratio=0.000000 */
};

static uint16_t AlgoMinAngle_GetU(uint32_t packedValue)
{
    return (uint16_t)(packedValue & ALGO_MIN_ANGLE_U_MASK);
}

static uint16_t AlgoMinAngle_GetV(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_MIN_ANGLE_V_MASK) >> ALGO_MIN_ANGLE_V_SHIFT);
}

static uint16_t AlgoMinAngle_GetRatio12(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_MIN_ANGLE_RATIO_MASK) >> ALGO_MIN_ANGLE_RATIO_SHIFT);
}

static uint16_t AlgoMinAngle_ConvertRatio12ToQ10000(uint16_t ratio12)
{
    uint32_t numerator = ((uint32_t)ratio12 * ALGO_MIN_ANGLE_RATIO_Q10000_MAX) + (ALGO_MIN_ANGLE_RATIO12_MAX / 2u);
    uint32_t value = numerator / ALGO_MIN_ANGLE_RATIO12_MAX;
    if (value > ALGO_MIN_ANGLE_RATIO_Q10000_MAX)
    {
        value = ALGO_MIN_ANGLE_RATIO_Q10000_MAX;
    }
    return (uint16_t)value;
}

static uint32_t AlgoMinAngle_CalcDistance2(uint16_t u1,
                                           uint16_t v1,
                                           uint16_t u2,
                                           uint16_t v2)
{
    int32_t du = (int32_t)u1 - (int32_t)u2;
    int32_t dv = (int32_t)v1 - (int32_t)v2;
    return (uint32_t)((du * du) + (dv * dv));
}

static uint32_t AlgoMinAngle_AbsS32(int32_t value)
{
    if (value < 0)
    {
        return (uint32_t)(-value);
    }
    return (uint32_t)value;
}

static uint8_t AlgoMinAngle_GetDotSign(int32_t dot)
{
    if (dot > 0)
    {
        return 2u;
    }
    if (dot == 0)
    {
        return 1u;
    }
    return 0u;
}

static uint8_t AlgoMinAngle_IsCandidateBetter(int32_t candidateDot,
                                              uint32_t candidateLen2,
                                              uint32_t candidateDistance2,
                                              int32_t bestDot,
                                              uint32_t bestLen2,
                                              uint32_t bestDistance2)
{
    uint8_t candidateSign = AlgoMinAngle_GetDotSign(candidateDot);
    uint8_t bestSign = AlgoMinAngle_GetDotSign(bestDot);
    uint64_t lhs;
    uint64_t rhs;

    if (candidateSign != bestSign)
    {
        return (candidateSign > bestSign) ? 1u : 0u;
    }

    if (candidateSign == 1u)
    {
        if (candidateDistance2 != bestDistance2)
        {
            return (candidateDistance2 < bestDistance2) ? 1u : 0u;
        }
        return (candidateLen2 < bestLen2) ? 1u : 0u;
    }

    lhs = (uint64_t)AlgoMinAngle_AbsS32(candidateDot);
    lhs = lhs * lhs * (uint64_t)bestLen2;

    rhs = (uint64_t)AlgoMinAngle_AbsS32(bestDot);
    rhs = rhs * rhs * (uint64_t)candidateLen2;

    if (candidateSign == 2u)
    {
        if (lhs != rhs)
        {
            return (lhs > rhs) ? 1u : 0u;
        }
    }
    else
    {
        if (lhs != rhs)
        {
            return (lhs < rhs) ? 1u : 0u;
        }
    }

    if (candidateDistance2 != bestDistance2)
    {
        return (candidateDistance2 < bestDistance2) ? 1u : 0u;
    }

    return (candidateLen2 < bestLen2) ? 1u : 0u;
}

uint8_t AlgoMinAngle_GetWhiteRatioQ10000(uint16_t targetU,
                                         uint16_t targetV,
                                         uint16_t whiteU,
                                         uint16_t whiteV,
                                         uint16_t *whiteRatioQ10000)
{
    uint16_t lutIndex;
    uint16_t pointU;
    uint16_t pointV;
    uint16_t pointRatio12;
    uint16_t nearestRatio12;
    uint16_t radiusNearestRatio12;
    uint16_t bestRatio12;
    uint32_t packedValue;
    uint32_t distance2;
    uint32_t nearestDistance2;
    uint32_t radiusNearestDistance2;
    uint32_t bestDistance2;
    uint32_t awLen2;
    uint32_t bwLen2;
    uint32_t bestBwLen2;
    int32_t awU;
    int32_t awV;
    int32_t bwU;
    int32_t bwV;
    int32_t dot;
    int32_t bestDot;
    uint8_t nearestFound;
    uint8_t radiusNearestFound;
    uint8_t bestFound;

    if (whiteRatioQ10000 == (void *)0)
    {
        return 0u;
    }

    if ((targetU == whiteU) && (targetV == whiteV))
    {
        *whiteRatioQ10000 = ALGO_MIN_ANGLE_RATIO_Q10000_MAX;
        return 1u;
    }

    awU = (int32_t)targetU - (int32_t)whiteU;
    awV = (int32_t)targetV - (int32_t)whiteV;
    awLen2 = (uint32_t)((awU * awU) + (awV * awV));

    nearestFound = 0u;
    radiusNearestFound = 0u;
    bestFound = 0u;
    nearestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;
    radiusNearestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;
    bestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;
    bestBwLen2 = 0u;
    bestDot = 0;
    nearestRatio12 = 0u;
    radiusNearestRatio12 = 0u;
    bestRatio12 = 0u;

    for (lutIndex = 0u; lutIndex < ALGO_MIN_ANGLE_LUT_COUNT; lutIndex++)
    {
        packedValue = g_algoMinAnglePackedLut[lutIndex];
        pointU = AlgoMinAngle_GetU(packedValue);
        pointV = AlgoMinAngle_GetV(packedValue);
        pointRatio12 = AlgoMinAngle_GetRatio12(packedValue);
        distance2 = AlgoMinAngle_CalcDistance2(targetU, targetV, pointU, pointV);

        if ((nearestFound == 0u) || (distance2 < nearestDistance2))
        {
            nearestFound = 1u;
            nearestDistance2 = distance2;
            nearestRatio12 = pointRatio12;
        }

        if (distance2 == 0u)
        {
            *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(pointRatio12);
            return 1u;
        }

        if (distance2 >= ALGO_MIN_ANGLE_DELTA_UV_LIMIT2)
        {
            continue;
        }

        if ((radiusNearestFound == 0u) || (distance2 < radiusNearestDistance2))
        {
            radiusNearestFound = 1u;
            radiusNearestDistance2 = distance2;
            radiusNearestRatio12 = pointRatio12;
        }

        bwU = (int32_t)pointU - (int32_t)whiteU;
        bwV = (int32_t)pointV - (int32_t)whiteV;
        bwLen2 = (uint32_t)((bwU * bwU) + (bwV * bwV));

        if ((awLen2 == 0u) || (bwLen2 == 0u))
        {
            continue;
        }

        dot = (awU * bwU) + (awV * bwV);

        if ((bestFound == 0u) ||
            (AlgoMinAngle_IsCandidateBetter(dot, bwLen2, distance2, bestDot, bestBwLen2, bestDistance2) != 0u))
        {
            bestFound = 1u;
            bestDot = dot;
            bestBwLen2 = bwLen2;
            bestDistance2 = distance2;
            bestRatio12 = pointRatio12;
        }
    }

    if (bestFound != 0u)
    {
        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(bestRatio12);
        return 1u;
    }

    if (radiusNearestFound != 0u)
    {
        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(radiusNearestRatio12);
        return 1u;
    }

    if (nearestFound != 0u)
    {
        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(nearestRatio12);
        return 1u;
    }

    return 0u;
}
