% S06_EXPORT_RATIOK_PACKED32
% Export the MATLAB-generated K-point LUT directly as AlgoRatioK.c.
%
% Input:
%   triangle_grid_lut_output/guangpu_triangle_grid_lut_results.csv
%
% Output:
%   triangle_grid_lut_output/AlgoRatioK.c
%   RGB/BLINKY_SIMPLE_EXAMPLE_TLD4020/Algorithm/AlgoRatioK.c
%
% Packed LUT format (unchanged):
%   bit[ 0: 9] = U       = round(Target_u1976 * 1000)
%   bit[10:19] = V       = round(Target_v1976 * 1000)
%   bit[20:31] = ratio12 = round(Best_SingleWhiteRatio * 4095)
%
% Public C interface (unchanged):
%   uint8_t AlgoRatioK_GetWhiteRatioQ10000(uint16_t targetU,
%                                          uint16_t targetV,
%                                          uint16_t *whiteRatioQ10000);

clear;
clc;

fprintf('\n============================================================\n');
fprintf('S06 current version: export packed LUT directly to AlgoRatioK.c\n');
fprintf('Input : triangle_grid_lut_output/guangpu_triangle_grid_lut_results.csv\n');
fprintf('Output: triangle_grid_lut_output/AlgoRatioK.c\n');
fprintf('Mirror: RGB/BLINKY_SIMPLE_EXAMPLE_TLD4020/Algorithm/AlgoRatioK.c\n');
fprintf('============================================================\n\n');

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = find_project_root(scriptDir, 'guangpu_case_input');
repoRoot = fileparts(projectRoot);
outputDir = fullfile(projectRoot, 'triangle_grid_lut_output');
firmwareDir = fullfile(repoRoot, 'RGB', 'BLINKY_SIMPLE_EXAMPLE_TLD4020', 'Algorithm');

inputFile = fullfile(outputDir, 'guangpu_triangle_grid_lut_results.csv');
outputFile = fullfile(outputDir, 'AlgoRatioK.c');
firmwareOutputFile = fullfile(firmwareDir, 'AlgoRatioK.c');

if ~exist(inputFile, 'file')
    error('Missing LUT result file:\n%s\nPlease run s01_make_lut_24_final.m first.', inputFile);
end

if ~exist(firmwareDir, 'dir')
    mkdir(firmwareDir);
end

T = readtable(inputFile, 'VariableNamingRule', 'preserve');
needCols = {'Target_u1976','Target_v1976','Best_SingleWhiteRatio'};
for i = 1:numel(needCols)
    if ~ismember(needCols{i}, T.Properties.VariableNames)
        error('Missing column: %s', needCols{i});
    end
end

n = height(T);

write_c_file(outputFile, T, n);
write_c_file(firmwareOutputFile, T, n);

fprintf('Generated C file:\n%s\n', outputFile);
fprintf('Mirrored firmware file:\n%s\n', firmwareOutputFile);

function write_c_file(filePath, T, lutCount)
    fid = fopen(filePath, 'w');
    if fid < 0
        error('Cannot open output file: %s', filePath);
    end
    cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

    write_c_preamble(fid, lutCount);
    write_lut_rows(fid, T);
    write_c_footer(fid);
end

function write_c_preamble(fid, lutCount)
    fprintf(fid, '/*********************************************************************************\n');
    fprintf(fid, ' * FileName:    AlgoRatioK.c\n');
    fprintf(fid, ' * Description: Auto-generated by test/s06_export_ratioK_packed32.m\n');
    fprintf(fid, ' *              32-bit packed K-point white-ratio lookup module.\n');
    fprintf(fid, ' *\n');
    fprintf(fid, ' * Packed LUT:\n');
    fprintf(fid, ' *   bit[ 0: 9] = U,      10 bit, u'' * 1000\n');
    fprintf(fid, ' *   bit[10:19] = V,      10 bit, v'' * 1000\n');
    fprintf(fid, ' *   bit[20:31] = ratio,  12 bit, whiteRatio * 4095\n');
    fprintf(fid, ' **********************************************************************************/\n\n');
    fprintf(fid, '#include "AlgoRatioK.h"\n\n');
    fprintf(fid, '#define ALGO_RATIO_K_LUT_COUNT           (%uu)\n\n', uint32(lutCount));
    fprintf(fid, '#define ALGO_RATIO_K_U_MASK              (0x000003FFu)\n');
    fprintf(fid, '#define ALGO_RATIO_K_V_MASK              (0x000FFC00u)\n');
    fprintf(fid, '#define ALGO_RATIO_K_RATIO_MASK          (0xFFF00000u)\n\n');
    fprintf(fid, '#define ALGO_RATIO_K_V_SHIFT             (10u)\n');
    fprintf(fid, '#define ALGO_RATIO_K_RATIO_SHIFT         (20u)\n\n');
    fprintf(fid, '#define ALGO_RATIO_K_RATIO12_MAX         (4095u)\n');
    fprintf(fid, '#define ALGO_RATIO_K_RATIO_Q10000_MAX    (10000u)\n');
    fprintf(fid, '#define ALGO_RATIO_K_DISTANCE_MAX        (0xFFFFFFFFu)\n\n');
    fprintf(fid, '#ifndef ALGO_RATIO_K_USE_WEIGHT\n');
    fprintf(fid, '#define ALGO_RATIO_K_USE_WEIGHT          (1u)\n');
    fprintf(fid, '#endif\n\n');
    fprintf(fid, '#define ALGO_RATIO_K_WEIGHT_SCALE        (32768u)\n\n');
    fprintf(fid, '#if (ALGO_RATIO_K_AMOUNT == 0u)\n');
    fprintf(fid, '#error "ALGO_RATIO_K_AMOUNT must be greater than 0."\n');
    fprintf(fid, '#endif\n\n');
    fprintf(fid, '#if (ALGO_RATIO_K_AMOUNT > 12u)\n');
    fprintf(fid, '#error "ALGO_RATIO_K_AMOUNT > 12 may overflow uint32 weighted sum."\n');
    fprintf(fid, '#endif\n\n');
    fprintf(fid, '#define ALGO_RATIO_K_PACK(U_, V_, RATIO12_) \\\n');
    fprintf(fid, '    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_RATIO_K_RATIO_SHIFT) | \\\n');
    fprintf(fid, '     (((uint32_t)(V_)       & 0x3FFu) << ALGO_RATIO_K_V_SHIFT) | \\\n');
    fprintf(fid, '     (((uint32_t)(U_)       & 0x3FFu)))\n\n');
    fprintf(fid, 'static const uint32_t g_algoRatioKPackedLut[ALGO_RATIO_K_LUT_COUNT] =\n{\n');
end

function write_lut_rows(fid, T)
    for i = 1:height(T)
        u = round(T.Target_u1976(i) * 1000);
        v = round(T.Target_v1976(i) * 1000);
        ratio12 = round(T.Best_SingleWhiteRatio(i) * 4095);

        u = min(max(u, 0), 1023);
        v = min(max(v, 0), 1023);
        ratio12 = min(max(ratio12, 0), 4095);

        fprintf(fid, '    ALGO_RATIO_K_PACK(%4du, %4du, %4du),  /* idx=%3d, ratio=%.6f */\n', ...
            u, v, ratio12, i - 1, T.Best_SingleWhiteRatio(i));
    end
end

function write_c_footer(fid)
    fprintf(fid, '};\n\n');
    fprintf(fid, 'static uint16_t AlgoRatioK_GetU(uint32_t packedValue)\n{\n');
    fprintf(fid, '    return (uint16_t)(packedValue & ALGO_RATIO_K_U_MASK);\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'static uint16_t AlgoRatioK_GetV(uint32_t packedValue)\n{\n');
    fprintf(fid, '    return (uint16_t)((packedValue & ALGO_RATIO_K_V_MASK) >> ALGO_RATIO_K_V_SHIFT);\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'static uint16_t AlgoRatioK_GetRatio12(uint32_t packedValue)\n{\n');
    fprintf(fid, '    return (uint16_t)((packedValue & ALGO_RATIO_K_RATIO_MASK) >> ALGO_RATIO_K_RATIO_SHIFT);\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'static uint16_t AlgoRatioK_ConvertRatio12ToQ10000(uint16_t ratio12)\n{\n');
    fprintf(fid, '    uint32_t numerator = ((uint32_t)ratio12 * ALGO_RATIO_K_RATIO_Q10000_MAX) + (ALGO_RATIO_K_RATIO12_MAX / 2u);\n');
    fprintf(fid, '    uint32_t value = numerator / ALGO_RATIO_K_RATIO12_MAX;\n');
    fprintf(fid, '    if (value > ALGO_RATIO_K_RATIO_Q10000_MAX)\n    {\n        value = ALGO_RATIO_K_RATIO_Q10000_MAX;\n    }\n');
    fprintf(fid, '    return (uint16_t)value;\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'static uint32_t AlgoRatioK_CalcDistance2(uint16_t u1,\n');
    fprintf(fid, '                                         uint16_t v1,\n');
    fprintf(fid, '                                         uint16_t u2,\n');
    fprintf(fid, '                                         uint16_t v2)\n{\n');
    fprintf(fid, '    int32_t du = (int32_t)u1 - (int32_t)u2;\n');
    fprintf(fid, '    int32_t dv = (int32_t)v1 - (int32_t)v2;\n');
    fprintf(fid, '    return (uint32_t)((du * du) + (dv * dv));\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'static uint16_t AlgoRatioK_DivRoundU32(uint32_t numerator,\n');
    fprintf(fid, '                                       uint32_t denominator)\n{\n');
    fprintf(fid, '    if (denominator == 0u)\n    {\n        return 0u;\n    }\n');
    fprintf(fid, '    return (uint16_t)((numerator + (denominator / 2u)) / denominator);\n');
    fprintf(fid, '}\n\n');
    fprintf(fid, 'uint8_t AlgoRatioK_GetWhiteRatioQ10000(uint16_t targetU,\n');
    fprintf(fid, '                                       uint16_t targetV,\n');
    fprintf(fid, '                                       uint16_t *whiteRatioQ10000)\n{\n');
    fprintf(fid, '    uint32_t nearestDistance[ALGO_RATIO_K_AMOUNT];\n');
    fprintf(fid, '    uint16_t nearestRatio12[ALGO_RATIO_K_AMOUNT];\n');
    fprintf(fid, '    uint16_t lutIndex;\n');
    fprintf(fid, '    uint16_t pointU;\n');
    fprintf(fid, '    uint16_t pointV;\n');
    fprintf(fid, '    uint16_t pointRatio12;\n');
    fprintf(fid, '    uint16_t pointRatioQ10000;\n');
    fprintf(fid, '    uint32_t packedValue;\n');
    fprintf(fid, '    uint32_t distance2;\n');
    fprintf(fid, '    uint8_t insertIndex;\n');
    fprintf(fid, '    uint8_t shiftIndex;\n');
    fprintf(fid, '    uint8_t nearestCount;\n');
    fprintf(fid, '    uint8_t i;\n');
    fprintf(fid, '#if (ALGO_RATIO_K_USE_WEIGHT != 0u)\n');
    fprintf(fid, '    uint32_t weight;\n');
    fprintf(fid, '    uint32_t weightSum;\n');
    fprintf(fid, '    uint32_t weightedRatioSum;\n');
    fprintf(fid, '#else\n');
    fprintf(fid, '    uint32_t ratioSum;\n');
    fprintf(fid, '#endif\n');
    fprintf(fid, '    uint16_t ratioResult;\n\n');
    fprintf(fid, '    if (whiteRatioQ10000 == (void *)0)\n    {\n        return 0u;\n    }\n\n');
    fprintf(fid, '    for (i = 0u; i < ALGO_RATIO_K_AMOUNT; i++)\n    {\n        nearestDistance[i] = ALGO_RATIO_K_DISTANCE_MAX;\n        nearestRatio12[i] = 0u;\n    }\n\n');
    fprintf(fid, '    nearestCount = 0u;\n\n');
    fprintf(fid, '    for (lutIndex = 0u; lutIndex < ALGO_RATIO_K_LUT_COUNT; lutIndex++)\n    {\n');
    fprintf(fid, '        packedValue = g_algoRatioKPackedLut[lutIndex];\n');
    fprintf(fid, '        pointU = AlgoRatioK_GetU(packedValue);\n');
    fprintf(fid, '        pointV = AlgoRatioK_GetV(packedValue);\n');
    fprintf(fid, '        pointRatio12 = AlgoRatioK_GetRatio12(packedValue);\n');
    fprintf(fid, '        distance2 = AlgoRatioK_CalcDistance2(targetU, targetV, pointU, pointV);\n\n');
    fprintf(fid, '        if (distance2 == 0u)\n        {\n');
    fprintf(fid, '            *whiteRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(pointRatio12);\n');
    fprintf(fid, '            return 1u;\n        }\n\n');
    fprintf(fid, '        for (insertIndex = 0u; insertIndex < ALGO_RATIO_K_AMOUNT; insertIndex++)\n        {\n');
    fprintf(fid, '            if (distance2 < nearestDistance[insertIndex])\n            {\n');
    fprintf(fid, '                for (shiftIndex = (uint8_t)(ALGO_RATIO_K_AMOUNT - 1u); shiftIndex > insertIndex; shiftIndex--)\n                {\n');
    fprintf(fid, '                    nearestDistance[shiftIndex] = nearestDistance[shiftIndex - 1u];\n');
    fprintf(fid, '                    nearestRatio12[shiftIndex] = nearestRatio12[shiftIndex - 1u];\n                }\n\n');
    fprintf(fid, '                nearestDistance[insertIndex] = distance2;\n');
    fprintf(fid, '                nearestRatio12[insertIndex] = pointRatio12;\n\n');
    fprintf(fid, '                if (nearestCount < ALGO_RATIO_K_AMOUNT)\n                {\n                    nearestCount++;\n                }\n\n');
    fprintf(fid, '                break;\n            }\n        }\n    }\n\n');
    fprintf(fid, '    if (nearestCount == 0u)\n    {\n        return 0u;\n    }\n\n');
    fprintf(fid, '#if (ALGO_RATIO_K_USE_WEIGHT != 0u)\n');
    fprintf(fid, '    weightSum = 0u;\n');
    fprintf(fid, '    weightedRatioSum = 0u;\n\n');
    fprintf(fid, '    for (i = 0u; i < nearestCount; i++)\n    {\n');
    fprintf(fid, '        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);\n');
    fprintf(fid, '        weight = (uint32_t)(ALGO_RATIO_K_WEIGHT_SCALE / (nearestDistance[i] + 1u));\n');
    fprintf(fid, '        if (weight == 0u)\n        {\n            weight = 1u;\n        }\n');
    fprintf(fid, '        weightedRatioSum += ((uint32_t)pointRatioQ10000 * weight);\n');
    fprintf(fid, '        weightSum += weight;\n    }\n\n');
    fprintf(fid, '    ratioResult = AlgoRatioK_DivRoundU32(weightedRatioSum, weightSum);\n');
    fprintf(fid, '#else\n');
    fprintf(fid, '    ratioSum = 0u;\n\n');
    fprintf(fid, '    for (i = 0u; i < nearestCount; i++)\n    {\n');
    fprintf(fid, '        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);\n');
    fprintf(fid, '        ratioSum += (uint32_t)pointRatioQ10000;\n    }\n\n');
    fprintf(fid, '    ratioResult = AlgoRatioK_DivRoundU32(ratioSum, nearestCount);\n');
    fprintf(fid, '#endif\n\n');
    fprintf(fid, '    if (ratioResult > ALGO_RATIO_K_RATIO_Q10000_MAX)\n    {\n        ratioResult = ALGO_RATIO_K_RATIO_Q10000_MAX;\n    }\n\n');
    fprintf(fid, '    *whiteRatioQ10000 = ratioResult;\n');
    fprintf(fid, '    return 1u;\n');
    fprintf(fid, '}\n');
end

function projectRoot = find_project_root(startDir, inputFolderName)
    projectRoot = startDir;
    while true
        if exist(fullfile(projectRoot, inputFolderName), 'dir')
            return;
        end

        parentDir = fileparts(projectRoot);
        if strcmp(parentDir, projectRoot)
            error('find_project_root:NotFound', ...
                'Cannot find %s from script folder or its parent folders.', inputFolderName);
        end

        projectRoot = parentDir;
    end
end
