% S06_EXPORT_MIN_ANGLE_PACKED32
% Export the MATLAB-generated LUT directly as AlgoMinAngle.c.
%
% Strategy:
%   For target color A and single-white point W, search LUT points B with
%   Delta uv < deltaUvLimit from A. Select the B whose angle between
%   vectors AW and BW is minimal, then use B's stored Best_SingleWhiteRatio.
%
% Input:
%   triangle_grid_lut_output/guangpu_triangle_grid_lut_results.csv
%
% Output:
%   triangle_grid_lut_output/AlgoMinAngle.c
%   RGB/BLINKY_SIMPLE_EXAMPLE_TLD4020/Algorithm/AlgoMinAngle/AlgoMinAngle.c
%
% Packed LUT format:
%   bit[ 0: 9] = U       = round(Target_u1976 * 1000)
%   bit[10:19] = V       = round(Target_v1976 * 1000)
%   bit[20:31] = ratio12 = round(Best_SingleWhiteRatio * 4095)
%
% Public C interface:
%   uint8_t AlgoMinAngle_GetWhiteRatioQ10000(uint16_t targetU,
%                                            uint16_t targetV,
%                                            uint16_t whiteU,
%                                            uint16_t whiteV,
%                                            uint16_t *whiteRatioQ10000);

clear;
clc;

% Minimum-angle candidate threshold in CIE 1976 u'v' space.
% Default = 0.02, emitted to C as ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000.
deltaUvLimit = 0.01;
deltaUvLimitQ1000 = round(deltaUvLimit * 1000);

if ~isscalar(deltaUvLimit) || ~isfinite(deltaUvLimit) || (deltaUvLimit <= 0)
    error('deltaUvLimit must be a finite positive scalar.');
end
if (deltaUvLimitQ1000 < 1) || (deltaUvLimitQ1000 > 1023)
    error('deltaUvLimit * 1000 must be within [1, 1023]. Current value = %d.', deltaUvLimitQ1000);
end

fprintf('\n============================================================\n');
fprintf('S06 minimum-angle version: export packed LUT to AlgoMinAngle.c\n');
fprintf('Input : triangle_grid_lut_output/guangpu_triangle_grid_lut_results.csv\n');
fprintf('Output: triangle_grid_lut_output/AlgoMinAngle.c\n');
fprintf('Mirror: RGB/BLINKY_SIMPLE_EXAMPLE_TLD4020/Algorithm/AlgoMinAngle/AlgoMinAngle.c\n');
fprintf('Delta uv candidate limit: %.6f (Q1000=%d)\n', deltaUvLimit, deltaUvLimitQ1000);
fprintf('============================================================\n\n');

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = find_project_root(scriptDir, 'guangpu_case_input');
repoRoot = fileparts(projectRoot);
outputDir = fullfile(projectRoot, 'triangle_grid_lut_output');
firmwareDir = fullfile(repoRoot, 'RGB', 'BLINKY_SIMPLE_EXAMPLE_TLD4020', ...
    'Algorithm', 'AlgoMinAngle');

inputFile = fullfile(outputDir, 'guangpu_triangle_grid_lut_results.csv');
outputFile = fullfile(outputDir, 'AlgoMinAngle.c');
firmwareOutputFile = fullfile(firmwareDir, 'AlgoMinAngle.c');

if ~exist(inputFile, 'file')
    error('Missing LUT result file:\n%s\nPlease run s01_make_lut_24_final.m first.', inputFile);
end

if ~exist(firmwareDir, 'dir')
    mkdir(firmwareDir);
end

T = readtable(inputFile, 'VariableNamingRule', 'preserve');
needCols = {'Target_u1976','Target_v1976','Best_SingleWhiteRatio'};
for i = 1:numel(needCols)
    if ~ismember(needCols{i}, T.Properties.VariableNames)
        error('Missing column: %s', needCols{i});
    end
end

write_c_file(outputFile, T, deltaUvLimit, deltaUvLimitQ1000);
write_c_file(firmwareOutputFile, T, deltaUvLimit, deltaUvLimitQ1000);

fprintf('Generated C file:\n%s\n', outputFile);
fprintf('Mirrored firmware file:\n%s\n', firmwareOutputFile);

function write_c_file(filePath, T, deltaUvLimit, deltaUvLimitQ1000)
    fid = fopen(filePath, 'w');
    if fid < 0
        error('Cannot open output file: %s', filePath);
    end
    cleanupObj = onCleanup(@() fclose(fid)); %#ok<NASGU>

    write_c_preamble(fid, height(T), deltaUvLimit, deltaUvLimitQ1000);
    write_lut_rows(fid, T);
    write_c_footer(fid);
end

function write_c_preamble(fid, lutCount, deltaUvLimit, deltaUvLimitQ1000)
    fprintf(fid, '/*********************************************************************************\n');
    fprintf(fid, ' * FileName:    AlgoMinAngle.c\n');
    fprintf(fid, ' * Description: Auto-generated by test/s06_export_min_angle_packed32.m\n');
    fprintf(fid, ' *              32-bit packed minimum-angle white-ratio lookup module.\n');
    fprintf(fid, ' *\n');
    fprintf(fid, ' * Strategy:\n');
    fprintf(fid, ' *   For target A and white point W, search LUT points B with Delta uv < %.6f.\n', deltaUvLimit);
    fprintf(fid, ' *   Select B whose angle between AW and BW is minimal, then use B''s ratio.\n');
    fprintf(fid, ' *   Override macro: ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 (default %uu).\n', uint32(deltaUvLimitQ1000));
    fprintf(fid, ' *\n');
    fprintf(fid, ' * Packed LUT:\n');
    fprintf(fid, ' *   bit[ 0: 9] = U,      10 bit, u'' * 1000\n');
    fprintf(fid, ' *   bit[10:19] = V,      10 bit, v'' * 1000\n');
    fprintf(fid, ' *   bit[20:31] = ratio,  12 bit, whiteRatio * 4095\n');
    fprintf(fid, ' **********************************************************************************/\n\n');
    fprintf(fid, '#include "AlgoMinAngle.h"\n\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_LUT_COUNT            (%uu)\n\n', uint32(lutCount));
    fprintf(fid, '#define ALGO_MIN_ANGLE_U_MASK               (0x000003FFu)\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_V_MASK               (0x000FFC00u)\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_RATIO_MASK           (0xFFF00000u)\n\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_V_SHIFT              (10u)\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_RATIO_SHIFT          (20u)\n\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_RATIO12_MAX          (4095u)\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_RATIO_Q10000_MAX     (10000u)\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_DISTANCE_MAX         (0xFFFFFFFFu)\n');
    fprintf(fid, '#ifndef ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 (%uu)\n', uint32(deltaUvLimitQ1000));
    fprintf(fid, '#endif\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_DELTA_UV_LIMIT2      ((uint32_t)(ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000 * ALGO_MIN_ANGLE_DELTA_UV_LIMIT_Q1000))\n\n');
    fprintf(fid, '#define ALGO_MIN_ANGLE_PACK(U_, V_, RATIO12_) \\\n');
    fprintf(fid, '    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_MIN_ANGLE_RATIO_SHIFT) | \\\n');
    fprintf(fid, '     (((uint32_t)(V_)       & 0x3FFu) << ALGO_MIN_ANGLE_V_SHIFT) | \\\n');
    fprintf(fid, '     (((uint32_t)(U_)       & 0x3FFu)))\n\n');
    fprintf(fid, 'static const uint32_t g_algoMinAnglePackedLut[ALGO_MIN_ANGLE_LUT_COUNT] =\n{\n');
end

function write_lut_rows(fid, T)
    for i = 1:height(T)
        u = round(T.Target_u1976(i) * 1000);
        v = round(T.Target_v1976(i) * 1000);
        ratio12 = round(T.Best_SingleWhiteRatio(i) * 4095);

        u = min(max(u, 0), 1023);
        v = min(max(v, 0), 1023);
        ratio12 = min(max(ratio12, 0), 4095);

        fprintf(fid, '    ALGO_MIN_ANGLE_PACK(%4du, %4du, %4du),  /* idx=%3d, ratio=%.6f */\n', ...
            u, v, ratio12, i - 1, T.Best_SingleWhiteRatio(i));
    end
end

function write_c_footer(fid)
    lines = {
        '};'
        ''
        'static uint16_t AlgoMinAngle_GetU(uint32_t packedValue)'
        '{'
        '    return (uint16_t)(packedValue & ALGO_MIN_ANGLE_U_MASK);'
        '}'
        ''
        'static uint16_t AlgoMinAngle_GetV(uint32_t packedValue)'
        '{'
        '    return (uint16_t)((packedValue & ALGO_MIN_ANGLE_V_MASK) >> ALGO_MIN_ANGLE_V_SHIFT);'
        '}'
        ''
        'static uint16_t AlgoMinAngle_GetRatio12(uint32_t packedValue)'
        '{'
        '    return (uint16_t)((packedValue & ALGO_MIN_ANGLE_RATIO_MASK) >> ALGO_MIN_ANGLE_RATIO_SHIFT);'
        '}'
        ''
        'static uint16_t AlgoMinAngle_ConvertRatio12ToQ10000(uint16_t ratio12)'
        '{'
        '    uint32_t numerator = ((uint32_t)ratio12 * ALGO_MIN_ANGLE_RATIO_Q10000_MAX) + (ALGO_MIN_ANGLE_RATIO12_MAX / 2u);'
        '    uint32_t value = numerator / ALGO_MIN_ANGLE_RATIO12_MAX;'
        '    if (value > ALGO_MIN_ANGLE_RATIO_Q10000_MAX)'
        '    {'
        '        value = ALGO_MIN_ANGLE_RATIO_Q10000_MAX;'
        '    }'
        '    return (uint16_t)value;'
        '}'
        ''
        'static uint32_t AlgoMinAngle_CalcDistance2(uint16_t u1,'
        '                                           uint16_t v1,'
        '                                           uint16_t u2,'
        '                                           uint16_t v2)'
        '{'
        '    int32_t du = (int32_t)u1 - (int32_t)u2;'
        '    int32_t dv = (int32_t)v1 - (int32_t)v2;'
        '    return (uint32_t)((du * du) + (dv * dv));'
        '}'
        ''
        'static uint32_t AlgoMinAngle_AbsS32(int32_t value)'
        '{'
        '    if (value < 0)'
        '    {'
        '        return (uint32_t)(-value);'
        '    }'
        '    return (uint32_t)value;'
        '}'
        ''
        'static uint8_t AlgoMinAngle_GetDotSign(int32_t dot)'
        '{'
        '    if (dot > 0)'
        '    {'
        '        return 2u;'
        '    }'
        '    if (dot == 0)'
        '    {'
        '        return 1u;'
        '    }'
        '    return 0u;'
        '}'
        ''
        'static uint8_t AlgoMinAngle_IsCandidateBetter(int32_t candidateDot,'
        '                                              uint32_t candidateLen2,'
        '                                              uint32_t candidateDistance2,'
        '                                              int32_t bestDot,'
        '                                              uint32_t bestLen2,'
        '                                              uint32_t bestDistance2)'
        '{'
        '    uint8_t candidateSign = AlgoMinAngle_GetDotSign(candidateDot);'
        '    uint8_t bestSign = AlgoMinAngle_GetDotSign(bestDot);'
        '    uint64_t lhs;'
        '    uint64_t rhs;'
        ''
        '    if (candidateSign != bestSign)'
        '    {'
        '        return (candidateSign > bestSign) ? 1u : 0u;'
        '    }'
        ''
        '    if (candidateSign == 1u)'
        '    {'
        '        if (candidateDistance2 != bestDistance2)'
        '        {'
        '            return (candidateDistance2 < bestDistance2) ? 1u : 0u;'
        '        }'
        '        return (candidateLen2 < bestLen2) ? 1u : 0u;'
        '    }'
        ''
        '    lhs = (uint64_t)AlgoMinAngle_AbsS32(candidateDot);'
        '    lhs = lhs * lhs * (uint64_t)bestLen2;'
        ''
        '    rhs = (uint64_t)AlgoMinAngle_AbsS32(bestDot);'
        '    rhs = rhs * rhs * (uint64_t)candidateLen2;'
        ''
        '    if (candidateSign == 2u)'
        '    {'
        '        if (lhs != rhs)'
        '        {'
        '            return (lhs > rhs) ? 1u : 0u;'
        '        }'
        '    }'
        '    else'
        '    {'
        '        if (lhs != rhs)'
        '        {'
        '            return (lhs < rhs) ? 1u : 0u;'
        '        }'
        '    }'
        ''
        '    if (candidateDistance2 != bestDistance2)'
        '    {'
        '        return (candidateDistance2 < bestDistance2) ? 1u : 0u;'
        '    }'
        ''
        '    return (candidateLen2 < bestLen2) ? 1u : 0u;'
        '}'
        ''
        'uint8_t AlgoMinAngle_GetWhiteRatioQ10000(uint16_t targetU,'
        '                                         uint16_t targetV,'
        '                                         uint16_t whiteU,'
        '                                         uint16_t whiteV,'
        '                                         uint16_t *whiteRatioQ10000)'
        '{'
        '    uint16_t lutIndex;'
        '    uint16_t pointU;'
        '    uint16_t pointV;'
        '    uint16_t pointRatio12;'
        '    uint16_t nearestRatio12;'
        '    uint16_t radiusNearestRatio12;'
        '    uint16_t bestRatio12;'
        '    uint32_t packedValue;'
        '    uint32_t distance2;'
        '    uint32_t nearestDistance2;'
        '    uint32_t radiusNearestDistance2;'
        '    uint32_t bestDistance2;'
        '    uint32_t awLen2;'
        '    uint32_t bwLen2;'
        '    uint32_t bestBwLen2;'
        '    int32_t awU;'
        '    int32_t awV;'
        '    int32_t bwU;'
        '    int32_t bwV;'
        '    int32_t dot;'
        '    int32_t bestDot;'
        '    uint8_t nearestFound;'
        '    uint8_t radiusNearestFound;'
        '    uint8_t bestFound;'
        ''
        '    if (whiteRatioQ10000 == (void *)0)'
        '    {'
        '        return 0u;'
        '    }'
        ''
        '    if ((targetU == whiteU) && (targetV == whiteV))'
        '    {'
        '        *whiteRatioQ10000 = ALGO_MIN_ANGLE_RATIO_Q10000_MAX;'
        '        return 1u;'
        '    }'
        ''
        '    awU = (int32_t)targetU - (int32_t)whiteU;'
        '    awV = (int32_t)targetV - (int32_t)whiteV;'
        '    awLen2 = (uint32_t)((awU * awU) + (awV * awV));'
        ''
        '    nearestFound = 0u;'
        '    radiusNearestFound = 0u;'
        '    bestFound = 0u;'
        '    nearestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;'
        '    radiusNearestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;'
        '    bestDistance2 = ALGO_MIN_ANGLE_DISTANCE_MAX;'
        '    bestBwLen2 = 0u;'
        '    bestDot = 0;'
        '    nearestRatio12 = 0u;'
        '    radiusNearestRatio12 = 0u;'
        '    bestRatio12 = 0u;'
        ''
        '    for (lutIndex = 0u; lutIndex < ALGO_MIN_ANGLE_LUT_COUNT; lutIndex++)'
        '    {'
        '        packedValue = g_algoMinAnglePackedLut[lutIndex];'
        '        pointU = AlgoMinAngle_GetU(packedValue);'
        '        pointV = AlgoMinAngle_GetV(packedValue);'
        '        pointRatio12 = AlgoMinAngle_GetRatio12(packedValue);'
        '        distance2 = AlgoMinAngle_CalcDistance2(targetU, targetV, pointU, pointV);'
        ''
        '        if ((nearestFound == 0u) || (distance2 < nearestDistance2))'
        '        {'
        '            nearestFound = 1u;'
        '            nearestDistance2 = distance2;'
        '            nearestRatio12 = pointRatio12;'
        '        }'
        ''
        '        if (distance2 == 0u)'
        '        {'
        '            *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(pointRatio12);'
        '            return 1u;'
        '        }'
        ''
        '        if (distance2 >= ALGO_MIN_ANGLE_DELTA_UV_LIMIT2)'
        '        {'
        '            continue;'
        '        }'
        ''
        '        if ((radiusNearestFound == 0u) || (distance2 < radiusNearestDistance2))'
        '        {'
        '            radiusNearestFound = 1u;'
        '            radiusNearestDistance2 = distance2;'
        '            radiusNearestRatio12 = pointRatio12;'
        '        }'
        ''
        '        bwU = (int32_t)pointU - (int32_t)whiteU;'
        '        bwV = (int32_t)pointV - (int32_t)whiteV;'
        '        bwLen2 = (uint32_t)((bwU * bwU) + (bwV * bwV));'
        ''
        '        if ((awLen2 == 0u) || (bwLen2 == 0u))'
        '        {'
        '            continue;'
        '        }'
        ''
        '        dot = (awU * bwU) + (awV * bwV);'
        ''
        '        if ((bestFound == 0u) ||'
        '            (AlgoMinAngle_IsCandidateBetter(dot, bwLen2, distance2, bestDot, bestBwLen2, bestDistance2) != 0u))'
        '        {'
        '            bestFound = 1u;'
        '            bestDot = dot;'
        '            bestBwLen2 = bwLen2;'
        '            bestDistance2 = distance2;'
        '            bestRatio12 = pointRatio12;'
        '        }'
        '    }'
        ''
        '    if (bestFound != 0u)'
        '    {'
        '        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(bestRatio12);'
        '        return 1u;'
        '    }'
        ''
        '    if (radiusNearestFound != 0u)'
        '    {'
        '        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(radiusNearestRatio12);'
        '        return 1u;'
        '    }'
        ''
        '    if (nearestFound != 0u)'
        '    {'
        '        *whiteRatioQ10000 = AlgoMinAngle_ConvertRatio12ToQ10000(nearestRatio12);'
        '        return 1u;'
        '    }'
        ''
        '    return 0u;'
        '}'
    };

    for i = 1:numel(lines)
        fprintf(fid, '%s\n', lines{i});
    end
end

function projectRoot = find_project_root(startDir, inputFolderName)
    projectRoot = startDir;
    while true
        if exist(fullfile(projectRoot, inputFolderName), 'dir')
            return;
        end

        parentDir = fileparts(projectRoot);
        if strcmp(parentDir, projectRoot)
            error('find_project_root:NotFound', ...
                'Cannot find %s from script folder or its parent folders.', inputFolderName);
        end

        projectRoot = parentDir;
    end
end
