% S15_TEMPERATURE_WHITERATIO_ON_25C_GRID_5TEMPS
% Purpose:
%   Use the SAME xy triangular grid generation as S01.
%   The target grid is generated ONLY from 25 deg C RGB chromaticity.
%   Then, for each temperature case such as 25/45/60/80/100 deg C,
%   use that temperature's RGB/W xyY and SPD to re-run Exact ray scan
%   on the fixed 25 deg C grid points.
%
% Output:
%   1. BestWhiteRatio and BestRa for every 25 deg C grid point under each temperature.
%   2. DeltaWhiteRatio_T = BestWhiteRatio_T - BestWhiteRatio_25C.
%   3. DeltaWhiteRatio_Q10000 table for possible compact C evaluation.
%
% Expected input folder structure:
%   projectRoot/
%       guangpu_temperature_input/
%           T25/  R.CSV / G.CSV / B.CSV / W.CSV
%           T45/  R.CSV / G.CSV / B.CSV / W.CSV
%           T60/  R.CSV / G.CSV / B.CSV / W.CSV
%           T80/  R.CSV / G.CSV / B.CSV / W.CSV
%           T100/ R.CSV / G.CSV / B.CSV / W.CSV
%
% Channel xyY is entered directly in the three arrays below:
%   channel_xyY_T25 / channel_xyY_T45 / channel_xyY_T60 / channel_xyY_T80 / channel_xyY_T100
%   Row order: R, G, B, W
%   Columns  : x, y, Y_lm
%
% Note:
%   Grid generation uses 25 deg C R/G/B xy only.
%   Optical evaluation uses the current temperature's xyY and SPD.

clear;
clc;

fprintf('\n============================================================\n');
fprintf('S15 temperature simulation on fixed 25C xy grid\n');
fprintf('Grid: generated by 25C RGB xy, same as S01 xy triangle grid\n');
fprintf('Evaluation: each temperature uses its own xyY and SPD\n');
fprintf('============================================================\n\n');

%% ================= User configurable parameters =================
triangleGridDivCount = 43;      % Same as S01: (43+1)*(43+2)/2 = 990 points
rayScanCount = 1001;            % Exact ray scan count
validateFastEvaluation = false; % Set true if you want a short validation pass
validationRaTolerance = 1e-4;

% Temperature input root. Each temperature has one subfolder for SPD files only.
temperatureInputRootName = 'guangpu_temperature_input';

% ================= Manual channel xyY input =================
% Row order: R, G, B, W
% Columns  : x, y, Y_lm
% Fill these three arrays with your measured/compensated channel data.
% Example row format: [x, y, Y_lm]

% =================1 =================
channel_xyY_T25 = [
    0.7025, 0.2967, 2.9000;  % R, MCU temp = 21.4 deg C
    0.1370, 0.7069, 4.7060;  % G, MCU temp = 21.4 deg C
    0.1521, 0.0284, 0.8733;  % B, MCU temp = 21.4 deg C
    0.3333, 0.3491, 5.5580   % W, MCU temp = 21.4 deg C / SingleWhite
];

channel_xyY_T45 = [
    0.7056, 0.2936, 2.3170;  % R, MCU temp = 43 deg C
    0.1441, 0.7049, 4.5910;  % G, MCU temp = 43 deg C
    0.1511, 0.0298, 0.8697;  % B, MCU temp = 43 deg C
    0.3319, 0.3456, 5.2870   % W, MCU temp = 43 deg C / SingleWhite
];

channel_xyY_T60 = [
    0.7079, 0.2913, 1.8870;  % R, MCU temp = 60 deg C
    0.1499, 0.7027, 4.4450;  % G, MCU temp = 60 deg C
    0.1503, 0.0310, 0.8578;  % B, MCU temp = 60 deg C
    0.3306, 0.3428, 5.0510   % W, MCU temp = 60 deg C / SingleWhite
];

channel_xyY_T80 = [
    0.7104, 0.2889, 1.4370;  % R, MCU temp = 80 deg C
    0.1562, 0.6998, 4.2570;  % G, MCU temp = 80 deg C
    0.1495, 0.0323, 0.8405;  % B, MCU temp = 80 deg C
    0.3294, 0.3404, 4.8170   % W, MCU temp = 80 deg C / SingleWhite
];

channel_xyY_T100 = [
    0.7125, 0.2867, 0.93;  % R, MCU temp = 100 deg C
    0.1631, 0.6951, 4.006;  % G, MCU temp = 100 deg C
    0.1484, 0.0345, 0.8122;  % B, MCU temp = 100 deg C
    0.3268, 0.3366, 4.4850   % W, MCU temp = 100 deg C / SingleWhite
];

% ================= 1=================

% ================= 2=================
% channel_xyY_T25 = [
%     0.7030, 0.2965, 2.8030;  % R, MCU temp = 21.4 deg C
%     0.1472, 0.7211, 5.1110;  % G, MCU temp = 21.4 deg C
%     0.1519, 0.0297, 0.8438;  % B, MCU temp = 21.4 deg C
%     0.3360, 0.3473, 5.3070   % W, MCU temp = 21.4 deg C / SingleWhite
% ];
% channel_xyY_T45 = [
%     0.7056, 0.2936, 2.2750;  % R, MCU temp = 43 deg C
%     0.1536, 0.7165, 4.8790;  % G, MCU temp = 43 deg C
%     0.1510, 0.0310, 0.8383;  % B, MCU temp = 43 deg C
%     0.3347, 0.3442, 5.0820   % W, MCU temp = 43 deg C / SingleWhite
% ];

% channel_xyY_T60 = [
%     0.7075, 0.2915, 1.8980;  % R, MCU temp = 60 deg C
%     0.1590, 0.7128, 4.6590;  % G, MCU temp = 60 deg C
%     0.1503, 0.0320, 0.8254;  % B, MCU temp = 60 deg C
%     0.3334, 0.3416, 4.8710   % W, MCU temp = 60 deg C / SingleWhite
% ];

% channel_xyY_T80 = [
%     0.7099, 0.2890, 1.4360;  % R, MCU temp = 80 deg C
%     0.1657, 0.7079, 4.3820;  % G, MCU temp = 80 deg C
%     0.1494, 0.0334, 0.8045;  % B, MCU temp = 80 deg C
%     0.3316, 0.3384, 4.6110   % W, MCU temp = 80 deg C / SingleWhite
% ];

% channel_xyY_T100 = [
%     0.7120, 0.2868, 1.0430;  % R, MCU temp = 100 deg C
%     0.1720, 0.7031, 4.1190;  % G, MCU temp = 100 deg C
%     0.1486, 0.0348, 0.7806;  % B, MCU temp = 100 deg C
%     0.3299, 0.3357, 4.3590   % W, MCU temp = 100 deg C / SingleWhite
% ];
% ================= 2=================

% ================= 3=================
% channel_xyY_T25 = [
%     0.7016, 0.2976, 2.6190;  % R, MCU temp = 21.4 deg C
%     0.1643, 0.7274, 5.5720;  % G, MCU temp = 21.4 deg C
%     0.1456, 0.0394, 1.2420;  % B, MCU temp = 21.4 deg C
%     0.3345, 0.3497, 5.1500   % W, MCU temp = 21.4 deg C / SingleWhite
% ];
% 
% channel_xyY_T45 = [
%     0.7035, 0.2958, 2.2250;  % R, MCU temp = 43 deg C
%     0.1711, 0.7240, 5.4190;  % G, MCU temp = 43 deg C
%     0.1448, 0.0409, 1.2360;  % B, MCU temp = 43 deg C
%     0.3330, 0.3463, 4.9450   % W, MCU temp = 43 deg C / SingleWhite
% ];
% 
% channel_xyY_T60 = [
%     0.7046, 0.2946, 1.9230;  % R, MCU temp = 60 deg C
%     0.1774, 0.7204, 5.2650;  % G, MCU temp = 60 deg C
%     0.1440, 0.0426, 1.2300;  % B, MCU temp = 60 deg C
%     0.3313, 0.3432, 4.7210   % W, MCU temp = 60 deg C / SingleWhite
% ];
% 
% channel_xyY_T80 = [
%     0.7058, 0.2934, 1.5690;  % R, MCU temp = 80 deg C
%     0.1849, 0.7156, 5.0660;  % G, MCU temp = 80 deg C
%     0.1430, 0.0445, 1.2190;  % B, MCU temp = 80 deg C
%     0.3295, 0.3399, 4.4640   % W, MCU temp = 80 deg C / SingleWhite
% ];
% 
% channel_xyY_T100 = [
%     0.7065, 0.2926, 1.2720;  % R, MCU temp = 100 deg C
%     0.1920, 0.7106, 4.8670;  % G, MCU temp = 100 deg C
%     0.1421, 0.0468, 1.1960;  % B, MCU temp = 100 deg C
%     0.3275, 0.3369, 4.2130   % W, MCU temp = 100 deg C / SingleWhite
% ];
% ================= 3=================


% Temperature cases: FolderName is only used for SPD files; Temperature_C is MCU software-read temperature used by S16/S17.
temperatureCases = struct( ...
    'Label', {'T25', 'T45', 'T60', 'T80', 'T100'}, ...
    'Temperature_C', {21.4, 43, 60, 80, 100}, ...
    'FolderName', {'T25', 'T45', 'T60', 'T80', 'T100'}, ...
    'ChannelXyY', {channel_xyY_T25, channel_xyY_T45, channel_xyY_T60, channel_xyY_T80, channel_xyY_T100} ...
);

% If NaN: use guangpu_case_config().target_xyY(3)
targetY_lm = NaN;

%% ================= Locate project =================
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = find_project_root(scriptDir, 'guangpu_case_input');
inputDir = fullfile(projectRoot, 'guangpu_case_input');
addpath(inputDir);
caseCfg = guangpu_case_config();

if isnan(targetY_lm)
    targetY_lm = caseCfg.target_xyY(3);
end

wl = caseCfg.wavelength_nm;
dLambda = caseCfg.dLambda;

standardDir = fullfile(projectRoot, 'standard_data');
if ~exist(standardDir, 'dir')
    mkdir(standardDir);
end

outputDir = fullfile(projectRoot, 'triangle_grid_lut_output');
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

resultDir = fullfile(outputDir, 's15_temperature_on_25grid');
if ~exist(resultDir, 'dir')
    mkdir(resultDir);
end

temperatureInputRoot = fullfile(projectRoot, temperatureInputRootName);
if ~exist(temperatureInputRoot, 'dir')
    error('Temperature input folder does not exist:\n%s', temperatureInputRoot);
end

std = load_standard_data(standardDir, wl);

%% ================= Load all temperature cases =================
caseCount = numel(temperatureCases);
tempData = repmat(make_empty_temperature_data(), caseCount, 1);

for caseIdx = 1:caseCount
    caseFolder = fullfile(temperatureInputRoot, temperatureCases(caseIdx).FolderName);
    tempData(caseIdx) = load_temperature_case(caseFolder, temperatureCases(caseIdx).Label, ...
        temperatureCases(caseIdx).Temperature_C, temperatureCases(caseIdx).ChannelXyY, std, wl, dLambda);

    fprintf('Loaded %-5s: folder=%s\n', temperatureCases(caseIdx).Label, caseFolder);
    fprintf('  R xyY=(%.6f, %.6f, %.6f)\n', tempData(caseIdx).channel_xyY.R(1), tempData(caseIdx).channel_xyY.R(2), tempData(caseIdx).channel_xyY.R(3));
    fprintf('  G xyY=(%.6f, %.6f, %.6f)\n', tempData(caseIdx).channel_xyY.G(1), tempData(caseIdx).channel_xyY.G(2), tempData(caseIdx).channel_xyY.G(3));
    fprintf('  B xyY=(%.6f, %.6f, %.6f)\n', tempData(caseIdx).channel_xyY.B(1), tempData(caseIdx).channel_xyY.B(2), tempData(caseIdx).channel_xyY.B(3));
    fprintf('  W xyY=(%.6f, %.6f, %.6f)\n', tempData(caseIdx).single_white_xyY(1), tempData(caseIdx).single_white_xyY(2), tempData(caseIdx).single_white_xyY(3));
end

%% ================= Build fixed 25C grid =================
baseCaseIndex = 1;
baseCase = tempData(baseCaseIndex);
baseGrid25 = make_triangle_target_grid_xy(baseCase.channel_xyY.R(1:2), ...
    baseCase.channel_xyY.G(1:2), baseCase.channel_xyY.B(1:2), ...
    targetY_lm, triangleGridDivCount);

fprintf('\n25C fixed xy grid generated. Div=%d, point count=%d\n', ...
    triangleGridDivCount, height(baseGrid25));

%% ================= Scan fixed 25C grid under each temperature =================
resultTable = baseGrid25;
summaryStruct = repmat(make_empty_summary_row(), caseCount, 1);
lutByCase = cell(caseCount, 1);

for caseIdx = 1:caseCount
    label = char(matlab.lang.makeValidName(char(tempData(caseIdx).Label)));
    fprintf('\n------------------------------------------------------------\n');
    fprintf('Scanning fixed 25C grid under %s optical condition...\n', tempData(caseIdx).Label);
    fprintf('------------------------------------------------------------\n');

    singleNorm = scale_to_photopic_Y(tempData(caseIdx).spd.SingleWhite, targetY_lm, std, wl, dLambda);
    singleWhiteXY = tempData(caseIdx).single_white_xyY(1:2);
    rgbTriangleXY = [tempData(caseIdx).channel_xyY.R(1:2); ...
                     tempData(caseIdx).channel_xyY.G(1:2); ...
                     tempData(caseIdx).channel_xyY.B(1:2)];
    rgbSolveMatrix = [xyY_to_XYZ(tempData(caseIdx).channel_xyY.R).', ...
                      xyY_to_XYZ(tempData(caseIdx).channel_xyY.G).', ...
                      xyY_to_XYZ(tempData(caseIdx).channel_xyY.B).'];

    fastPre = build_fast_cri_precompute(tempData(caseIdx).spd, singleNorm, std, dLambda);

    if validateFastEvaluation
        validate_fast_cri_evaluation(baseGrid25, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
            tempData(caseIdx).spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre, validationRaTolerance);
    end

    lutRows = scan_target_grid_to_lut(baseGrid25, targetY_lm, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
        tempData(caseIdx).spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre);
    lutByCase{caseIdx} = lutRows;

    perCaseCsv = fullfile(resultDir, sprintf('s15_fixed25grid_exact_%s.csv', label));
    writetable(lutRows, perCaseCsv);
    fprintf('Exported per-temperature exact LUT: %s\n', perCaseCsv);

    resultTable.([label '_Valid']) = lutRows.Valid;
    resultTable.([label '_BestRa']) = lutRows.Best_Ra;
    resultTable.([label '_BestRmin8']) = lutRows.Best_Rmin_8;
    resultTable.([label '_BestWhiteRatio']) = lutRows.Best_SingleWhiteRatio;
    resultTable.([label '_BestRGBRatio']) = lutRows.Best_RGBWhiteRatio;
    resultTable.([label '_BestRayT']) = lutRows.Best_RayT;
    resultTable.([label '_BestRGBPoint_x']) = lutRows.Best_RGBPoint_x;
    resultTable.([label '_BestRGBPoint_y']) = lutRows.Best_RGBPoint_y;
    resultTable.([label '_R_weight']) = lutRows.Best_R_weight;
    resultTable.([label '_G_weight']) = lutRows.Best_G_weight;
    resultTable.([label '_B_weight']) = lutRows.Best_B_weight;
    resultTable.([label '_BoundaryEdge']) = lutRows.BoundaryEdge;

    validMask = lutRows.Valid & isfinite(lutRows.Best_SingleWhiteRatio) & isfinite(lutRows.Best_Ra);
    summaryStruct(caseIdx).Label = string(tempData(caseIdx).Label);
    summaryStruct(caseIdx).Temperature_C = tempData(caseIdx).Temperature_C;
    summaryStruct(caseIdx).PointCount = height(lutRows);
    summaryStruct(caseIdx).ValidCount = sum(validMask);
    summaryStruct(caseIdx).InvalidCount = height(lutRows) - sum(validMask);
    summaryStruct(caseIdx).MeanBestRa = mean(lutRows.Best_Ra(validMask));
    summaryStruct(caseIdx).MeanBestWhiteRatio = mean(lutRows.Best_SingleWhiteRatio(validMask));

    fprintf('%s summary: valid=%u/%u, mean Ra=%.6f, mean WhiteRatio=%.6f\n', ...
        tempData(caseIdx).Label, uint32(summaryStruct(caseIdx).ValidCount), uint32(summaryStruct(caseIdx).PointCount), ...
        summaryStruct(caseIdx).MeanBestRa, summaryStruct(caseIdx).MeanBestWhiteRatio);
end

%% ================= Delta against 25C =================
baseLabel = char(matlab.lang.makeValidName(char(tempData(baseCaseIndex).Label)));
baseValid = resultTable.([baseLabel '_Valid']);
baseWhite = resultTable.([baseLabel '_BestWhiteRatio']);
baseRa = resultTable.([baseLabel '_BestRa']);

deltaQTable = baseGrid25(:, {'GridI','GridJ','GridK','x','y','Y_lm','u1976','v1976'});

for caseIdx = 1:caseCount
    label = char(matlab.lang.makeValidName(char(tempData(caseIdx).Label)));
    validBoth = baseValid & resultTable.([label '_Valid']);

    deltaWhite = resultTable.([label '_BestWhiteRatio']) - baseWhite;
    deltaRa = resultTable.([label '_BestRa']) - baseRa;
    deltaWhite(~validBoth) = NaN;
    deltaRa(~validBoth) = NaN;

    resultTable.([label '_DeltaWhiteRatio_From25C']) = deltaWhite;
    resultTable.([label '_DeltaRa_From25C']) = deltaRa;

    deltaQ = round(deltaWhite .* 10000);
    deltaQ(~isfinite(deltaQ)) = 0;
    deltaQ = min(max(deltaQ, -32768), 32767);
    deltaQTable.([label '_DeltaWhiteRatio_Q10000']) = int16(deltaQ);

    if caseIdx ~= baseCaseIndex
        absDeltaWhite = abs(deltaWhite(validBoth));
        absDeltaRa = abs(deltaRa(validBoth));
        summaryStruct(caseIdx).MeanDeltaWhiteRatio_From25C = mean(deltaWhite(validBoth));
        summaryStruct(caseIdx).MeanAbsDeltaWhiteRatio_From25C = mean(absDeltaWhite);
        summaryStruct(caseIdx).P95AbsDeltaWhiteRatio_From25C = local_percentile(absDeltaWhite, 95);
        summaryStruct(caseIdx).MaxAbsDeltaWhiteRatio_From25C = max(absDeltaWhite);
        summaryStruct(caseIdx).MeanDeltaRa_From25C = mean(deltaRa(validBoth));
        summaryStruct(caseIdx).MeanAbsDeltaRa_From25C = mean(absDeltaRa);
        summaryStruct(caseIdx).P95AbsDeltaRa_From25C = local_percentile(absDeltaRa, 95);
        summaryStruct(caseIdx).MaxAbsDeltaRa_From25C = max(absDeltaRa);
    end
end

%% ================= Export final tables =================
fullCsv = fullfile(resultDir, 's15_fixed25grid_temperature_exact_and_delta_full.csv');
compactCsv = fullfile(resultDir, 's15_fixed25grid_temperature_delta_q10000.csv');
summaryCsv = fullfile(resultDir, 's15_fixed25grid_temperature_summary.csv');

writetable(resultTable, fullCsv);
writetable(deltaQTable, compactCsv);
writetable(struct2table(summaryStruct), summaryCsv);

fprintf('\n============================================================\n');
fprintf('S15 finished. Output files:\n');
fprintf('  Full result : %s\n', fullCsv);
fprintf('  Delta Q10000: %s\n', compactCsv);
fprintf('  Summary     : %s\n', summaryCsv);
fprintf('============================================================\n');

%% ================= S15 helper functions =================
function s = make_empty_temperature_data()
    s.Label = "";
    s.Temperature_C = NaN;
    s.channel_xyY.R = [NaN, NaN, NaN];
    s.channel_xyY.G = [NaN, NaN, NaN];
    s.channel_xyY.B = [NaN, NaN, NaN];
    s.channel_xyY.W = [NaN, NaN, NaN];
    s.single_white_xyY = [NaN, NaN, NaN];
    s.spd.R = [];
    s.spd.G = [];
    s.spd.B = [];
    s.spd.W = [];
    s.spd.SingleWhite = [];
end

function s = make_empty_summary_row()
    s.Label = "";
    s.Temperature_C = NaN;
    s.PointCount = NaN;
    s.ValidCount = NaN;
    s.InvalidCount = NaN;
    s.MeanBestRa = NaN;
    s.MeanBestWhiteRatio = NaN;
    s.MeanDeltaWhiteRatio_From25C = NaN;
    s.MeanAbsDeltaWhiteRatio_From25C = NaN;
    s.P95AbsDeltaWhiteRatio_From25C = NaN;
    s.MaxAbsDeltaWhiteRatio_From25C = NaN;
    s.MeanDeltaRa_From25C = NaN;
    s.MeanAbsDeltaRa_From25C = NaN;
    s.P95AbsDeltaRa_From25C = NaN;
    s.MaxAbsDeltaRa_From25C = NaN;
end

function data = load_temperature_case(caseFolder, label, temperatureC, channelXyYMatrix, std, wl, dLambda)
    if ~exist(caseFolder, 'dir')
        error('Temperature case folder does not exist: %s', caseFolder);
    end

    channel_xyY = channel_xyY_matrix_to_struct(channelXyYMatrix, label);

    raw.R = read_spd(fullfile(caseFolder, 'R.CSV'), '', wl);
    raw.G = read_spd(fullfile(caseFolder, 'G.CSV'), '', wl);
    raw.B = read_spd(fullfile(caseFolder, 'B.CSV'), '', wl);
    raw.W = read_spd(fullfile(caseFolder, 'W.CSV'), '', wl);
    raw.SingleWhite = raw.W;

    spd.R = scale_to_photopic_Y(raw.R, channel_xyY.R(3), std, wl, dLambda);
    spd.G = scale_to_photopic_Y(raw.G, channel_xyY.G(3), std, wl, dLambda);
    spd.B = scale_to_photopic_Y(raw.B, channel_xyY.B(3), std, wl, dLambda);
    spd.W = scale_to_photopic_Y(raw.W, channel_xyY.W(3), std, wl, dLambda);
    spd.SingleWhite = spd.W;

    data = make_empty_temperature_data();
    data.Label = string(label);
    data.Temperature_C = temperatureC;
    data.channel_xyY = channel_xyY;
    data.single_white_xyY = channel_xyY.W;
    data.spd = spd;
end

function channel_xyY = channel_xyY_matrix_to_struct(M, label)
    if ~isequal(size(M), [4, 3])
        error('%s channel xyY array must be 4x3. Row order: R,G,B,W. Columns: x,y,Y_lm.', string(label));
    end

    if any(~isfinite(M(:)))
        error('%s channel xyY array contains NaN/Inf. Please fill channel_xyY_%s first.', string(label), erase(string(label), "T"));
    end

    channel_xyY.R = M(1, :);
    channel_xyY.G = M(2, :);
    channel_xyY.B = M(3, :);
    channel_xyY.W = M(4, :);
end

function p = local_percentile(x, pct)
    x = x(isfinite(x));
    if isempty(x)
        p = NaN;
        return;
    end
    x = sort(x(:));
    if numel(x) == 1
        p = x(1);
        return;
    end
    pos = 1 + (pct / 100) * (numel(x) - 1);
    lo = floor(pos);
    hi = ceil(pos);
    if lo == hi
        p = x(lo);
    else
        p = x(lo) + (x(hi) - x(lo)) * (pos - lo);
    end
end


%% ================= Local functions =================

function lutRows = scan_target_grid_to_lut(targetGrid, targetY_lm, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
    spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre)

    pointCount = height(targetGrid);

    varNames = {'GridI','GridJ','GridK', ...
        'Target_x','Target_y','Target_Y_lm','Target_u1976','Target_v1976', ...
        'Best_Ra','Best_Rmin_8','Best_Worst_R','Best_RayT', ...
        'Best_SingleWhiteRatio','Best_RGBWhiteRatio', ...
        'Best_RGBPoint_x','Best_RGBPoint_y','Best_RGBPoint_Y_lm','Best_RGBPoint_u1976','Best_RGBPoint_v1976', ...
        'Best_R_weight','Best_G_weight','Best_B_weight', ...
        'Mix_x','Mix_y','Mix_Y_lm','Mix_CCT_K','BoundaryEdge','Valid'};

    varTypes = {'double','double','double', ...
        'double','double','double','double','double', ...
        'double','double','string','double', ...
        'double','double', ...
        'double','double','double','double','double', ...
        'double','double','double', ...
        'double','double','double','double','string','logical'};

    lutRows = table('Size', [pointCount, numel(varNames)], ...
        'VariableTypes', varTypes, 'VariableNames', varNames);

    for i = 1:pointCount
        target_xyY = [targetGrid.x(i), targetGrid.y(i), targetY_lm];

        best = find_best_ra_for_target_optimized(target_xyY, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
            spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre);

        lutRows.GridI(i) = targetGrid.GridI(i);
        lutRows.GridJ(i) = targetGrid.GridJ(i);
        lutRows.GridK(i) = targetGrid.GridK(i);
        lutRows.Target_x(i) = targetGrid.x(i);
        lutRows.Target_y(i) = targetGrid.y(i);
        lutRows.Target_Y_lm(i) = targetY_lm;
        lutRows.Target_u1976(i) = targetGrid.u1976(i);
        lutRows.Target_v1976(i) = targetGrid.v1976(i);

        if best.Valid
            lutRows.Best_Ra(i) = best.Ra;
            lutRows.Best_Rmin_8(i) = best.Rmin8;
            lutRows.Best_Worst_R(i) = "R" + string(best.WorstIndex);
            lutRows.Best_RayT(i) = best.RayT;
            lutRows.Best_SingleWhiteRatio(i) = best.SingleWhiteRatio;
            lutRows.Best_RGBWhiteRatio(i) = best.RGBWhiteRatio;
            lutRows.Best_RGBPoint_x(i) = best.RGBPoint_xyY(1);
            lutRows.Best_RGBPoint_y(i) = best.RGBPoint_xyY(2);
            lutRows.Best_RGBPoint_Y_lm(i) = best.RGBPoint_xyY(3);
            bestRgbUv = xy_to_uv1976(best.RGBPoint_xyY(1:2));
            lutRows.Best_RGBPoint_u1976(i) = bestRgbUv(1);
            lutRows.Best_RGBPoint_v1976(i) = bestRgbUv(2);
            lutRows.Best_R_weight(i) = best.R_weight;
            lutRows.Best_G_weight(i) = best.G_weight;
            lutRows.Best_B_weight(i) = best.B_weight;
            lutRows.Mix_x(i) = best.Mix_xyY(1);
            lutRows.Mix_y(i) = best.Mix_xyY(2);
            lutRows.Mix_Y_lm(i) = best.Mix_xyY(3);
            lutRows.Mix_CCT_K(i) = best.CCT;
            lutRows.BoundaryEdge(i) = best.BoundaryEdge;
            lutRows.Valid(i) = true;
        else
            lutRows.Best_Worst_R(i) = "";
            lutRows.BoundaryEdge(i) = "";
            lutRows.Valid(i) = false;
        end
    end
end

function centerGrid = make_triangle_cell_center_grid_xy(baseGrid, divCount, targetY_lm)
    % 每个基础小三角形取一个中心点，用于判断是否需要自适应加密。
    baseKey = make_grid_key(baseGrid.GridI, baseGrid.GridJ, baseGrid.GridK);
    baseIndex = containers.Map(baseKey, num2cell(1:height(baseGrid)));

    maxCenterCount = divCount * divCount;
    vals = nan(maxCenterCount, 11);
    idx = 0;

    for i = 0:(divCount - 1)
        for j = 0:(divCount - i - 1)
            k = divCount - i - j;

            % Lower triangle: (i,j,k), (i+1,j,k-1), (i,j+1,k-1)
            v1 = get_grid_row(baseGrid, baseIndex, i, j, k);
            v2 = get_grid_row(baseGrid, baseIndex, i + 1, j, k - 1);
            v3 = get_grid_row(baseGrid, baseIndex, i, j + 1, k - 1);
            idx = idx + 1;
            vals(idx, :) = make_center_row(baseGrid, [v1, v2, v3], targetY_lm);

            % Upper triangle exists when k >= 2:
            % (i+1,j,k-1), (i+1,j+1,k-2), (i,j+1,k-1)
            if k >= 2
                v1 = get_grid_row(baseGrid, baseIndex, i + 1, j, k - 1);
                v2 = get_grid_row(baseGrid, baseIndex, i + 1, j + 1, k - 2);
                v3 = get_grid_row(baseGrid, baseIndex, i, j + 1, k - 1);
                idx = idx + 1;
                vals(idx, :) = make_center_row(baseGrid, [v1, v2, v3], targetY_lm);
            end
        end
    end

    vals = vals(1:idx, :);
    centerGrid = array2table(vals, 'VariableNames', ...
        {'GridI','GridJ','GridK','x','y','Y_lm','u1976','v1976','V1','V2','V3'});
end

function row = make_center_row(baseGrid, vertexRows, targetY_lm)
    % xy grid refinement: average the cell vertices in xy space first,
    % then convert that xy center to CIE 1976 u'v' for exported columns and distance search.
    xy = mean([baseGrid.x(vertexRows), baseGrid.y(vertexRows)], 1);
    uv = xy_to_uv1976(xy);
    gridI = mean(baseGrid.GridI(vertexRows));
    gridJ = mean(baseGrid.GridJ(vertexRows));
    gridK = mean(baseGrid.GridK(vertexRows));
    row = [gridI, gridJ, gridK, xy(1), xy(2), targetY_lm, uv(1), uv(2), vertexRows(1), vertexRows(2), vertexRows(3)];
end

function rowIndex = get_grid_row(baseGrid, baseIndex, i, j, k)
    key = make_grid_key(i, j, k);
    if ~isKey(baseIndex, key)
        error('Cannot find base grid vertex (%g,%g,%g).', i, j, k);
    end
    rowIndex = baseIndex(key);
end

function key = make_grid_key(i, j, k)
    key = string(i) + "_" + string(j) + "_" + string(k);
    key = cellstr(key);
    if numel(key) == 1
        key = key{1};
    end
end

function refineMask = select_adaptive_center_points(baseRows, centerRows, centerGrid, ...
    keepAllCenters, whiteRatioDiffThreshold, raErrorThreshold, whiteRatioMin)

    if keepAllCenters
        refineMask = true(height(centerGrid), 1);
        return;
    end

    refineMask = false(height(centerGrid), 1);

    for i = 1:height(centerGrid)
        if ~centerRows.Valid(i)
            continue;
        end

        v = [centerGrid.V1(i), centerGrid.V2(i), centerGrid.V3(i)];
        vertexValid = baseRows.Valid(v);
        if ~all(vertexValid)
            refineMask(i) = true;
            continue;
        end

        vertexWhite = baseRows.Best_SingleWhiteRatio(v);
        vertexRa = baseRows.Best_Ra(v);

        interpWhite = mean(vertexWhite);
        interpRa = mean(vertexRa);

        centerWhite = centerRows.Best_SingleWhiteRatio(i);
        centerRa = centerRows.Best_Ra(i);

        whiteError = abs(centerWhite - interpWhite);
        raError = abs(centerRa - interpRa);

        transitionHidden = (centerWhite > whiteRatioMin) && (max(vertexWhite) <= whiteRatioMin);

        if whiteError > whiteRatioDiffThreshold || raError > raErrorThreshold || transitionHidden
            refineMask(i) = true;
        end
    end
end

function outGrid = unique_target_grid(inGrid)
    core = inGrid(:, {'GridI','GridJ','GridK','x','y','Y_lm','u1976','v1976'});
    % xy grid: de-duplicate by xy, not by u'v'.
    keyX = round(core.x .* 1e10);
    keyY = round(core.y .* 1e10);
    [~, uniqueIndex] = unique([keyX, keyY], 'rows', 'stable');
    outGrid = core(uniqueIndex, :);
end

function projectRoot = find_project_root(startDir, inputFolderName)
    projectRoot = startDir;
    while true
        if exist(fullfile(projectRoot, inputFolderName), 'dir')
            return;
        end
        parentDir = fileparts(projectRoot);
        if strcmp(parentDir, projectRoot)
            error('find_project_root:NotFound', ...
                'Cannot find %s from script folder or its parent folders.', inputFolderName);
        end
        projectRoot = parentDir;
    end
end

function grid = make_triangle_target_grid_xy(Rxy, Gxy, Bxy, targetY_lm, divCount)
    % Uniform xy triangular grid:
    %   xy = a * Rxy + b * Gxy + c * Bxy
    %   a + b + c = 1
    % u'v' is calculated after xy is generated, only for export/search compatibility.
    pointCount = (divCount + 1) * (divCount + 2) / 2;
    vals = nan(pointCount, 8);
    idx = 0;

    for i = 0:divCount
        for j = 0:(divCount - i)
            k = divCount - i - j;
            a = i / divCount;
            b = j / divCount;
            c = k / divCount;
            xy = a .* Rxy + b .* Gxy + c .* Bxy;
            uv = xy_to_uv1976(xy);
            idx = idx + 1;
            vals(idx, :) = [i, j, k, xy(1), xy(2), targetY_lm, uv(1), uv(2)];
        end
    end

    grid = array2table(vals, 'VariableNames', ...
        {'GridI','GridJ','GridK','x','y','Y_lm','u1976','v1976'});
end

function best = find_best_ra_for_target_optimized(target_xyY, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
    spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre)
% Same geometric ray-scan logic as calculate_guangpu_metameric_cri_backup_20260509_before_duv005.m.
% Optimization: do not build a per-target blendRows table and do not redo fixed
% channel integrals for every rayT. The mixed spectrum math is still linear and
% equivalent to the original calculation.

    best.Valid = false;
    best.Ra = -Inf;
    best.Rmin8 = -Inf;
    best.WorstIndex = NaN;
    best.RayT = NaN;
    best.SingleWhiteRatio = NaN;
    best.RGBWhiteRatio = NaN;
    best.RGBPoint_xyY = [NaN NaN NaN];
    best.R_weight = NaN;
    best.G_weight = NaN;
    best.B_weight = NaN;
    best.Mix_xyY = [NaN NaN NaN];
    best.CCT = NaN;
    best.BoundaryEdge = "";

    targetXY = target_xyY(1:2);

    try
        [~, boundaryRayT, boundaryEdge, ~] = ...
            find_ray_gamut_intersection(singleWhiteXY, targetXY, rgbTriangleXY);
        rayTList = linspace(1, boundaryRayT, rayScanCount).';

        % Reference source is fixed for this target because every valid rayT
        % is constrained to the same target xyY.
        targetXYZ = xyY_to_XYZ(target_xyY);
        targetUV = XYZ_to_uv1960(targetXYZ);
        [targetCCT, ~] = estimate_cct_uv(targetUV, std.cmf, wl, dLambda);
        refSpd = reference_spd(targetCCT, std, wl);
        refXYZ = source_XYZ(refSpd, std.cmf, dLambda);
        refUV = XYZ_to_uv1960(refXYZ);
        refUVW = tcs_uvw(refSpd, std.cmf, std.tcs, dLambda, refUV, refUV, false);

        for i = 1:numel(rayTList)
            rayT = rayTList(i);
            rgbPointXY = singleWhiteXY + rayT .* (targetXY - singleWhiteXY);
            split = split_target_on_ray(target_xyY, singleWhiteXY, rgbPointXY, rayT);
            rgbPoint_xyY = [rgbPointXY, split.RGBY];
            pointWeights = solve_rgb_point_weights(rgbPoint_xyY, rgbSolveMatrix);

            % Fast equivalent of:
            % rgbPointSpd = Rw*spd.R + Gw*spd.G + Bw*spd.B;
            % mixSpd = split.WhiteYRatio*singleNorm + rgbPointSpd;
            m = spectrum_metrics_fast(split.WhiteYRatio, pointWeights, fastPre, targetCCT, refUV, refUVW);

            if m.Ra > best.Ra
                best.Valid = true;
                best.Ra = m.Ra;
                best.Rmin8 = m.Rmin8;
                best.WorstIndex = m.WorstIndex;
                best.RayT = rayT;
                best.SingleWhiteRatio = split.WhiteYRatio;
                best.RGBWhiteRatio = split.RGBYRatio;
                best.RGBPoint_xyY = [rgbPointXY, split.RGBY];
                best.R_weight = pointWeights(1);
                best.G_weight = pointWeights(2);
                best.B_weight = pointWeights(3);
                best.Mix_xyY = m.xyY;
                best.CCT = m.CCT;
                if i == numel(rayTList)
                    best.BoundaryEdge = string(boundaryEdge);
                else
                    best.BoundaryEdge = "";
                end
            end
        end
    catch ME
        warning('find_best_ra_for_target_optimized:InvalidTarget', ...
            'Skip target xy=(%.6f, %.6f): %s', target_xyY(1), target_xyY(2), ME.message);
    end
end

function weights = solve_rgb_point_weights(point_xyY, rgbSolveMatrix)
    b = xyY_to_XYZ(point_xyY).';
    weights = rgbSolveMatrix \ b;
    weights(abs(weights) < 1e-10) = 0;

    if any(weights < -1e-8)
        error('solve_rgb_point_weights:OutsideGamut', ...
            'RGB candidate xy=(%.6f, %.6f) is outside the measured RGB gamut.', ...
            point_xyY(1), point_xyY(2));
    end
end

function fastPre = build_fast_cri_precompute(spd, singleNorm, std, dLambda)
    fastPre.cmf = std.cmf;
    fastPre.tcs = std.tcs;
    fastPre.dLambda = dLambda;

    fastPre.XYZ.SingleWhite = source_XYZ(singleNorm, std.cmf, dLambda);
    fastPre.XYZ.R = source_XYZ(spd.R, std.cmf, dLambda);
    fastPre.XYZ.G = source_XYZ(spd.G, std.cmf, dLambda);
    fastPre.XYZ.B = source_XYZ(spd.B, std.cmf, dLambda);

    fastPre.TCS.SingleWhite = channel_tcs_xyz_unscaled(singleNorm, std.cmf, std.tcs, dLambda);
    fastPre.TCS.R = channel_tcs_xyz_unscaled(spd.R, std.cmf, std.tcs, dLambda);
    fastPre.TCS.G = channel_tcs_xyz_unscaled(spd.G, std.cmf, std.tcs, dLambda);
    fastPre.TCS.B = channel_tcs_xyz_unscaled(spd.B, std.cmf, std.tcs, dLambda);
end

function tcsXYZ = channel_tcs_xyz_unscaled(channelSpd, cmf, tcs, dLambda)
    sampleCount = size(tcs, 2);
    tcsXYZ = zeros(sampleCount, 3);
    for i = 1:sampleCount
        tcsXYZ(i, :) = sum(channelSpd(:) .* tcs(:, i) .* cmf, 1) .* dLambda;
    end
end

function m = spectrum_metrics_fast(singleWhiteRatio, weights, fastPre, CCT, refUV, refUVW)
    mixXYZ = singleWhiteRatio .* fastPre.XYZ.SingleWhite + ...
             weights(1) .* fastPre.XYZ.R + ...
             weights(2) .* fastPre.XYZ.G + ...
             weights(3) .* fastPre.XYZ.B;

    xyY = XYZ_to_xyY(mixXYZ);
    photopicY = 683 * mixXYZ(2);
    sourceUV = XYZ_to_uv1960(mixXYZ);

    mixTcsXYZ = singleWhiteRatio .* fastPre.TCS.SingleWhite + ...
                weights(1) .* fastPre.TCS.R + ...
                weights(2) .* fastPre.TCS.G + ...
                weights(3) .* fastPre.TCS.B;

    testUVW = tcs_uvw_from_unscaled_tcs_xyz(mixTcsXYZ, mixXYZ(2), sourceUV, refUV, true);

    Ri = zeros(8, 1);
    for i = 1:8
        deltaE = norm(refUVW(i,:) - testUVW(i,:));
        Ri(i) = 100 - 4.6 * deltaE;
    end

    [Rmin8, worstIndex] = min(Ri);
    m.XYZ = mixXYZ;
    m.xyY = [xyY(1), xyY(2), photopicY];
    m.photopicY = photopicY;
    m.uv1960 = sourceUV;
    m.CCT = CCT;
    m.Ri = Ri;
    m.Ra = mean(Ri);
    m.Rmin8 = Rmin8;
    m.WorstIndex = worstIndex;
end

function UVW = tcs_uvw_from_unscaled_tcs_xyz(unscaledTcsXYZ, sourceY, sourceUV, refUV, doAdapt)
    k = 100 / sourceY;
    UVW = zeros(size(unscaledTcsXYZ, 1), 3);

    cfun = @(u, v) (4 - u - 10 * v) / v;
    dfun = @(u, v) (1.708 * v + 0.404 - 1.481 * u) / v;
    sourceC = cfun(sourceUV(1), sourceUV(2));
    sourceD = dfun(sourceUV(1), sourceUV(2));
    refC = cfun(refUV(1), refUV(2));
    refD = dfun(refUV(1), refUV(2));

    for i = 1:size(unscaledTcsXYZ, 1)
        sampleXYZ = k .* unscaledTcsXYZ(i, :);
        sampleXY = XYZ_to_xyY(sampleXYZ);
        sampleUV = XYZ_to_uv1960(sampleXYZ);
        u = sampleUV(1);
        v = sampleUV(2);
        if doAdapt
            sampleC = cfun(u, v);
            sampleD = dfun(u, v);
            denominator = 16.518 + 1.481 * refC / sourceC * sampleC - refD / sourceD * sampleD;
            u = (10.872 + 0.404 * refC / sourceC * sampleC - 4 * refD / sourceD * sampleD) / denominator;
            v = 5.520 / denominator;
        end
        W = 25 * sampleXY(3)^(1/3) - 17;
        U = 13 * W * (u - refUV(1));
        V = 13 * W * (v - refUV(2));
        UVW(i,:) = [U, V, W];
    end
end

function validate_fast_cri_evaluation(targetGrid, singleWhiteXY, rgbTriangleXY, rgbSolveMatrix, ...
    spd, singleNorm, std, wl, dLambda, rayScanCount, fastPre, toleranceRa)
    fprintf('\nValidating fast CRI evaluation against original spectrum_metrics...\n');
    if height(targetGrid) == 0
        return;
    end

    targetIndices = unique(round(linspace(1, height(targetGrid), min(5, height(targetGrid)))));
    maxRaDiff = 0;

    for ti = targetIndices(:).'
        target_xyY = [targetGrid.x(ti), targetGrid.y(ti), targetGrid.Y_lm(ti)];
        try
            [~, boundaryRayT, ~, ~] = find_ray_gamut_intersection(singleWhiteXY, target_xyY(1:2), rgbTriangleXY);
            rayList = linspace(1, boundaryRayT, min(9, rayScanCount)).';
            targetXYZ = xyY_to_XYZ(target_xyY);
            targetUV = XYZ_to_uv1960(targetXYZ);
            [targetCCT, ~] = estimate_cct_uv(targetUV, std.cmf, wl, dLambda);
            refSpd = reference_spd(targetCCT, std, wl);
            refXYZ = source_XYZ(refSpd, std.cmf, dLambda);
            refUV = XYZ_to_uv1960(refXYZ);
            refUVW = tcs_uvw(refSpd, std.cmf, std.tcs, dLambda, refUV, refUV, false);

            for ri = 1:numel(rayList)
                rayT = rayList(ri);
                rgbPointXY = singleWhiteXY + rayT .* (target_xyY(1:2) - singleWhiteXY);
                split = split_target_on_ray(target_xyY, singleWhiteXY, rgbPointXY, rayT);
                rgbPoint_xyY = [rgbPointXY, split.RGBY];
                [weights, rgbPointSpd] = solve_rgb_point_spectrum(rgbPoint_xyY, rgbSolveMatrix, spd);
                mixSpd = split.WhiteYRatio .* singleNorm + rgbPointSpd;
                exactM = spectrum_metrics(mixSpd, std, wl, dLambda);
                fastM = spectrum_metrics_fast(split.WhiteYRatio, weights, fastPre, targetCCT, refUV, refUVW);
                maxRaDiff = max(maxRaDiff, abs(exactM.Ra - fastM.Ra));
            end
        catch ME
            warning('validate_fast_cri_evaluation:SkipTarget', ...
                'Skip validation target xy=(%.6f, %.6f): %s', target_xyY(1), target_xyY(2), ME.message);
        end
    end

    fprintf('  Max Ra difference = %.10f\n', maxRaDiff);
    if maxRaDiff > toleranceRa
        error('Fast CRI validation failed: max Ra difference %.10f > tolerance %.10f.', maxRaDiff, toleranceRa);
    end
    fprintf('  Fast CRI validation passed.\n');
end

function [pointXY, rayT, edgeName, edgeIndex] = find_ray_gamut_intersection(whiteXY, targetXY, triangleXY)
    edgeNames = {'R-G'; 'G-B'; 'B-R'};
    whiteXY = double(whiteXY(:).');
    targetXY = double(targetXY(:).');
    triangleXY = double(triangleXY(:, 1:2));
    direction = targetXY - whiteXY;

    if norm(direction) <= eps
        error('find_ray_gamut_intersection:SamePoint', ...
            'The fixed single white and target have the same xy.');
    end

    tol = 1e-12;
    rayT = Inf;
    edgeIndex = NaN;
    pointXY = [NaN NaN];

    for i = 1:3
        edgeStart = triangleXY(i, :);
        edgeEnd = triangleXY(mod(i, 3) + 1, :);
        edgeVector = edgeEnd - edgeStart;
        systemMatrix = [direction(:), -edgeVector(:)];
        if abs(det(systemMatrix)) < tol
            continue;
        end

        params = systemMatrix \ (edgeStart - whiteXY).';
        t = params(1);
        s = params(2);

        if t >= 1 - tol && s >= -tol && s <= 1 + tol && t < rayT
            rayT = t;
            edgeIndex = i;
            pointXY = whiteXY + t .* direction;
        end
    end

    if ~isfinite(rayT)
        error('find_ray_gamut_intersection:NoIntersection', ...
            'The fixed-white to target ray does not hit the RGB gamut boundary after the target.');
    end

    edgeName = edgeNames{edgeIndex};
end

function split = split_target_on_ray(target_xyY, whiteXY, pointXY, rayT)
    targetY = target_xyY(3);
    target_y = target_xyY(2);
    if target_y <= eps
        error('split_target_on_ray:InvalidTarget', 'Target y is too small for luminance splitting.');
    end

    lambda = 1 ./ rayT;
    oneMinusLambda = 1 - lambda;

    split.WhiteXYCoeff = oneMinusLambda;
    split.RGBXYCoeff = lambda;
    split.WhiteY = targetY * oneMinusLambda * whiteXY(2) / target_y;
    split.RGBY = targetY * lambda * pointXY(2) / target_y;
    split.WhiteYRatio = split.WhiteY / targetY;
    split.RGBYRatio = split.RGBY / targetY;
end

function [weights, rgbSpd] = solve_rgb_point_spectrum(point_xyY, rgbSolveMatrix, spd)
    b = xyY_to_XYZ(point_xyY).';
    weights = rgbSolveMatrix \ b;
    weights(abs(weights) < 1e-10) = 0;

    if any(weights < -1e-8)
        error('solve_rgb_point_spectrum:OutsideGamut', ...
            'RGB candidate xy=(%.6f, %.6f) is outside the measured RGB gamut.', ...
            point_xyY(1), point_xyY(2));
    end

    rgbSpd = weights(1) .* spd.R + weights(2) .* spd.G + weights(3) .* spd.B;
end

function export_best_rgb_uv_c_header(filePath, rows, divCount)
    fid = fopen(filePath, 'w');
    if fid < 0
        error('Cannot open C header for writing: %s', filePath);
    end

    cleanupObj = onCleanup(@() fclose(fid));
    fprintf(fid, '/* Auto-generated by calculate_guangpu_triangle_grid_lut.m */\n');
    fprintf(fid, '#ifndef GUANGPU_TRIANGLE_GRID_BEST_RGB_UV_LUT_H\n');
    fprintf(fid, '#define GUANGPU_TRIANGLE_GRID_BEST_RGB_UV_LUT_H\n\n');
    fprintf(fid, '#include <stdint.h>\n\n');
    fprintf(fid, '#define GUANGPU_TRI_GRID_DIV_COUNT   %uU\n', uint32(divCount));
    fprintf(fid, '#define GUANGPU_TRI_GRID_POINT_COUNT %uU\n\n', uint32(height(rows)));
    fprintf(fid, 'typedef struct\n{\n    uint16_t u_q16;\n    uint16_t v_q16;\n} ST_GuangpuBestRgbUv;\n\n');
    fprintf(fid, 'static const ST_GuangpuBestRgbUv g_GuangpuBestRgbUvLut[GUANGPU_TRI_GRID_POINT_COUNT] =\n{\n');

    for i = 1:height(rows)
        uq = q0_1_to_u16(rows.Best_RGBPoint_u1976(i));
        vq = q0_1_to_u16(rows.Best_RGBPoint_v1976(i));
        if ~rows.Valid(i)
            uq = uint16(0);
            vq = uint16(0);
        end
        fprintf(fid, '    { %5uU, %5uU }, /* %4u: grid=(%u,%u,%u) */\n', ...
            uq, vq, uint32(i - 1), uint32(rows.GridI(i)), uint32(rows.GridJ(i)), uint32(rows.GridK(i)));
    end

    fprintf(fid, '};\n\n');
    fprintf(fid, '#endif /* GUANGPU_TRIANGLE_GRID_BEST_RGB_UV_LUT_H */\n');
end

function q = q0_1_to_u16(x)
    if ~isfinite(x)
        x = 0;
    end
    x = min(max(x, 0), 1);
    q = uint16(round(x * 65535));
end

function xyY = spectrum_xyY(spd, std, dLambda)
    XYZ = source_XYZ(spd, std.cmf, dLambda);
    xy = XYZ_to_xyY(XYZ);
    xyY = [xy(1), xy(2), 683 * XYZ(2)];
end

function std = load_standard_data(standardDir, wl)
    xyzPath = ensure_file(standardDir, 'CIE_xyz_1931_2deg.csv', 'https://files.cie.co.at/CIE_xyz_1931_2deg.csv');
    tcsPath = ensure_file(standardDir, 'CIE_srf_cri.csv', 'https://files.cie.co.at/CIE_srf_cri.csv');
    dPath = ensure_file(standardDir, 'CIE_illum_Dxx_comp.csv', 'https://files.cie.co.at/CIE_illum_Dxx_comp.csv');

    xyz = readmatrix(xyzPath);
    tcs = readmatrix(tcsPath);
    d = readmatrix(dPath);

    std.cmf = interp1(xyz(:,1), xyz(:,2:4), wl, 'linear', 'extrap');
    std.tcs = interp1(tcs(:,1), tcs(:,2:9), wl, 'linear', 'extrap');
    std.daylightComponents = interp1(d(:,1), d(:,2:4), wl, 'linear', 'extrap');
end

function path = ensure_file(folder, fileName, url)
    path = fullfile(folder, fileName);
    if ~exist(path, 'file')
        websave(path, url);
    end
end

function spd = read_spd(fileName, sheetName, wlOut)
    if isempty(sheetName)
        M = readmatrix(fileName);
    else
        M = readmatrix(fileName, 'Sheet', sheetName);
    end
    wl = M(:,1);
    if size(M, 2) >= 3
        s = M(:,3);
    else
        s = M(:,2);
    end
    ok = isfinite(wl) & isfinite(s);
    wl = wl(ok);
    s = s(ok);
    [wl, order] = sort(wl);
    s = s(order);
    spd = interp1(wl, s, wlOut, 'linear', 0);
    spd = spd(:);
    spd(spd < 0) = 0;
end

function XYZ = xyY_to_XYZ(xyY)
    x = xyY(1);
    y = xyY(2);
    Y = xyY(3);
    X = x / y * Y;
    Z = (1 - x - y) / y * Y;
    XYZ = [X, Y, Z];
end

function spdScaled = scale_to_photopic_Y(spd, targetYlm, std, ~, dLambda)
    Ylm = 683 * sum(spd(:) .* std.cmf(:,2)) * dLambda;
    if Ylm <= 0
        error('The spectrum photopic Y is 0 and cannot be normalized.');
    end
    spdScaled = spd(:) .* (targetYlm / Ylm);
end

function m = spectrum_metrics(spd, std, wl, dLambda)
    XYZ = source_XYZ(spd, std.cmf, dLambda);
    xyY = XYZ_to_xyY(XYZ);
    photopicY = 683 * XYZ(2);
    uv = XYZ_to_uv1960(XYZ);
    [CCT, Duv] = estimate_cct_uv(uv, std.cmf, wl, dLambda);
    refSpd = reference_spd(CCT, std, wl);
    Ri = cri_R1_R8(spd, refSpd, std.cmf, std.tcs, dLambda);
    [Rmin8, worstIndex] = min(Ri);
    m.XYZ = XYZ;
    m.xyY = [xyY(1), xyY(2), photopicY];
    m.photopicY = photopicY;
    m.uv1960 = uv;
    m.CCT = CCT;
    m.Duv = Duv;
    m.Ri = Ri;
    m.Ra = mean(Ri);
    m.Rmin8 = Rmin8;
    m.WorstIndex = worstIndex;
end

function XYZ = source_XYZ(spd, cmf, dLambda)
    XYZ = sum(spd(:) .* cmf, 1) .* dLambda;
end

function xyY = XYZ_to_xyY(XYZ)
    s = sum(XYZ);
    if s <= 0
        xyY = [NaN, NaN, NaN];
    else
        xyY = [XYZ(1) / s, XYZ(2) / s, XYZ(2)];
    end
end

function uv = XYZ_to_uv1960(XYZ)
    den = XYZ(1) + 15 * XYZ(2) + 3 * XYZ(3);
    uv = [4 * XYZ(1) / den, 6 * XYZ(2) / den];
end

function uv = xy_to_uv1976(xy)
    x = xy(1);
    y = xy(2);
    den = -2 * x + 12 * y + 3;
    uv = [4 * x / den, 9 * y / den];
end

function xy = uv1976_to_xy(uv)
    u = uv(1);
    v = uv(2);
    den = 6 * u - 16 * v + 12;
    xy = [9 * u / den, 4 * v / den];
end

function [CCT, Duv] = estimate_cct_uv(uv, cmf, wl, dLambda)
    gridT = linspace(1000, 25000, 481);
    dist2 = zeros(size(gridT));
    for i = 1:numel(gridT)
        bb = blackbody_spd(gridT(i), wl);
        bbXYZ = source_XYZ(bb, cmf, dLambda);
        bbuv = XYZ_to_uv1960(bbXYZ);
        dist2(i) = sum((uv - bbuv).^2);
    end
    [~, idx] = min(dist2);
    lo = max(1000, gridT(max(1, idx - 2)));
    hi = min(25000, gridT(min(numel(gridT), idx + 2)));
    CCT = fminbnd(@(T) blackbody_uv_distance2(T, uv, cmf, wl, dLambda), lo, hi);
    Duv = sqrt(blackbody_uv_distance2(CCT, uv, cmf, wl, dLambda));
end

function d2 = blackbody_uv_distance2(T, uv, cmf, wl, dLambda)
    bb = blackbody_spd(T, wl);
    bbXYZ = source_XYZ(bb, cmf, dLambda);
    bbuv = XYZ_to_uv1960(bbXYZ);
    d2 = sum((uv - bbuv).^2);
end

function spd = blackbody_spd(T, wl)
    c2 = 1.438776877e-2;
    lambda = wl(:) * 1e-9;
    spd = 1 ./ (lambda .^ 5 .* (exp(c2 ./ (lambda .* T)) - 1));
    spd = spd ./ max(spd);
end

function spd = reference_spd(CCT, std, wl)
    if CCT < 5000
        spd = blackbody_spd(CCT, wl);
        return;
    end
    T = min(max(CCT, 4000), 25000);
    if T <= 7000
        xD = 0.244063 + 0.09911e3 / T + 2.9678e6 / T^2 - 4.6070e9 / T^3;
    else
        xD = 0.237040 + 0.24748e3 / T + 1.9018e6 / T^2 - 2.0064e9 / T^3;
    end
    yD = -3.000 * xD^2 + 2.870 * xD - 0.275;
    den = 0.0241 + 0.2562 * xD - 0.7341 * yD;
    M1 = (-1.3515 - 1.7703 * xD + 5.9114 * yD) / den;
    M2 = (0.0300 - 31.4424 * xD + 30.0717 * yD) / den;
    spd = std.daylightComponents(:,1) + M1 .* std.daylightComponents(:,2) + M2 .* std.daylightComponents(:,3);
    spd = max(spd, 0);
end

function Ri = cri_R1_R8(testSpd, refSpd, cmf, tcs, dLambda)
    testXYZ = source_XYZ(testSpd, cmf, dLambda);
    refXYZ = source_XYZ(refSpd, cmf, dLambda);
    testUV = XYZ_to_uv1960(testXYZ);
    refUV = XYZ_to_uv1960(refXYZ);

    testUVW = tcs_uvw(testSpd, cmf, tcs, dLambda, testUV, refUV, true);
    refUVW = tcs_uvw(refSpd, cmf, tcs, dLambda, refUV, refUV, false);

    Ri = zeros(8, 1);
    for i = 1:8
        deltaE = norm(refUVW(i,:) - testUVW(i,:));
        Ri(i) = 100 - 4.6 * deltaE;
    end
end

function UVW = tcs_uvw(sourceSpd, cmf, tcs, dLambda, sourceUV, refUV, doAdapt)
    sourceY = sum(sourceSpd(:) .* cmf(:,2)) * dLambda;
    k = 100 / sourceY;
    UVW = zeros(size(tcs, 2), 3);

    cfun = @(u, v) (4 - u - 10 * v) / v;
    dfun = @(u, v) (1.708 * v + 0.404 - 1.481 * u) / v;
    sourceC = cfun(sourceUV(1), sourceUV(2));
    sourceD = dfun(sourceUV(1), sourceUV(2));
    refC = cfun(refUV(1), refUV(2));
    refD = dfun(refUV(1), refUV(2));

    for i = 1:size(tcs, 2)
        sampleXYZ = k .* sum(sourceSpd(:) .* tcs(:,i) .* cmf, 1) .* dLambda;
        sampleXY = XYZ_to_xyY(sampleXYZ);
        sampleUV = XYZ_to_uv1960(sampleXYZ);
        u = sampleUV(1);
        v = sampleUV(2);
        if doAdapt
            sampleC = cfun(u, v);
            sampleD = dfun(u, v);
            denominator = 16.518 + 1.481 * refC / sourceC * sampleC - refD / sourceD * sampleD;
            u = (10.872 + 0.404 * refC / sourceC * sampleC - 4 * refD / sourceD * sampleD) / denominator;
            v = 5.520 / denominator;
        end
        W = 25 * sampleXY(3)^(1/3) - 17;
        U = 13 * W * (u - refUV(1));
        V = 13 * W * (v - refUV(2));
        UVW(i,:) = [U, V, W];
    end
end
