/******************************************************************************
*                                                                             *
*                _  _               ___             _                         *
*               (_)| |__   _ __    / _ \ _ __ ___  | |__    /\  /\            *
*               | || '_ \ | '__|  / /_\/| '_ ` _ \ | '_ \  / /_/ /            *
*               | || | | || |    / /_\\ | | | | | || |_) |/ __  /             *
*               |_||_| |_||_|    \____/ |_| |_| |_||_.__/ \/ /_/              *
*                                                                             *
*  ihr GmbH                                                                   *
*  Airport Boulevard B210                                                     *
*  77836 Rheinmuenster - Germany                                              *
*  http://www.ihr.de                                                          *
*  Phone +49(0) 7229-18475-0                                                  *
*  Fax   +49(0) 7229-18475-11                                                 *
*                                                                             *
******************************************************************************/
/* Generated by LDCTool 2.3.3.0      Date: 2024/4/22 */
/* Generated from LDF: d:\ihr_allen\allen\stack_support\keboda_tld4020\≈‰÷√Œƒº˛\keboda_newldf\mqb2020.mqb_w_bcm_lin5_kmatrix_v9.07f_20190529_tr.ldf */
 
#include "genLinConfig.h"
volatile t_l_flags_RGBe_Slave_a l_flags_RGBe_Slave_a;
volatile t_l_flags_RGBs_Slave_08a l_flags_RGBs_Slave_08a;

/* Dynamic access functions for frames */
/* Please use this function with great care as it is not prevented to overwrite received data! */
l_bool l_bytes_rd_Frame (l_u8 FrameIdx, l_u8 Start, l_u8 Count, l_u8 Destination[])
{
   l_bool retValue = 0u;
   if (FrameIdx < LIN_NUMBER_OF_FRAMES)
   {
      l_get_byte_array(&l_LinData.Frame[FrameIdx].frame_data[Start], Count, Destination);
      retValue = 1u;
   }
   return retValue;
}
/* Please use this function with great care as it is not prevented to read out frames prepared for transmission! */
l_bool l_bytes_wr_Frame (l_u8 FrameIdx, l_u8 Start, l_u8 Count, l_u8 Destination[])
{
   l_bool retValue = 0u;
   if (FrameIdx < LIN_NUMBER_OF_FRAMES)
   {
      l_set_byte_array(&l_LinData.Frame[FrameIdx].frame_data[Start], Count, Destination);
      retValue = 1u;
   }
   return retValue;
}

void l_Update_Frame_Flags(l_u8 number)
{
  switch(number)
  {
    case(0u):
      l_Update_flags_frame0();
      break;
    case(1u):
      l_Update_flags_frame1();
      break;
    default:
      /* No action */ 
      break;
  }
}

/* define generated LIN data variables with init value */

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)8,(l_u8)64,(l_u8)8,(l_u8)129,(l_u8)8}}\
};

unsigned char SlaveNodeNAD;
/* define generated lin data variables with init value */

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT01 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)1,(l_u8)64,(l_u8)193,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT02 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)2,(l_u8)64,(l_u8)66,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT03 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)3,(l_u8)64,(l_u8)3,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT04 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)4,(l_u8)64,(l_u8)196,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT05 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)5,(l_u8)64,(l_u8)133,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT06 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)6,(l_u8)64,(l_u8)6,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT07 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)7,(l_u8)64,(l_u8)71,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT08 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)8,(l_u8)64,(l_u8)8,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT09 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)9,(l_u8)64,(l_u8)73,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT10 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)10,(l_u8)64,(l_u8)202,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT11 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)11,(l_u8)64,(l_u8)139,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT12 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)12,(l_u8)64,(l_u8)76,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT13 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)13,(l_u8)64,(l_u8)13,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT14 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)14,(l_u8)64,(l_u8)142,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT15 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)15,(l_u8)64,(l_u8)207,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT16 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)16,(l_u8)64,(l_u8)80,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT17 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)17,(l_u8)64,(l_u8)17,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT18 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)18,(l_u8)64,(l_u8)146,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT19 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)19,(l_u8)64,(l_u8)211,(l_u8)129,(l_u8)8}}\
};

const t_Lin_Frame_Ctrl const_LIN_FRAME_CTRL_INIT20 [LIN_NUMBER_OF_FRAMES] = {
  {{(l_u8)21,(l_u8)64,(l_u8)85,(l_u8)128,(l_u8)8}},\
  {{(l_u8)20,(l_u8)64,(l_u8)20,(l_u8)129,(l_u8)8}}\
};


t_l_Lin_Data l_LinData = {{
  (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)126u, (l_u8)16u, (l_u8)248u,\
  (l_u8)127u, (l_u8)0u, (l_u8)128u, (l_u8)192u, (l_u8)255u, (l_u8)255u, (l_u8)255u, (l_u8)255u
}};

const t_l_Lin_Data const_LinData = {{
  (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)0u, (l_u8)126u, (l_u8)16u, (l_u8)248u,\
  (l_u8)127u, (l_u8)0u, (l_u8)128u, (l_u8)192u, (l_u8)255u, (l_u8)255u, (l_u8)255u, (l_u8)255u
}};


/* File Footer */
/* genLinConfig.c file for ARISU-SRM */
