/*********************************************************************************
 * FileName:    AlgoRatioK.c
 * Description: Auto-generated by test/s06_export_ratioK_packed32.m
 *              32-bit packed K-point white-ratio lookup module.
 *
 * Packed LUT:
 *   bit[ 0: 9] = U,      10 bit, u' * 1000
 *   bit[10:19] = V,      10 bit, v' * 1000
 *   bit[20:31] = ratio,  12 bit, whiteRatio * 4095
 **********************************************************************************/

#include "AlgoRatioK.h"

#define ALGO_RATIO_K_LUT_COUNT           (325u)

#define ALGO_RATIO_K_U_MASK              (0x000003FFu)
#define ALGO_RATIO_K_V_MASK              (0x000FFC00u)
#define ALGO_RATIO_K_RATIO_MASK          (0xFFF00000u)

#define ALGO_RATIO_K_V_SHIFT             (10u)
#define ALGO_RATIO_K_RATIO_SHIFT         (20u)

#define ALGO_RATIO_K_RATIO12_MAX         (4095u)
#define ALGO_RATIO_K_RATIO_Q10000_MAX    (10000u)
#define ALGO_RATIO_K_DISTANCE_MAX        (0xFFFFFFFFu)

#ifndef ALGO_RATIO_K_USE_WEIGHT
#define ALGO_RATIO_K_USE_WEIGHT          (1u)
#endif

#define ALGO_RATIO_K_WEIGHT_SCALE        (32768u)

#if (ALGO_RATIO_K_AMOUNT == 0u)
#error "ALGO_RATIO_K_AMOUNT must be greater than 0."
#endif

#if (ALGO_RATIO_K_AMOUNT > 12u)
#error "ALGO_RATIO_K_AMOUNT > 12 may overflow uint32 weighted sum."
#endif

#define ALGO_RATIO_K_PACK(U_, V_, RATIO12_) \
    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_RATIO_K_RATIO_SHIFT) | \
     (((uint32_t)(V_)       & 0x3FFu) << ALGO_RATIO_K_V_SHIFT) | \
     (((uint32_t)(U_)       & 0x3FFu)))

static const uint32_t g_algoRatioKPackedLut[ALGO_RATIO_K_LUT_COUNT] =
{
    ALGO_RATIO_K_PACK( 201u,   84u,    0u),  /* idx=  0, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 194u,  104u,    0u),  /* idx=  1, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 188u,  124u,    0u),  /* idx=  2, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 182u,  144u,    0u),  /* idx=  3, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 175u,  165u,    0u),  /* idx=  4, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 169u,  185u,    0u),  /* idx=  5, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 163u,  205u,    0u),  /* idx=  6, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 156u,  225u,    0u),  /* idx=  7, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 150u,  245u,    0u),  /* idx=  8, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 144u,  265u,    0u),  /* idx=  9, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 137u,  286u,    0u),  /* idx= 10, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 131u,  306u,    0u),  /* idx= 11, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 125u,  326u,    0u),  /* idx= 12, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 118u,  346u,    0u),  /* idx= 13, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 112u,  366u,    0u),  /* idx= 14, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 106u,  386u,    0u),  /* idx= 15, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  99u,  406u,    0u),  /* idx= 16, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  93u,  427u,    0u),  /* idx= 17, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  87u,  447u,    0u),  /* idx= 18, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  80u,  467u,    0u),  /* idx= 19, ratio=-0.000000 */
    ALGO_RATIO_K_PACK(  74u,  487u,    0u),  /* idx= 20, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  68u,  507u,    0u),  /* idx= 21, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  61u,  527u,    0u),  /* idx= 22, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  55u,  548u,    0u),  /* idx= 23, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  49u,  568u,    0u),  /* idx= 24, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 215u,  102u,    0u),  /* idx= 25, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 209u,  122u,    0u),  /* idx= 26, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 202u,  142u,    0u),  /* idx= 27, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 196u,  163u,    0u),  /* idx= 28, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 190u,  183u,    0u),  /* idx= 29, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 183u,  203u,    0u),  /* idx= 30, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 177u,  223u,    0u),  /* idx= 31, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 171u,  243u,    0u),  /* idx= 32, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 164u,  263u,    0u),  /* idx= 33, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 158u,  283u,    0u),  /* idx= 34, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 152u,  304u,    0u),  /* idx= 35, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 145u,  324u,    0u),  /* idx= 36, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 139u,  344u,    0u),  /* idx= 37, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 133u,  364u,    0u),  /* idx= 38, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 126u,  384u,    0u),  /* idx= 39, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 120u,  404u,    0u),  /* idx= 40, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 114u,  425u,    0u),  /* idx= 41, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 107u,  445u,    0u),  /* idx= 42, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 101u,  465u,    0u),  /* idx= 43, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  95u,  485u,    0u),  /* idx= 44, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  88u,  505u,    0u),  /* idx= 45, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  82u,  525u,    0u),  /* idx= 46, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  76u,  545u,    0u),  /* idx= 47, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  69u,  566u,    0u),  /* idx= 48, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 229u,  120u,    0u),  /* idx= 49, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 223u,  140u, 1006u),  /* idx= 50, ratio=0.245733 */
    ALGO_RATIO_K_PACK( 217u,  160u, 1760u),  /* idx= 51, ratio=0.429741 */
    ALGO_RATIO_K_PACK( 210u,  181u, 1879u),  /* idx= 52, ratio=0.458753 */
    ALGO_RATIO_K_PACK( 204u,  201u, 1660u),  /* idx= 53, ratio=0.405374 */
    ALGO_RATIO_K_PACK( 198u,  221u, 1471u),  /* idx= 54, ratio=0.359106 */
    ALGO_RATIO_K_PACK( 191u,  241u, 1289u),  /* idx= 55, ratio=0.314798 */
    ALGO_RATIO_K_PACK( 185u,  261u, 1111u),  /* idx= 56, ratio=0.271428 */
    ALGO_RATIO_K_PACK( 179u,  281u,  956u),  /* idx= 57, ratio=0.233522 */
    ALGO_RATIO_K_PACK( 172u,  302u,  838u),  /* idx= 58, ratio=0.204661 */
    ALGO_RATIO_K_PACK( 166u,  322u,  757u),  /* idx= 59, ratio=0.184797 */
    ALGO_RATIO_K_PACK( 160u,  342u,  704u),  /* idx= 60, ratio=0.172036 */
    ALGO_RATIO_K_PACK( 153u,  362u,  682u),  /* idx= 61, ratio=0.166636 */
    ALGO_RATIO_K_PACK( 147u,  382u,  636u),  /* idx= 62, ratio=0.155218 */
    ALGO_RATIO_K_PACK( 141u,  402u,  599u),  /* idx= 63, ratio=0.146322 */
    ALGO_RATIO_K_PACK( 134u,  422u,  565u),  /* idx= 64, ratio=0.138087 */
    ALGO_RATIO_K_PACK( 128u,  443u,  473u),  /* idx= 65, ratio=0.115446 */
    ALGO_RATIO_K_PACK( 122u,  463u,  298u),  /* idx= 66, ratio=0.072793 */
    ALGO_RATIO_K_PACK( 115u,  483u,  135u),  /* idx= 67, ratio=0.032946 */
    ALGO_RATIO_K_PACK( 109u,  503u,    0u),  /* idx= 68, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 103u,  523u,    0u),  /* idx= 69, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  96u,  543u,    0u),  /* idx= 70, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  90u,  564u,    0u),  /* idx= 71, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 244u,  138u,    0u),  /* idx= 72, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 237u,  158u,  891u),  /* idx= 73, ratio=0.217689 */
    ALGO_RATIO_K_PACK( 231u,  179u, 1582u),  /* idx= 74, ratio=0.386233 */
    ALGO_RATIO_K_PACK( 225u,  199u, 2132u),  /* idx= 75, ratio=0.520585 */
    ALGO_RATIO_K_PACK( 218u,  219u, 2581u),  /* idx= 76, ratio=0.630193 */
    ALGO_RATIO_K_PACK( 212u,  239u, 2954u),  /* idx= 77, ratio=0.721315 */
    ALGO_RATIO_K_PACK( 206u,  259u, 2913u),  /* idx= 78, ratio=0.711269 */
    ALGO_RATIO_K_PACK( 199u,  279u, 2709u),  /* idx= 79, ratio=0.661462 */
    ALGO_RATIO_K_PACK( 193u,  299u, 2535u),  /* idx= 80, ratio=0.618944 */
    ALGO_RATIO_K_PACK( 187u,  320u, 2367u),  /* idx= 81, ratio=0.578050 */
    ALGO_RATIO_K_PACK( 180u,  340u, 2186u),  /* idx= 82, ratio=0.533872 */
    ALGO_RATIO_K_PACK( 174u,  360u, 2029u),  /* idx= 83, ratio=0.495528 */
    ALGO_RATIO_K_PACK( 168u,  380u, 1920u),  /* idx= 84, ratio=0.468769 */
    ALGO_RATIO_K_PACK( 161u,  400u, 1828u),  /* idx= 85, ratio=0.446452 */
    ALGO_RATIO_K_PACK( 155u,  420u, 1739u),  /* idx= 86, ratio=0.424675 */
    ALGO_RATIO_K_PACK( 149u,  441u, 1534u),  /* idx= 87, ratio=0.374579 */
    ALGO_RATIO_K_PACK( 142u,  461u, 1307u),  /* idx= 88, ratio=0.319218 */
    ALGO_RATIO_K_PACK( 136u,  481u, 1094u),  /* idx= 89, ratio=0.267162 */
    ALGO_RATIO_K_PACK( 130u,  501u,  884u),  /* idx= 90, ratio=0.215864 */
    ALGO_RATIO_K_PACK( 123u,  521u,  652u),  /* idx= 91, ratio=0.159296 */
    ALGO_RATIO_K_PACK( 117u,  541u,  398u),  /* idx= 92, ratio=0.097198 */
    ALGO_RATIO_K_PACK( 111u,  561u,    0u),  /* idx= 93, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 258u,  156u,    0u),  /* idx= 94, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 252u,  176u,  800u),  /* idx= 95, ratio=0.195390 */
    ALGO_RATIO_K_PACK( 245u,  197u, 1436u),  /* idx= 96, ratio=0.350725 */
    ALGO_RATIO_K_PACK( 239u,  217u, 1954u),  /* idx= 97, ratio=0.477175 */
    ALGO_RATIO_K_PACK( 233u,  237u, 2384u),  /* idx= 98, ratio=0.582113 */
    ALGO_RATIO_K_PACK( 226u,  257u, 2746u),  /* idx= 99, ratio=0.670597 */
    ALGO_RATIO_K_PACK( 220u,  277u, 3056u),  /* idx=100, ratio=0.746217 */
    ALGO_RATIO_K_PACK( 214u,  297u, 3323u),  /* idx=101, ratio=0.811587 */
    ALGO_RATIO_K_PACK( 207u,  318u, 3557u),  /* idx=102, ratio=0.868659 */
    ALGO_RATIO_K_PACK( 201u,  338u, 3518u),  /* idx=103, ratio=0.859168 */
    ALGO_RATIO_K_PACK( 195u,  358u, 3334u),  /* idx=104, ratio=0.814166 */
    ALGO_RATIO_K_PACK( 189u,  378u, 3178u),  /* idx=105, ratio=0.775999 */
    ALGO_RATIO_K_PACK( 182u,  398u, 3037u),  /* idx=106, ratio=0.741747 */
    ALGO_RATIO_K_PACK( 176u,  418u, 2828u),  /* idx=107, ratio=0.690571 */
    ALGO_RATIO_K_PACK( 170u,  438u, 2557u),  /* idx=108, ratio=0.624362 */
    ALGO_RATIO_K_PACK( 163u,  459u, 2285u),  /* idx=109, ratio=0.557968 */
    ALGO_RATIO_K_PACK( 157u,  479u, 2022u),  /* idx=110, ratio=0.493859 */
    ALGO_RATIO_K_PACK( 151u,  499u, 1768u),  /* idx=111, ratio=0.431667 */
    ALGO_RATIO_K_PACK( 144u,  519u, 1495u),  /* idx=112, ratio=0.365034 */
    ALGO_RATIO_K_PACK( 138u,  539u, 1013u),  /* idx=113, ratio=0.247486 */
    ALGO_RATIO_K_PACK( 132u,  559u,    0u),  /* idx=114, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 273u,  174u,    0u),  /* idx=115, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 266u,  195u,  726u),  /* idx=116, ratio=0.177235 */
    ALGO_RATIO_K_PACK( 260u,  215u, 1315u),  /* idx=117, ratio=0.321196 */
    ALGO_RATIO_K_PACK( 254u,  235u, 1804u),  /* idx=118, ratio=0.440447 */
    ALGO_RATIO_K_PACK( 247u,  255u, 2215u),  /* idx=119, ratio=0.540849 */
    ALGO_RATIO_K_PACK( 241u,  275u, 2566u),  /* idx=120, ratio=0.626543 */
    ALGO_RATIO_K_PACK( 235u,  295u, 2869u),  /* idx=121, ratio=0.700541 */
    ALGO_RATIO_K_PACK( 228u,  315u, 3133u),  /* idx=122, ratio=0.765083 */
    ALGO_RATIO_K_PACK( 222u,  336u, 3366u),  /* idx=123, ratio=0.821874 */
    ALGO_RATIO_K_PACK( 216u,  356u, 3572u),  /* idx=124, ratio=0.872231 */
    ALGO_RATIO_K_PACK( 209u,  376u, 3756u),  /* idx=125, ratio=0.917188 */
    ALGO_RATIO_K_PACK( 203u,  396u, 3876u),  /* idx=126, ratio=0.946613 */
    ALGO_RATIO_K_PACK( 197u,  416u, 3689u),  /* idx=127, ratio=0.900778 */
    ALGO_RATIO_K_PACK( 190u,  436u, 3518u),  /* idx=128, ratio=0.859177 */
    ALGO_RATIO_K_PACK( 184u,  457u, 3191u),  /* idx=129, ratio=0.779360 */
    ALGO_RATIO_K_PACK( 178u,  477u, 2893u),  /* idx=130, ratio=0.706443 */
    ALGO_RATIO_K_PACK( 171u,  497u, 2600u),  /* idx=131, ratio=0.635004 */
    ALGO_RATIO_K_PACK( 165u,  517u, 2114u),  /* idx=132, ratio=0.516256 */
    ALGO_RATIO_K_PACK( 159u,  537u, 1017u),  /* idx=133, ratio=0.248443 */
    ALGO_RATIO_K_PACK( 152u,  557u,    0u),  /* idx=134, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 287u,  192u,    0u),  /* idx=135, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 281u,  213u,  664u),  /* idx=136, ratio=0.162167 */
    ALGO_RATIO_K_PACK( 274u,  233u, 1213u),  /* idx=137, ratio=0.296253 */
    ALGO_RATIO_K_PACK( 268u,  253u, 1675u),  /* idx=138, ratio=0.408969 */
    ALGO_RATIO_K_PACK( 262u,  273u, 2068u),  /* idx=139, ratio=0.505049 */
    ALGO_RATIO_K_PACK( 255u,  293u, 2408u),  /* idx=140, ratio=0.587921 */
    ALGO_RATIO_K_PACK( 249u,  313u, 2703u),  /* idx=141, ratio=0.660134 */
    ALGO_RATIO_K_PACK( 243u,  334u, 2963u),  /* idx=142, ratio=0.723620 */
    ALGO_RATIO_K_PACK( 236u,  354u, 3194u),  /* idx=143, ratio=0.779871 */
    ALGO_RATIO_K_PACK( 230u,  374u, 3399u),  /* idx=144, ratio=0.830057 */
    ALGO_RATIO_K_PACK( 224u,  394u, 3584u),  /* idx=145, ratio=0.875109 */
    ALGO_RATIO_K_PACK( 217u,  414u, 3750u),  /* idx=146, ratio=0.915777 */
    ALGO_RATIO_K_PACK( 211u,  434u, 3901u),  /* idx=147, ratio=0.952670 */
    ALGO_RATIO_K_PACK( 205u,  454u, 4035u),  /* idx=148, ratio=0.985337 */
    ALGO_RATIO_K_PACK( 198u,  475u, 3641u),  /* idx=149, ratio=0.889182 */
    ALGO_RATIO_K_PACK( 192u,  495u, 3314u),  /* idx=150, ratio=0.809179 */
    ALGO_RATIO_K_PACK( 186u,  515u, 2123u),  /* idx=151, ratio=0.518339 */
    ALGO_RATIO_K_PACK( 179u,  535u, 1021u),  /* idx=152, ratio=0.249408 */
    ALGO_RATIO_K_PACK( 173u,  555u,    0u),  /* idx=153, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 301u,  211u,    0u),  /* idx=154, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 295u,  231u,  612u),  /* idx=155, ratio=0.149461 */
    ALGO_RATIO_K_PACK( 289u,  251u, 1126u),  /* idx=156, ratio=0.274905 */
    ALGO_RATIO_K_PACK( 282u,  271u, 1563u),  /* idx=157, ratio=0.381691 */
    ALGO_RATIO_K_PACK( 276u,  291u, 1940u),  /* idx=158, ratio=0.473693 */
    ALGO_RATIO_K_PACK( 270u,  311u, 2268u),  /* idx=159, ratio=0.553783 */
    ALGO_RATIO_K_PACK( 263u,  331u, 2556u),  /* idx=160, ratio=0.624134 */
    ALGO_RATIO_K_PACK( 257u,  352u, 2811u),  /* idx=161, ratio=0.686420 */
    ALGO_RATIO_K_PACK( 251u,  372u, 3038u),  /* idx=162, ratio=0.741952 */
    ALGO_RATIO_K_PACK( 244u,  392u, 3242u),  /* idx=163, ratio=0.791774 */
    ALGO_RATIO_K_PACK( 238u,  412u, 3426u),  /* idx=164, ratio=0.836722 */
    ALGO_RATIO_K_PACK( 232u,  432u, 3593u),  /* idx=165, ratio=0.877478 */
    ALGO_RATIO_K_PACK( 225u,  452u, 3745u),  /* idx=166, ratio=0.914604 */
    ALGO_RATIO_K_PACK( 219u,  473u, 3884u),  /* idx=167, ratio=0.948562 */
    ALGO_RATIO_K_PACK( 213u,  493u, 3328u),  /* idx=168, ratio=0.812592 */
    ALGO_RATIO_K_PACK( 206u,  513u, 2131u),  /* idx=169, ratio=0.520439 */
    ALGO_RATIO_K_PACK( 200u,  533u, 1025u),  /* idx=170, ratio=0.250380 */
    ALGO_RATIO_K_PACK( 194u,  553u,    0u),  /* idx=171, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 316u,  229u,    0u),  /* idx=172, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 309u,  249u,  568u),  /* idx=173, ratio=0.138600 */
    ALGO_RATIO_K_PACK( 303u,  269u, 1050u),  /* idx=174, ratio=0.256427 */
    ALGO_RATIO_K_PACK( 297u,  289u, 1465u),  /* idx=175, ratio=0.357823 */
    ALGO_RATIO_K_PACK( 290u,  309u, 1826u),  /* idx=176, ratio=0.446003 */
    ALGO_RATIO_K_PACK( 284u,  329u, 2143u),  /* idx=177, ratio=0.523392 */
    ALGO_RATIO_K_PACK( 278u,  350u, 2424u),  /* idx=178, ratio=0.591857 */
    ALGO_RATIO_K_PACK( 271u,  370u, 2673u),  /* idx=179, ratio=0.652857 */
    ALGO_RATIO_K_PACK( 265u,  390u, 2897u),  /* idx=180, ratio=0.707550 */
    ALGO_RATIO_K_PACK( 259u,  410u, 3099u),  /* idx=181, ratio=0.756866 */
    ALGO_RATIO_K_PACK( 252u,  430u, 3282u),  /* idx=182, ratio=0.801561 */
    ALGO_RATIO_K_PACK( 246u,  450u, 3449u),  /* idx=183, ratio=0.842255 */
    ALGO_RATIO_K_PACK( 240u,  470u, 3601u),  /* idx=184, ratio=0.879463 */
    ALGO_RATIO_K_PACK( 233u,  491u, 3342u),  /* idx=185, ratio=0.816033 */
    ALGO_RATIO_K_PACK( 227u,  511u, 2140u),  /* idx=186, ratio=0.522556 */
    ALGO_RATIO_K_PACK( 221u,  531u, 1029u),  /* idx=187, ratio=0.251360 */
    ALGO_RATIO_K_PACK( 214u,  551u,    0u),  /* idx=188, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 330u,  247u,    0u),  /* idx=189, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 324u,  267u,  529u),  /* idx=190, ratio=0.129212 */
    ALGO_RATIO_K_PACK( 317u,  287u,  984u),  /* idx=191, ratio=0.240276 */
    ALGO_RATIO_K_PACK( 311u,  307u, 1379u),  /* idx=192, ratio=0.336765 */
    ALGO_RATIO_K_PACK( 305u,  327u, 1726u),  /* idx=193, ratio=0.421372 */
    ALGO_RATIO_K_PACK( 298u,  347u, 2032u),  /* idx=194, ratio=0.496164 */
    ALGO_RATIO_K_PACK( 292u,  368u, 2304u),  /* idx=195, ratio=0.562755 */
    ALGO_RATIO_K_PACK( 286u,  388u, 2549u),  /* idx=196, ratio=0.622424 */
    ALGO_RATIO_K_PACK( 279u,  408u, 2769u),  /* idx=197, ratio=0.676197 */
    ALGO_RATIO_K_PACK( 273u,  428u, 2968u),  /* idx=198, ratio=0.724906 */
    ALGO_RATIO_K_PACK( 267u,  448u, 3150u),  /* idx=199, ratio=0.769236 */
    ALGO_RATIO_K_PACK( 260u,  468u, 3316u),  /* idx=200, ratio=0.809750 */
    ALGO_RATIO_K_PACK( 254u,  489u, 3356u),  /* idx=201, ratio=0.819504 */
    ALGO_RATIO_K_PACK( 248u,  509u, 2149u),  /* idx=202, ratio=0.524690 */
    ALGO_RATIO_K_PACK( 241u,  529u, 1033u),  /* idx=203, ratio=0.252347 */
    ALGO_RATIO_K_PACK( 235u,  549u,    0u),  /* idx=204, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 344u,  265u,    0u),  /* idx=205, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 338u,  285u,  496u),  /* idx=206, ratio=0.121014 */
    ALGO_RATIO_K_PACK( 332u,  305u,  926u),  /* idx=207, ratio=0.226039 */
    ALGO_RATIO_K_PACK( 325u,  325u, 1302u),  /* idx=208, ratio=0.318048 */
    ALGO_RATIO_K_PACK( 319u,  345u, 1635u),  /* idx=209, ratio=0.399319 */
    ALGO_RATIO_K_PACK( 313u,  366u, 1931u),  /* idx=210, ratio=0.471628 */
    ALGO_RATIO_K_PACK( 306u,  386u, 2196u),  /* idx=211, ratio=0.536380 */
    ALGO_RATIO_K_PACK( 300u,  406u, 2435u),  /* idx=212, ratio=0.594701 */
    ALGO_RATIO_K_PACK( 294u,  426u, 2652u),  /* idx=213, ratio=0.647504 */
    ALGO_RATIO_K_PACK( 287u,  446u, 2848u),  /* idx=214, ratio=0.695537 */
    ALGO_RATIO_K_PACK( 281u,  466u, 3028u),  /* idx=215, ratio=0.739417 */
    ALGO_RATIO_K_PACK( 275u,  486u, 3193u),  /* idx=216, ratio=0.779661 */
    ALGO_RATIO_K_PACK( 268u,  507u, 2157u),  /* idx=217, ratio=0.526842 */
    ALGO_RATIO_K_PACK( 262u,  527u, 1037u),  /* idx=218, ratio=0.253343 */
    ALGO_RATIO_K_PACK( 256u,  547u,    0u),  /* idx=219, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 359u,  283u,    0u),  /* idx=220, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 353u,  303u,  466u),  /* idx=221, ratio=0.113795 */
    ALGO_RATIO_K_PACK( 346u,  323u,  874u),  /* idx=222, ratio=0.213395 */
    ALGO_RATIO_K_PACK( 340u,  343u, 1234u),  /* idx=223, ratio=0.301302 */
    ALGO_RATIO_K_PACK( 334u,  363u, 1554u),  /* idx=224, ratio=0.379459 */
    ALGO_RATIO_K_PACK( 327u,  384u, 1840u),  /* idx=225, ratio=0.449405 */
    ALGO_RATIO_K_PACK( 321u,  404u, 2098u),  /* idx=226, ratio=0.512367 */
    ALGO_RATIO_K_PACK( 315u,  424u, 2331u),  /* idx=227, ratio=0.569343 */
    ALGO_RATIO_K_PACK( 308u,  444u, 2544u),  /* idx=228, ratio=0.621148 */
    ALGO_RATIO_K_PACK( 302u,  464u, 2737u),  /* idx=229, ratio=0.668454 */
    ALGO_RATIO_K_PACK( 296u,  484u, 2915u),  /* idx=230, ratio=0.711824 */
    ALGO_RATIO_K_PACK( 289u,  505u, 2166u),  /* idx=231, ratio=0.529012 */
    ALGO_RATIO_K_PACK( 283u,  525u, 1042u),  /* idx=232, ratio=0.254346 */
    ALGO_RATIO_K_PACK( 277u,  545u,    0u),  /* idx=233, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 373u,  301u,    0u),  /* idx=234, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 367u,  321u,  440u),  /* idx=235, ratio=0.107388 */
    ALGO_RATIO_K_PACK( 361u,  341u,  828u),  /* idx=236, ratio=0.202091 */
    ALGO_RATIO_K_PACK( 354u,  361u, 1172u),  /* idx=237, ratio=0.286231 */
    ALGO_RATIO_K_PACK( 348u,  382u, 1480u),  /* idx=238, ratio=0.361482 */
    ALGO_RATIO_K_PACK( 342u,  402u, 1757u),  /* idx=239, ratio=0.429181 */
    ALGO_RATIO_K_PACK( 335u,  422u, 2008u),  /* idx=240, ratio=0.490412 */
    ALGO_RATIO_K_PACK( 329u,  442u, 2236u),  /* idx=241, ratio=0.546059 */
    ALGO_RATIO_K_PACK( 323u,  462u, 2444u),  /* idx=242, ratio=0.596853 */
    ALGO_RATIO_K_PACK( 316u,  482u, 2635u),  /* idx=243, ratio=0.643401 */
    ALGO_RATIO_K_PACK( 310u,  502u, 2175u),  /* idx=244, ratio=0.531200 */
    ALGO_RATIO_K_PACK( 304u,  523u, 1046u),  /* idx=245, ratio=0.255357 */
    ALGO_RATIO_K_PACK( 297u,  543u,    0u),  /* idx=246, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 388u,  319u,    0u),  /* idx=247, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 381u,  339u,  416u),  /* idx=248, ratio=0.101665 */
    ALGO_RATIO_K_PACK( 375u,  359u,  786u),  /* idx=249, ratio=0.191924 */
    ALGO_RATIO_K_PACK( 369u,  379u, 1116u),  /* idx=250, ratio=0.272596 */
    ALGO_RATIO_K_PACK( 362u,  400u, 1413u),  /* idx=251, ratio=0.345130 */
    ALGO_RATIO_K_PACK( 356u,  420u, 1682u),  /* idx=252, ratio=0.410700 */
    ALGO_RATIO_K_PACK( 350u,  440u, 1926u),  /* idx=253, ratio=0.470261 */
    ALGO_RATIO_K_PACK( 343u,  460u, 2148u),  /* idx=254, ratio=0.524605 */
    ALGO_RATIO_K_PACK( 337u,  480u, 2352u),  /* idx=255, ratio=0.574387 */
    ALGO_RATIO_K_PACK( 331u,  500u, 2184u),  /* idx=256, ratio=0.533406 */
    ALGO_RATIO_K_PACK( 324u,  521u, 1050u),  /* idx=257, ratio=0.256377 */
    ALGO_RATIO_K_PACK( 318u,  541u,    0u),  /* idx=258, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 402u,  337u,    0u),  /* idx=259, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 396u,  357u,  395u),  /* idx=260, ratio=0.096520 */
    ALGO_RATIO_K_PACK( 389u,  377u,  748u),  /* idx=261, ratio=0.182731 */
    ALGO_RATIO_K_PACK( 383u,  398u, 1066u),  /* idx=262, ratio=0.260201 */
    ALGO_RATIO_K_PACK( 377u,  418u, 1352u),  /* idx=263, ratio=0.330194 */
    ALGO_RATIO_K_PACK( 370u,  438u, 1612u),  /* idx=264, ratio=0.393744 */
    ALGO_RATIO_K_PACK( 364u,  458u, 1850u),  /* idx=265, ratio=0.451701 */
    ALGO_RATIO_K_PACK( 358u,  478u, 2067u),  /* idx=266, ratio=0.504772 */
    ALGO_RATIO_K_PACK( 351u,  498u, 2193u),  /* idx=267, ratio=0.535630 */
    ALGO_RATIO_K_PACK( 345u,  518u, 1054u),  /* idx=268, ratio=0.257404 */
    ALGO_RATIO_K_PACK( 339u,  539u,    0u),  /* idx=269, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 416u,  355u,    0u),  /* idx=270, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 410u,  375u,  376u),  /* idx=271, ratio=0.091871 */
    ALGO_RATIO_K_PACK( 404u,  395u,  714u),  /* idx=272, ratio=0.174379 */
    ALGO_RATIO_K_PACK( 397u,  416u, 1019u),  /* idx=273, ratio=0.248884 */
    ALGO_RATIO_K_PACK( 391u,  436u, 1296u),  /* idx=274, ratio=0.316497 */
    ALGO_RATIO_K_PACK( 385u,  456u, 1548u),  /* idx=275, ratio=0.378133 */
    ALGO_RATIO_K_PACK( 378u,  476u, 1779u),  /* idx=276, ratio=0.434550 */
    ALGO_RATIO_K_PACK( 372u,  496u, 1992u),  /* idx=277, ratio=0.486385 */
    ALGO_RATIO_K_PACK( 366u,  516u, 1058u),  /* idx=278, ratio=0.258440 */
    ALGO_RATIO_K_PACK( 359u,  537u,    0u),  /* idx=279, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 431u,  373u,    0u),  /* idx=280, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 424u,  393u,  359u),  /* idx=281, ratio=0.087650 */
    ALGO_RATIO_K_PACK( 418u,  414u,  683u),  /* idx=282, ratio=0.166756 */
    ALGO_RATIO_K_PACK( 412u,  434u,  977u),  /* idx=283, ratio=0.238510 */
    ALGO_RATIO_K_PACK( 405u,  454u, 1244u),  /* idx=284, ratio=0.303891 */
    ALGO_RATIO_K_PACK( 399u,  474u, 1489u),  /* idx=285, ratio=0.363713 */
    ALGO_RATIO_K_PACK( 393u,  494u, 1714u),  /* idx=286, ratio=0.418654 */
    ALGO_RATIO_K_PACK( 386u,  514u, 1063u),  /* idx=287, ratio=0.259484 */
    ALGO_RATIO_K_PACK( 380u,  534u,    0u),  /* idx=288, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 445u,  391u,    0u),  /* idx=289, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 439u,  411u,  343u),  /* idx=290, ratio=0.083799 */
    ALGO_RATIO_K_PACK( 432u,  432u,  654u),  /* idx=291, ratio=0.159772 */
    ALGO_RATIO_K_PACK( 426u,  452u,  938u),  /* idx=292, ratio=0.228967 */
    ALGO_RATIO_K_PACK( 420u,  472u, 1197u),  /* idx=293, ratio=0.292251 */
    ALGO_RATIO_K_PACK( 414u,  492u, 1435u),  /* idx=294, ratio=0.350352 */
    ALGO_RATIO_K_PACK( 407u,  512u, 1067u),  /* idx=295, ratio=0.260537 */
    ALGO_RATIO_K_PACK( 401u,  532u,    0u),  /* idx=296, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 460u,  409u,    0u),  /* idx=297, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 453u,  430u,  329u),  /* idx=298, ratio=0.080273 */
    ALGO_RATIO_K_PACK( 447u,  450u,  628u),  /* idx=299, ratio=0.153350 */
    ALGO_RATIO_K_PACK( 441u,  470u,  902u),  /* idx=300, ratio=0.220158 */
    ALGO_RATIO_K_PACK( 434u,  490u, 1153u),  /* idx=301, ratio=0.281470 */
    ALGO_RATIO_K_PACK( 428u,  510u, 1071u),  /* idx=302, ratio=0.261598 */
    ALGO_RATIO_K_PACK( 422u,  530u,    0u),  /* idx=303, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 474u,  427u,    0u),  /* idx=304, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 468u,  448u,  315u),  /* idx=305, ratio=0.077031 */
    ALGO_RATIO_K_PACK( 461u,  468u,  604u),  /* idx=306, ratio=0.147424 */
    ALGO_RATIO_K_PACK( 455u,  488u,  868u),  /* idx=307, ratio=0.212002 */
    ALGO_RATIO_K_PACK( 449u,  508u, 1076u),  /* idx=308, ratio=0.262668 */
    ALGO_RATIO_K_PACK( 442u,  528u,    0u),  /* idx=309, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 488u,  446u,    0u),  /* idx=310, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 482u,  466u,  303u),  /* idx=311, ratio=0.074041 */
    ALGO_RATIO_K_PACK( 476u,  486u,  581u),  /* idx=312, ratio=0.141939 */
    ALGO_RATIO_K_PACK( 469u,  506u,  837u),  /* idx=313, ratio=0.204428 */
    ALGO_RATIO_K_PACK( 463u,  526u,    0u),  /* idx=314, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 503u,  464u,    0u),  /* idx=315, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 496u,  484u,  292u),  /* idx=316, ratio=0.071274 */
    ALGO_RATIO_K_PACK( 490u,  504u,  560u),  /* idx=317, ratio=0.136847 */
    ALGO_RATIO_K_PACK( 484u,  524u,    0u),  /* idx=318, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 517u,  482u,    0u),  /* idx=319, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 511u,  502u,  228u),  /* idx=320, ratio=0.055723 */
    ALGO_RATIO_K_PACK( 504u,  522u,    0u),  /* idx=321, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 531u,  500u,    0u),  /* idx=322, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 525u,  520u,    0u),  /* idx=323, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 546u,  518u,    0u),  /* idx=324, ratio=0.000000 */
};

static uint16_t AlgoRatioK_GetU(uint32_t packedValue)
{
    return (uint16_t)(packedValue & ALGO_RATIO_K_U_MASK);
}

static uint16_t AlgoRatioK_GetV(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_V_MASK) >> ALGO_RATIO_K_V_SHIFT);
}

static uint16_t AlgoRatioK_GetRatio12(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_RATIO_MASK) >> ALGO_RATIO_K_RATIO_SHIFT);
}

static uint16_t AlgoRatioK_ConvertRatio12ToQ10000(uint16_t ratio12)
{
    uint32_t numerator = ((uint32_t)ratio12 * ALGO_RATIO_K_RATIO_Q10000_MAX) + (ALGO_RATIO_K_RATIO12_MAX / 2u);
    uint32_t value = numerator / ALGO_RATIO_K_RATIO12_MAX;
    if (value > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        value = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }
    return (uint16_t)value;
}

static uint32_t AlgoRatioK_CalcDistance2(uint16_t u1,
                                         uint16_t v1,
                                         uint16_t u2,
                                         uint16_t v2)
{
    int32_t du = (int32_t)u1 - (int32_t)u2;
    int32_t dv = (int32_t)v1 - (int32_t)v2;
    return (uint32_t)((du * du) + (dv * dv));
}

static uint16_t AlgoRatioK_DivRoundU32(uint32_t numerator,
                                       uint32_t denominator)
{
    if (denominator == 0u)
    {
        return 0u;
    }
    return (uint16_t)((numerator + (denominator / 2u)) / denominator);
}

uint8_t AlgoRatioK_GetWhiteRatioQ10000(uint16_t targetU,
                                       uint16_t targetV,
                                       uint16_t *whiteRatioQ10000)
{
    uint32_t nearestDistance[ALGO_RATIO_K_AMOUNT];
    uint16_t nearestRatio12[ALGO_RATIO_K_AMOUNT];
    uint16_t lutIndex;
    uint16_t pointU;
    uint16_t pointV;
    uint16_t pointRatio12;
    uint16_t pointRatioQ10000;
    uint32_t packedValue;
    uint32_t distance2;
    uint8_t insertIndex;
    uint8_t shiftIndex;
    uint8_t nearestCount;
    uint8_t i;
#if (ALGO_RATIO_K_USE_WEIGHT != 0u)
    uint32_t weight;
    uint32_t weightSum;
    uint32_t weightedRatioSum;
#else
    uint32_t ratioSum;
#endif
    uint16_t ratioResult;

    if (whiteRatioQ10000 == (void *)0)
    {
        return 0u;
    }

    for (i = 0u; i < ALGO_RATIO_K_AMOUNT; i++)
    {
        nearestDistance[i] = ALGO_RATIO_K_DISTANCE_MAX;
        nearestRatio12[i] = 0u;
    }

    nearestCount = 0u;

    for (lutIndex = 0u; lutIndex < ALGO_RATIO_K_LUT_COUNT; lutIndex++)
    {
        packedValue = g_algoRatioKPackedLut[lutIndex];
        pointU = AlgoRatioK_GetU(packedValue);
        pointV = AlgoRatioK_GetV(packedValue);
        pointRatio12 = AlgoRatioK_GetRatio12(packedValue);
        distance2 = AlgoRatioK_CalcDistance2(targetU, targetV, pointU, pointV);

        if (distance2 == 0u)
        {
            *whiteRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(pointRatio12);
            return 1u;
        }

        for (insertIndex = 0u; insertIndex < ALGO_RATIO_K_AMOUNT; insertIndex++)
        {
            if (distance2 < nearestDistance[insertIndex])
            {
                for (shiftIndex = (uint8_t)(ALGO_RATIO_K_AMOUNT - 1u); shiftIndex > insertIndex; shiftIndex--)
                {
                    nearestDistance[shiftIndex] = nearestDistance[shiftIndex - 1u];
                    nearestRatio12[shiftIndex] = nearestRatio12[shiftIndex - 1u];
                }

                nearestDistance[insertIndex] = distance2;
                nearestRatio12[insertIndex] = pointRatio12;

                if (nearestCount < ALGO_RATIO_K_AMOUNT)
                {
                    nearestCount++;
                }

                break;
            }
        }
    }

    if (nearestCount == 0u)
    {
        return 0u;
    }

#if (ALGO_RATIO_K_USE_WEIGHT != 0u)
    weightSum = 0u;
    weightedRatioSum = 0u;

    for (i = 0u; i < nearestCount; i++)
    {
        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);
        weight = (uint32_t)(ALGO_RATIO_K_WEIGHT_SCALE / (nearestDistance[i] + 1u));
        if (weight == 0u)
        {
            weight = 1u;
        }
        weightedRatioSum += ((uint32_t)pointRatioQ10000 * weight);
        weightSum += weight;
    }

    ratioResult = AlgoRatioK_DivRoundU32(weightedRatioSum, weightSum);
#else
    ratioSum = 0u;

    for (i = 0u; i < nearestCount; i++)
    {
        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);
        ratioSum += (uint32_t)pointRatioQ10000;
    }

    ratioResult = AlgoRatioK_DivRoundU32(ratioSum, nearestCount);
#endif

    if (ratioResult > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        ratioResult = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }

    *whiteRatioQ10000 = ratioResult;
    return 1u;
}
