
#ifndef _ALGORITHM_H_
#define _ALGORITHM_H_

#include "SystemType.h"
/* ���� SysCtrl_t::State */
#define FunState_None					0
#define FunState_Dimming				1
#define FunState_ShowroomColorInit		2
#define FunState_ShowroomOn				3

#define FunState_BreathDown				4
#define FunState_BreathUp				5
#define FunState_BreathOn				6

#define FunState_BlinkDown				7
#define FunState_BlinkUp				8
#define FunState_BlinkOn				9



/** @file
*
* @defgroup RGB_Algorithm RGB Color Algorithm
* @{
*
* @brief This module converts LIN RGB signal to PWM pulse.
*
* @details This module converts LIN RGB signal to target CIE color,
*          than compensate LED parameters referring to temperature.
*          At last it generates PWM pulse.
*/

/**@brief Parameters this module needed to generate PWM.*/
typedef struct ColorParams
{
  uint16_t colorU;
  uint16_t colorV;
  int16_t  ledTemprature; /**<Current LED junction temperature.*/
  uint16_t factor;        /**<Parameter for adjusting intensity.*/
  uint32_t  intensity;    /**<Intensity.*/
  uint32_t  tempAdjust;   /**<Temperature protection intensity adjusting parameter.*/
  bool_t RGBFlag;
}SColorParams;

#if 0
typedef struct
{
    uint16_t u16_ColorU;        /**<Color U'.*/
    uint16_t u16_ColorV;        /**<Color V'.*/
    uint32_t u32_Intensity;    /**<Intensity.*/
    int16_t s16_LEDTemprature; /**<Current LED junction temperature.*/
    int16_t s16_reserved;
}ST_COLOR_PARAMS;
#endif

/**@brief this macro is to enhance the performance of dimming.*/
#define DINTENSITY_ADJUST_SHIFT_LEVEL 6
#define DINTENSITY_ADJUST_SHIFT 40
/**@brief this macro is to enhance the performance of temperature protection dimming.*/
#define DINTENSITY_TEMP_ADJUST_SHIFT_LEVEL 6

/**@brief PWM pulse this module generated.*/
typedef struct PWMParams
{
  uint16_t PWM_R;   /**<PWM Red.*/
  uint16_t PWM_G;   /**<PWM Green.*/
  uint16_t PWM_B;   /**<PWM Blue.*/
  uint16_t PWM_W;   /**<PWM White.*/
}SPWMParams;
typedef struct
{
    int32_t calibration_whitePointU, calibration_whitePointV;
    int32_t target_whitePointU, target_whitePointV;
}CIE1976WhiteBalanceInfo;
typedef union UPWM32
{
	uint64_t num64;
	struct SR
	{
		int64_t Value : 21;
		int64_t reserved2 : 43;
	}R;
	struct SG
	{
		int64_t reserved1 : 21;
		int64_t Value : 21;
		int64_t reserved2 : 22;
	}G;
	struct SB
	{
		int64_t reserved1 : 42;
		int64_t Value : 21;
		uint64_t reserved2 : 1;
	}B;
}PWMs32_t;
/**
*@details   Update red led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  red x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  red y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  red Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateRedCIE(int16_t x, int16_t y, int32_t Y);

/**
*@details   Update green led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  green x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  green y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  green Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateGreenCIE(int16_t x, int16_t y, int32_t Y);

/**
*@details   Update blue led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  blue x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  blue y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  blue Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateBlueCIE(int16_t x, int16_t y, int32_t Y);
void algoUpdateWhiteCIE(int32_t Y);
/**
*@details   The raw R,G,B signals from LIN bus need to be fixed first. This function fix only R, G, B.
*
*@param[in&out] rawColor  The raw LIN signal.
*
*@retval    None.
*/
void algoGetFixedRGB(SColorParams *rawColor);

/**
*@details   Generate PWM pulse.
*
*@param[in] inputColor  Algorithm input parameters.
*
*@param[out] outputPWM  PWM generated by algorithm.
*
*@retval    if this input color can be mixed by our led.
*/
bool_t algoGetPWMOutput(SColorParams * const inputColor, SPWMParams *outputPWM);
void Algorithm_GetMathPWM(SColorParams* outputColor);
/** @} */
bool_t RGBalgoGetPWMOutput(SColorParams * const inputColor, SPWMParams *outputPWM);
void SystemCtrl_GetPWM_Lreal(PWMs32_t* math, PWMs32_t* outputPWM, uint8_t L);
void local_AdjustPWMRange(SColorParams* inputColor,PWMs32_t* PWMAfterCtrl);
void whiteBalanceInit(const CIE1976WhiteBalanceInfo* WB_info);
void WitheBalanceTempInit(void);
extern uint16_t Debug_0100[15];
#endif
