#ifndef APPLICATION_CONFIG_H
#define APPLICATION_CONFIG_H

#define DAPP_CONFIG_WINDOW_WIDTH    1366
#define DAPP_CONFIG_WINDOW_HEIGHT   768

#define DLIN_COMMUNICATION_DEVICE   "/dev/ttySAC3"

#define DSLAVE_NODE_AMOUNT          30//20

#endif // APPLICATION_CONFIG_H
