/*
 * FileName    : ratioK_upper_gui.c
 * Description : K-point ratio method desktop GUI for Windows.
 *
 * Build with MinGW:
 *   gcc ratioK_upper_gui.c -o ratioK_upper_gui.exe -mwindows
 *
 * Required:
 *   Put AlgoRatioK_PackedLut.inc in the same folder.
 *
 * The GUI calculates only the K-point ratio method:
 *   input U/V -> K-point whiteRatio -> RGB mixed point -> RGB/W ratio -> PWM estimation
 *
 * Note:
 *   Ra is not calculated in this C GUI. Ra calculation belongs to MATLAB CRI model.
 *   Default xyY values use OSRAM 90 group.
 */

#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdarg.h>
#include <string.h>

#define APP_TITLE "K Ratio RGBW Test GUI"

#define ALGO_RATIO_K_U_MASK              (0x000003FFu)
#define ALGO_RATIO_K_V_MASK              (0x000FFC00u)
#define ALGO_RATIO_K_RATIO_MASK          (0xFFF00000u)
#define ALGO_RATIO_K_V_SHIFT             (10u)
#define ALGO_RATIO_K_RATIO_SHIFT         (20u)
#define ALGO_RATIO_K_RATIO12_MAX         (4095u)
#define ALGO_RATIO_K_RATIO_Q10000_MAX    (10000u)
#define ALGO_RATIO_K_DISTANCE_MAX        (0xFFFFFFFFu)
#define ALGO_RATIO_K_WEIGHT_SCALE        (32768u)
#define ALGO_RATIO_K_MAX_K               (12u)

#define ALGO_RATIO_K_PACK(U_, V_, RATIO12_) \
    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_RATIO_K_RATIO_SHIFT) | \
     (((uint32_t)(V_)       & 0x3FFu) << ALGO_RATIO_K_V_SHIFT) | \
     (((uint32_t)(U_)       & 0x3FFu)))

static const uint32_t g_algoRatioKPackedLut[] =
{
/* Auto-generated by s06_export_ratioK_packed32.m */
/* Format: ALGO_RATIO_K_PACK(U, V, ratio12) */
/* U/V = round(u'v' * 1000), ratio12 = round(whiteRatio * 4095) */

    ALGO_RATIO_K_PACK( 195u,   92u,    0u),  /* idx=  0, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 189u,  112u,    0u),  /* idx=  1, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 183u,  132u,    0u),  /* idx=  2, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 177u,  152u,    0u),  /* idx=  3, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 172u,  172u,    0u),  /* idx=  4, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 166u,  192u,    0u),  /* idx=  5, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 160u,  212u,    0u),  /* idx=  6, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 154u,  232u,    0u),  /* idx=  7, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 149u,  253u,    0u),  /* idx=  8, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 143u,  273u,    0u),  /* idx=  9, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 137u,  293u,    0u),  /* idx= 10, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 132u,  313u,    0u),  /* idx= 11, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 126u,  333u,    0u),  /* idx= 12, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 120u,  353u,    0u),  /* idx= 13, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 114u,  373u,    0u),  /* idx= 14, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 109u,  393u,    0u),  /* idx= 15, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 103u,  413u,    0u),  /* idx= 16, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  97u,  433u,    0u),  /* idx= 17, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  91u,  453u,    0u),  /* idx= 18, ratio=-0.000000 */
    ALGO_RATIO_K_PACK(  86u,  473u,    0u),  /* idx= 19, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  80u,  493u,    0u),  /* idx= 20, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  74u,  513u,    0u),  /* idx= 21, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  68u,  533u,    0u),  /* idx= 22, ratio=-0.000000 */
    ALGO_RATIO_K_PACK(  63u,  553u,    0u),  /* idx= 23, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  57u,  573u,    0u),  /* idx= 24, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 210u,  110u,    0u),  /* idx= 25, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 204u,  130u,    0u),  /* idx= 26, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 198u,  150u,    0u),  /* idx= 27, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 192u,  170u,    0u),  /* idx= 28, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 187u,  190u,    0u),  /* idx= 29, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 181u,  210u,    0u),  /* idx= 30, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 175u,  230u,    0u),  /* idx= 31, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 169u,  250u,    0u),  /* idx= 32, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 164u,  270u,    0u),  /* idx= 33, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 158u,  290u,    0u),  /* idx= 34, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 152u,  310u,    0u),  /* idx= 35, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 146u,  330u,    0u),  /* idx= 36, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 141u,  350u,    0u),  /* idx= 37, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 135u,  370u,    0u),  /* idx= 38, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 129u,  390u,    0u),  /* idx= 39, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 124u,  410u,    0u),  /* idx= 40, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 118u,  431u,    0u),  /* idx= 41, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 112u,  451u,    0u),  /* idx= 42, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 106u,  471u,    0u),  /* idx= 43, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 101u,  491u,    0u),  /* idx= 44, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  95u,  511u,    0u),  /* idx= 45, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  89u,  531u,    0u),  /* idx= 46, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  83u,  551u,    0u),  /* idx= 47, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  78u,  571u,    0u),  /* idx= 48, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 225u,  128u,    0u),  /* idx= 49, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 219u,  148u,  954u),  /* idx= 50, ratio=0.232850 */
    ALGO_RATIO_K_PACK( 213u,  168u, 1679u),  /* idx= 51, ratio=0.410046 */
    ALGO_RATIO_K_PACK( 207u,  188u, 1686u),  /* idx= 52, ratio=0.411758 */
    ALGO_RATIO_K_PACK( 202u,  208u, 1524u),  /* idx= 53, ratio=0.372265 */
    ALGO_RATIO_K_PACK( 196u,  228u, 1391u),  /* idx= 54, ratio=0.339772 */
    ALGO_RATIO_K_PACK( 190u,  248u, 1266u),  /* idx= 55, ratio=0.309256 */
    ALGO_RATIO_K_PACK( 184u,  268u, 1133u),  /* idx= 56, ratio=0.276744 */
    ALGO_RATIO_K_PACK( 179u,  288u,  995u),  /* idx= 57, ratio=0.243064 */
    ALGO_RATIO_K_PACK( 173u,  308u,  882u),  /* idx= 58, ratio=0.215292 */
    ALGO_RATIO_K_PACK( 167u,  328u,  803u),  /* idx= 59, ratio=0.196032 */
    ALGO_RATIO_K_PACK( 161u,  348u,  761u),  /* idx= 60, ratio=0.185936 */
    ALGO_RATIO_K_PACK( 156u,  368u,  754u),  /* idx= 61, ratio=0.184060 */
    ALGO_RATIO_K_PACK( 150u,  388u,  742u),  /* idx= 62, ratio=0.181275 */
    ALGO_RATIO_K_PACK( 144u,  408u,  731u),  /* idx= 63, ratio=0.178594 */
    ALGO_RATIO_K_PACK( 138u,  428u,  690u),  /* idx= 64, ratio=0.168604 */
    ALGO_RATIO_K_PACK( 133u,  448u,  540u),  /* idx= 65, ratio=0.131884 */
    ALGO_RATIO_K_PACK( 127u,  468u,  370u),  /* idx= 66, ratio=0.090437 */
    ALGO_RATIO_K_PACK( 121u,  488u,  209u),  /* idx= 67, ratio=0.051062 */
    ALGO_RATIO_K_PACK( 116u,  508u,   51u),  /* idx= 68, ratio=0.012433 */
    ALGO_RATIO_K_PACK( 110u,  528u,    0u),  /* idx= 69, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 104u,  548u,    0u),  /* idx= 70, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  98u,  568u,    0u),  /* idx= 71, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 240u,  145u,    0u),  /* idx= 72, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 234u,  165u,  852u),  /* idx= 73, ratio=0.207947 */
    ALGO_RATIO_K_PACK( 228u,  185u, 1519u),  /* idx= 74, ratio=0.370933 */
    ALGO_RATIO_K_PACK( 222u,  205u, 2056u),  /* idx= 75, ratio=0.502118 */
    ALGO_RATIO_K_PACK( 217u,  225u, 2498u),  /* idx= 76, ratio=0.609981 */
    ALGO_RATIO_K_PACK( 211u,  245u, 2867u),  /* idx= 77, ratio=0.700233 */
    ALGO_RATIO_K_PACK( 205u,  265u, 2896u),  /* idx= 78, ratio=0.707183 */
    ALGO_RATIO_K_PACK( 199u,  286u, 2726u),  /* idx= 79, ratio=0.665763 */
    ALGO_RATIO_K_PACK( 194u,  306u, 2583u),  /* idx= 80, ratio=0.630867 */
    ALGO_RATIO_K_PACK( 188u,  326u, 2458u),  /* idx= 81, ratio=0.600294 */
    ALGO_RATIO_K_PACK( 182u,  346u, 2335u),  /* idx= 82, ratio=0.570163 */
    ALGO_RATIO_K_PACK( 176u,  366u, 2166u),  /* idx= 83, ratio=0.528825 */
    ALGO_RATIO_K_PACK( 171u,  386u, 2031u),  /* idx= 84, ratio=0.496068 */
    ALGO_RATIO_K_PACK( 165u,  406u, 1996u),  /* idx= 85, ratio=0.487468 */
    ALGO_RATIO_K_PACK( 159u,  426u, 1882u),  /* idx= 86, ratio=0.459643 */
    ALGO_RATIO_K_PACK( 153u,  446u, 1644u),  /* idx= 87, ratio=0.401463 */
    ALGO_RATIO_K_PACK( 148u,  466u, 1420u),  /* idx= 88, ratio=0.346650 */
    ALGO_RATIO_K_PACK( 142u,  486u, 1207u),  /* idx= 89, ratio=0.294798 */
    ALGO_RATIO_K_PACK( 136u,  506u, 1003u),  /* idx= 90, ratio=0.244860 */
    ALGO_RATIO_K_PACK( 130u,  526u,  781u),  /* idx= 91, ratio=0.190784 */
    ALGO_RATIO_K_PACK( 125u,  546u,  466u),  /* idx= 92, ratio=0.113913 */
    ALGO_RATIO_K_PACK( 119u,  566u,    0u),  /* idx= 93, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 254u,  163u,    0u),  /* idx= 94, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 249u,  183u,  769u),  /* idx= 95, ratio=0.187856 */
    ALGO_RATIO_K_PACK( 243u,  203u, 1387u),  /* idx= 96, ratio=0.338632 */
    ALGO_RATIO_K_PACK( 237u,  223u, 1893u),  /* idx= 97, ratio=0.462321 */
    ALGO_RATIO_K_PACK( 232u,  243u, 2316u),  /* idx= 98, ratio=0.565620 */
    ALGO_RATIO_K_PACK( 226u,  263u, 2675u),  /* idx= 99, ratio=0.653186 */
    ALGO_RATIO_K_PACK( 220u,  283u, 2983u),  /* idx=100, ratio=0.728361 */
    ALGO_RATIO_K_PACK( 214u,  303u, 3250u),  /* idx=101, ratio=0.793600 */
    ALGO_RATIO_K_PACK( 209u,  323u, 3484u),  /* idx=102, ratio=0.850751 */
    ALGO_RATIO_K_PACK( 203u,  343u, 3669u),  /* idx=103, ratio=0.895968 */
    ALGO_RATIO_K_PACK( 197u,  363u, 3490u),  /* idx=104, ratio=0.852206 */
    ALGO_RATIO_K_PACK( 191u,  383u, 3329u),  /* idx=105, ratio=0.813002 */
    ALGO_RATIO_K_PACK( 186u,  403u, 3196u),  /* idx=106, ratio=0.780411 */
    ALGO_RATIO_K_PACK( 180u,  423u, 2972u),  /* idx=107, ratio=0.725823 */
    ALGO_RATIO_K_PACK( 174u,  443u, 2708u),  /* idx=108, ratio=0.661332 */
    ALGO_RATIO_K_PACK( 168u,  464u, 2429u),  /* idx=109, ratio=0.593149 */
    ALGO_RATIO_K_PACK( 163u,  484u, 2164u),  /* idx=110, ratio=0.528405 */
    ALGO_RATIO_K_PACK( 157u,  504u, 1910u),  /* idx=111, ratio=0.466435 */
    ALGO_RATIO_K_PACK( 151u,  524u, 1638u),  /* idx=112, ratio=0.400028 */
    ALGO_RATIO_K_PACK( 145u,  544u,  869u),  /* idx=113, ratio=0.212251 */
    ALGO_RATIO_K_PACK( 140u,  564u,    0u),  /* idx=114, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 269u,  181u,    0u),  /* idx=115, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 264u,  201u,  701u),  /* idx=116, ratio=0.171306 */
    ALGO_RATIO_K_PACK( 258u,  221u, 1276u),  /* idx=117, ratio=0.311506 */
    ALGO_RATIO_K_PACK( 252u,  241u, 1754u),  /* idx=118, ratio=0.428369 */
    ALGO_RATIO_K_PACK( 246u,  261u, 2159u),  /* idx=119, ratio=0.527273 */
    ALGO_RATIO_K_PACK( 241u,  281u, 2506u),  /* idx=120, ratio=0.612063 */
    ALGO_RATIO_K_PACK( 235u,  301u, 2807u),  /* idx=121, ratio=0.685559 */
    ALGO_RATIO_K_PACK( 229u,  321u, 3071u),  /* idx=122, ratio=0.749877 */
    ALGO_RATIO_K_PACK( 224u,  341u, 3303u),  /* idx=123, ratio=0.806634 */
    ALGO_RATIO_K_PACK( 218u,  361u, 3510u),  /* idx=124, ratio=0.857090 */
    ALGO_RATIO_K_PACK( 212u,  381u, 3695u),  /* idx=125, ratio=0.902238 */
    ALGO_RATIO_K_PACK( 206u,  401u, 3861u),  /* idx=126, ratio=0.942876 */
    ALGO_RATIO_K_PACK( 201u,  421u, 3847u),  /* idx=127, ratio=0.939551 */
    ALGO_RATIO_K_PACK( 195u,  441u, 3673u),  /* idx=128, ratio=0.896872 */
    ALGO_RATIO_K_PACK( 189u,  461u, 3345u),  /* idx=129, ratio=0.816853 */
    ALGO_RATIO_K_PACK( 183u,  481u, 3046u),  /* idx=130, ratio=0.743752 */
    ALGO_RATIO_K_PACK( 178u,  501u, 2748u),  /* idx=131, ratio=0.671093 */
    ALGO_RATIO_K_PACK( 172u,  521u, 1813u),  /* idx=132, ratio=0.442739 */
    ALGO_RATIO_K_PACK( 166u,  541u,  873u),  /* idx=133, ratio=0.213175 */
    ALGO_RATIO_K_PACK( 160u,  561u,    0u),  /* idx=134, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 284u,  198u,    0u),  /* idx=135, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 279u,  218u,  645u),  /* idx=136, ratio=0.157435 */
    ALGO_RATIO_K_PACK( 273u,  238u, 1181u),  /* idx=137, ratio=0.288404 */
    ALGO_RATIO_K_PACK( 267u,  258u, 1634u),  /* idx=138, ratio=0.399063 */
    ALGO_RATIO_K_PACK( 261u,  278u, 2022u),  /* idx=139, ratio=0.493797 */
    ALGO_RATIO_K_PACK( 256u,  298u, 2358u),  /* idx=140, ratio=0.575812 */
    ALGO_RATIO_K_PACK( 250u,  319u, 2652u),  /* idx=141, ratio=0.647509 */
    ALGO_RATIO_K_PACK( 244u,  339u, 2910u),  /* idx=142, ratio=0.710719 */
    ALGO_RATIO_K_PACK( 238u,  359u, 3140u),  /* idx=143, ratio=0.766866 */
    ALGO_RATIO_K_PACK( 233u,  379u, 3346u),  /* idx=144, ratio=0.817071 */
    ALGO_RATIO_K_PACK( 227u,  399u, 3531u),  /* idx=145, ratio=0.862229 */
    ALGO_RATIO_K_PACK( 221u,  419u, 3698u),  /* idx=146, ratio=0.903065 */
    ALGO_RATIO_K_PACK( 216u,  439u, 3850u),  /* idx=147, ratio=0.940171 */
    ALGO_RATIO_K_PACK( 210u,  459u, 3989u),  /* idx=148, ratio=0.974036 */
    ALGO_RATIO_K_PACK( 204u,  479u, 3802u),  /* idx=149, ratio=0.928366 */
    ALGO_RATIO_K_PACK( 198u,  499u, 2842u),  /* idx=150, ratio=0.693921 */
    ALGO_RATIO_K_PACK( 193u,  519u, 1821u),  /* idx=151, ratio=0.444750 */
    ALGO_RATIO_K_PACK( 187u,  539u,  877u),  /* idx=152, ratio=0.214108 */
    ALGO_RATIO_K_PACK( 181u,  559u,    0u),  /* idx=153, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 299u,  216u,    0u),  /* idx=154, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 294u,  236u,  596u),  /* idx=155, ratio=0.145642 */
    ALGO_RATIO_K_PACK( 288u,  256u, 1099u),  /* idx=156, ratio=0.268492 */
    ALGO_RATIO_K_PACK( 282u,  276u, 1530u),  /* idx=157, ratio=0.373510 */
    ALGO_RATIO_K_PACK( 276u,  296u, 1901u),  /* idx=158, ratio=0.464317 */
    ALGO_RATIO_K_PACK( 271u,  316u, 2226u),  /* idx=159, ratio=0.543614 */
    ALGO_RATIO_K_PACK( 265u,  336u, 2512u),  /* idx=160, ratio=0.613460 */
    ALGO_RATIO_K_PACK( 259u,  356u, 2766u),  /* idx=161, ratio=0.675449 */
    ALGO_RATIO_K_PACK( 253u,  376u, 2993u),  /* idx=162, ratio=0.730836 */
    ALGO_RATIO_K_PACK( 248u,  396u, 3197u),  /* idx=163, ratio=0.780622 */
    ALGO_RATIO_K_PACK( 242u,  416u, 3381u),  /* idx=164, ratio=0.825617 */
    ALGO_RATIO_K_PACK( 236u,  436u, 3548u),  /* idx=165, ratio=0.866480 */
    ALGO_RATIO_K_PACK( 230u,  456u, 3701u),  /* idx=166, ratio=0.903755 */
    ALGO_RATIO_K_PACK( 225u,  476u, 3841u),  /* idx=167, ratio=0.937895 */
    ALGO_RATIO_K_PACK( 219u,  497u, 2855u),  /* idx=168, ratio=0.697216 */
    ALGO_RATIO_K_PACK( 213u,  517u, 1830u),  /* idx=169, ratio=0.446780 */
    ALGO_RATIO_K_PACK( 207u,  537u,  881u),  /* idx=170, ratio=0.215048 */
    ALGO_RATIO_K_PACK( 202u,  557u,    0u),  /* idx=171, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 314u,  234u,    0u),  /* idx=172, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 309u,  254u,  555u),  /* idx=173, ratio=0.135493 */
    ALGO_RATIO_K_PACK( 303u,  274u, 1028u),  /* idx=174, ratio=0.251151 */
    ALGO_RATIO_K_PACK( 297u,  294u, 1437u),  /* idx=175, ratio=0.351032 */
    ALGO_RATIO_K_PACK( 291u,  314u, 1794u),  /* idx=176, ratio=0.438159 */
    ALGO_RATIO_K_PACK( 286u,  334u, 2108u),  /* idx=177, ratio=0.514827 */
    ALGO_RATIO_K_PACK( 280u,  354u, 2387u),  /* idx=178, ratio=0.582813 */
    ALGO_RATIO_K_PACK( 274u,  374u, 2635u),  /* idx=179, ratio=0.643513 */
    ALGO_RATIO_K_PACK( 268u,  394u, 2858u),  /* idx=180, ratio=0.698039 */
    ALGO_RATIO_K_PACK( 263u,  414u, 3060u),  /* idx=181, ratio=0.747287 */
    ALGO_RATIO_K_PACK( 257u,  434u, 3243u),  /* idx=182, ratio=0.791988 */
    ALGO_RATIO_K_PACK( 251u,  454u, 3410u),  /* idx=183, ratio=0.832743 */
    ALGO_RATIO_K_PACK( 245u,  474u, 3563u),  /* idx=184, ratio=0.870054 */
    ALGO_RATIO_K_PACK( 240u,  494u, 2869u),  /* idx=185, ratio=0.700542 */
    ALGO_RATIO_K_PACK( 234u,  514u, 1838u),  /* idx=186, ratio=0.448829 */
    ALGO_RATIO_K_PACK( 228u,  534u,  885u),  /* idx=187, ratio=0.215997 */
    ALGO_RATIO_K_PACK( 222u,  554u,    0u),  /* idx=188, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 329u,  251u,    0u),  /* idx=189, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 324u,  271u,  519u),  /* idx=190, ratio=0.126667 */
    ALGO_RATIO_K_PACK( 318u,  291u,  966u),  /* idx=191, ratio=0.235915 */
    ALGO_RATIO_K_PACK( 312u,  311u, 1356u),  /* idx=192, ratio=0.331107 */
    ALGO_RATIO_K_PACK( 306u,  331u, 1699u),  /* idx=193, ratio=0.414791 */
    ALGO_RATIO_K_PACK( 301u,  352u, 2002u),  /* idx=194, ratio=0.488935 */
    ALGO_RATIO_K_PACK( 295u,  372u, 2273u),  /* idx=195, ratio=0.555083 */
    ALGO_RATIO_K_PACK( 289u,  392u, 2516u),  /* idx=196, ratio=0.614461 */
    ALGO_RATIO_K_PACK( 283u,  412u, 2736u),  /* idx=197, ratio=0.668059 */
    ALGO_RATIO_K_PACK( 278u,  432u, 2935u),  /* idx=198, ratio=0.716682 */
    ALGO_RATIO_K_PACK( 272u,  452u, 3116u),  /* idx=199, ratio=0.760991 */
    ALGO_RATIO_K_PACK( 266u,  472u, 3282u),  /* idx=200, ratio=0.801536 */
    ALGO_RATIO_K_PACK( 260u,  492u, 2882u),  /* idx=201, ratio=0.703901 */
    ALGO_RATIO_K_PACK( 255u,  512u, 1846u),  /* idx=202, ratio=0.450896 */
    ALGO_RATIO_K_PACK( 249u,  532u,  888u),  /* idx=203, ratio=0.216955 */
    ALGO_RATIO_K_PACK( 243u,  552u,    0u),  /* idx=204, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 344u,  269u,    0u),  /* idx=205, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 338u,  289u,  487u),  /* idx=206, ratio=0.118920 */
    ALGO_RATIO_K_PACK( 333u,  309u,  911u),  /* idx=207, ratio=0.222421 */
    ALGO_RATIO_K_PACK( 327u,  329u, 1283u),  /* idx=208, ratio=0.313321 */
    ALGO_RATIO_K_PACK( 321u,  349u, 1613u),  /* idx=209, ratio=0.393789 */
    ALGO_RATIO_K_PACK( 316u,  369u, 1906u),  /* idx=210, ratio=0.465523 */
    ALGO_RATIO_K_PACK( 310u,  389u, 2170u),  /* idx=211, ratio=0.529871 */
    ALGO_RATIO_K_PACK( 304u,  409u, 2408u),  /* idx=212, ratio=0.587919 */
    ALGO_RATIO_K_PACK( 298u,  429u, 2623u),  /* idx=213, ratio=0.640549 */
    ALGO_RATIO_K_PACK( 293u,  449u, 2819u),  /* idx=214, ratio=0.688485 */
    ALGO_RATIO_K_PACK( 287u,  469u, 2999u),  /* idx=215, ratio=0.732329 */
    ALGO_RATIO_K_PACK( 281u,  489u, 2896u),  /* idx=216, ratio=0.707292 */
    ALGO_RATIO_K_PACK( 275u,  509u, 1855u),  /* idx=217, ratio=0.452983 */
    ALGO_RATIO_K_PACK( 270u,  530u,  892u),  /* idx=218, ratio=0.217921 */
    ALGO_RATIO_K_PACK( 264u,  550u,    0u),  /* idx=219, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 359u,  287u,    0u),  /* idx=220, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 353u,  307u,  459u),  /* idx=221, ratio=0.112065 */
    ALGO_RATIO_K_PACK( 348u,  327u,  862u),  /* idx=222, ratio=0.210388 */
    ALGO_RATIO_K_PACK( 342u,  347u, 1218u),  /* idx=223, ratio=0.297350 */
    ALGO_RATIO_K_PACK( 336u,  367u, 1535u),  /* idx=224, ratio=0.374812 */
    ALGO_RATIO_K_PACK( 330u,  387u, 1819u),  /* idx=225, ratio=0.444250 */
    ALGO_RATIO_K_PACK( 325u,  407u, 2076u),  /* idx=226, ratio=0.506851 */
    ALGO_RATIO_K_PACK( 319u,  427u, 2308u),  /* idx=227, ratio=0.563575 */
    ALGO_RATIO_K_PACK( 313u,  447u, 2519u),  /* idx=228, ratio=0.615215 */
    ALGO_RATIO_K_PACK( 308u,  467u, 2713u),  /* idx=229, ratio=0.662423 */
    ALGO_RATIO_K_PACK( 302u,  487u, 2890u),  /* idx=230, ratio=0.705747 */
    ALGO_RATIO_K_PACK( 296u,  507u, 1864u),  /* idx=231, ratio=0.455089 */
    ALGO_RATIO_K_PACK( 290u,  527u,  896u),  /* idx=232, ratio=0.218896 */
    ALGO_RATIO_K_PACK( 285u,  547u,    0u),  /* idx=233, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 374u,  304u,    0u),  /* idx=234, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 368u,  324u,  434u),  /* idx=235, ratio=0.105958 */
    ALGO_RATIO_K_PACK( 363u,  344u,  817u),  /* idx=236, ratio=0.199590 */
    ALGO_RATIO_K_PACK( 357u,  364u, 1159u),  /* idx=237, ratio=0.282927 */
    ALGO_RATIO_K_PACK( 351u,  385u, 1464u),  /* idx=238, ratio=0.357579 */
    ALGO_RATIO_K_PACK( 345u,  405u, 1740u),  /* idx=239, ratio=0.424837 */
    ALGO_RATIO_K_PACK( 340u,  425u, 1989u),  /* idx=240, ratio=0.485747 */
    ALGO_RATIO_K_PACK( 334u,  445u, 2216u),  /* idx=241, ratio=0.541167 */
    ALGO_RATIO_K_PACK( 328u,  465u, 2423u),  /* idx=242, ratio=0.591808 */
    ALGO_RATIO_K_PACK( 322u,  485u, 2614u),  /* idx=243, ratio=0.638262 */
    ALGO_RATIO_K_PACK( 317u,  505u, 1872u),  /* idx=244, ratio=0.457215 */
    ALGO_RATIO_K_PACK( 311u,  525u,  900u),  /* idx=245, ratio=0.219879 */
    ALGO_RATIO_K_PACK( 305u,  545u,    0u),  /* idx=246, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 389u,  322u,    0u),  /* idx=247, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 383u,  342u,  411u),  /* idx=248, ratio=0.100483 */
    ALGO_RATIO_K_PACK( 378u,  362u,  777u),  /* idx=249, ratio=0.189846 */
    ALGO_RATIO_K_PACK( 372u,  382u, 1105u),  /* idx=250, ratio=0.269839 */
    ALGO_RATIO_K_PACK( 366u,  402u, 1400u),  /* idx=251, ratio=0.341862 */
    ALGO_RATIO_K_PACK( 360u,  422u, 1667u),  /* idx=252, ratio=0.407049 */
    ALGO_RATIO_K_PACK( 355u,  442u, 1910u),  /* idx=253, ratio=0.466330 */
    ALGO_RATIO_K_PACK( 349u,  462u, 2131u),  /* idx=254, ratio=0.520473 */
    ALGO_RATIO_K_PACK( 343u,  482u, 2335u),  /* idx=255, ratio=0.570117 */
    ALGO_RATIO_K_PACK( 337u,  502u, 1881u),  /* idx=256, ratio=0.459360 */
    ALGO_RATIO_K_PACK( 332u,  522u,  904u),  /* idx=257, ratio=0.220871 */
    ALGO_RATIO_K_PACK( 326u,  542u,    0u),  /* idx=258, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 404u,  340u,    0u),  /* idx=259, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 398u,  360u,  391u),  /* idx=260, ratio=0.095545 */
    ALGO_RATIO_K_PACK( 393u,  380u,  741u),  /* idx=261, ratio=0.181009 */
    ALGO_RATIO_K_PACK( 387u,  400u, 1056u),  /* idx=262, ratio=0.257908 */
    ALGO_RATIO_K_PACK( 381u,  420u, 1341u),  /* idx=263, ratio=0.327468 */
    ALGO_RATIO_K_PACK( 375u,  440u, 1600u),  /* idx=264, ratio=0.390691 */
    ALGO_RATIO_K_PACK( 370u,  460u, 1836u),  /* idx=265, ratio=0.448406 */
    ALGO_RATIO_K_PACK( 364u,  480u, 2053u),  /* idx=266, ratio=0.501303 */
    ALGO_RATIO_K_PACK( 358u,  500u, 1890u),  /* idx=267, ratio=0.461526 */
    ALGO_RATIO_K_PACK( 352u,  520u,  909u),  /* idx=268, ratio=0.221872 */
    ALGO_RATIO_K_PACK( 347u,  540u,    0u),  /* idx=269, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 419u,  357u,    0u),  /* idx=270, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 413u,  377u,  373u),  /* idx=271, ratio=0.091070 */
    ALGO_RATIO_K_PACK( 408u,  397u,  708u),  /* idx=272, ratio=0.172959 */
    ALGO_RATIO_K_PACK( 402u,  418u, 1011u),  /* idx=273, ratio=0.246988 */
    ALGO_RATIO_K_PACK( 396u,  438u, 1287u),  /* idx=274, ratio=0.314237 */
    ALGO_RATIO_K_PACK( 390u,  458u, 1538u),  /* idx=275, ratio=0.375597 */
    ALGO_RATIO_K_PACK( 385u,  478u, 1768u),  /* idx=276, ratio=0.431809 */
    ALGO_RATIO_K_PACK( 379u,  498u, 1899u),  /* idx=277, ratio=0.463713 */
    ALGO_RATIO_K_PACK( 373u,  518u,  913u),  /* idx=278, ratio=0.222883 */
    ALGO_RATIO_K_PACK( 367u,  538u,    0u),  /* idx=279, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 434u,  375u,    0u),  /* idx=280, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 428u,  395u,  356u),  /* idx=281, ratio=0.086995 */
    ALGO_RATIO_K_PACK( 422u,  415u,  678u),  /* idx=282, ratio=0.165593 */
    ALGO_RATIO_K_PACK( 417u,  435u,  970u),  /* idx=283, ratio=0.236954 */
    ALGO_RATIO_K_PACK( 411u,  455u, 1237u),  /* idx=284, ratio=0.302034 */
    ALGO_RATIO_K_PACK( 405u,  475u, 1481u),  /* idx=285, ratio=0.361626 */
    ALGO_RATIO_K_PACK( 399u,  495u, 1705u),  /* idx=286, ratio=0.416397 */
    ALGO_RATIO_K_PACK( 394u,  515u,  917u),  /* idx=287, ratio=0.223903 */
    ALGO_RATIO_K_PACK( 388u,  535u,    0u),  /* idx=288, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 449u,  393u,    0u),  /* idx=289, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 443u,  413u,  341u),  /* idx=290, ratio=0.083270 */
    ALGO_RATIO_K_PACK( 437u,  433u,  650u),  /* idx=291, ratio=0.158830 */
    ALGO_RATIO_K_PACK( 432u,  453u,  932u),  /* idx=292, ratio=0.227705 */
    ALGO_RATIO_K_PACK( 426u,  473u, 1191u),  /* idx=293, ratio=0.290743 */
    ALGO_RATIO_K_PACK( 420u,  493u, 1428u),  /* idx=294, ratio=0.348657 */
    ALGO_RATIO_K_PACK( 414u,  513u,  921u),  /* idx=295, ratio=0.224932 */
    ALGO_RATIO_K_PACK( 409u,  533u,    0u),  /* idx=296, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 464u,  410u,    0u),  /* idx=297, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 458u,  431u,  327u),  /* idx=298, ratio=0.079850 */
    ALGO_RATIO_K_PACK( 452u,  451u,  625u),  /* idx=299, ratio=0.152597 */
    ALGO_RATIO_K_PACK( 447u,  471u,  897u),  /* idx=300, ratio=0.219150 */
    ALGO_RATIO_K_PACK( 441u,  491u, 1148u),  /* idx=301, ratio=0.280266 */
    ALGO_RATIO_K_PACK( 435u,  511u,  925u),  /* idx=302, ratio=0.225970 */
    ALGO_RATIO_K_PACK( 429u,  531u,    0u),  /* idx=303, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 479u,  428u,    0u),  /* idx=304, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 473u,  448u,  314u),  /* idx=305, ratio=0.076700 */
    ALGO_RATIO_K_PACK( 467u,  468u,  601u),  /* idx=306, ratio=0.146835 */
    ALGO_RATIO_K_PACK( 462u,  488u,  865u),  /* idx=307, ratio=0.211214 */
    ALGO_RATIO_K_PACK( 456u,  508u,  930u),  /* idx=308, ratio=0.227018 */
    ALGO_RATIO_K_PACK( 450u,  528u,    0u),  /* idx=309, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 494u,  446u,    0u),  /* idx=310, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 488u,  466u,  302u),  /* idx=311, ratio=0.073789 */
    ALGO_RATIO_K_PACK( 482u,  486u,  579u),  /* idx=312, ratio=0.141493 */
    ALGO_RATIO_K_PACK( 477u,  506u,  835u),  /* idx=313, ratio=0.203834 */
    ALGO_RATIO_K_PACK( 471u,  526u,    0u),  /* idx=314, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 509u,  464u,    0u),  /* idx=315, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 503u,  484u,  291u),  /* idx=316, ratio=0.071091 */
    ALGO_RATIO_K_PACK( 497u,  504u,  559u),  /* idx=317, ratio=0.136525 */
    ALGO_RATIO_K_PACK( 491u,  524u,    0u),  /* idx=318, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 524u,  481u,    0u),  /* idx=319, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 518u,  501u,  254u),  /* idx=320, ratio=0.061949 */
    ALGO_RATIO_K_PACK( 512u,  521u,    0u),  /* idx=321, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 539u,  499u,    0u),  /* idx=322, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 533u,  519u,    0u),  /* idx=323, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 554u,  517u,    0u),  /* idx=324, ratio=0.000000 */

};

#define ALGO_RATIO_K_LUT_COUNT ((uint16_t)(sizeof(g_algoRatioKPackedLut) / sizeof(g_algoRatioKPackedLut[0])))

enum
{
    IDC_U_INPUT = 1001,
    IDC_V_INPUT,
    IDC_Y_INPUT,
    IDC_K_INPUT,
    IDC_WEIGHT_ENABLE,

    IDC_WHITE_X,
    IDC_WHITE_Y,
    IDC_WHITE_YMAX,

    IDC_R_X,
    IDC_R_Y,
    IDC_R_YMAX,

    IDC_G_X,
    IDC_G_Y,
    IDC_G_YMAX,

    IDC_B_X,
    IDC_B_Y,
    IDC_B_YMAX,

    IDC_PWM_MAX,
    IDC_CALC_BUTTON,
    IDC_RESULT_EDIT
};

typedef struct GuiField
{
    int id;
    const char *label;
    const char *defaultText;
    int x;
    int y;
    int w;
} GuiField;

typedef struct RatioKResult
{
    uint8_t valid;
    uint16_t whiteRatioQ10000;
    double whiteRatio;
    double rgbRatio;
    uint8_t kUsed;
} RatioKResult;

typedef struct CiePoint
{
    double x;
    double y;
    double Y;
} CiePoint;

typedef struct RgbWeight
{
    double r;
    double g;
    double b;
    uint8_t valid;
} RgbWeight;

static HWND g_hwndResult;

static uint16_t RatioK_GetU(uint32_t packedValue)
{
    return (uint16_t)(packedValue & ALGO_RATIO_K_U_MASK);
}

static uint16_t RatioK_GetV(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_V_MASK) >> ALGO_RATIO_K_V_SHIFT);
}

static uint16_t RatioK_GetRatio12(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_RATIO_MASK) >> ALGO_RATIO_K_RATIO_SHIFT);
}

static uint16_t RatioK_ConvertRatio12ToQ10000(uint16_t ratio12)
{
    uint32_t ratioQ10000;

    ratioQ10000 = (((uint32_t)ratio12 * ALGO_RATIO_K_RATIO_Q10000_MAX) +
                   (ALGO_RATIO_K_RATIO12_MAX / 2u)) /
                  ALGO_RATIO_K_RATIO12_MAX;

    if (ratioQ10000 > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        ratioQ10000 = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }

    return (uint16_t)ratioQ10000;
}

static uint32_t RatioK_CalcDistance2(uint16_t u1, uint16_t v1, uint16_t u2, uint16_t v2)
{
    int32_t du;
    int32_t dv;

    du = (int32_t)u1 - (int32_t)u2;
    dv = (int32_t)v1 - (int32_t)v2;

    return (uint32_t)((du * du) + (dv * dv));
}

static uint16_t RatioK_DivRoundU32(uint32_t numerator, uint32_t denominator)
{
    if (denominator == 0u)
    {
        return 0u;
    }

    return (uint16_t)((numerator + (denominator / 2u)) / denominator);
}

static RatioKResult RatioK_GetWhiteRatio(uint16_t targetU, uint16_t targetV, uint8_t kAmount, uint8_t useWeight)
{
    RatioKResult result;
    uint32_t nearestDistance[ALGO_RATIO_K_MAX_K];
    uint16_t nearestRatio12[ALGO_RATIO_K_MAX_K];

    uint16_t lutIndex;
    uint16_t pointU;
    uint16_t pointV;
    uint16_t pointRatio12;
    uint32_t packedValue;
    uint32_t distance2;

    uint8_t insertIndex;
    uint8_t shiftIndex;
    uint8_t nearestCount;
    uint8_t i;

    uint32_t weight;
    uint32_t weightSum;
    uint32_t weightedRatioSum;
    uint32_t ratioSum;

    uint16_t pointRatioQ10000;
    uint16_t ratioResult;

    result.valid = 0u;
    result.whiteRatioQ10000 = 0u;
    result.whiteRatio = 0.0;
    result.rgbRatio = 0.0;
    result.kUsed = 0u;

    if (kAmount == 0u)
    {
        return result;
    }

    if (kAmount > ALGO_RATIO_K_MAX_K)
    {
        kAmount = ALGO_RATIO_K_MAX_K;
    }

    for (i = 0u; i < kAmount; i++)
    {
        nearestDistance[i] = ALGO_RATIO_K_DISTANCE_MAX;
        nearestRatio12[i] = 0u;
    }

    nearestCount = 0u;

    for (lutIndex = 0u; lutIndex < ALGO_RATIO_K_LUT_COUNT; lutIndex++)
    {
        packedValue = g_algoRatioKPackedLut[lutIndex];

        pointU = RatioK_GetU(packedValue);
        pointV = RatioK_GetV(packedValue);
        pointRatio12 = RatioK_GetRatio12(packedValue);

        distance2 = RatioK_CalcDistance2(targetU, targetV, pointU, pointV);

        if (distance2 == 0u)
        {
            result.whiteRatioQ10000 = RatioK_ConvertRatio12ToQ10000(pointRatio12);
            result.whiteRatio = (double)result.whiteRatioQ10000 / 10000.0;
            result.rgbRatio = 1.0 - result.whiteRatio;
            result.kUsed = 1u;
            result.valid = 1u;
            return result;
        }

        for (insertIndex = 0u; insertIndex < kAmount; insertIndex++)
        {
            if (distance2 < nearestDistance[insertIndex])
            {
                for (shiftIndex = (uint8_t)(kAmount - 1u); shiftIndex > insertIndex; shiftIndex--)
                {
                    nearestDistance[shiftIndex] = nearestDistance[shiftIndex - 1u];
                    nearestRatio12[shiftIndex] = nearestRatio12[shiftIndex - 1u];
                }

                nearestDistance[insertIndex] = distance2;
                nearestRatio12[insertIndex] = pointRatio12;

                if (nearestCount < kAmount)
                {
                    nearestCount++;
                }

                break;
            }
        }
    }

    if (nearestCount == 0u)
    {
        return result;
    }

    if (useWeight != 0u)
    {
        weightSum = 0u;
        weightedRatioSum = 0u;

        for (i = 0u; i < nearestCount; i++)
        {
            pointRatioQ10000 = RatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);

            weight = (uint32_t)(ALGO_RATIO_K_WEIGHT_SCALE / (nearestDistance[i] + 1u));

            if (weight == 0u)
            {
                weight = 1u;
            }

            weightedRatioSum += ((uint32_t)pointRatioQ10000 * weight);
            weightSum += weight;
        }

        ratioResult = RatioK_DivRoundU32(weightedRatioSum, weightSum);
    }
    else
    {
        ratioSum = 0u;

        for (i = 0u; i < nearestCount; i++)
        {
            pointRatioQ10000 = RatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);
            ratioSum += (uint32_t)pointRatioQ10000;
        }

        ratioResult = RatioK_DivRoundU32(ratioSum, nearestCount);
    }

    if (ratioResult > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        ratioResult = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }

    result.whiteRatioQ10000 = ratioResult;
    result.whiteRatio = (double)ratioResult / 10000.0;
    result.rgbRatio = 1.0 - result.whiteRatio;
    result.kUsed = nearestCount;
    result.valid = 1u;

    return result;
}

static int ClampInt(int value, int minValue, int maxValue)
{
    if (value < minValue)
    {
        return minValue;
    }

    if (value > maxValue)
    {
        return maxValue;
    }

    return value;
}

static int RoundToInt(double value)
{
    if (value >= 0.0)
    {
        return (int)(value + 0.5);
    }

    return (int)(value - 0.5);
}

static double GetDlgDouble(HWND hwnd, int id, double fallback)
{
    char buf[64];
    char *endPtr;
    double value;

    GetDlgItemTextA(hwnd, id, buf, sizeof(buf));
    value = strtod(buf, &endPtr);

    if (endPtr == buf)
    {
        value = fallback;
    }

    return value;
}

static int GetDlgIntSafe(HWND hwnd, int id, int fallback)
{
    char buf[64];
    char *endPtr;
    long value;

    GetDlgItemTextA(hwnd, id, buf, sizeof(buf));
    value = strtol(buf, &endPtr, 10);

    if (endPtr == buf)
    {
        value = fallback;
    }

    return (int)value;
}

static void Uv1976ToXy(double u, double v, double *x, double *y)
{
    double den;

    den = 6.0 * u - 16.0 * v + 12.0;

    if (fabs(den) < 1e-12)
    {
        *x = 0.0;
        *y = 0.0;
    }
    else
    {
        *x = 9.0 * u / den;
        *y = 4.0 * v / den;
    }
}

static void XyYToXYZ(CiePoint p, double *X, double *Y, double *Z)
{
    if (fabs(p.y) < 1e-12)
    {
        *X = 0.0;
        *Y = 0.0;
        *Z = 0.0;
        return;
    }

    *X = p.x * p.Y / p.y;
    *Y = p.Y;
    *Z = (1.0 - p.x - p.y) * p.Y / p.y;
}

static double Det3(double a11, double a12, double a13,
                   double a21, double a22, double a23,
                   double a31, double a32, double a33)
{
    return a11 * (a22 * a33 - a23 * a32)
         - a12 * (a21 * a33 - a23 * a31)
         + a13 * (a21 * a32 - a22 * a31);
}

static RgbWeight SolveRgbWeight(CiePoint r, CiePoint g, CiePoint b, CiePoint target)
{
    RgbWeight w;
    double rX, rY, rZ;
    double gX, gY, gZ;
    double bX, bY, bZ;
    double tX, tY, tZ;
    double detM;

    w.r = 0.0;
    w.g = 0.0;
    w.b = 0.0;
    w.valid = 0u;

    XyYToXYZ(r, &rX, &rY, &rZ);
    XyYToXYZ(g, &gX, &gY, &gZ);
    XyYToXYZ(b, &bX, &bY, &bZ);
    XyYToXYZ(target, &tX, &tY, &tZ);

    detM = Det3(rX, gX, bX,
                rY, gY, bY,
                rZ, gZ, bZ);

    if (fabs(detM) < 1e-12)
    {
        return w;
    }

    w.r = Det3(tX, gX, bX,
               tY, gY, bY,
               tZ, gZ, bZ) / detM;

    w.g = Det3(rX, tX, bX,
               rY, tY, bY,
               rZ, tZ, bZ) / detM;

    w.b = Det3(rX, gX, tX,
               rY, gY, tY,
               rZ, gZ, tZ) / detM;

    w.valid = 1u;

    return w;
}

static void AppendText(char *dst, size_t dstSize, const char *fmt, ...)
{
    va_list args;
    size_t len;

    len = strlen(dst);

    if (len >= dstSize)
    {
        return;
    }

    va_start(args, fmt);
    vsnprintf(dst + len, dstSize - len, fmt, args);
    va_end(args);
}

static void CalculateAndShow(HWND hwnd)
{
    double inputU;
    double inputV;
    double targetU;
    double targetV;
    uint16_t targetU1000;
    uint16_t targetV1000;

    double targetX;
    double targetYxy;
    double targetLum;

    int kAmount;
    int useWeight;
    int pwmMax;

    CiePoint whitePoint;
    CiePoint splitWhite;
    CiePoint splitRgb;
    CiePoint redPoint;
    CiePoint greenPoint;
    CiePoint bluePoint;

    RatioKResult ratioResult;
    RgbWeight rgbWeight;

    double ratioFactor;
    double lambda;
    double rayT;
    double dirX;
    double dirY;
    double rawWhiteRatio;
    double maxWhiteRatioByY;
    uint8_t whiteRatioClamped;

    int pwmR;
    int pwmG;
    int pwmB;
    int pwmW;

    char resultText[12000];

    inputU = GetDlgDouble(hwnd, IDC_U_INPUT, 40.0);
    inputV = GetDlgDouble(hwnd, IDC_V_INPUT, 94.0);
    targetLum = GetDlgDouble(hwnd, IDC_Y_INPUT, 3.0);

    /*
     * Engineering input:
     *   40 / 94 -> 200 / 470 -> 0.200 / 0.470
     */
    if (inputU > 1.0)
    {
        targetU1000 = (uint16_t)RoundToInt(inputU * 5.0);
        targetU = (double)targetU1000 / 1000.0;
    }
    else
    {
        targetU = inputU;
        targetU1000 = (uint16_t)RoundToInt(targetU * 1000.0);
    }

    if (inputV > 1.0)
    {
        targetV1000 = (uint16_t)RoundToInt(inputV * 5.0);
        targetV = (double)targetV1000 / 1000.0;
    }
    else
    {
        targetV = inputV;
        targetV1000 = (uint16_t)RoundToInt(targetV * 1000.0);
    }

    Uv1976ToXy(targetU, targetV, &targetX, &targetYxy);

    kAmount = ClampInt(GetDlgIntSafe(hwnd, IDC_K_INPUT, 6), 1, (int)ALGO_RATIO_K_MAX_K);
    useWeight = (int)SendDlgItemMessageA(hwnd, IDC_WEIGHT_ENABLE, BM_GETCHECK, 0, 0);
    pwmMax = ClampInt(GetDlgIntSafe(hwnd, IDC_PWM_MAX, 255), 1, 65535);

    whitePoint.x = GetDlgDouble(hwnd, IDC_WHITE_X, 0.2810);
    whitePoint.y = GetDlgDouble(hwnd, IDC_WHITE_Y, 0.2900);
    whitePoint.Y = GetDlgDouble(hwnd, IDC_WHITE_YMAX, 21.5);

    redPoint.x = GetDlgDouble(hwnd, IDC_R_X, 0.6250);
    redPoint.y = GetDlgDouble(hwnd, IDC_R_Y, 0.3420);
    redPoint.Y = GetDlgDouble(hwnd, IDC_R_YMAX, 15.8);

    greenPoint.x = GetDlgDouble(hwnd, IDC_G_X, 0.3270);
    greenPoint.y = GetDlgDouble(hwnd, IDC_G_Y, 0.5280);
    greenPoint.Y = GetDlgDouble(hwnd, IDC_G_YMAX, 17.8);

    bluePoint.x = GetDlgDouble(hwnd, IDC_B_X, 0.1770);
    bluePoint.y = GetDlgDouble(hwnd, IDC_B_Y, 0.0990);
    bluePoint.Y = GetDlgDouble(hwnd, IDC_B_YMAX, 13.1);

    ratioResult = RatioK_GetWhiteRatio(targetU1000, targetV1000, (uint8_t)kAmount, (uint8_t)useWeight);

    rawWhiteRatio = ratioResult.whiteRatio;
    maxWhiteRatioByY = 1.0;
    whiteRatioClamped = 0u;

    resultText[0] = '\0';

    AppendText(resultText, sizeof(resultText), "================ K-Ratio RGBW GUI Result ================\r\n");
    AppendText(resultText, sizeof(resultText), "Raw input: Uin = %.6f, Vin = %.6f\r\n", inputU, inputV);
    AppendText(resultText, sizeof(resultText), "Algorithm input: U = %u, V = %u  ->  u' = %.6f, v' = %.6f\r\n", targetU1000, targetV1000, targetU, targetV);
    AppendText(resultText, sizeof(resultText), "Converted xyY: x = %.6f, y = %.6f, Y = %.6f\r\n", targetX, targetYxy, targetLum);
    AppendText(resultText, sizeof(resultText), "K = %d, Weight = %s, LUT Count = %u\r\n\r\n", kAmount, useWeight ? "ON" : "OFF", ALGO_RATIO_K_LUT_COUNT);

    if (ratioResult.valid == 0u)
    {
        AppendText(resultText, sizeof(resultText), "K-ratio LUT lookup failed.\r\n");
        SetWindowTextA(g_hwndResult, resultText);
        return;
    }

    if (fabs(whitePoint.y) < 1e-12)
    {
        AppendText(resultText, sizeof(resultText), "RGB mixed point failed: whitePoint.y is too small.\r\n");
        SetWindowTextA(g_hwndResult, resultText);
        return;
    }

    if (fabs(targetYxy) > 1e-12)
    {
        /*
         * Keep lambda positive:
         *   lambda = 1 - whiteRatio * target_y / white_y
         * Therefore:
         *   whiteRatio < white_y / target_y
         *
         * This GUI clamp is only for desktop display. The ECU branch should use
         * the original Algorithm.c boundary clamp when available.
         */
        maxWhiteRatioByY = (whitePoint.y / targetYxy) - 0.000001;

        if (maxWhiteRatioByY < 0.0)
        {
            maxWhiteRatioByY = 0.0;
        }

        if (maxWhiteRatioByY > 1.0)
        {
            maxWhiteRatioByY = 1.0;
        }

        if (ratioResult.whiteRatio > maxWhiteRatioByY)
        {
            ratioResult.whiteRatio = maxWhiteRatioByY;
            ratioResult.whiteRatioQ10000 = (uint16_t)ClampInt(RoundToInt(ratioResult.whiteRatio * 10000.0), 0, 10000);
            ratioResult.rgbRatio = 1.0 - ratioResult.whiteRatio;
            whiteRatioClamped = 1u;
        }
    }

    splitWhite.x = whitePoint.x;
    splitWhite.y = whitePoint.y;
    splitWhite.Y = targetLum * ratioResult.whiteRatio;

    ratioFactor = ratioResult.whiteRatio * targetYxy / whitePoint.y;
    lambda = 1.0 - ratioFactor;

    if (lambda <= 1e-12)
    {
        AppendText(resultText, sizeof(resultText), "RGB mixed point failed: lambda is invalid.\r\n");
        SetWindowTextA(g_hwndResult, resultText);
        return;
    }

    rayT = 1.0 / lambda;
    dirX = targetX - whitePoint.x;
    dirY = targetYxy - whitePoint.y;

    splitRgb.x = whitePoint.x + rayT * dirX;
    splitRgb.y = whitePoint.y + rayT * dirY;
    splitRgb.Y = targetLum * ratioResult.rgbRatio;

    rgbWeight = SolveRgbWeight(redPoint, greenPoint, bluePoint, splitRgb);

    if (rgbWeight.valid != 0u)
    {
        pwmR = ClampInt(RoundToInt(rgbWeight.r * (double)pwmMax), 0, pwmMax);
        pwmG = ClampInt(RoundToInt(rgbWeight.g * (double)pwmMax), 0, pwmMax);
        pwmB = ClampInt(RoundToInt(rgbWeight.b * (double)pwmMax), 0, pwmMax);
    }
    else
    {
        pwmR = 0;
        pwmG = 0;
        pwmB = 0;
    }

    if (whitePoint.Y > 1e-12)
    {
        pwmW = ClampInt(RoundToInt((splitWhite.Y / whitePoint.Y) * (double)pwmMax), 0, pwmMax);
    }
    else
    {
        pwmW = ClampInt(RoundToInt(ratioResult.whiteRatio * (double)pwmMax), 0, pwmMax);
    }

    AppendText(resultText, sizeof(resultText), "---------------- K-Ratio LUT Result ----------------\r\n");
    AppendText(resultText, sizeof(resultText), "valid              = %u\r\n", ratioResult.valid);
    AppendText(resultText, sizeof(resultText), "kUsed              = %u\r\n", ratioResult.kUsed);
    AppendText(resultText, sizeof(resultText), "whiteRatioQ10000   = %u\r\n", ratioResult.whiteRatioQ10000);
    AppendText(resultText, sizeof(resultText), "rawWhiteRatio      = %.6f\r\n", rawWhiteRatio);
    AppendText(resultText, sizeof(resultText), "usedWhiteRatio     = %.6f\r\n", ratioResult.whiteRatio);
    AppendText(resultText, sizeof(resultText), "maxWhiteRatioByY   = %.6f\r\n", maxWhiteRatioByY);
    AppendText(resultText, sizeof(resultText), "whiteRatioClamped  = %u\r\n", whiteRatioClamped);
    AppendText(resultText, sizeof(resultText), "rgbRatio           = %.6f\r\n\r\n", ratioResult.rgbRatio);

    AppendText(resultText, sizeof(resultText), "---------------- White Output Point splitWhiteCIE ----------------\r\n");
    AppendText(resultText, sizeof(resultText), "splitWhiteCIE.x    = %.6f\r\n", splitWhite.x);
    AppendText(resultText, sizeof(resultText), "splitWhiteCIE.y    = %.6f\r\n", splitWhite.y);
    AppendText(resultText, sizeof(resultText), "splitWhiteCIE.Y    = %.6f\r\n\r\n", splitWhite.Y);

    AppendText(resultText, sizeof(resultText), "---------------- RGB Mixed Point splitPointCIE ----------------\r\n");
    AppendText(resultText, sizeof(resultText), "splitPointCIE.x    = %.6f\r\n", splitRgb.x);
    AppendText(resultText, sizeof(resultText), "splitPointCIE.y    = %.6f\r\n", splitRgb.y);
    AppendText(resultText, sizeof(resultText), "splitPointCIE.Y    = %.6f\r\n", splitRgb.Y);
    AppendText(resultText, sizeof(resultText), "rayT               = %.6f\r\n", rayT);
    AppendText(resultText, sizeof(resultText), "lambda             = %.6f\r\n\r\n", lambda);

    AppendText(resultText, sizeof(resultText), "---------------- RGB Weight and PWM Estimation ----------------\r\n");
    AppendText(resultText, sizeof(resultText), "RGB weight valid   = %u\r\n", rgbWeight.valid);
    AppendText(resultText, sizeof(resultText), "R weight           = %.6f\r\n", rgbWeight.r);
    AppendText(resultText, sizeof(resultText), "G weight           = %.6f\r\n", rgbWeight.g);
    AppendText(resultText, sizeof(resultText), "B weight           = %.6f\r\n", rgbWeight.b);
    AppendText(resultText, sizeof(resultText), "PWM R/G/B/W        = %d / %d / %d / %d\r\n", pwmR, pwmG, pwmB, pwmW);

    AppendText(resultText, sizeof(resultText), "\r\nNote: This GUI only calculates K-ratio method. It does not calculate Ra. Use MATLAB s07 for Ra.\r\n");

    SetWindowTextA(g_hwndResult, resultText);
}

static void CreateLabel(HWND hwnd, const char *text, int x, int y, int w, int h)
{
    CreateWindowA("STATIC", text, WS_CHILD | WS_VISIBLE,
                  x, y, w, h, hwnd, NULL, GetModuleHandle(NULL), NULL);
}

static HWND CreateEdit(HWND hwnd, int id, const char *text, int x, int y, int w, int h)
{
    return CreateWindowA("EDIT", text,
                         WS_CHILD | WS_VISIBLE | WS_BORDER | WS_TABSTOP | ES_AUTOHSCROLL,
                         x, y, w, h, hwnd, (HMENU)(intptr_t)id, GetModuleHandle(NULL), NULL);
}

static void CreateField(HWND hwnd, int id, const char *label, const char *value, int x, int y, int w)
{
    CreateLabel(hwnd, label, x, y + 4, 95, 20);
    CreateEdit(hwnd, id, value, x + 100, y, w, 24);
}

static void CreateMainControls(HWND hwnd)
{
    CreateLabel(hwnd, "Input", 20, 15, 120, 20);
    CreateField(hwnd, IDC_U_INPUT, "U input", "40", 20, 40, 80);
    CreateField(hwnd, IDC_V_INPUT, "V input", "94", 20, 70, 80);
    CreateField(hwnd, IDC_Y_INPUT, "Target Y", "3.0", 20, 100, 80);
    CreateField(hwnd, IDC_K_INPUT, "K", "6", 20, 130, 80);
    CreateField(hwnd, IDC_PWM_MAX, "PWM Max", "255", 20, 160, 80);

    CreateWindowA("BUTTON", "Weighted", WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_AUTOCHECKBOX,
                  120, 190, 120, 24, hwnd, (HMENU)(intptr_t)IDC_WEIGHT_ENABLE,
                  GetModuleHandle(NULL), NULL);
    SendDlgItemMessageA(hwnd, IDC_WEIGHT_ENABLE, BM_SETCHECK, BST_CHECKED, 0);

    CreateLabel(hwnd, "White point", 20, 225, 120, 20);
    CreateField(hwnd, IDC_WHITE_X, "White x", "0.3291", 20, 250, 80);
    CreateField(hwnd, IDC_WHITE_Y, "White y", "0.3396", 20, 280, 80);
    CreateField(hwnd, IDC_WHITE_YMAX, "White Ymax", "2.885", 20, 310, 80);

    CreateLabel(hwnd, "RGB primaries", 20, 345, 120, 20);
    CreateField(hwnd, IDC_R_X, "R x", "0.7058", 20, 370, 80);
    CreateField(hwnd, IDC_R_Y, "R y", "0.2931", 20, 400, 80);
    CreateField(hwnd, IDC_R_YMAX, "R Ymax", "1.116", 20, 430, 80);

    CreateField(hwnd, IDC_G_X, "G x", "0.1619", 20, 470, 80);
    CreateField(hwnd, IDC_G_Y, "G y", "0.7220", 20, 500, 80);
    CreateField(hwnd, IDC_G_YMAX, "G Ymax", "2.786", 20, 530, 80);

    CreateField(hwnd, IDC_B_X, "B x", "0.1498", 20, 570, 80);
    CreateField(hwnd, IDC_B_Y, "B y", "0.0317", 20, 600, 80);
    CreateField(hwnd, IDC_B_YMAX, "B Ymax", "0.4863", 20, 630, 80);

    CreateWindowA("BUTTON", "Calculate", WS_CHILD | WS_VISIBLE | WS_TABSTOP | BS_DEFPUSHBUTTON,
                  20, 670, 180, 36, hwnd, (HMENU)(intptr_t)IDC_CALC_BUTTON,
                  GetModuleHandle(NULL), NULL);

    g_hwndResult = CreateWindowA("EDIT", "",
                                 WS_CHILD | WS_VISIBLE | WS_BORDER |
                                 ES_MULTILINE | ES_AUTOVSCROLL | ES_AUTOHSCROLL |
                                 WS_VSCROLL | WS_HSCROLL | ES_READONLY,
                                 260, 20, 890, 690, hwnd,
                                 (HMENU)(intptr_t)IDC_RESULT_EDIT,
                                 GetModuleHandle(NULL), NULL);

    SendMessageA(g_hwndResult, WM_SETFONT, (WPARAM)GetStockObject(ANSI_FIXED_FONT), TRUE);
}

static LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    switch (msg)
    {
    case WM_CREATE:
        CreateMainControls(hwnd);
        SendMessageA(hwnd, DM_SETDEFID, IDC_CALC_BUTTON, 0);
        break;

    case WM_COMMAND:
        if ((LOWORD(wParam) == IDC_CALC_BUTTON) || (LOWORD(wParam) == IDOK))
        {
            CalculateAndShow(hwnd);
        }
        break;

    case WM_DESTROY:
        PostQuitMessage(0);
        break;

    default:
        return DefWindowProcA(hwnd, msg, wParam, lParam);
    }

    return 0;
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
    WNDCLASSA wc;
    HWND hwnd;
    MSG msg;

    (void)hPrevInstance;
    (void)lpCmdLine;

    memset(&wc, 0, sizeof(wc));
    wc.lpfnWndProc = WndProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = "RatioKUpperGuiClass";
    wc.hCursor = LoadCursor(NULL, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_BTNFACE + 1);

    RegisterClassA(&wc);

    hwnd = CreateWindowA("RatioKUpperGuiClass",
                         APP_TITLE,
                         WS_OVERLAPPEDWINDOW,
                         CW_USEDEFAULT,
                         CW_USEDEFAULT,
                         1180,
                         760,
                         NULL,
                         NULL,
                         hInstance,
                         NULL);

    ShowWindow(hwnd, nCmdShow);
    UpdateWindow(hwnd);

    while (GetMessageA(&msg, NULL, 0, 0) > 0)
    {
        if (IsDialogMessageA(hwnd, &msg) == 0)
        {
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
    }

    return (int)msg.wParam;
}
