% PLOT_RA_LINE_ANALYSIS_SIMPLE_CN_UI
% 中文说明：
% 只画三条 Ra 折线，并把数值同时输出到：
%   1. 命令行
%   2. 可复制结果框
%   3. 独立表格界面
%
% 三条曲线：
%   1. 精确计算 Ra
%   2. 网格法 Ra
%   3. 纯RGB Ra
%
% 使用前提：
% 先运行：
%   1. batch_compare_targets_grid_cn
%   2. calc_pure_rgb_ra_only_cn_v2
%   3. export_ra_compare_merge_pure_rgb_cn_ui_v2
%
% 输入：
%   triangle_grid_lut_output/ra_compare_merge_pure_rgb.csv
%
% 输出：
%   triangle_grid_lut_output/ra_line_compare_simple.png

clear;
clc;

%% Step 0: locate project folders
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = find_project_root(scriptDir, 'guangpu_case_input');
outputDir = fullfile(projectRoot, 'triangle_grid_lut_output');

inputFile = fullfile(outputDir, 'ra_compare_merge_pure_rgb.csv');
outputPng = fullfile(outputDir, 'ra_line_compare_simple.png');

if ~exist(inputFile, 'file')
    error(['没有找到 Ra 对比结果文件：\n%s\n\n' ...
           '请先运行 export_ra_compare_merge_pure_rgb_cn_ui_v2.m。'], inputFile);
end

%% Step 1: read data
T = readtable(inputFile, 'VariableNamingRule', 'preserve');

idx = T.("序号");
exactRa = T.("射线扫描最大_Ra");
gridRa = T.("网格法_Ra");
pureRgbRa = T.("纯RGB_Ra");

%% Step 2: build simple table for output
RaSimpleTable = table( ...
    idx, ...
    exactRa, ...
    gridRa, ...
    pureRgbRa, ...
    exactRa - gridRa, ...
    abs(exactRa - gridRa), ...
    exactRa - pureRgbRa, ...
    abs(exactRa - pureRgbRa), ...
    'VariableNames', { ...
        '序号', ...
        '精确计算_Ra', ...
        '网格法_Ra', ...
        '纯RGB_Ra', ...
        '精确减网格', ...
        '精确网格绝对差', ...
        '精确减纯RGB', ...
        '精确纯RGB绝对差'});

%% Step 3: plot only three curves
fig = figure('Name', 'Ra三线对比：精确计算 / 网格法 / 纯RGB', ...
             'NumberTitle', 'off', ...
             'Position', [80, 80, 1350, 650]);

plot(idx, exactRa, '-o', 'LineWidth', 1.6, 'MarkerSize', 5);
hold on;
plot(idx, gridRa, '-^', 'LineWidth', 1.6, 'MarkerSize', 5);
plot(idx, pureRgbRa, '-s', 'LineWidth', 1.6, 'MarkerSize', 5);
hold off;

grid on;
xlabel('目标颜色序号');
ylabel('Ra');
title('Ra 折线对比：精确计算 Ra / 网格法 Ra / 纯RGB Ra');
legend({'精确计算 Ra', '网格法 Ra', '纯RGB Ra'}, 'Location', 'best');

xlim([min(idx), max(idx)]);
xticks(idx);

saveas(fig, outputPng);

%% Step 4: command window output
fprintf('\n================ Ra 三线数值表 ================\n');
disp(RaSimpleTable);
fprintf('\nRa三线折线图已生成：\n%s\n', outputPng);

%% Step 5: result text box
resultText = make_result_text(RaSimpleTable, outputPng);
show_result_text_window(resultText);

%% Step 6: table UI window
show_result_table_window(RaSimpleTable, outputPng);

drawnow;

%% ================= Local functions =================
function resultText = make_result_text(RaSimpleTable, outputPng)
    n = height(RaSimpleTable);
    lines = strings(n + 8, 1);

    lines(1) = "================ Ra 三线数值结果 ================";
    lines(2) = sprintf("目标点数量：%d", n);
    lines(3) = "列含义：精确计算Ra / 网格法Ra / 纯RGB Ra";
    lines(4) = "--------------------------------------------------------------";
    lines(5) = sprintf("%-4s %-12s %-12s %-12s %-12s %-12s", ...
        "序号", "精确Ra", "网格Ra", "纯RGB", "精确-网格", "精确-纯RGB");
    lines(6) = "--------------------------------------------------------------";

    for i = 1:n
        lines(i + 6) = sprintf("%-4d %-12.4f %-12.4f %-12.4f %-12.4f %-12.4f", ...
            RaSimpleTable.("序号")(i), ...
            RaSimpleTable.("精确计算_Ra")(i), ...
            RaSimpleTable.("网格法_Ra")(i), ...
            RaSimpleTable.("纯RGB_Ra")(i), ...
            RaSimpleTable.("精确减网格")(i), ...
            RaSimpleTable.("精确减纯RGB")(i));
    end

    lines(n + 7) = "--------------------------------------------------------------";
    lines(n + 8) = "图片输出路径：" + string(outputPng);

    resultText = char(strjoin(lines, newline));
end

function show_result_text_window(resultText)
    try
        d = dialog('Name', 'Ra三线数值结果框', ...
                   'Position', [120, 120, 760, 640], ...
                   'WindowStyle', 'normal');

        uicontrol('Parent', d, ...
                  'Style', 'text', ...
                  'String', 'Ra三线数值结果（可复制）', ...
                  'Units', 'normalized', ...
                  'Position', [0.03, 0.94, 0.94, 0.04], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'HorizontalAlignment', 'left');

        uicontrol('Parent', d, ...
                  'Style', 'edit', ...
                  'String', resultText, ...
                  'Units', 'normalized', ...
                  'Position', [0.03, 0.10, 0.94, 0.83], ...
                  'Max', 2, ...
                  'Min', 0, ...
                  'HorizontalAlignment', 'left', ...
                  'FontName', 'Consolas', ...
                  'FontSize', 10);

        uicontrol('Parent', d, ...
                  'Style', 'pushbutton', ...
                  'String', '关闭', ...
                  'Units', 'normalized', ...
                  'Position', [0.43, 0.025, 0.14, 0.05], ...
                  'Callback', @(~,~) close(d));
    catch
        fprintf('\n结果框打开失败，已保留命令行输出。\n');
    end
end

function show_result_table_window(RaSimpleTable, outputPng)
    try
        fig = figure('Name', 'Ra三线数值表格界面', ...
                     'NumberTitle', 'off', ...
                     'MenuBar', 'none', ...
                     'ToolBar', 'none', ...
                     'Color', [0.96, 0.96, 0.96], ...
                     'Position', [100, 90, 1250, 720]);

        uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', 'Ra三线数值表：精确计算 Ra / 网格法 Ra / 纯RGB Ra', ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.94, 0.97, 0.045], ...
            'BackgroundColor', [0.96, 0.96, 0.96], ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left');

        displayData = table_to_uitable_cell(RaSimpleTable);

        uitable('Parent', fig, ...
            'Data', displayData, ...
            'ColumnName', RaSimpleTable.Properties.VariableNames, ...
            'RowName', [], ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.09, 0.97, 0.84], ...
            'FontSize', 10, ...
            'ColumnWidth', {70,110,110,110,110,120,120,130});

        uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', ['图片输出路径：' outputPng], ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.02, 0.97, 0.045], ...
            'BackgroundColor', [0.96, 0.96, 0.96], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
    catch ME
        fprintf('\n表格界面打开失败：%s\n', ME.message);
    end
end

function C = table_to_uitable_cell(T)
    C = table2cell(T);
    for r = 1:size(C, 1)
        for c = 1:size(C, 2)
            value = C{r, c};
            if isstring(value)
                C{r, c} = char(value);
            elseif iscategorical(value)
                C{r, c} = char(value);
            elseif ismissing(value)
                C{r, c} = '';
            elseif isnumeric(value)
                if isscalar(value) && isnan(value)
                    C{r, c} = 'NaN';
                else
                    C{r, c} = value;
                end
            end
        end
    end
end

function projectRoot = find_project_root(startDir, inputFolderName)
    projectRoot = startDir;
    while true
        if exist(fullfile(projectRoot, inputFolderName), 'dir')
            return;
        end

        parentDir = fileparts(projectRoot);
        if strcmp(parentDir, projectRoot)
            error('find_project_root:NotFound', ...
                'Cannot find %s from script folder or its parent folders.', inputFolderName);
        end

        projectRoot = parentDir;
    end
end
