% S05_PLOT_RA_LINE_CURRENT
% 中文说明：
% 与当前模型匹配：
%   输入文件：triangle_grid_lut_output/batch_compare_targets_grid_results.csv
%   当前模型列：
%       Exact_Ra   ：精确法 Ra
%       Grid1_Ra   ：最近1点RGB投影法 Ra
%       Grid_Ra    ：最近K点RGB加权投影法 Ra
%       PureRGB_Ra ：纯RGB Ra
%
% 输出：
%   1. Ra 折线图
%   2. 命令行数值表
%   3. 可复制结果框
%   4. 独立表格界面
%   5. PNG 图片：triangle_grid_lut_output/ra_line_current_model.png

clear;
clc;

%% Step 0: locate project folders
scriptDir = fileparts(mfilename('fullpath'));
projectRoot = find_project_root(scriptDir, 'guangpu_case_input');
outputDir = fullfile(projectRoot, 'triangle_grid_lut_output');

inputFile = fullfile(outputDir, 'batch_compare_targets_grid_results.csv');
outputPng = fullfile(outputDir, 'ra_line_current_model.png');

if ~exist(inputFile, 'file')
    error(['没有找到当前模型结果文件：\n%s\n\n' ...
           '请先运行 s02_projection_rebuild.m 或 run_s02_projection_rebuild.m。'], inputFile);
end

%% Step 1: read data
sourceTable = readtable(inputFile, 'VariableNamingRule', 'preserve');

needCols = {'Index','Target_x','Target_y','Exact_Ra','Grid1_Ra','Grid_Ra','PureRGB_Ra'};
for colIdx = 1:numel(needCols)
    if ~ismember(needCols{colIdx}, sourceTable.Properties.VariableNames)
        error('结果文件缺少列：%s。请确认运行的是当前投影法模型 s02_projection_rebuild。', needCols{colIdx});
    end
end

idx = sourceTable.Index;
targetX = sourceTable.Target_x;
targetY = sourceTable.Target_y;

exactRa = sourceTable.Exact_Ra;
proj1Ra = sourceTable.Grid1_Ra;
projKRa = sourceTable.Grid_Ra;
pureRgbRa = sourceTable.PureRGB_Ra;

%% Step 2: build output table
proj1Diff = exactRa - proj1Ra;
projKDiff = exactRa - projKRa;
pureDiff = exactRa - pureRgbRa;

proj1AbsDiff = abs(proj1Diff);
projKAbsDiff = abs(projKDiff);
pureAbsDiff = abs(pureDiff);

targetXYText = strings(numel(idx), 1);
bestMethodText = strings(numel(idx), 1);

for rowIdx = 1:numel(idx)
    targetXYText(rowIdx) = sprintf('(%.4f, %.4f)', targetX(rowIdx), targetY(rowIdx));

    methodRaList = [proj1Ra(rowIdx), projKRa(rowIdx), pureRgbRa(rowIdx)];
    methodNameList = ["投影1点", "投影K点", "纯RGB"];
    validMask = isfinite(methodRaList);

    if any(validMask)
        validRaList = methodRaList(validMask);
        validNameList = methodNameList(validMask);
        [~, bestIdx] = max(validRaList);
        bestMethodText(rowIdx) = validNameList(bestIdx);
    else
        bestMethodText(rowIdx) = "无有效近似法";
    end
end

raCompareTable = table( ...
    idx, ...
    targetXYText, ...
    exactRa, ...
    proj1Ra, ...
    proj1Diff, ...
    proj1AbsDiff, ...
    projKRa, ...
    projKDiff, ...
    projKAbsDiff, ...
    pureRgbRa, ...
    pureDiff, ...
    pureAbsDiff, ...
    bestMethodText, ...
    'VariableNames', { ...
        '序号', ...
        '目标xy', ...
        '精确法_Ra', ...
        '投影1点_Ra', ...
        '精确减投影1点', ...
        '投影1点绝对误差', ...
        '投影K点_Ra', ...
        '精确减投影K点', ...
        '投影K点绝对误差', ...
        '纯RGB_Ra', ...
        '精确减纯RGB', ...
        '纯RGB绝对误差', ...
        '近似法中Ra最高'});

%% Step 3: plot current model curves
fig = figure('Name', '当前模型 Ra 对比：精确法 / 投影1点 / 投影K点 / 纯RGB', ...
             'NumberTitle', 'off', ...
             'Position', [80, 80, 1400, 680]);

plot(idx, exactRa, '-o', 'LineWidth', 1.7, 'MarkerSize', 5);
hold on;
plot(idx, proj1Ra, '-d', 'LineWidth', 1.5, 'MarkerSize', 5);
plot(idx, projKRa, '-^', 'LineWidth', 1.5, 'MarkerSize', 5);
plot(idx, pureRgbRa, '-s', 'LineWidth', 1.5, 'MarkerSize', 5);
hold off;

grid on;
xlabel('目标颜色序号');
ylabel('Ra');
title('当前模型 Ra 折线对比：精确法 / 投影1点 / 投影K点 / 纯RGB');
legend({'精确法 Ra', '投影1点 Ra', '投影K点 Ra', '纯RGB Ra'}, 'Location', 'best');

xlim([min(idx), max(idx)]);
xticks(idx);

saveas(fig, outputPng);

%% Step 4: command window output
fprintf('\n================ 当前模型 Ra 数值表 ================\n');
disp(raCompareTable);
fprintf('\n当前模型 Ra 折线图已生成：\n%s\n', outputPng);

%% Step 5: result text box
resultText = make_result_text(raCompareTable, outputPng);
show_result_text_window(resultText);

%% Step 6: table UI window
show_result_table_window(raCompareTable, outputPng);

drawnow;

%% ================= Local functions =================
function resultText = make_result_text(raCompareTable, outputPng)
    rowCount = height(raCompareTable);
    lines = strings(rowCount + 8, 1);

    lines(1) = "================ 当前模型 Ra 数值结果 ================";
    lines(2) = sprintf("目标点数量：%d", rowCount);
    lines(3) = "列含义：精确法 / 投影1点 / 投影K点 / 纯RGB";
    lines(4) = "误差含义：精确法Ra - 对应方法Ra";
    lines(5) = "--------------------------------------------------------------------------------";
    lines(6) = sprintf("%-4s %-10s %-10s %-10s %-10s %-10s %-10s", ...
        "序号", "精确Ra", "投影1点", "投影K点", "纯RGB", "K点误差", "最高近似");

    for rowIdx = 1:rowCount
        lines(rowIdx + 6) = sprintf("%-4d %-10.4f %-10.4f %-10.4f %-10.4f %-10.4f %s", ...
            raCompareTable.("序号")(rowIdx), ...
            raCompareTable.("精确法_Ra")(rowIdx), ...
            raCompareTable.("投影1点_Ra")(rowIdx), ...
            raCompareTable.("投影K点_Ra")(rowIdx), ...
            raCompareTable.("纯RGB_Ra")(rowIdx), ...
            raCompareTable.("精确减投影K点")(rowIdx), ...
            char(string(raCompareTable.("近似法中Ra最高")(rowIdx))));
    end

    lines(rowCount + 7) = "--------------------------------------------------------------------------------";
    lines(rowCount + 8) = "图片输出路径：" + string(outputPng);

    resultText = char(strjoin(lines, newline));
end

function show_result_text_window(resultText)
    try
        d = dialog('Name', '当前模型Ra结果框', ...
                   'Position', [120, 120, 860, 660], ...
                   'WindowStyle', 'normal');

        uicontrol('Parent', d, ...
                  'Style', 'text', ...
                  'String', '当前模型Ra结果（可复制）', ...
                  'Units', 'normalized', ...
                  'Position', [0.03, 0.94, 0.94, 0.04], ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold', ...
                  'HorizontalAlignment', 'left');

        uicontrol('Parent', d, ...
                  'Style', 'edit', ...
                  'String', resultText, ...
                  'Units', 'normalized', ...
                  'Position', [0.03, 0.10, 0.94, 0.83], ...
                  'Max', 2, ...
                  'Min', 0, ...
                  'HorizontalAlignment', 'left', ...
                  'FontName', 'Consolas', ...
                  'FontSize', 10);

        uicontrol('Parent', d, ...
                  'Style', 'pushbutton', ...
                  'String', '关闭', ...
                  'Units', 'normalized', ...
                  'Position', [0.43, 0.025, 0.14, 0.05], ...
                  'Callback', @(~,~) close(d));
    catch
        fprintf('\n结果框打开失败，已保留命令行输出。\n');
    end
end

function show_result_table_window(raCompareTable, outputPng)
    try
        fig = figure('Name', '当前模型Ra数值表格界面', ...
                     'NumberTitle', 'off', ...
                     'MenuBar', 'none', ...
                     'ToolBar', 'none', ...
                     'Color', [0.96, 0.96, 0.96], ...
                     'Position', [70, 80, 1550, 740]);

        uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', '当前模型Ra数值表：精确法 / 投影1点 / 投影K点 / 纯RGB', ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.94, 0.97, 0.045], ...
            'BackgroundColor', [0.96, 0.96, 0.96], ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'left');

        displayData = table_to_uitable_cell(raCompareTable);

        uitable('Parent', fig, ...
            'Data', displayData, ...
            'ColumnName', raCompareTable.Properties.VariableNames, ...
            'RowName', [], ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.09, 0.97, 0.84], ...
            'FontSize', 10, ...
            'ColumnWidth', {55,110,95,95,110,125,95,110,125,95,110,125,130});

        uicontrol('Parent', fig, ...
            'Style', 'text', ...
            'String', ['图片输出路径：' outputPng], ...
            'Units', 'normalized', ...
            'Position', [0.015, 0.02, 0.97, 0.045], ...
            'BackgroundColor', [0.96, 0.96, 0.96], ...
            'FontSize', 9, ...
            'HorizontalAlignment', 'left');
    catch ME
        fprintf('\n表格界面打开失败：%s\n', ME.message);
    end
end

function C = table_to_uitable_cell(T)
    C = table2cell(T);
    for r = 1:size(C, 1)
        for c = 1:size(C, 2)
            value = C{r, c};
            if isstring(value)
                C{r, c} = char(value);
            elseif iscategorical(value)
                C{r, c} = char(value);
            elseif ismissing(value)
                C{r, c} = '';
            elseif isnumeric(value)
                if isscalar(value) && isnan(value)
                    C{r, c} = 'NaN';
                else
                    C{r, c} = value;
                end
            end
        end
    end
end

function projectRoot = find_project_root(startDir, inputFolderName)
    projectRoot = startDir;
    while true
        if exist(fullfile(projectRoot, inputFolderName), 'dir')
            return;
        end

        parentDir = fileparts(projectRoot);
        if strcmp(parentDir, projectRoot)
            error('find_project_root:NotFound', ...
                'Cannot find %s from script folder or its parent folders.', inputFolderName);
        end

        projectRoot = parentDir;
    end
end
