/*********************************************************************************
 * FileName:    AlgoRatioK.c
 * Description: Auto-generated by test/s06_export_ratioK_packed32.m
 *              32-bit packed K-point white-ratio lookup module.
 *
 * Packed LUT:
 *   bit[ 0: 9] = U,      10 bit, u' * 1000
 *   bit[10:19] = V,      10 bit, v' * 1000
 *   bit[20:31] = ratio,  12 bit, whiteRatio * 4095
 **********************************************************************************/

#include "AlgoRatioK.h"

#define ALGO_RATIO_K_LUT_COUNT           (325u)

#define ALGO_RATIO_K_U_MASK              (0x000003FFu)
#define ALGO_RATIO_K_V_MASK              (0x000FFC00u)
#define ALGO_RATIO_K_RATIO_MASK          (0xFFF00000u)

#define ALGO_RATIO_K_V_SHIFT             (10u)
#define ALGO_RATIO_K_RATIO_SHIFT         (20u)

#define ALGO_RATIO_K_RATIO12_MAX         (4095u)
#define ALGO_RATIO_K_RATIO_Q10000_MAX    (10000u)
#define ALGO_RATIO_K_DISTANCE_MAX        (0xFFFFFFFFu)

#ifndef ALGO_RATIO_K_USE_WEIGHT
#define ALGO_RATIO_K_USE_WEIGHT          (1u)
#endif

#define ALGO_RATIO_K_WEIGHT_SCALE        (32768u)

#if (ALGO_RATIO_K_AMOUNT == 0u)
#error "ALGO_RATIO_K_AMOUNT must be greater than 0."
#endif

#if (ALGO_RATIO_K_AMOUNT > 12u)
#error "ALGO_RATIO_K_AMOUNT > 12 may overflow uint32 weighted sum."
#endif

#define ALGO_RATIO_K_PACK(U_, V_, RATIO12_) \
    ((((uint32_t)(RATIO12_) & 0xFFFu) << ALGO_RATIO_K_RATIO_SHIFT) | \
     (((uint32_t)(V_)       & 0x3FFu) << ALGO_RATIO_K_V_SHIFT) | \
     (((uint32_t)(U_)       & 0x3FFu)))

static const uint32_t g_algoRatioKPackedLut[ALGO_RATIO_K_LUT_COUNT] =
{
    ALGO_RATIO_K_PACK( 200u,   85u,    0u),  /* idx=  0, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 194u,  105u,    0u),  /* idx=  1, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 187u,  125u,    0u),  /* idx=  2, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 181u,  145u,    0u),  /* idx=  3, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 175u,  166u,    0u),  /* idx=  4, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 169u,  186u,    0u),  /* idx=  5, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 162u,  206u,    0u),  /* idx=  6, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 156u,  226u,    0u),  /* idx=  7, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 150u,  246u,    0u),  /* idx=  8, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 143u,  267u,    0u),  /* idx=  9, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 137u,  287u,    0u),  /* idx= 10, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 131u,  307u,    0u),  /* idx= 11, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 125u,  327u,    0u),  /* idx= 12, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 118u,  347u,    0u),  /* idx= 13, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 112u,  367u,    0u),  /* idx= 14, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 106u,  388u,    0u),  /* idx= 15, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 100u,  408u,    0u),  /* idx= 16, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  93u,  428u,    0u),  /* idx= 17, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  87u,  448u,    0u),  /* idx= 18, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  81u,  468u,    0u),  /* idx= 19, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  75u,  488u,    0u),  /* idx= 20, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  68u,  509u,    0u),  /* idx= 21, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  62u,  529u,    0u),  /* idx= 22, ratio=-0.000000 */
    ALGO_RATIO_K_PACK(  56u,  549u,    0u),  /* idx= 23, ratio=-0.000000 */
    ALGO_RATIO_K_PACK(  50u,  569u,    0u),  /* idx= 24, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 214u,  103u,    0u),  /* idx= 25, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 208u,  123u,    0u),  /* idx= 26, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 202u,  143u,    0u),  /* idx= 27, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 195u,  164u,    0u),  /* idx= 28, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 189u,  184u,    0u),  /* idx= 29, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 183u,  204u,    0u),  /* idx= 30, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 177u,  224u,    0u),  /* idx= 31, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 170u,  244u,    0u),  /* idx= 32, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 164u,  264u,    0u),  /* idx= 33, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 158u,  285u,    0u),  /* idx= 34, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 152u,  305u,    0u),  /* idx= 35, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 145u,  325u,    0u),  /* idx= 36, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 139u,  345u,    0u),  /* idx= 37, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 133u,  365u,    0u),  /* idx= 38, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 127u,  385u,    0u),  /* idx= 39, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 120u,  406u,    0u),  /* idx= 40, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 114u,  426u,    0u),  /* idx= 41, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 108u,  446u,    0u),  /* idx= 42, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 102u,  466u,    0u),  /* idx= 43, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  95u,  486u,    0u),  /* idx= 44, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  89u,  506u,    0u),  /* idx= 45, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  83u,  527u,    0u),  /* idx= 46, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  76u,  547u,    0u),  /* idx= 47, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  70u,  567u,    0u),  /* idx= 48, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 229u,  121u,    0u),  /* idx= 49, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 222u,  141u, 1002u),  /* idx= 50, ratio=0.244621 */
    ALGO_RATIO_K_PACK( 216u,  161u, 1753u),  /* idx= 51, ratio=0.428093 */
    ALGO_RATIO_K_PACK( 210u,  182u, 1829u),  /* idx= 52, ratio=0.446664 */
    ALGO_RATIO_K_PACK( 204u,  202u, 1620u),  /* idx= 53, ratio=0.395713 */
    ALGO_RATIO_K_PACK( 197u,  222u, 1439u),  /* idx= 54, ratio=0.351416 */
    ALGO_RATIO_K_PACK( 191u,  242u, 1263u),  /* idx= 55, ratio=0.308411 */
    ALGO_RATIO_K_PACK( 185u,  262u, 1090u),  /* idx= 56, ratio=0.266099 */
    ALGO_RATIO_K_PACK( 179u,  282u,  938u),  /* idx= 57, ratio=0.229085 */
    ALGO_RATIO_K_PACK( 172u,  303u,  821u),  /* idx= 58, ratio=0.200487 */
    ALGO_RATIO_K_PACK( 166u,  323u,  743u),  /* idx= 59, ratio=0.181373 */
    ALGO_RATIO_K_PACK( 160u,  343u,  695u),  /* idx= 60, ratio=0.169780 */
    ALGO_RATIO_K_PACK( 154u,  363u,  678u),  /* idx= 61, ratio=0.165454 */
    ALGO_RATIO_K_PACK( 147u,  383u,  631u),  /* idx= 62, ratio=0.154120 */
    ALGO_RATIO_K_PACK( 141u,  403u,  600u),  /* idx= 63, ratio=0.146534 */
    ALGO_RATIO_K_PACK( 135u,  424u,  566u),  /* idx= 64, ratio=0.138326 */
    ALGO_RATIO_K_PACK( 128u,  444u,  462u),  /* idx= 65, ratio=0.112897 */
    ALGO_RATIO_K_PACK( 122u,  464u,  286u),  /* idx= 66, ratio=0.069926 */
    ALGO_RATIO_K_PACK( 116u,  484u,  121u),  /* idx= 67, ratio=0.029630 */
    ALGO_RATIO_K_PACK( 110u,  504u,    0u),  /* idx= 68, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 103u,  525u,    0u),  /* idx= 69, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  97u,  545u,    0u),  /* idx= 70, ratio=0.000000 */
    ALGO_RATIO_K_PACK(  91u,  565u,    0u),  /* idx= 71, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 243u,  139u,    0u),  /* idx= 72, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 237u,  159u,  888u),  /* idx= 73, ratio=0.216916 */
    ALGO_RATIO_K_PACK( 231u,  179u, 1577u),  /* idx= 74, ratio=0.385059 */
    ALGO_RATIO_K_PACK( 224u,  200u, 2126u),  /* idx= 75, ratio=0.519216 */
    ALGO_RATIO_K_PACK( 218u,  220u, 2575u),  /* idx= 76, ratio=0.628745 */
    ALGO_RATIO_K_PACK( 212u,  240u, 2948u),  /* idx= 77, ratio=0.719859 */
    ALGO_RATIO_K_PACK( 206u,  260u, 2893u),  /* idx= 78, ratio=0.706381 */
    ALGO_RATIO_K_PACK( 199u,  280u, 2695u),  /* idx= 79, ratio=0.658166 */
    ALGO_RATIO_K_PACK( 193u,  300u, 2525u),  /* idx= 80, ratio=0.616663 */
    ALGO_RATIO_K_PACK( 187u,  321u, 2364u),  /* idx= 81, ratio=0.577191 */
    ALGO_RATIO_K_PACK( 180u,  341u, 2186u),  /* idx= 82, ratio=0.533715 */
    ALGO_RATIO_K_PACK( 174u,  361u, 2031u),  /* idx= 83, ratio=0.495995 */
    ALGO_RATIO_K_PACK( 168u,  381u, 1922u),  /* idx= 84, ratio=0.469325 */
    ALGO_RATIO_K_PACK( 162u,  401u, 1836u),  /* idx= 85, ratio=0.448405 */
    ALGO_RATIO_K_PACK( 155u,  422u, 1744u),  /* idx= 86, ratio=0.425813 */
    ALGO_RATIO_K_PACK( 149u,  442u, 1529u),  /* idx= 87, ratio=0.373308 */
    ALGO_RATIO_K_PACK( 143u,  462u, 1302u),  /* idx= 88, ratio=0.317901 */
    ALGO_RATIO_K_PACK( 137u,  482u, 1088u),  /* idx= 89, ratio=0.265706 */
    ALGO_RATIO_K_PACK( 130u,  502u,  877u),  /* idx= 90, ratio=0.214099 */
    ALGO_RATIO_K_PACK( 124u,  522u,  645u),  /* idx= 91, ratio=0.157451 */
    ALGO_RATIO_K_PACK( 118u,  543u,  375u),  /* idx= 92, ratio=0.091554 */
    ALGO_RATIO_K_PACK( 112u,  563u,    0u),  /* idx= 93, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 258u,  157u,    0u),  /* idx= 94, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 251u,  177u,  798u),  /* idx= 95, ratio=0.194848 */
    ALGO_RATIO_K_PACK( 245u,  197u, 1433u),  /* idx= 96, ratio=0.349886 */
    ALGO_RATIO_K_PACK( 239u,  218u, 1950u),  /* idx= 97, ratio=0.476185 */
    ALGO_RATIO_K_PACK( 232u,  238u, 2379u),  /* idx= 98, ratio=0.581057 */
    ALGO_RATIO_K_PACK( 226u,  258u, 2742u),  /* idx= 99, ratio=0.669529 */
    ALGO_RATIO_K_PACK( 220u,  278u, 3051u),  /* idx=100, ratio=0.745169 */
    ALGO_RATIO_K_PACK( 214u,  298u, 3319u),  /* idx=101, ratio=0.810580 */
    ALGO_RATIO_K_PACK( 207u,  319u, 3553u),  /* idx=102, ratio=0.867705 */
    ALGO_RATIO_K_PACK( 201u,  339u, 3521u),  /* idx=103, ratio=0.859924 */
    ALGO_RATIO_K_PACK( 195u,  359u, 3337u),  /* idx=104, ratio=0.815009 */
    ALGO_RATIO_K_PACK( 189u,  379u, 3183u),  /* idx=105, ratio=0.777328 */
    ALGO_RATIO_K_PACK( 182u,  399u, 3043u),  /* idx=106, ratio=0.743076 */
    ALGO_RATIO_K_PACK( 176u,  419u, 2837u),  /* idx=107, ratio=0.692768 */
    ALGO_RATIO_K_PACK( 170u,  440u, 2558u),  /* idx=108, ratio=0.624752 */
    ALGO_RATIO_K_PACK( 164u,  460u, 2283u),  /* idx=109, ratio=0.557578 */
    ALGO_RATIO_K_PACK( 157u,  480u, 2020u),  /* idx=110, ratio=0.493359 */
    ALGO_RATIO_K_PACK( 151u,  500u, 1765u),  /* idx=111, ratio=0.430916 */
    ALGO_RATIO_K_PACK( 145u,  520u, 1490u),  /* idx=112, ratio=0.363813 */
    ALGO_RATIO_K_PACK( 138u,  540u,  987u),  /* idx=113, ratio=0.241059 */
    ALGO_RATIO_K_PACK( 132u,  561u,    0u),  /* idx=114, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 272u,  175u,    0u),  /* idx=115, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 266u,  195u,  724u),  /* idx=116, ratio=0.176855 */
    ALGO_RATIO_K_PACK( 259u,  216u, 1313u),  /* idx=117, ratio=0.320602 */
    ALGO_RATIO_K_PACK( 253u,  236u, 1801u),  /* idx=118, ratio=0.439741 */
    ALGO_RATIO_K_PACK( 247u,  256u, 2212u),  /* idx=119, ratio=0.540093 */
    ALGO_RATIO_K_PACK( 241u,  276u, 2563u),  /* idx=120, ratio=0.625777 */
    ALGO_RATIO_K_PACK( 234u,  296u, 2866u),  /* idx=121, ratio=0.699791 */
    ALGO_RATIO_K_PACK( 228u,  316u, 3130u),  /* idx=122, ratio=0.764365 */
    ALGO_RATIO_K_PACK( 222u,  337u, 3363u),  /* idx=123, ratio=0.821199 */
    ALGO_RATIO_K_PACK( 216u,  357u, 3569u),  /* idx=124, ratio=0.871604 */
    ALGO_RATIO_K_PACK( 209u,  377u, 3754u),  /* idx=125, ratio=0.916614 */
    ALGO_RATIO_K_PACK( 203u,  397u, 3885u),  /* idx=126, ratio=0.948757 */
    ALGO_RATIO_K_PACK( 197u,  417u, 3697u),  /* idx=127, ratio=0.902886 */
    ALGO_RATIO_K_PACK( 190u,  437u, 3527u),  /* idx=128, ratio=0.861246 */
    ALGO_RATIO_K_PACK( 184u,  458u, 3198u),  /* idx=129, ratio=0.780842 */
    ALGO_RATIO_K_PACK( 178u,  478u, 2894u),  /* idx=130, ratio=0.706776 */
    ALGO_RATIO_K_PACK( 172u,  498u, 2601u),  /* idx=131, ratio=0.635055 */
    ALGO_RATIO_K_PACK( 165u,  518u, 2059u),  /* idx=132, ratio=0.502876 */
    ALGO_RATIO_K_PACK( 159u,  538u,  991u),  /* idx=133, ratio=0.242015 */
    ALGO_RATIO_K_PACK( 153u,  558u,    0u),  /* idx=134, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 286u,  193u,    0u),  /* idx=135, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 280u,  213u,  663u),  /* idx=136, ratio=0.161905 */
    ALGO_RATIO_K_PACK( 274u,  234u, 1211u),  /* idx=137, ratio=0.295841 */
    ALGO_RATIO_K_PACK( 268u,  254u, 1673u),  /* idx=138, ratio=0.408478 */
    ALGO_RATIO_K_PACK( 261u,  274u, 2066u),  /* idx=139, ratio=0.504524 */
    ALGO_RATIO_K_PACK( 255u,  294u, 2405u),  /* idx=140, ratio=0.587393 */
    ALGO_RATIO_K_PACK( 249u,  314u, 2701u),  /* idx=141, ratio=0.659622 */
    ALGO_RATIO_K_PACK( 242u,  334u, 2961u),  /* idx=142, ratio=0.723137 */
    ALGO_RATIO_K_PACK( 236u,  355u, 3192u),  /* idx=143, ratio=0.779425 */
    ALGO_RATIO_K_PACK( 230u,  375u, 3397u),  /* idx=144, ratio=0.829653 */
    ALGO_RATIO_K_PACK( 224u,  395u, 3582u),  /* idx=145, ratio=0.874749 */
    ALGO_RATIO_K_PACK( 217u,  415u, 3749u),  /* idx=146, ratio=0.915463 */
    ALGO_RATIO_K_PACK( 211u,  435u, 3900u),  /* idx=147, ratio=0.952403 */
    ALGO_RATIO_K_PACK( 205u,  455u, 4038u),  /* idx=148, ratio=0.986071 */
    ALGO_RATIO_K_PACK( 199u,  476u, 3650u),  /* idx=149, ratio=0.891245 */
    ALGO_RATIO_K_PACK( 192u,  496u, 3228u),  /* idx=150, ratio=0.788254 */
    ALGO_RATIO_K_PACK( 186u,  516u, 2068u),  /* idx=151, ratio=0.504957 */
    ALGO_RATIO_K_PACK( 180u,  536u,  995u),  /* idx=152, ratio=0.242979 */
    ALGO_RATIO_K_PACK( 174u,  556u,    0u),  /* idx=153, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 301u,  211u,    0u),  /* idx=154, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 294u,  231u,  611u),  /* idx=155, ratio=0.149285 */
    ALGO_RATIO_K_PACK( 288u,  252u, 1125u),  /* idx=156, ratio=0.274630 */
    ALGO_RATIO_K_PACK( 282u,  272u, 1562u),  /* idx=157, ratio=0.381366 */
    ALGO_RATIO_K_PACK( 276u,  292u, 1938u),  /* idx=158, ratio=0.473351 */
    ALGO_RATIO_K_PACK( 269u,  312u, 2266u),  /* idx=159, ratio=0.553445 */
    ALGO_RATIO_K_PACK( 263u,  332u, 2555u),  /* idx=160, ratio=0.623814 */
    ALGO_RATIO_K_PACK( 257u,  352u, 2810u),  /* idx=161, ratio=0.686128 */
    ALGO_RATIO_K_PACK( 251u,  373u, 3037u),  /* idx=162, ratio=0.741695 */
    ALGO_RATIO_K_PACK( 244u,  393u, 3241u),  /* idx=163, ratio=0.791554 */
    ALGO_RATIO_K_PACK( 238u,  413u, 3426u),  /* idx=164, ratio=0.836542 */
    ALGO_RATIO_K_PACK( 232u,  433u, 3593u),  /* idx=165, ratio=0.877340 */
    ALGO_RATIO_K_PACK( 226u,  453u, 3745u),  /* idx=166, ratio=0.914506 */
    ALGO_RATIO_K_PACK( 219u,  473u, 3884u),  /* idx=167, ratio=0.948506 */
    ALGO_RATIO_K_PACK( 213u,  494u, 3242u),  /* idx=168, ratio=0.791663 */
    ALGO_RATIO_K_PACK( 207u,  514u, 2076u),  /* idx=169, ratio=0.507055 */
    ALGO_RATIO_K_PACK( 200u,  534u,  999u),  /* idx=170, ratio=0.243950 */
    ALGO_RATIO_K_PACK( 194u,  554u,    0u),  /* idx=171, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 315u,  229u,    0u),  /* idx=172, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 309u,  249u,  567u),  /* idx=173, ratio=0.138490 */
    ALGO_RATIO_K_PACK( 303u,  270u, 1049u),  /* idx=174, ratio=0.256257 */
    ALGO_RATIO_K_PACK( 296u,  290u, 1464u),  /* idx=175, ratio=0.357629 */
    ALGO_RATIO_K_PACK( 290u,  310u, 1826u),  /* idx=176, ratio=0.445806 */
    ALGO_RATIO_K_PACK( 284u,  330u, 2143u),  /* idx=177, ratio=0.523207 */
    ALGO_RATIO_K_PACK( 278u,  350u, 2423u),  /* idx=178, ratio=0.591694 */
    ALGO_RATIO_K_PACK( 271u,  370u, 2673u),  /* idx=179, ratio=0.652723 */
    ALGO_RATIO_K_PACK( 265u,  391u, 2897u),  /* idx=180, ratio=0.707449 */
    ALGO_RATIO_K_PACK( 259u,  411u, 3099u),  /* idx=181, ratio=0.756800 */
    ALGO_RATIO_K_PACK( 252u,  431u, 3282u),  /* idx=182, ratio=0.801532 */
    ALGO_RATIO_K_PACK( 246u,  451u, 3449u),  /* idx=183, ratio=0.842264 */
    ALGO_RATIO_K_PACK( 240u,  471u, 3602u),  /* idx=184, ratio=0.879510 */
    ALGO_RATIO_K_PACK( 234u,  492u, 3256u),  /* idx=185, ratio=0.795102 */
    ALGO_RATIO_K_PACK( 227u,  512u, 2085u),  /* idx=186, ratio=0.509171 */
    ALGO_RATIO_K_PACK( 221u,  532u, 1003u),  /* idx=187, ratio=0.244930 */
    ALGO_RATIO_K_PACK( 215u,  552u,    0u),  /* idx=188, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 330u,  247u,    0u),  /* idx=189, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 323u,  267u,  529u),  /* idx=190, ratio=0.129151 */
    ALGO_RATIO_K_PACK( 317u,  288u,  984u),  /* idx=191, ratio=0.240189 */
    ALGO_RATIO_K_PACK( 311u,  308u, 1379u),  /* idx=192, ratio=0.336673 */
    ALGO_RATIO_K_PACK( 304u,  328u, 1725u),  /* idx=193, ratio=0.421290 */
    ALGO_RATIO_K_PACK( 298u,  348u, 2032u),  /* idx=194, ratio=0.496102 */
    ALGO_RATIO_K_PACK( 292u,  368u, 2304u),  /* idx=195, ratio=0.562720 */
    ALGO_RATIO_K_PACK( 286u,  389u, 2549u),  /* idx=196, ratio=0.622419 */
    ALGO_RATIO_K_PACK( 279u,  409u, 2769u),  /* idx=197, ratio=0.676226 */
    ALGO_RATIO_K_PACK( 273u,  429u, 2969u),  /* idx=198, ratio=0.724970 */
    ALGO_RATIO_K_PACK( 267u,  449u, 3150u),  /* idx=199, ratio=0.769336 */
    ALGO_RATIO_K_PACK( 261u,  469u, 3316u),  /* idx=200, ratio=0.809886 */
    ALGO_RATIO_K_PACK( 254u,  489u, 3270u),  /* idx=201, ratio=0.798571 */
    ALGO_RATIO_K_PACK( 248u,  510u, 2094u),  /* idx=202, ratio=0.511304 */
    ALGO_RATIO_K_PACK( 242u,  530u, 1007u),  /* idx=203, ratio=0.245917 */
    ALGO_RATIO_K_PACK( 236u,  550u,    0u),  /* idx=204, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 344u,  265u,    0u),  /* idx=205, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 338u,  286u,  495u),  /* idx=206, ratio=0.120992 */
    ALGO_RATIO_K_PACK( 331u,  306u,  926u),  /* idx=207, ratio=0.226017 */
    ALGO_RATIO_K_PACK( 325u,  326u, 1302u),  /* idx=208, ratio=0.318038 */
    ALGO_RATIO_K_PACK( 319u,  346u, 1635u),  /* idx=209, ratio=0.399330 */
    ALGO_RATIO_K_PACK( 313u,  366u, 1931u),  /* idx=210, ratio=0.471667 */
    ALGO_RATIO_K_PACK( 306u,  386u, 2197u),  /* idx=211, ratio=0.536450 */
    ALGO_RATIO_K_PACK( 300u,  407u, 2436u),  /* idx=212, ratio=0.594805 */
    ALGO_RATIO_K_PACK( 294u,  427u, 2652u),  /* idx=213, ratio=0.647642 */
    ALGO_RATIO_K_PACK( 288u,  447u, 2849u),  /* idx=214, ratio=0.695710 */
    ALGO_RATIO_K_PACK( 281u,  467u, 3029u),  /* idx=215, ratio=0.739625 */
    ALGO_RATIO_K_PACK( 275u,  487u, 3194u),  /* idx=216, ratio=0.779905 */
    ALGO_RATIO_K_PACK( 269u,  507u, 2103u),  /* idx=217, ratio=0.513456 */
    ALGO_RATIO_K_PACK( 262u,  528u, 1011u),  /* idx=218, ratio=0.246912 */
    ALGO_RATIO_K_PACK( 256u,  548u,    0u),  /* idx=219, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 358u,  283u,    0u),  /* idx=220, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 352u,  304u,  466u),  /* idx=221, ratio=0.113803 */
    ALGO_RATIO_K_PACK( 346u,  324u,  874u),  /* idx=222, ratio=0.213424 */
    ALGO_RATIO_K_PACK( 340u,  344u, 1234u),  /* idx=223, ratio=0.301357 */
    ALGO_RATIO_K_PACK( 333u,  364u, 1554u),  /* idx=224, ratio=0.379546 */
    ALGO_RATIO_K_PACK( 327u,  384u, 1841u),  /* idx=225, ratio=0.449526 */
    ALGO_RATIO_K_PACK( 321u,  404u, 2099u),  /* idx=226, ratio=0.512524 */
    ALGO_RATIO_K_PACK( 314u,  425u, 2332u),  /* idx=227, ratio=0.569537 */
    ALGO_RATIO_K_PACK( 308u,  445u, 2545u),  /* idx=228, ratio=0.621377 */
    ALGO_RATIO_K_PACK( 302u,  465u, 2738u),  /* idx=229, ratio=0.668720 */
    ALGO_RATIO_K_PACK( 296u,  485u, 2916u),  /* idx=230, ratio=0.712125 */
    ALGO_RATIO_K_PACK( 289u,  505u, 2111u),  /* idx=231, ratio=0.515625 */
    ALGO_RATIO_K_PACK( 283u,  525u, 1015u),  /* idx=232, ratio=0.247915 */
    ALGO_RATIO_K_PACK( 277u,  546u,    0u),  /* idx=233, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 373u,  301u,    0u),  /* idx=234, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 366u,  322u,  440u),  /* idx=235, ratio=0.107420 */
    ALGO_RATIO_K_PACK( 360u,  342u,  828u),  /* idx=236, ratio=0.202160 */
    ALGO_RATIO_K_PACK( 354u,  362u, 1173u),  /* idx=237, ratio=0.286339 */
    ALGO_RATIO_K_PACK( 348u,  382u, 1481u),  /* idx=238, ratio=0.361630 */
    ALGO_RATIO_K_PACK( 341u,  402u, 1758u),  /* idx=239, ratio=0.429370 */
    ALGO_RATIO_K_PACK( 335u,  422u, 2009u),  /* idx=240, ratio=0.490641 */
    ALGO_RATIO_K_PACK( 329u,  443u, 2237u),  /* idx=241, ratio=0.546328 */
    ALGO_RATIO_K_PACK( 323u,  463u, 2445u),  /* idx=242, ratio=0.597160 */
    ALGO_RATIO_K_PACK( 316u,  483u, 2636u),  /* idx=243, ratio=0.643745 */
    ALGO_RATIO_K_PACK( 310u,  503u, 2120u),  /* idx=244, ratio=0.517813 */
    ALGO_RATIO_K_PACK( 304u,  523u, 1019u),  /* idx=245, ratio=0.248927 */
    ALGO_RATIO_K_PACK( 298u,  544u,    0u),  /* idx=246, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 387u,  319u,    0u),  /* idx=247, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 381u,  340u,  417u),  /* idx=248, ratio=0.101715 */
    ALGO_RATIO_K_PACK( 375u,  360u,  786u),  /* idx=249, ratio=0.192025 */
    ALGO_RATIO_K_PACK( 368u,  380u, 1117u),  /* idx=250, ratio=0.272746 */
    ALGO_RATIO_K_PACK( 362u,  400u, 1414u),  /* idx=251, ratio=0.345329 */
    ALGO_RATIO_K_PACK( 356u,  420u, 1683u),  /* idx=252, ratio=0.410945 */
    ALGO_RATIO_K_PACK( 350u,  441u, 1927u),  /* idx=253, ratio=0.470551 */
    ALGO_RATIO_K_PACK( 343u,  461u, 2150u),  /* idx=254, ratio=0.524936 */
    ALGO_RATIO_K_PACK( 337u,  481u, 2354u),  /* idx=255, ratio=0.574759 */
    ALGO_RATIO_K_PACK( 331u,  501u, 2129u),  /* idx=256, ratio=0.520020 */
    ALGO_RATIO_K_PACK( 325u,  521u, 1024u),  /* idx=257, ratio=0.249946 */
    ALGO_RATIO_K_PACK( 318u,  541u,    0u),  /* idx=258, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 402u,  338u,    0u),  /* idx=259, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 395u,  358u,  396u),  /* idx=260, ratio=0.096586 */
    ALGO_RATIO_K_PACK( 389u,  378u,  749u),  /* idx=261, ratio=0.182858 */
    ALGO_RATIO_K_PACK( 383u,  398u, 1066u),  /* idx=262, ratio=0.260386 */
    ALGO_RATIO_K_PACK( 377u,  418u, 1353u),  /* idx=263, ratio=0.330434 */
    ALGO_RATIO_K_PACK( 370u,  438u, 1614u),  /* idx=264, ratio=0.394035 */
    ALGO_RATIO_K_PACK( 364u,  459u, 1851u),  /* idx=265, ratio=0.452041 */
    ALGO_RATIO_K_PACK( 358u,  479u, 2069u),  /* idx=266, ratio=0.505157 */
    ALGO_RATIO_K_PACK( 351u,  499u, 2139u),  /* idx=267, ratio=0.522245 */
    ALGO_RATIO_K_PACK( 345u,  519u, 1028u),  /* idx=268, ratio=0.250974 */
    ALGO_RATIO_K_PACK( 339u,  539u,    0u),  /* idx=269, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 416u,  356u,    0u),  /* idx=270, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 410u,  376u,  377u),  /* idx=271, ratio=0.091949 */
    ALGO_RATIO_K_PACK( 403u,  396u,  715u),  /* idx=272, ratio=0.174527 */
    ALGO_RATIO_K_PACK( 397u,  416u, 1020u),  /* idx=273, ratio=0.249097 */
    ALGO_RATIO_K_PACK( 391u,  436u, 1297u),  /* idx=274, ratio=0.316771 */
    ALGO_RATIO_K_PACK( 385u,  456u, 1550u),  /* idx=275, ratio=0.378463 */
    ALGO_RATIO_K_PACK( 378u,  477u, 1781u),  /* idx=276, ratio=0.434932 */
    ALGO_RATIO_K_PACK( 372u,  497u, 1994u),  /* idx=277, ratio=0.486814 */
    ALGO_RATIO_K_PACK( 366u,  517u, 1032u),  /* idx=278, ratio=0.252011 */
    ALGO_RATIO_K_PACK( 360u,  537u,    0u),  /* idx=279, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 430u,  374u,    0u),  /* idx=280, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 424u,  394u,  359u),  /* idx=281, ratio=0.087737 */
    ALGO_RATIO_K_PACK( 418u,  414u,  684u),  /* idx=282, ratio=0.166922 */
    ALGO_RATIO_K_PACK( 412u,  434u,  978u),  /* idx=283, ratio=0.238747 */
    ALGO_RATIO_K_PACK( 405u,  454u, 1246u),  /* idx=284, ratio=0.304193 */
    ALGO_RATIO_K_PACK( 399u,  474u, 1491u),  /* idx=285, ratio=0.364074 */
    ALGO_RATIO_K_PACK( 393u,  495u, 1716u),  /* idx=286, ratio=0.419070 */
    ALGO_RATIO_K_PACK( 387u,  515u, 1036u),  /* idx=287, ratio=0.253056 */
    ALGO_RATIO_K_PACK( 380u,  535u,    0u),  /* idx=288, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 445u,  392u,    0u),  /* idx=289, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 439u,  412u,  344u),  /* idx=290, ratio=0.083893 */
    ALGO_RATIO_K_PACK( 432u,  432u,  655u),  /* idx=291, ratio=0.159951 */
    ALGO_RATIO_K_PACK( 426u,  452u,  939u),  /* idx=292, ratio=0.229222 */
    ALGO_RATIO_K_PACK( 420u,  472u, 1198u),  /* idx=293, ratio=0.292576 */
    ALGO_RATIO_K_PACK( 413u,  492u, 1436u),  /* idx=294, ratio=0.350739 */
    ALGO_RATIO_K_PACK( 407u,  513u, 1041u),  /* idx=295, ratio=0.254110 */
    ALGO_RATIO_K_PACK( 401u,  533u,    0u),  /* idx=296, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 459u,  410u,    0u),  /* idx=297, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 453u,  430u,  329u),  /* idx=298, ratio=0.080373 */
    ALGO_RATIO_K_PACK( 447u,  450u,  629u),  /* idx=299, ratio=0.153540 */
    ALGO_RATIO_K_PACK( 440u,  470u,  903u),  /* idx=300, ratio=0.220428 */
    ALGO_RATIO_K_PACK( 434u,  490u, 1154u),  /* idx=301, ratio=0.281813 */
    ALGO_RATIO_K_PACK( 428u,  511u, 1045u),  /* idx=302, ratio=0.255173 */
    ALGO_RATIO_K_PACK( 422u,  531u,    0u),  /* idx=303, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 474u,  428u,    0u),  /* idx=304, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 467u,  448u,  316u),  /* idx=305, ratio=0.077136 */
    ALGO_RATIO_K_PACK( 461u,  468u,  605u),  /* idx=306, ratio=0.147623 */
    ALGO_RATIO_K_PACK( 455u,  488u,  869u),  /* idx=307, ratio=0.212284 */
    ALGO_RATIO_K_PACK( 449u,  508u, 1049u),  /* idx=308, ratio=0.256245 */
    ALGO_RATIO_K_PACK( 442u,  529u,    0u),  /* idx=309, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 488u,  446u,    0u),  /* idx=310, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 482u,  466u,  304u),  /* idx=311, ratio=0.074150 */
    ALGO_RATIO_K_PACK( 475u,  486u,  582u),  /* idx=312, ratio=0.142144 */
    ALGO_RATIO_K_PACK( 469u,  506u,  838u),  /* idx=313, ratio=0.204721 */
    ALGO_RATIO_K_PACK( 463u,  526u,    0u),  /* idx=314, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 502u,  464u,    0u),  /* idx=315, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 496u,  484u,  292u),  /* idx=316, ratio=0.071386 */
    ALGO_RATIO_K_PACK( 490u,  504u,  561u),  /* idx=317, ratio=0.137058 */
    ALGO_RATIO_K_PACK( 484u,  524u,    0u),  /* idx=318, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 517u,  482u,    0u),  /* idx=319, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 511u,  502u,  210u),  /* idx=320, ratio=0.051218 */
    ALGO_RATIO_K_PACK( 504u,  522u,    0u),  /* idx=321, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 531u,  500u,    0u),  /* idx=322, ratio=0.000000 */
    ALGO_RATIO_K_PACK( 525u,  520u,    0u),  /* idx=323, ratio=-0.000000 */
    ALGO_RATIO_K_PACK( 546u,  518u,    0u),  /* idx=324, ratio=0.000000 */
};

static uint16_t AlgoRatioK_GetU(uint32_t packedValue)
{
    return (uint16_t)(packedValue & ALGO_RATIO_K_U_MASK);
}

static uint16_t AlgoRatioK_GetV(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_V_MASK) >> ALGO_RATIO_K_V_SHIFT);
}

static uint16_t AlgoRatioK_GetRatio12(uint32_t packedValue)
{
    return (uint16_t)((packedValue & ALGO_RATIO_K_RATIO_MASK) >> ALGO_RATIO_K_RATIO_SHIFT);
}

static uint16_t AlgoRatioK_ConvertRatio12ToQ10000(uint16_t ratio12)
{
    uint32_t numerator = ((uint32_t)ratio12 * ALGO_RATIO_K_RATIO_Q10000_MAX) + (ALGO_RATIO_K_RATIO12_MAX / 2u);
    uint32_t value = numerator / ALGO_RATIO_K_RATIO12_MAX;
    if (value > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        value = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }
    return (uint16_t)value;
}

static uint32_t AlgoRatioK_CalcDistance2(uint16_t u1,
                                         uint16_t v1,
                                         uint16_t u2,
                                         uint16_t v2)
{
    int32_t du = (int32_t)u1 - (int32_t)u2;
    int32_t dv = (int32_t)v1 - (int32_t)v2;
    return (uint32_t)((du * du) + (dv * dv));
}

static uint16_t AlgoRatioK_DivRoundU32(uint32_t numerator,
                                       uint32_t denominator)
{
    if (denominator == 0u)
    {
        return 0u;
    }
    return (uint16_t)((numerator + (denominator / 2u)) / denominator);
}

uint8_t AlgoRatioK_GetWhiteRatioQ10000(uint16_t targetU,
                                       uint16_t targetV,
                                       uint16_t *whiteRatioQ10000)
{
    uint32_t nearestDistance[ALGO_RATIO_K_AMOUNT];
    uint16_t nearestRatio12[ALGO_RATIO_K_AMOUNT];
    uint16_t lutIndex;
    uint16_t pointU;
    uint16_t pointV;
    uint16_t pointRatio12;
    uint16_t pointRatioQ10000;
    uint32_t packedValue;
    uint32_t distance2;
    uint8_t insertIndex;
    uint8_t shiftIndex;
    uint8_t nearestCount;
    uint8_t i;
#if (ALGO_RATIO_K_USE_WEIGHT != 0u)
    uint32_t weight;
    uint32_t weightSum;
    uint32_t weightedRatioSum;
#else
    uint32_t ratioSum;
#endif
    uint16_t ratioResult;

    if (whiteRatioQ10000 == (void *)0)
    {
        return 0u;
    }

    for (i = 0u; i < ALGO_RATIO_K_AMOUNT; i++)
    {
        nearestDistance[i] = ALGO_RATIO_K_DISTANCE_MAX;
        nearestRatio12[i] = 0u;
    }

    nearestCount = 0u;

    for (lutIndex = 0u; lutIndex < ALGO_RATIO_K_LUT_COUNT; lutIndex++)
    {
        packedValue = g_algoRatioKPackedLut[lutIndex];
        pointU = AlgoRatioK_GetU(packedValue);
        pointV = AlgoRatioK_GetV(packedValue);
        pointRatio12 = AlgoRatioK_GetRatio12(packedValue);
        distance2 = AlgoRatioK_CalcDistance2(targetU, targetV, pointU, pointV);

        if (distance2 == 0u)
        {
            *whiteRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(pointRatio12);
            return 1u;
        }

        for (insertIndex = 0u; insertIndex < ALGO_RATIO_K_AMOUNT; insertIndex++)
        {
            if (distance2 < nearestDistance[insertIndex])
            {
                for (shiftIndex = (uint8_t)(ALGO_RATIO_K_AMOUNT - 1u); shiftIndex > insertIndex; shiftIndex--)
                {
                    nearestDistance[shiftIndex] = nearestDistance[shiftIndex - 1u];
                    nearestRatio12[shiftIndex] = nearestRatio12[shiftIndex - 1u];
                }

                nearestDistance[insertIndex] = distance2;
                nearestRatio12[insertIndex] = pointRatio12;

                if (nearestCount < ALGO_RATIO_K_AMOUNT)
                {
                    nearestCount++;
                }

                break;
            }
        }
    }

    if (nearestCount == 0u)
    {
        return 0u;
    }

#if (ALGO_RATIO_K_USE_WEIGHT != 0u)
    weightSum = 0u;
    weightedRatioSum = 0u;

    for (i = 0u; i < nearestCount; i++)
    {
        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);
        weight = (uint32_t)(ALGO_RATIO_K_WEIGHT_SCALE / (nearestDistance[i] + 1u));
        if (weight == 0u)
        {
            weight = 1u;
        }
        weightedRatioSum += ((uint32_t)pointRatioQ10000 * weight);
        weightSum += weight;
    }

    ratioResult = AlgoRatioK_DivRoundU32(weightedRatioSum, weightSum);
#else
    ratioSum = 0u;

    for (i = 0u; i < nearestCount; i++)
    {
        pointRatioQ10000 = AlgoRatioK_ConvertRatio12ToQ10000(nearestRatio12[i]);
        ratioSum += (uint32_t)pointRatioQ10000;
    }

    ratioResult = AlgoRatioK_DivRoundU32(ratioSum, nearestCount);
#endif

    if (ratioResult > ALGO_RATIO_K_RATIO_Q10000_MAX)
    {
        ratioResult = ALGO_RATIO_K_RATIO_Q10000_MAX;
    }

    *whiteRatioQ10000 = ratioResult;
    return 1u;
}
