
#define USE_ZERO_IT_SUM_CHECK 1
#define FLASH_CS_START 0x5800
#define FLASH_CS_END 55296
#define BIST_PAGE_COUNT 0x0100
#define PROJECT_ID 0x1002
#define __MLX81116__
#define PRODUCT_STR "81116xAC"
#define __MLX81116xAC__
#define BL_AWD_TIMEOUT 80
#define BL_PHY_USE_MELIBUS 1
#define COMPILE_CONFIG_ID 2
#define FL_EE_HAS_WRITE_FUNC 1
#define FPLL 32000
#define HAS_EEPROM_WRITE_DATA 1
#define HAS_HW_FLASH_15 1
#define HAS_HW_FLASH_VCTAT_CTRL 1
#define HAS_HW_MELIBU_TRIM2 1
#define HAS_HW_NO_EN_AAIN 1
#define HAS_SW_MELIBU_EE_CTRL_CFG 1
#define MAX_RESET_COUNTER 0
#define HAS_MLS_API 0
#define HAS_MLS_DEVICE_ID 0
