
#ifndef _ALGORITHM_H_
#define _ALGORITHM_H_

#include "SystemConfig.h"
//#include "../Modules/ModulePwm.h"

/** @file
*
* @defgroup RGB_Algorithm RGB Color Algorithm
* @{
*
* @brief This module converts LIN RGB signal to PWM pulse.
*
* @details This module converts LIN RGB signal to target CIE color,
*          than compensate LED parameters referring to temperature.
*          At last it generates PWM pulse.
*/

/**@brief Parameters this module needed to generate PWM.*/
typedef struct ColorParams
{
  uint16_t colorU[RGBLEDMAX];        /**<Color U'.*/
  uint16_t colorV[RGBLEDMAX];        /**<Color V'.*/
  uint16_t  intensity[RGBLEDMAX];    /**<Intensity.*/
  int16_t  ledTemprature[RGBLEDMAX]; /**<Current LED junction temperature.*/
  uint16_t  tempAdjust[RGBLEDMAX];   /**<Temperature protection intensity adjusting parameter.*/
}SColorParams;

/**@brief this macro is to enhance the performance of dimming.*/
#define DINTENSITY_ADJUST_SHIFT_LEVEL 6

/**@brief this macro is to enhance the performance of temperature protection dimming.*/
#define DINTENSITY_TEMP_ADJUST_SHIFT_LEVEL 6

/**@brief PWM pulse this module generated.*/
typedef struct PWMParams
{
  uint16_t PWM_R[RGBLEDMAX];   /**<PWM Red.*/
  uint16_t PWM_G[RGBLEDMAX];   /**<PWM Green.*/
  uint16_t PWM_B[RGBLEDMAX];   /**<PWM Blue.*/
}SPWMParams;

/**
*@details   Update red led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  red x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  red y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  red Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateRedCIE(uint16_t ledIndex, int16_t x, int16_t y, int32_t Y);

/**
*@details   Update green led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  green x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  green y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  green Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateGreenCIE(uint16_t ledIndex, int16_t x, int16_t y, int32_t Y);

/**
*@details   Update blue led parameter.
*
*@note      The intensity(Y) value only have 40% of normal intensity for our float LIB has limitation.
*
*@param[in] x  blue x coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] y  blue y coordinate in CIE color. This value has been multiplied by 10000.
*
*@param[in] Y  blue Luminous in CIE color. This value has been multiplied by 10000.
*
*@retval    None.
*/
void algoUpdateBlueCIE(uint16_t ledIndex, int16_t x, int16_t y, int32_t Y);

/**
*@details   Generate PWM pulse.
*
*@param[in] inputColor  Algorithm input parameters.
*
*@param[out] outputPWM  PWM generated by algorithm.
*
*@retval    if this input color can be mixed by our led.
*/
bool_t algoGetPWMOutput(SColorParams * const inputColor, SPWMParams *outputPWM);

/** @} */

#endif
