function [referenceTable, compareTable, summaryTable] = verify_blinky_algorithm_split(csvPath, excelPath)
%VERIFY_BLINKY_ALGORITHM_SPLIT
% Compare BLINKY host C validation output with MATLAB reference results.

    rootDir = fileparts(fileparts(mfilename('fullpath')));
    if exist('default_white_mix_config', 'file') ~= 2
        addpath(rootDir);
    end

    if nargin < 1 || isempty(csvPath)
        csvPath = fullfile(rootDir, 'host_gcc_validation', 'flat_source', ...
            'algorithm_validation_output.csv');
    end
    if ~isfile(csvPath)
        error('verify_blinky_algorithm_split:CsvNotFound', ...
            'CSV not found: %s', csvPath);
    end

    if nargin < 2 || isempty(excelPath)
        excelPath = fullfile(rootDir, 'c_validation', '奥迪30色.xlsx');
    end
    [inputSignals, excelTargetxyY] = read_audi30_excel_inputs(excelPath);
    rawPreview = readtable(csvPath);
    referenceTargetxyY = table2array(rawPreview(:, {'target_x10000', 'target_y10000', 'target_Y10000'})) ./ 10000;

    whiteXY = [0.3152 0.3147];
    verifyPrimaries = [ ...
        0.7038 0.2953 0.7767; ...
        0.1792 0.7356 1.9320; ...
        0.1491 0.0333 0.2253];
    whiteChannelY = 2.2170;
    intersectionTriangleXY = verifyPrimaries(:, 1:2);
    config = default_white_mix_config(intersectionTriangleXY, verifyPrimaries);
    pwmConfig = get_blinky_pwm_config();

    n = size(referenceTargetxyY, 1);
    [insideMask, onMask] = inpolygon( ...
        referenceTargetxyY(:, 1), referenceTargetxyY(:, 2), ...
        config.intersectionTriangleXY(:, 1), ...
        config.intersectionTriangleXY(:, 2));
    insideMask = insideMask | onMask;

    refValid = false(n, 1);
    refWhite = nan(n, 3);
    refPoint = nan(n, 3);
    refLambda = nan(n, 1);
    refOneMinusLambda = nan(n, 1);
    refRayT = nan(n, 1);
    refEdge = strings(n, 1);
    refDeltaUv = nan(n, 1);
    refDeltaY = nan(n, 1);
    refPwm = nan(n, 4);
    refPwmRatio = nan(n, 4);

    for i = 1:n
        step = white_mix_one_target(referenceTargetxyY(i, :), whiteXY, config);
        refValid(i) = step.IsValid;
        refWhite(i, :) = step.WhiteComponent_xyY;
        refPoint(i, :) = step.PointComponent_xyY;
        refLambda(i) = step.Coeff.lambda;
        refOneMinusLambda(i) = step.Coeff.oneMinusLambda;
        refRayT(i) = step.Ray_t;
        refEdge(i) = string(step.Edge);
        refDeltaUv(i) = step.Delta_uv;
        refDeltaY(i) = step.DeltaY;
        [refPwm(i, :), refPwmRatio(i, :)] = compute_blinky_pwm(step, pwmConfig);
    end

    referenceTable = table( ...
        (1:n).', inputSignals.DisplayU, inputSignals.DisplayV, ...
        inputSignals.AlgoU, inputSignals.AlgoV, inputSignals.Intensity10000, ...
        yes_no_text(insideMask), yes_no_text(refValid), ...
        excelTargetxyY(:, 1), excelTargetxyY(:, 2), excelTargetxyY(:, 3), ...
        referenceTargetxyY(:, 1), referenceTargetxyY(:, 2), referenceTargetxyY(:, 3), ...
        refWhite(:, 1), refWhite(:, 2), refWhite(:, 3), ...
        refPoint(:, 1), refPoint(:, 2), refPoint(:, 3), ...
        refEdge, refLambda, refOneMinusLambda, refRayT, ...
        refPwm(:, 1), refPwm(:, 2), refPwm(:, 3), refPwm(:, 4), ...
        refPwmRatio(:, 1), refPwmRatio(:, 2), refPwmRatio(:, 3), refPwmRatio(:, 4), ...
        refDeltaUv, refDeltaY, ...
        'VariableNames', { ...
            'Index', 'DisplayU', 'DisplayV', 'AlgoU', 'AlgoV', 'InputIntensity10000', ...
            'InsideGamutTriangle', 'MatlabValid', ...
            'ExcelTargetX', 'ExcelTargetY', 'ExcelTargetL', ...
            'ReferenceTargetX', 'ReferenceTargetY', 'ReferenceTargetL', ...
            'WhiteX', 'WhiteY', 'WhiteL', ...
            'PointX', 'PointY', 'PointL', ...
            'Edge', 'Lambda', 'OneMinusLambda', 'RayT', ...
            'MatlabPwmR', 'MatlabPwmG', 'MatlabPwmB', 'MatlabPwmW', ...
            'MatlabPwmRatioR', 'MatlabPwmRatioG', 'MatlabPwmRatioB', 'MatlabPwmRatioW', ...
            'VerifyDeltaUV', 'VerifyDeltaY'});

    compareTable = build_compare_table(csvPath, inputSignals, excelTargetxyY, referenceTargetxyY, ...
        insideMask, refValid, refWhite, refPoint, refLambda, ...
        refOneMinusLambda, refRayT, refPwm, refPwmRatio, pwmConfig);

    validBoth = strcmp(compareTable.CValid, "Yes") & strcmp(compareTable.MatlabValid, "Yes");
    summaryTable = table( ...
        n, ...
        sum(insideMask), ...
        sum(~insideMask), ...
        sum(strcmp(compareTable.CValid, "Yes")), ...
        sum(refValid), ...
        sum(validBoth), ...
        sum(strcmp(compareTable.CValid, "Yes") ~= refValid), ...
        max_abs_or_nan(compareTable.WhiteXError(validBoth)), ...
        max_abs_or_nan(compareTable.WhiteYError(validBoth)), ...
        max_abs_or_nan(compareTable.WhiteLError(validBoth)), ...
        max_abs_or_nan(compareTable.PointXError(validBoth)), ...
        max_abs_or_nan(compareTable.PointYError(validBoth)), ...
        max_abs_or_nan(compareTable.PointLError(validBoth)), ...
        max_abs_or_nan(compareTable.TargetXError), ...
        max_abs_or_nan(compareTable.TargetYError), ...
        max_abs_or_nan(compareTable.TargetLError), ...
        max_abs_or_nan(compareTable.LambdaError(validBoth)), ...
        max_abs_or_nan(compareTable.OneMinusLambdaError(validBoth)), ...
        max_abs_or_nan(compareTable.RayTError(validBoth)), ...
        max_abs_or_nan(compareTable.PwmRError(validBoth)), ...
        max_abs_or_nan(compareTable.PwmGError(validBoth)), ...
        max_abs_or_nan(compareTable.PwmBError(validBoth)), ...
        max_abs_or_nan(compareTable.PwmWError(validBoth)), ...
        'VariableNames', { ...
            'TotalCount', 'InsideGamutTriangleCount', 'OutsideGamutTriangleCount', ...
            'CValidCount', 'MatlabValidCount', 'ValidBothCount', 'ValidMismatchCount', ...
            'MaxWhiteXError', 'MaxWhiteYError', 'MaxWhiteLError', ...
            'MaxPointXError', 'MaxPointYError', 'MaxPointLError', ...
            'MaxTargetXError', 'MaxTargetYError', 'MaxTargetLError', ...
            'MaxLambdaError', 'MaxOneMinusLambdaError', 'MaxRayTError', ...
            'MaxPwmRError', 'MaxPwmGError', 'MaxPwmBError', 'MaxPwmWError'});

    if nargout == 0
        fprintf('\nBLINKY Algorithm.c validation:\n');
        fprintf('White point: (%.4f, %.4f)\n', whiteXY(1), whiteXY(2));
        fprintf('White channel Y: %.4f\n', whiteChannelY);
        fprintf('Excel: %s\n', excelPath);
        fprintf('CSV: %s\n', csvPath);
        show_blinky_validation_window(compareTable, summaryTable, referenceTargetxyY, insideMask, config, whiteXY, csvPath, excelPath);
        disp(summaryTable);
        disp(compareTable);
    end
end

function compareTable = build_compare_table(csvPath, inputSignals, excelTargetxyY, referenceTargetxyY, ...
    insideMask, refValid, refWhite, refPoint, refLambda, refOneMinusLambda, refRayT, ...
    refPwm, refPwmRatio, pwmConfig)

    requiredColumns = { ...
        'index', 'display_u', 'display_v', 'algo_u', 'algo_v', 'input_intensity10000', ...
        'target_x10000', 'target_y10000', 'target_Y10000', 'valid', ...
        'white_x10000', 'white_y10000', 'white_Y10000', ...
        'point_x10000', 'point_y10000', 'point_Y10000', ...
        'edge_index', 'lambda_fix16', 'one_minus_lambda_fix16', 'ray_t_fix16', ...
        'pwm_r', 'pwm_g', 'pwm_b', 'pwm_w'};

    rawTable = readtable(csvPath);
    missingColumns = requiredColumns(~ismember(requiredColumns, rawTable.Properties.VariableNames));
    if ~isempty(missingColumns)
        error('verify_blinky_algorithm_split:MissingColumns', ...
            'CSV is missing required columns: %s', strjoin(missingColumns, ', '));
    end

    n = height(rawTable);
    if size(referenceTargetxyY, 1) < n || size(excelTargetxyY,1) < n
        error('verify_blinky_algorithm_split:TargetCountMismatch', ...
            'MATLAB target list has fewer rows than CSV: excel=%d, ref=%d, csv=%d.', ...
            size(excelTargetxyY, 1), size(referenceTargetxyY, 1), n);
    end

    cIndex = rawTable.index;
    cDisplayU = rawTable.display_u;
    cDisplayV = rawTable.display_v;
    cAlgoU = rawTable.algo_u;
    cAlgoV = rawTable.algo_v;
    cInputIntensity = rawTable.input_intensity10000;
    cTarget = table2array(rawTable(:, {'target_x10000', 'target_y10000', 'target_Y10000'})) ./ 10000;
    cWhite = table2array(rawTable(:, {'white_x10000', 'white_y10000', 'white_Y10000'})) ./ 10000;
    cPoint = table2array(rawTable(:, {'point_x10000', 'point_y10000', 'point_Y10000'})) ./ 10000;
    cValid = logical(rawTable.valid);
    cLambda = double(rawTable.lambda_fix16) / 65536;
    cOneMinusLambda = double(rawTable.one_minus_lambda_fix16) / 65536;
    cRayT = double(rawTable.ray_t_fix16) / 65536;
    cPwm = table2array(rawTable(:, {'pwm_r', 'pwm_g', 'pwm_b', 'pwm_w'}));
    cPwmRatio = double(cPwm) / pwmConfig.PwmPeriod;

    cWhiteError = cWhite - refWhite(1:n, :);
    cPointError = cPoint - refPoint(1:n, :);
    cLambdaError = cLambda - refLambda(1:n);
    cOneMinusLambdaError = cOneMinusLambda - refOneMinusLambda(1:n);
    cRayTError = cRayT - refRayT(1:n);
    cTargetError = cTarget - excelTargetxyY(1:n, :);
    cPwmError = double(cPwm) - refPwm(1:n, :);
    cPwmRatioError = cPwmRatio - refPwmRatio(1:n, :);

    compareTable = table( ...
        cIndex, cDisplayU, cDisplayV, cAlgoU, cAlgoV, cInputIntensity, ...
        yes_no_text(insideMask(1:n)), yes_no_text(cValid), yes_no_text(refValid(1:n)), ...
        excelTargetxyY(1:n, 1), excelTargetxyY(1:n, 2), excelTargetxyY(1:n, 3), ...
        cTarget(:, 1), cTarget(:, 2), cTarget(:, 3), ...
        cTargetError(:, 1), cTargetError(:, 2), cTargetError(:, 3), ...
        cWhite(:, 1), cWhite(:, 2), cWhite(:, 3), ...
        refWhite(1:n, 1), refWhite(1:n, 2), refWhite(1:n, 3), ...
        cWhiteError(:, 1), cWhiteError(:, 2), cWhiteError(:, 3), ...
        cPoint(:, 1), cPoint(:, 2), cPoint(:, 3), ...
        refPoint(1:n, 1), refPoint(1:n, 2), refPoint(1:n, 3), ...
        cPointError(:, 1), cPointError(:, 2), cPointError(:, 3), ...
        cLambda, refLambda(1:n), cLambdaError, ...
        cOneMinusLambda, refOneMinusLambda(1:n), cOneMinusLambdaError, ...
        cRayT, refRayT(1:n), cRayTError, ...
        cPwm(:, 1), cPwm(:, 2), cPwm(:, 3), cPwm(:, 4), ...
        refPwm(1:n, 1), refPwm(1:n, 2), refPwm(1:n, 3), refPwm(1:n, 4), ...
        cPwmError(:, 1), cPwmError(:, 2), cPwmError(:, 3), cPwmError(:, 4), ...
        cPwmRatio(:, 1), cPwmRatio(:, 2), cPwmRatio(:, 3), cPwmRatio(:, 4), ...
        refPwmRatio(1:n, 1), refPwmRatio(1:n, 2), refPwmRatio(1:n, 3), refPwmRatio(1:n, 4), ...
        cPwmRatioError(:, 1), cPwmRatioError(:, 2), cPwmRatioError(:, 3), cPwmRatioError(:, 4), ...
        'VariableNames', { ...
            'Index', 'DisplayU', 'DisplayV', 'AlgoU', 'AlgoV', 'InputIntensity10000', ...
            'InsideGamutTriangle', 'CValid', 'MatlabValid', ...
            'ExcelTargetX', 'ExcelTargetY', 'ExcelTargetL', ...
            'CTargetX', 'CTargetY', 'CTargetL', ...
            'TargetXError', 'TargetYError', 'TargetLError', ...
            'CWhiteX', 'CWhiteY', 'CWhiteL', 'MatlabWhiteX', 'MatlabWhiteY', 'MatlabWhiteL', ...
            'WhiteXError', 'WhiteYError', 'WhiteLError', ...
            'CPointX', 'CPointY', 'CPointL', 'MatlabPointX', 'MatlabPointY', 'MatlabPointL', ...
            'PointXError', 'PointYError', 'PointLError', ...
            'CLambda', 'MatlabLambda', 'LambdaError', ...
            'COneMinusLambda', 'MatlabOneMinusLambda', 'OneMinusLambdaError', ...
            'CRayT', 'MatlabRayT', 'RayTError', ...
            'CPwmR', 'CPwmG', 'CPwmB', 'CPwmW', ...
            'MatlabPwmR', 'MatlabPwmG', 'MatlabPwmB', 'MatlabPwmW', ...
            'PwmRError', 'PwmGError', 'PwmBError', 'PwmWError', ...
            'CPwmRatioR', 'CPwmRatioG', 'CPwmRatioB', 'CPwmRatioW', ...
            'MatlabPwmRatioR', 'MatlabPwmRatioG', 'MatlabPwmRatioB', 'MatlabPwmRatioW', ...
            'PwmRatioRError', 'PwmRatioGError', 'PwmRatioBError', 'PwmRatioWError'});
end

function pwmConfig = get_blinky_pwm_config()
    pwmConfig = struct();
    pwmConfig.PwmPeriod = 32000;
    pwmConfig.Factor = hex2dec('8000');
    pwmConfig.BrightnessFactor = 100;
    pwmConfig.TempAdjust = 100 * 2^6;
    pwmConfig.WhiteXY = [0.3152 0.3147];

    redY20 = floor(7767 / 20);
    greenY20 = floor(19320 / 20);
    blueY20 = floor(2253 / 20);
    whiteY20 = floor(22170 / 20);

    pwmConfig.CurrentRed = [0.7038, 0.2953, redY20 / 10000 * 7.5];
    pwmConfig.CurrentGreen = [0.1792, 0.7356, greenY20 / 10000 * 7.5];
    pwmConfig.CurrentBlue = [0.1491, 0.0333, blueY20 / 10000 * 7.5];
    pwmConfig.CurrentWhiteY = whiteY20 / 10000 * 7.5;
end

function [pwmValues, pwmRatios] = compute_blinky_pwm(step, cfg)
    if step.IsValid
        dutyColor = step.PointComponent_xyY;
        whiteColor = step.WhiteComponent_xyY;
    else
        dutyColor = step.Target_xyY;
        whiteColor = [cfg.WhiteXY, 0];
    end

    [pwmR, pwmG, pwmB] = compute_rgb_pwm(dutyColor, cfg);
    pwmW = compute_white_pwm(whiteColor, cfg);

    pwmValues = [pwmR, pwmG, pwmB, pwmW];
    pwmRatios = pwmValues / cfg.PwmPeriod;
end

function [pwmR, pwmG, pwmB] = compute_rgb_pwm(colorxyY, cfg)
    x = colorxyY(1);
    y = colorxyY(2);
    Y = colorxyY(3);

    red = cfg.CurrentRed;
    green = cfg.CurrentGreen;
    blue = cfg.CurrentBlue;

    a = x - blue(1);
    d = y - blue(2);
    Bm = blue(3) / blue(2);

    b = green(2) - y;
    c = green(1) - x;
    Gm = green(3) / green(2);

    e = red(1) - x;
    f = red(2) - y;
    Rm = red(3) / red(2);

    R_all = a * b - c * d;
    B_all = e * b - c * f;
    G_all = d * e - f * a;

    duty_r = Bm * Gm * R_all;
    duty_g = Rm * Bm * G_all;
    duty_b = Rm * Gm * B_all;

    mixY = compute_mix_y(Y, cfg.TempAdjust);
    denominator = red(3) * duty_r + green(3) * duty_g + blue(3) * duty_b;

    if denominator <= 0 || mixY <= 0
        pwmR = 0;
        pwmG = 0;
        pwmB = 0;
        return;
    end

    scale = mixY / denominator;
    duty_r = clamp01(duty_r * scale);
    duty_g = clamp01(duty_g * scale);
    duty_b = clamp01(duty_b * scale);

    pwmR = scale_pwm_count(duty_r, cfg);
    pwmG = scale_pwm_count(duty_g, cfg);
    pwmB = scale_pwm_count(duty_b, cfg);
end

function pwmW = compute_white_pwm(whitexyY, cfg)
    mixY = compute_mix_y(whitexyY(3), cfg.TempAdjust);
    if mixY <= 0 || cfg.CurrentWhiteY <= 0
        pwmW = 0;
        return;
    end

    duty = clamp01(mixY / cfg.CurrentWhiteY);
    pwmW = scale_pwm_count(duty, cfg);
end

function mixY = compute_mix_y(Y, tempAdjust)
    mixY = Y * floor(tempAdjust / 2);
    mixY = mixY * 0.02;
    mixY = mixY * 0.015625;
end

function pwm = scale_pwm_count(duty, cfg)
    pwm = floor(duty * cfg.PwmPeriod);
    pwm = floor(pwm * bitshift(cfg.Factor, -7) / 256);
    pwm = floor(pwm * bitand(cfg.BrightnessFactor, 127) / 100);
    pwm = max(min(pwm, 32767), 0);
end

function value = clamp01(value)
    value = min(max(value, 0), 1);
end

function show_blinky_validation_window(compareTable, summaryTable, targetxyY, insideMask, config, whiteXY, csvPath, excelPath)
    fig = figure( ...
        'Name', 'BLINKY PWM Validation', ...
        'Color', 'w', ...
        'NumberTitle', 'off', ...
        'Position', [80 60 1660 920]);

    ax = axes('Parent', fig, 'Position', [0.05 0.10 0.42 0.82]);
    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');
    axis(ax, 'equal');
    xlabel(ax, 'x');
    ylabel(ax, 'y');
    title(ax, 'Target points and BLINKY gamut triangle');

    tri = config.intersectionTriangleXY;
    triClosed = [tri; tri(1, :)];

    patch('Parent', ax, ...
        'XData', tri(:, 1), ...
        'YData', tri(:, 2), ...
        'FaceColor', [0.90 0.94 1.00], ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.60);
    plot(ax, triClosed(:, 1), triClosed(:, 2), 'k-', 'LineWidth', 1.5);
    plot(ax, whiteXY(1), whiteXY(2), 'ks', 'MarkerFaceColor', 'w', 'MarkerSize', 8);
    text(ax, whiteXY(1) + 0.006, whiteXY(2) - 0.010, 'White', 'FontSize', 10);

    insideValid = insideMask & strcmp(compareTable.CValid, "Yes") & strcmp(compareTable.MatlabValid, "Yes");
    outside = ~insideMask;
    insideInvalid = insideMask & ~insideValid;

    if any(insideValid)
        scatter(ax, targetxyY(insideValid, 1), targetxyY(insideValid, 2), 46, [0.10 0.60 0.22], 'filled');
    end
    if any(insideInvalid)
        scatter(ax, targetxyY(insideInvalid, 1), targetxyY(insideInvalid, 2), 58, [0.60 0.15 0.75], 'x', 'LineWidth', 1.4);
    end
    if any(outside)
        scatter(ax, targetxyY(outside, 1), targetxyY(outside, 2), 56, [0.85 0.15 0.15], 'diamond', 'filled');
    end

    for i = 1:size(targetxyY, 1)
        label = sprintf('%d', i);
        if outside(i)
            label = sprintf('%d out', i);
        end
        text(ax, targetxyY(i, 1) + 0.004, targetxyY(i, 2) + 0.004, label, 'FontSize', 9);
    end

    summaryPanel = uipanel(fig, ...
        'Units', 'normalized', ...
        'Position', [0.50 0.72 0.46 0.22], ...
        'Title', 'Result box', ...
        'BackgroundColor', [0.98 0.98 0.98], ...
        'FontSize', 10);

    summaryText = {
        ['CSV: ', csvPath]
        ['Excel: ', excelPath]
        sprintf('White point: (%.4f, %.4f)', whiteXY(1), whiteXY(2))
        sprintf('Total points: %d', summaryTable.TotalCount)
        sprintf('Inside gamut: %d', summaryTable.InsideGamutTriangleCount)
        sprintf('Outside gamut: %d', summaryTable.OutsideGamutTriangleCount)
        sprintf('C valid: %d', summaryTable.CValidCount)
        sprintf('MATLAB valid: %d', summaryTable.MatlabValidCount)
        sprintf('Valid both: %d', summaryTable.ValidBothCount)
        sprintf('Max target error [x y Y]: [%g %g %g]', ...
            summaryTable.MaxTargetXError, summaryTable.MaxTargetYError, summaryTable.MaxTargetLError)
        sprintf('Max lambda error: %.6g', summaryTable.MaxLambdaError)
        sprintf('Max PWM error [R G B W]: [%g %g %g %g]', ...
            summaryTable.MaxPwmRError, summaryTable.MaxPwmGError, ...
            summaryTable.MaxPwmBError, summaryTable.MaxPwmWError)
        };

    uicontrol(summaryPanel, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.02 0.02 0.96 0.96], ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', [0.98 0.98 0.98], ...
        'FontSize', 10, ...
        'String', summaryText);

    tablePanel = uipanel(fig, ...
        'Units', 'normalized', ...
        'Position', [0.50 0.10 0.46 0.58], ...
        'Title', 'PWM and validation results', ...
        'BackgroundColor', 'w', ...
        'FontSize', 10);

    displayTable = table( ...
        compareTable.Index, ...
        compareTable.DisplayU, compareTable.DisplayV, ...
        compareTable.AlgoU, compareTable.AlgoV, ...
        compareTable.InputIntensity10000, ...
        compareTable.CValid, ...
        compareTable.MatlabValid, ...
        compareTable.ExcelTargetX, compareTable.ExcelTargetY, compareTable.ExcelTargetL, ...
        compareTable.CTargetX, compareTable.CTargetY, compareTable.CTargetL, ...
        compareTable.TargetXError, compareTable.TargetYError, compareTable.TargetLError, ...
        compareTable.CPwmR, compareTable.CPwmG, compareTable.CPwmB, compareTable.CPwmW, ...
        compareTable.CPwmRatioR, compareTable.CPwmRatioG, compareTable.CPwmRatioB, compareTable.CPwmRatioW, ...
        compareTable.MatlabPwmR, compareTable.MatlabPwmG, compareTable.MatlabPwmB, compareTable.MatlabPwmW, ...
        compareTable.MatlabPwmRatioR, compareTable.MatlabPwmRatioG, compareTable.MatlabPwmRatioB, compareTable.MatlabPwmRatioW, ...
        compareTable.PwmRError, compareTable.PwmGError, compareTable.PwmBError, compareTable.PwmWError, ...
        compareTable.PwmRatioRError, compareTable.PwmRatioGError, compareTable.PwmRatioBError, compareTable.PwmRatioWError, ...
        compareTable.CLambda, compareTable.MatlabLambda, compareTable.LambdaError, ...
        'VariableNames', { ...
            'Index', 'DispU', 'DispV', 'AlgoU', 'AlgoV', 'InputL10000', ...
            'CValid', 'MatlabValid', ...
            'ExcelTargetX', 'ExcelTargetY', 'ExcelTargetL', ...
            'CTargetX', 'CTargetY', 'CTargetL', ...
            'ErrTargetX', 'ErrTargetY', 'ErrTargetL', ...
            'CPwmR', 'CPwmG', 'CPwmB', 'CPwmW', ...
            'CRatioR', 'CRatioG', 'CRatioB', 'CRatioW', ...
            'MatlabPwmR', 'MatlabPwmG', 'MatlabPwmB', 'MatlabPwmW', ...
            'MatlabRatioR', 'MatlabRatioG', 'MatlabRatioB', 'MatlabRatioW', ...
            'ErrPwmR', 'ErrPwmG', 'ErrPwmB', 'ErrPwmW', ...
            'ErrRatioR', 'ErrRatioG', 'ErrRatioB', 'ErrRatioW', ...
            'CLambda', 'MatlabLambda', 'ErrLambda'});

    uitable(tablePanel, ...
        'Units', 'normalized', ...
        'Position', [0.01 0.01 0.98 0.98], ...
        'Data', sanitize_uitable_data(table2cell(displayTable)), ...
        'ColumnName', displayTable.Properties.VariableNames, ...
        'RowName', []);
end

function out = yes_no_text(mask)
    out = repmat("No", numel(mask), 1);
    out(logical(mask)) = "Yes";
end

function value = max_abs_or_nan(data)
    data = data(isfinite(data));
    if isempty(data)
        value = NaN;
    else
        value = max(abs(data(:)));
    end
end

function data = sanitize_uitable_data(data)
    for i = 1:numel(data)
        if isstring(data{i})
            data{i} = char(data{i});
        end
    end
end

function [inputSignals, targetxyY] = read_audi30_excel_inputs(excelPath)
    raw = readcell(excelPath);
    data = raw(2:31, :);

    targetxyY = [ ...
        cell2mat(data(:, 4)), ...
        cell2mat(data(:, 5)), ...
        cell2mat(data(:, 12))];

    inputSignals = table( ...
        cell2mat(data(:, 10)), ...
        cell2mat(data(:, 11)), ...
        cell2mat(data(:, 10)) * 5, ...
        cell2mat(data(:, 11)) * 5, ...
        repmat(6400, size(data, 1), 1), ...
        'VariableNames', {'DisplayU', 'DisplayV', 'AlgoU', 'AlgoV', 'Intensity10000'});
end
